"Resource/UI/NotificationToastControl.res"
{
	"NotificationToastControl"
	{
		"ControlName"	"CNotificationToastControl"
		"fieldName"		"NotificationToastControl"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"1"
		"wide"			"200"
		"tall"			"32"
		"visible"		"1"
		"enabled"		"1"
		"border"		""
		"paintborder"			"1"
		"paintbackground"		"0"
		"PaintBackgroundType"	"0"
		"bgcolor_override"		"owwhite"
	}

	"DeleteButton"
	{
		"ControlName"	"CExImageButton"
		"fieldName"		"DeleteButton"
		"xpos"			"160"
		"ypos"			"0"
		"zpos"			"10"
		"Wide"                              "32"
        "Tall"                              "32"
        "Visible"                           "1"
        "Enabled"                           "1"
        "ProportionalToParent"              "1"
        "Use_Proportional_Insets"           "1"
        "TextInsetX"                        "5"
        "Font"                              "Symbols16"
        "LabelText"                         "X"
        "Command"                           "delete"
        "TextAlignment"                     "center"
        "Sound_Depressed"                   "UI/buttonclick.wav"
        "DefaultFGColor_Override"           "Red"
        "ArmedFGColor_Override"             "Menu_Accent"
        "DepressedFGColor_Override"         "Menu_Accent"
        "paintBackground"                   "0"
        "paintborder"                       "1"
        "border_default"                    "BG_TransparentBlack"
        "border_depressed"                  "OL_White_BG_TransparentBlack_Glow_Blue"
        "border_armed"                      "OL_White_BG_TransparentBlack_Glow_Blue"
	}

	"TriggerButton"
	{
		"ControlName"	"CExImageButton"
		"fieldName"		"TriggerButton"
		"xpos"			"134"
		"ypos"			"0"
		"zpos"			"10"
		"Wide"                              "32"
        "Tall"                              "32"
        "Visible"                           "1"
        "Enabled"                           "1"
        "ProportionalToParent"              "1"
        "Use_Proportional_Insets"           "1"
        "TextInsetX"                        "5"
        "Font"                              "Symbols16"
        "LabelText"                         "@"
        "Command"                           "trigger"
        "TextAlignment"                     "center"
        "Sound_Depressed"                   "UI/buttonclick.wav"
        "DefaultFGColor_Override"           "White"
        "ArmedFGColor_Override"             "Menu_Accent"
        "DepressedFGColor_Override"         "Menu_Accent"
        "paintBackground"                   "0"
        "paintborder"                       "1"
        "border_default"                    "BG_TransparentBlack"
        "border_depressed"                  "OL_White_BG_TransparentBlack_Glow_Blue"
        "border_armed"                      "OL_White_BG_TransparentBlack_Glow_Blue"
    }

	"AcceptButton"
	{
		"ControlName"	"CExImageButton"
		"fieldName"		"AcceptButton"
		"xpos"			"144"
		"ypos"			"5"
		"zpos"			"10"
		"wide"			"20"
		"tall"			"20"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"1"
		"tabPosition"	"0"
		"labeltext"		""
		"font"			"HudFontSmallestBold"
		"textAlignment"	"center"
		"dulltext"		"0"
		"brighttext"	"0"
		"default"		"1"
		"sound_depressed"	"UI/buttonclick.wav"
		"sound_released"	"UI/buttonclickrelease.wav"
		"Command"		"accept"

		"border_default"	"BlueButton"
		"border_armed"		"BlueButtonSel"
		"paintbackground"	"0"
		
		"defaultBgColor_override"	"100 90 85 255"
		"defaultFgColor_override"	"255 255 255 255"
		"armedFgColor_override" "OWWHITE"
		"depressedFgColor_override" "46 43 42 255"
		
		"image_drawcolor"	"255 255 255 255"
		"image_armedcolor"	"oworange"
		"SubImage"
		{
			"ControlName"	"ImagePanel"
			"fieldName"		"SubImage"
			"xpos"			"2"
			"ypos"			"2"
			"zpos"			"1"
			"wide"			"16"
			"tall"			"16"
			"visible"		"1"
			"enabled"		"1"
			"image"			"glyph_view"
			"scaleImage"	"1"
		}	
	}		

	"DeclineButton"
	{
		"ControlName"	"CExImageButton"
		"fieldName"		"DeclineButton"
		"xpos"			"165"
		"ypos"			"5"
		"zpos"			"10"
		"wide"			"20"
		"tall"			"20"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"1"
		"tabPosition"	"0"
		"labeltext"		""
		"font"			"HudFontSmallestBold"
		"textAlignment"	"center"
		"dulltext"		"0"
		"brighttext"	"0"
		"default"		"1"
		"sound_depressed"	"UI/buttonclick.wav"
		"sound_released"	"UI/buttonclickrelease.wav"
		"Command"		"decline"

		"border_default"	"BlueButton"
		"border_armed"		"BlueButtonSel"
		"paintbackground"	"0"
		
		"defaultBgColor_override"	"100 90 85 255"		
		"defaultFgColor_override" "46 43 42 255"
		"armedFgColor_override" "OWWHITE"
		"depressedFgColor_override" "46 43 42 255"
		
		"image_drawcolor"	"238 54 36 255"
		"image_armedcolor"	"oworange"
		"SubImage"
		{
			"ControlName"	"ImagePanel"
			"fieldName"		"SubImage"
			"xpos"			"2"
			"ypos"			"2"
			"zpos"			"1"
			"wide"			"16"
			"tall"			"16"
			"visible"		"1"
			"enabled"		"1"
			"image"			"glyph_close_X"
			"scaleImage"	"1"
		}				
	}
}
