"Resource/UI/ClassSelection.res"
{
    "class"
    {
        "ControlName"           "Frame"
        "fieldName"             "class"
        "xpos"                  "0"
        "ypos"                  "0"
        "wide"                  "f0"
        "tall"                  "480"
        "autoResize"            "0"
        "pinCorner"             "0"
        "visible"               "1"
        "enabled"               "1"
        "tabPosition"           "0"
    }
    "SysMenu"
    {
        "ControlName"           "Menu"
        "fieldName"             "SysMenu"
        "xpos"                  "0"
        "ypos"                  "0"
        "wide"                  "64"
        "tall"                  "24"
        "autoResize"            "0"
        "pinCorner"             "0"
        "visible"               "0"
        "enabled"               "0"
        "tabPosition"           "0"
    }
    "SelectAClassLabel"
    {
        "ControlName"               "Label"
        "fieldName"                 "SelectAClassLabel"
        "xpos"                      "20"
        "ypos"                      "20"
        "zpos"                      "1"
        "wide"                      "300"
        "tall"                      "25"
        "labelText"                 "PICK A CLASS"
        "textAlignment"             "west"
        "font"                      "Header_XL"
        "visible"                   "1"
        "enabled"                   "1"
        "fgcolor_override"          "White"
    }
    // MARK: Cards
    "ClassCardAnchor"
    {
        "ControlName"               "EditablePanel"
        "fieldName"                 "ClassCardAnchor"
        "xpos"                      "cs-0.5"
        "ypos"                      "rs1-140"
        "zpos"                      "7"
        "wide"                      "480"
        "tall"                      "1"
        "visible"                   "0"
        "enabled"                   "1"
        "bgcolor_override"          "blue"
    }
    "Offense"
    {
        "ControlName"                   "CExLabel"
        "fieldName"                     "Offense"
        "xpos"                          "0"
        "ypos"                          "0"
        "zpos"                          "1"
        "wide"                          "100"
        "tall"                          "18"
        "labelText"                     "#TF_OFFENSE"
        "textAlignment"                 "center"
        "font"                          "BodyEm_MD"
        "visible"                       "1"
        "enabled"                       "1"
        "fgcolor_override"              "White"
        "pin_to_sibling"                "OffenseDivider"
        "pin_corner_to_sibling"         "PIN_CENTER_BOTTOM"
        "pin_to_sibling_corner"         "PIN_CENTER_BOTTOM"
    }
    "OffenseDivider"
    {
        "ControlName"                   "EditablePanel"
        "fieldName"                     "OffenseDivider"
        "XPos"                          "20"
        "YPos"                          "0"
        "ZPos"                          "5"
        "Wide"                          "188"
        "Tall"                          "1"
        "proportionaltoparent"          "1"
        "paintBackground"               "1"
        "paintBackgroundType"           "2"
        "roundedCorners"                "15"
        "bgcolor_override"              "255 255 255 20"
        "pin_to_sibling"                "DefenseDivider"
        "pin_corner_to_sibling"         "PIN_BOTTOMRIGHT"
        "pin_to_sibling_corner"         "PIN_BOTTOMLEFT"
    }
    "Defense"
    {
        "ControlName"                   "CExLabel"
        "fieldName"                     "Defense"
        "xpos"                          "0"
        "ypos"                          "0"
        "zpos"                          "1"
        "wide"                          "100"
        "tall"                          "18"
        "labelText"                     "#TF_Defense"
        "textAlignment"                 "center"
        "font"                          "BodyEm_MD"
        "visible"                       "1"
        "enabled"                       "1"
        "fgcolor_override"              "White"
        "pin_to_sibling"                "DefenseDivider"
        "pin_corner_to_sibling"         "PIN_CENTER_BOTTOM"
        "pin_to_sibling_corner"         "PIN_CENTER_BOTTOM"
    }
    "DefenseDivider"
    {
        "ControlName"                   "EditablePanel"
        "fieldName"                     "DefenseDivider"
        "XPos"                          "0"
        "YPos"                          "0"
        "ZPos"                          "5"
        "Wide"                          "188"
        "Tall"                          "1"
        "proportionaltoparent"          "1"
        "paintBackground"               "1"
        "paintBackgroundType"           "2"
        "roundedCorners"                "15"
        "bgcolor_override"              "255 255 255 20"
        "pin_to_sibling"                "ClassCardAnchor"
        "pin_corner_to_sibling"         "PIN_CENTER_BOTTOM"
        "pin_to_sibling_corner"         "PIN_CENTER_BOTTOM"
    }
    "Support"
    {
        "ControlName"                   "CExLabel"
        "fieldName"                     "Support"
        "xpos"                          "0"
        "ypos"                          "0"
        "zpos"                          "1"
        "wide"                          "100"
        "tall"                          "18"
        "labelText"                     "#TF_SUPPORT"
        "textAlignment"                 "center"
        "font"                          "BodyEm_MD"
        "visible"                       "1"
        "enabled"                       "1"
        "fgcolor_override"              "White"
        "pin_to_sibling"                "SupportDivider"
        "pin_corner_to_sibling"         "PIN_CENTER_BOTTOM"
        "pin_to_sibling_corner"         "PIN_CENTER_BOTTOM"
    }
    "SupportDivider"
    {
        "ControlName"                   "EditablePanel"
        "fieldName"                     "SupportDivider"
        "XPos"                          "20"
        "YPos"                          "0"
        "ZPos"                          "5"
        "Wide"                          "188"
        "Tall"                          "1"
        "proportionaltoparent"          "1"
        "paintBackground"               "1"
        "paintBackgroundType"           "2"
        "roundedCorners"                "15"
        "bgcolor_override"              "255 255 255 20"
        "pin_to_sibling"                "DefenseDivider"
        "pin_corner_to_sibling"         "PIN_BOTTOMLEFT"
        "pin_to_sibling_corner"         "PIN_BOTTOMRIGHT"
    }
    "ScoutCard"
    {
        "ControlName"                   "EditablePanel"
        "fieldName"                     "ScoutCard"
        "XPos"                          "0"
        "YPos"                          "4"
        "ZPos"                          "5"
        "Wide"                          "60"
        "Tall"                          "75"
        "paintBackground"               "1"
        "paintBackgroundType"           "2"
        "bgcolor_override"              "FinalsCardWhite"
        "mouseinputenabled"             "0"
        "pin_to_sibling"                "OffenseDivider"
        "pin_corner_to_sibling"         "PIN_TOPLEFT"
        "pin_to_sibling_corner"         "PIN_BOTTOMLEFT"
        "ClassImage"
        {
            "ControlName"                   "CTFClassImage"
            "FieldName"                     "ClassImage"
            "XPos"                          "cs-0.5"
            "YPos"                          "rs1-p0.2"
            "ZPos"                          "5"
            "Wide"                          "55"
            "Tall"                          "55"
            "Visible"                       "1"
            "Enabled"                       "1"
            "Image"                         "../hud/class_scoutred"
            "ScaleImage"                    "1"
            "ProportionalToParent"          "1"
        }
        "Footer"
        {
            "ControlName"                   "EditablePanel"
            "fieldName"                     "Footer"
            "XPos"                          "cs-0.5"
            "YPos"                          "rs1"
            "ZPos"                          "5"
            "Wide"                          "f0"
            "Tall"                          "p0.2"
            "proportionaltoparent"          "1"
            "paintBackground"               "1"
            "paintBackgroundType"           "2"
            "roundedCorners"                "12"
            "bgcolor_override"              "Black"
            "ClassLabel"
            {
                "ControlName"                   "Label"
                "fieldName"                     "ClassLabel"
                "xpos"                          "0"
                "ypos"                          "0"
                "zpos"                          "1"
                "wide"                          "f0"
                "tall"                          "f0"
                "proportionaltoparent"          "1"
                "labelText"                     "SCOUT"
                "textAlignment"                 "center"
                "font"                          "CardLabel"
                "visible"                       "1"
                "enabled"                       "1"
                "fgcolor_override"              "White"
            }
        }
    }
    "SoldierCard"
    {
        "ControlName"                   "EditablePanel"
        "fieldName"                     "SoldierCard"
        "XPos"                          "0"
        "YPos"                          "4"
        "ZPos"                          "5"
        "Wide"                          "60"
        "Tall"                          "75"
        "paintBackground"               "1"
        "paintBackgroundType"           "2"
        "bgcolor_override"              "FinalsCardWhite"
        "mouseinputenabled"             "0"
        "pin_to_sibling"                "OffenseDivider"
        "pin_corner_to_sibling"         "PIN_CENTER_TOP"
        "pin_to_sibling_corner"         "PIN_CENTER_BOTTOM"
        "ClassImage"
        {
            "ControlName"                   "CTFClassImage"
            "FieldName"                     "ClassImage"
            "XPos"                          "cs-0.5+2"
            "YPos"                          "rs1-p0.2"
            "ZPos"                          "5"
            "Wide"                          "55"
            "Tall"                          "55"
            "Visible"                       "1"
            "Enabled"                       "1"
            "Image"                         "../hud/class_soldierred"
            "ScaleImage"                    "1"
            "ProportionalToParent"          "1"
        }
        "Footer"
        {
            "ControlName"                   "EditablePanel"
            "fieldName"                     "Footer"
            "XPos"                          "cs-0.5"
            "YPos"                          "rs1"
            "ZPos"                          "5"
            "Wide"                          "f0"
            "Tall"                          "p0.2"
            "proportionaltoparent"          "1"
            "paintBackground"               "1"
            "paintBackgroundType"           "2"
            "roundedCorners"                "12"
            "bgcolor_override"              "Black"
            "ClassLabel"
            {
                "ControlName"                   "Label"
                "fieldName"                     "ClassLabel"
                "xpos"                          "0"
                "ypos"                          "0"
                "zpos"                          "1"
                "wide"                          "f0"
                "tall"                          "f0"
                "proportionaltoparent"          "1"
                "labelText"                     "SOLDIER"
                "textAlignment"                 "center"
                "font"                          "CardLabel"
                "visible"                       "1"
                "enabled"                       "1"
                "fgcolor_override"              "White"
            }
        }
    }
    "PyroCard"
    {
        "ControlName"                   "EditablePanel"
        "fieldName"                     "PyroCard"
        "XPos"                          "0"
        "YPos"                          "4"
        "ZPos"                          "5"
        "Wide"                          "60"
        "Tall"                          "75"
        "paintBackground"               "1"
        "paintBackgroundType"           "2"
        "bgcolor_override"              "FinalsCardWhite"
        "mouseinputenabled"             "0"
        "pin_to_sibling"                "OffenseDivider"
        "pin_corner_to_sibling"         "PIN_TOPRIGHT"
        "pin_to_sibling_corner"         "PIN_BOTTOMRIGHT"
        "ClassImage"
        {
            "ControlName"                   "CTFClassImage"
            "FieldName"                     "ClassImage"
            "XPos"                          "cs-0.5"
            "YPos"                          "rs1-p0.2"
            "ZPos"                          "5"
            "Wide"                          "55"
            "Tall"                          "55"
            "Visible"                       "1"
            "Enabled"                       "1"
            "Image"                         "../hud/class_pyrored"
            "ScaleImage"                    "1"
            "ProportionalToParent"          "1"
        }
        "Footer"
        {
            "ControlName"                   "EditablePanel"
            "fieldName"                     "Footer"
            "XPos"                          "cs-0.5"
            "YPos"                          "rs1"
            "ZPos"                          "5"
            "Wide"                          "f0"
            "Tall"                          "p0.2"
            "proportionaltoparent"          "1"
            "paintBackground"               "1"
            "paintBackgroundType"           "2"
            "roundedCorners"                "12"
            "bgcolor_override"              "Black"
            "ClassLabel"
            {
                "ControlName"                   "Label"
                "fieldName"                     "ClassLabel"
                "xpos"                          "0"
                "ypos"                          "0"
                "zpos"                          "1"
                "wide"                          "f0"
                "tall"                          "f0"
                "proportionaltoparent"          "1"
                "labelText"                     "PYRO"
                "textAlignment"                 "center"
                "font"                          "CardLabel"
                "visible"                       "1"
                "enabled"                       "1"
                "fgcolor_override"              "White"
            }
        }
    }
    "DemoCard"
    {
        "ControlName"                   "EditablePanel"
        "fieldName"                     "DemoCard"
        "XPos"                          "0"
        "YPos"                          "4"
        "ZPos"                          "5"
        "Wide"                          "60"
        "Tall"                          "75"
        "paintBackground"               "1"
        "paintBackgroundType"           "2"
        "bgcolor_override"              "FinalsCardWhite"
        "mouseinputenabled"             "0"
        "pin_to_sibling"                "DefenseDivider"
        "pin_corner_to_sibling"         "PIN_TOPLEFT"
        "pin_to_sibling_corner"         "PIN_BOTTOMLEFT"
        "ClassImage"
        {
            "ControlName"                   "CTFClassImage"
            "FieldName"                     "ClassImage"
            "XPos"                          "cs-0.5"
            "YPos"                          "rs1-p0.2"
            "ZPos"                          "5"
            "Wide"                          "55"
            "Tall"                          "55"
            "Visible"                       "1"
            "Enabled"                       "1"
            "Image"                         "../hud/class_demored"
            "ScaleImage"                    "1"
            "ProportionalToParent"          "1"
        }
        "Footer"
        {
            "ControlName"                   "EditablePanel"
            "fieldName"                     "Footer"
            "XPos"                          "cs-0.5"
            "YPos"                          "rs1"
            "ZPos"                          "5"
            "Wide"                          "f0"
            "Tall"                          "p0.2"
            "proportionaltoparent"          "1"
            "paintBackground"               "1"
            "paintBackgroundType"           "2"
            "roundedCorners"                "12"
            "bgcolor_override"              "Black"
            "ClassLabel"
            {
                "ControlName"                   "Label"
                "fieldName"                     "ClassLabel"
                "xpos"                          "0"
                "ypos"                          "0"
                "zpos"                          "1"
                "wide"                          "f0"
                "tall"                          "f0"
                "proportionaltoparent"          "1"
                "labelText"                     "DEMOMAN"
                "textAlignment"                 "center"
                "font"                          "CardLabel"
                "visible"                       "1"
                "enabled"                       "1"
                "fgcolor_override"              "White"
            }
        }
    }
    "HeavyCard"
    {
        "ControlName"                   "EditablePanel"
        "fieldName"                     "HeavyCard"
        "XPos"                          "0"
        "YPos"                          "4"
        "ZPos"                          "5"
        "Wide"                          "60"
        "Tall"                          "75"
        "paintBackground"               "1"
        "paintBackgroundType"           "2"
        "bgcolor_override"              "FinalsCardWhite"
        "mouseinputenabled"             "0"
        "pin_to_sibling"                "DefenseDivider"
        "pin_corner_to_sibling"         "PIN_CENTER_TOP"
        "pin_to_sibling_corner"         "PIN_CENTER_BOTTOM"
        "ClassImage"
        {
            "ControlName"                   "CTFClassImage"
            "FieldName"                     "ClassImage"
            "XPos"                          "cs-0.5"
            "YPos"                          "rs1-p0.2"
            "ZPos"                          "5"
            "Wide"                          "55"
            "Tall"                          "55"
            "Visible"                       "1"
            "Enabled"                       "1"
            "Image"                         "../hud/class_heavyred"
            "ScaleImage"                    "1"
            "ProportionalToParent"          "1"
        }
        "Footer"
        {
            "ControlName"                   "EditablePanel"
            "fieldName"                     "Footer"
            "XPos"                          "cs-0.5"
            "YPos"                          "rs1"
            "ZPos"                          "5"
            "Wide"                          "f0"
            "Tall"                          "p0.2"
            "proportionaltoparent"          "1"
            "paintBackground"               "1"
            "paintBackgroundType"           "2"
            "roundedCorners"                "12"
            "bgcolor_override"              "Black"
            "ClassLabel"
            {
                "ControlName"                   "Label"
                "fieldName"                     "ClassLabel"
                "xpos"                          "0"
                "ypos"                          "0"
                "zpos"                          "1"
                "wide"                          "f0"
                "tall"                          "f0"
                "proportionaltoparent"          "1"
                "labelText"                     "HEAVY"
                "textAlignment"                 "center"
                "font"                          "CardLabel"
                "visible"                       "1"
                "enabled"                       "1"
                "fgcolor_override"              "White"
            }
        }
    }
    "EngineerCard"
    {
        "ControlName"                   "EditablePanel"
        "fieldName"                     "EngineerCard"
        "XPos"                          "0"
        "YPos"                          "4"
        "ZPos"                          "5"
        "Wide"                          "60"
        "Tall"                          "75"
        "paintBackground"               "1"
        "paintBackgroundType"           "2"
        "bgcolor_override"              "FinalsCardWhite"
        "mouseinputenabled"             "0"
        "pin_to_sibling"                "DefenseDivider"
        "pin_corner_to_sibling"         "PIN_TOPRIGHT"
        "pin_to_sibling_corner"         "PIN_BOTTOMRIGHT"
        "ClassImage"
        {
            "ControlName"                   "CTFClassImage"
            "FieldName"                     "ClassImage"
            "XPos"                          "cs-0.5"
            "YPos"                          "rs1-p0.2"
            "ZPos"                          "5"
            "Wide"                          "55"
            "Tall"                          "55"
            "Visible"                       "1"
            "Enabled"                       "1"
            "Image"                         "../hud/class_engired"
            "ScaleImage"                    "1"
            "ProportionalToParent"          "1"
        }
        "Footer"
        {
            "ControlName"                   "EditablePanel"
            "fieldName"                     "Footer"
            "XPos"                          "cs-0.5"
            "YPos"                          "rs1"
            "ZPos"                          "5"
            "Wide"                          "f0"
            "Tall"                          "p0.2"
            "proportionaltoparent"          "1"
            "paintBackground"               "1"
            "paintBackgroundType"           "2"
            "roundedCorners"                "12"
            "bgcolor_override"              "Black"
            "ClassLabel"
            {
                "ControlName"                   "Label"
                "fieldName"                     "ClassLabel"
                "xpos"                          "0"
                "ypos"                          "0"
                "zpos"                          "1"
                "wide"                          "f0"
                "tall"                          "f0"
                "proportionaltoparent"          "1"
                "labelText"                     "ENGINEER"
                "textAlignment"                 "center"
                "font"                          "CardLabel"
                "visible"                       "1"
                "enabled"                       "1"
                "fgcolor_override"              "White"
            }
        }
    }
    "MedicCard"
    {
        "ControlName"                   "EditablePanel"
        "fieldName"                     "MedicCard"
        "XPos"                          "0"
        "YPos"                          "4"
        "ZPos"                          "5"
        "Wide"                          "60"
        "Tall"                          "75"
        "paintBackground"               "1"
        "paintBackgroundType"           "2"
        "bgcolor_override"              "FinalsCardWhite"
        "mouseinputenabled"             "0"
        "pin_to_sibling"                "SupportDivider"
        "pin_corner_to_sibling"         "PIN_TOPLEFT"
        "pin_to_sibling_corner"         "PIN_BOTTOMLEFT"
        "ClassImage"
        {
            "ControlName"                   "CTFClassImage"
            "FieldName"                     "ClassImage"
            "XPos"                          "cs-0.5"
            "YPos"                          "rs1-p0.2"
            "ZPos"                          "5"
            "Wide"                          "55"
            "Tall"                          "55"
            "Visible"                       "1"
            "Enabled"                       "1"
            "Image"                         "../hud/class_medicred"
            "ScaleImage"                    "1"
            "ProportionalToParent"          "1"
        }
        "Footer"
        {
            "ControlName"                   "EditablePanel"
            "fieldName"                     "Footer"
            "XPos"                          "cs-0.5"
            "YPos"                          "rs1"
            "ZPos"                          "5"
            "Wide"                          "f0"
            "Tall"                          "p0.2"
            "proportionaltoparent"          "1"
            "paintBackground"               "1"
            "paintBackgroundType"           "2"
            "roundedCorners"                "12"
            "bgcolor_override"              "Black"
            "ClassLabel"
            {
                "ControlName"                   "Label"
                "fieldName"                     "ClassLabel"
                "xpos"                          "0"
                "ypos"                          "0"
                "zpos"                          "1"
                "wide"                          "f0"
                "tall"                          "f0"
                "proportionaltoparent"          "1"
                "labelText"                     "MEDIC"
                "textAlignment"                 "center"
                "font"                          "CardLabel"
                "visible"                       "1"
                "enabled"                       "1"
                "fgcolor_override"              "White"
            }
        }
    }
    "SniperCard"
    {
        "ControlName"                   "EditablePanel"
        "fieldName"                     "SniperCard"
        "XPos"                          "0"
        "YPos"                          "4"
        "ZPos"                          "5"
        "Wide"                          "60"
        "Tall"                          "75"
        "paintBackground"               "1"
        "paintBackgroundType"           "2"
        "bgcolor_override"              "FinalsCardWhite"
        "mouseinputenabled"             "0"
        "pin_to_sibling"                "SupportDivider"
        "pin_corner_to_sibling"         "PIN_CENTER_TOP"
        "pin_to_sibling_corner"         "PIN_CENTER_BOTTOM"
        "ClassImage"
        {
            "ControlName"                   "CTFClassImage"
            "FieldName"                     "ClassImage"
            "XPos"                          "cs-0.5"
            "YPos"                          "rs1-p0.2"
            "ZPos"                          "5"
            "Wide"                          "55"
            "Tall"                          "55"
            "Visible"                       "1"
            "Enabled"                       "1"
            "Image"                         "../hud/class_sniperred"
            "ScaleImage"                    "1"
            "ProportionalToParent"          "1"
        }
        "Footer"
        {
            "ControlName"                   "EditablePanel"
            "fieldName"                     "Footer"
            "XPos"                          "cs-0.5"
            "YPos"                          "rs1"
            "ZPos"                          "5"
            "Wide"                          "f0"
            "Tall"                          "p0.2"
            "proportionaltoparent"          "1"
            "paintBackground"               "1"
            "paintBackgroundType"           "2"
            "roundedCorners"                "12"
            "bgcolor_override"              "Black"
            "ClassLabel"
            {
                "ControlName"                   "Label"
                "fieldName"                     "ClassLabel"
                "xpos"                          "0"
                "ypos"                          "0"
                "zpos"                          "1"
                "wide"                          "f0"
                "tall"                          "f0"
                "proportionaltoparent"          "1"
                "labelText"                     "SNIPER"
                "textAlignment"                 "center"
                "font"                          "CardLabel"
                "visible"                       "1"
                "enabled"                       "1"
                "fgcolor_override"              "White"
            }
        }
    }
    "SpyCard"
    {
        "ControlName"                   "EditablePanel"
        "fieldName"                     "SpyCard"
        "XPos"                          "0"
        "YPos"                          "4"
        "ZPos"                          "5"
        "Wide"                          "60"
        "Tall"                          "75"
        "paintBackground"               "1"
        "paintBackgroundType"           "2"
        "bgcolor_override"              "FinalsCardWhite"
        "mouseinputenabled"             "0"
        "pin_to_sibling"                "SupportDivider"
        "pin_corner_to_sibling"         "PIN_TOPRIGHT"
        "pin_to_sibling_corner"         "PIN_BOTTOMRIGHT"
        "ClassImage"
        {
            "ControlName"                   "CTFClassImage"
            "FieldName"                     "ClassImage"
            "XPos"                          "cs-0.5"
            "YPos"                          "rs1-p0.2"
            "ZPos"                          "5"
            "Wide"                          "55"
            "Tall"                          "55"
            "Visible"                       "1"
            "Enabled"                       "1"
            "Image"                         "../hud/class_spyred"
            "ScaleImage"                    "1"
            "ProportionalToParent"          "1"
        }
        "Footer"
        {
            "ControlName"                   "EditablePanel"
            "fieldName"                     "Footer"
            "XPos"                          "cs-0.5"
            "YPos"                          "rs1"
            "ZPos"                          "5"
            "Wide"                          "f0"
            "Tall"                          "p0.2"
            "proportionaltoparent"          "1"
            "paintBackground"               "1"
            "paintBackgroundType"           "2"
            "roundedCorners"                "12"
            "bgcolor_override"              "Black"
            "ClassLabel"
            {
                "ControlName"                   "Label"
                "fieldName"                     "ClassLabel"
                "xpos"                          "0"
                "ypos"                          "0"
                "zpos"                          "1"
                "wide"                          "f0"
                "tall"                          "f0"
                "proportionaltoparent"          "1"
                "labelText"                     "SPY"
                "textAlignment"                 "center"
                "font"                          "CardLabel"
                "visible"                       "1"
                "enabled"                       "1"
                "fgcolor_override"              "White"
            }
        }
    }
    // MARK: Class Controls
    "scout"
    {
        "ControlName"                       "CExButton"
        "fieldName"                         "scout"
        "xpos"                              "0"
        "ypos"                              "1"
        "zpos"                              "-1"
        "wide"                              "62"
        "tall"                              "77"
        "autoResize"                        "0"
        "pinCorner"                         "2"
        "visible"                           "1"
        "enabled"                           "1"
        "tabPosition"                       "0"
        "labelText"                         ""
        "textAlignment"                     "west"
        "Command"                           "select 1"
        "Default"                           "0"
        "font"                              ""
        "sound_depressed"                   "UI/buttonclick.wav"
        "sound_released"                    "UI/buttonclickrelease.wav"
        "sound_armed"                       "UI/buttonrollover.wav"
        "paintBackground"                   "1"
        "paintbackgroundtype"               "2"
        "DefaultBGColor_Override"           "Blank"
        "ArmedBGColor_Override"             "FinalsYellow"
        "DepressedBGColor_Override"         "FinalsYellow"
        "stayselectedonclick"               "1"
        "selectonhover"                     "1"
        "keyboardinputenabled"              "0"
        "pin_to_sibling"                    "ScoutCard"
        "pin_corner_to_sibling"             "PIN_CENTER_TOP"
        "pin_to_sibling_corner"             "PIN_CENTER_TOP"
    }
    "soldier"
    {
        "ControlName"                       "CExButton"
        "fieldName"                         "soldier"
        "xpos"                              "0"
        "ypos"                              "1"
        "zpos"                              "-1"
        "wide"                              "62"
        "tall"                              "77"
        "autoResize"                        "0"
        "pinCorner"                         "2"
        "visible"                           "1"
        "enabled"                           "1"
        "tabPosition"                       "0"
        "labelText"                         ""
        "textAlignment"                     "west"
        "Command"                           "select 3"
        "Default"                           "0"
        "font"                              ""
        "sound_depressed"                   "UI/buttonclick.wav"
        "sound_released"                    "UI/buttonclickrelease.wav"
        "sound_armed"                       "UI/buttonrollover.wav"
        "paintBackground"                   "1"
        "paintbackgroundtype"               "2"
        "DefaultBGColor_Override"           "Blank"
        "ArmedBGColor_Override"             "FinalsYellow"
        "DepressedBGColor_Override"         "FinalsYellow"
        "stayselectedonclick"               "1"
        "selectonhover"                     "1"
        "keyboardinputenabled"              "0"
        "pin_to_sibling"                    "SoldierCard"
        "pin_corner_to_sibling"             "PIN_CENTER_TOP"
        "pin_to_sibling_corner"             "PIN_CENTER_TOP"
    }
    "pyro"
    {
        "ControlName"                       "CExButton"
        "fieldName"                         "pyro"
        "xpos"                              "0"
        "ypos"                              "1"
        "zpos"                              "-1"
        "wide"                              "62"
        "tall"                              "77"
        "autoResize"                        "0"
        "pinCorner"                         "2"
        "visible"                           "1"
        "enabled"                           "1"
        "tabPosition"                       "0"
        "labelText"                         ""
        "textAlignment"                     "west"
        "Command"                           "select 7"
        "Default"                           "0"
        "font"                              ""
        "sound_depressed"                   "UI/buttonclick.wav"
        "sound_released"                    "UI/buttonclickrelease.wav"
        "sound_armed"                       "UI/buttonrollover.wav"
        "paintBackground"                   "1"
        "paintbackgroundtype"               "2"
        "DefaultBGColor_Override"           "Blank"
        "ArmedBGColor_Override"             "FinalsYellow"
        "DepressedBGColor_Override"         "FinalsYellow"
        "stayselectedonclick"               "1"
        "selectonhover"                     "1"
        "keyboardinputenabled"              "0"
        "pin_to_sibling"                    "PyroCard"
        "pin_corner_to_sibling"             "PIN_CENTER_TOP"
        "pin_to_sibling_corner"             "PIN_CENTER_TOP"
    }
    "demoman"
    {
        "ControlName"                       "CExButton"
        "fieldName"                         "demoman"
        "xpos"                              "0"
        "ypos"                              "1"
        "zpos"                              "-1"
        "wide"                              "62"
        "tall"                              "77"
        "autoResize"                        "0"
        "pinCorner"                         "2"
        "visible"                           "1"
        "enabled"                           "1"
        "tabPosition"                       "0"
        "labelText"                         ""
        "textAlignment"                     "west"
        "Command"                           "select 4"
        "Default"                           "0"
        "font"                              ""
        "sound_depressed"                   "UI/buttonclick.wav"
        "sound_released"                    "UI/buttonclickrelease.wav"
        "sound_armed"                       "UI/buttonrollover.wav"
        "paintBackground"                   "1"
        "paintbackgroundtype"               "2"
        "DefaultBGColor_Override"           "Blank"
        "ArmedBGColor_Override"             "FinalsYellow"
        "DepressedBGColor_Override"         "FinalsYellow"
        "stayselectedonclick"               "1"
        "selectonhover"                     "1"
        "keyboardinputenabled"              "0"
        "pin_to_sibling"                    "DemoCard"
        "pin_corner_to_sibling"             "PIN_CENTER_TOP"
        "pin_to_sibling_corner"             "PIN_CENTER_TOP"
    }
    "heavyweapons"
    {
        "ControlName"                       "CExButton"
        "fieldName"                         "heavyweapons"
        "xpos"                              "0"
        "ypos"                              "1"
        "zpos"                              "-1"
        "wide"                              "62"
        "tall"                              "77"
        "autoResize"                        "0"
        "pinCorner"                         "2"
        "visible"                           "1"
        "enabled"                           "1"
        "tabPosition"                       "0"
        "labelText"                         ""
        "textAlignment"                     "west"
        "Command"                           "select 6"
        "Default"                           "0"
        "font"                              ""
        "sound_depressed"                   "UI/buttonclick.wav"
        "sound_released"                    "UI/buttonclickrelease.wav"
        "sound_armed"                       "UI/buttonrollover.wav"
        "paintBackground"                   "1"
        "paintbackgroundtype"               "2"
        "DefaultBGColor_Override"           "Blank"
        "ArmedBGColor_Override"             "FinalsYellow"
        "DepressedBGColor_Override"         "FinalsYellow"
        "stayselectedonclick"               "1"
        "selectonhover"                     "1"
        "keyboardinputenabled"              "0"
        "pin_to_sibling"                    "HeavyCard"
        "pin_corner_to_sibling"             "PIN_CENTER_TOP"
        "pin_to_sibling_corner"             "PIN_CENTER_TOP"
    }
    "engineer"
    {
        "ControlName"                       "CExButton"
        "fieldName"                         "engineer"
        "xpos"                              "0"
        "ypos"                              "1"
        "zpos"                              "-1"
        "wide"                              "62"
        "tall"                              "77"
        "autoResize"                        "0"
        "pinCorner"                         "2"
        "visible"                           "1"
        "enabled"                           "1"
        "tabPosition"                       "0"
        "labelText"                         ""
        "textAlignment"                     "west"
        "Command"                           "select 9"
        "Default"                           "0"
        "font"                              ""
        "sound_depressed"                   "UI/buttonclick.wav"
        "sound_released"                    "UI/buttonclickrelease.wav"
        "sound_armed"                       "UI/buttonrollover.wav"
        "paintBackground"                   "1"
        "paintbackgroundtype"               "2"
        "DefaultBGColor_Override"           "Blank"
        "ArmedBGColor_Override"             "FinalsYellow"
        "DepressedBGColor_Override"         "FinalsYellow"
        "stayselectedonclick"               "1"
        "selectonhover"                     "1"
        "keyboardinputenabled"              "0"
        "pin_to_sibling"                    "EngineerCard"
        "pin_corner_to_sibling"             "PIN_CENTER_TOP"
        "pin_to_sibling_corner"             "PIN_CENTER_TOP"
    }
    "medic"
    {
        "ControlName"                       "CExButton"
        "fieldName"                         "medic"
        "xpos"                              "0"
        "ypos"                              "1"
        "zpos"                              "-1"
        "wide"                              "62"
        "tall"                              "77"
        "autoResize"                        "0"
        "pinCorner"                         "2"
        "visible"                           "1"
        "enabled"                           "1"
        "tabPosition"                       "0"
        "labelText"                         ""
        "textAlignment"                     "west"
        "Command"                           "select 5"
        "Default"                           "0"
        "font"                              ""
        "sound_depressed"                   "UI/buttonclick.wav"
        "sound_released"                    "UI/buttonclickrelease.wav"
        "sound_armed"                       "UI/buttonrollover.wav"
        "paintBackground"                   "1"
        "paintbackgroundtype"               "2"
        "DefaultBGColor_Override"           "Blank"
        "ArmedBGColor_Override"             "FinalsYellow"
        "DepressedBGColor_Override"         "FinalsYellow"
        "stayselectedonclick"               "1"
        "selectonhover"                     "1"
        "keyboardinputenabled"              "0"
        "pin_to_sibling"                    "MedicCard"
        "pin_corner_to_sibling"             "PIN_CENTER_TOP"
        "pin_to_sibling_corner"             "PIN_CENTER_TOP"
    }
    "sniper"
    {
        "ControlName"                       "CExButton"
        "fieldName"                         "sniper"
        "xpos"                              "0"
        "ypos"                              "1"
        "zpos"                              "-1"
        "wide"                              "62"
        "tall"                              "77"
        "autoResize"                        "0"
        "pinCorner"                         "2"
        "visible"                           "1"
        "enabled"                           "1"
        "tabPosition"                       "0"
        "labelText"                         ""
        "textAlignment"                     "west"
        "Command"                           "select 2"
        "Default"                           "0"
        "font"                              ""
        "sound_depressed"                   "UI/buttonclick.wav"
        "sound_released"                    "UI/buttonclickrelease.wav"
        "sound_armed"                       "UI/buttonrollover.wav"
        "paintBackground"                   "1"
        "paintbackgroundtype"               "2"
        "DefaultBGColor_Override"           "Blank"
        "ArmedBGColor_Override"             "FinalsYellow"
        "DepressedBGColor_Override"         "FinalsYellow"
        "stayselectedonclick"               "1"
        "selectonhover"                     "1"
        "keyboardinputenabled"              "0"
        "pin_to_sibling"                    "SniperCard"
        "pin_corner_to_sibling"             "PIN_CENTER_TOP"
        "pin_to_sibling_corner"             "PIN_CENTER_TOP"
    }
    "spy"
    {
        "ControlName"                       "CExButton"
        "fieldName"                         "spy"
        "xpos"                              "0"
        "ypos"                              "1"
        "zpos"                              "-1"
        "wide"                              "62"
        "tall"                              "77"
        "autoResize"                        "0"
        "pinCorner"                         "2"
        "visible"                           "1"
        "enabled"                           "1"
        "tabPosition"                       "0"
        "labelText"                         ""
        "textAlignment"                     "west"
        "Command"                           "select 8"
        "Default"                           "0"
        "font"                              ""
        "scaleImage"                        "1"
        "sound_depressed"                   "UI/buttonclick.wav"
        "sound_released"                    "UI/buttonclickrelease.wav"
        "sound_armed"                       "UI/buttonrollover.wav"
        "paintBackground"                   "1"
        "paintbackgroundtype"               "2"
        "DefaultBGColor_Override"           "Blank"
        "ArmedBGColor_Override"             "FinalsYellow"
        "DepressedBGColor_Override"         "FinalsYellow"
        "stayselectedonclick"               "1"
        "selectonhover"                     "1"
        "keyboardinputenabled"              "0"
        "pin_to_sibling"                    "SpyCard"
        "pin_corner_to_sibling"             "PIN_CENTER_TOP"
        "pin_to_sibling_corner"             "PIN_CENTER_TOP"
    }
    "random"	// dead
    {
        "ControlName"                       "CExButton"
        "fieldName"                         "random"
        "xpos"                              "99999"
        "ypos"                              "99999"
        "zpos"                              "6"
        "wide"                              "0"
        "tall"                              "0"
        "autoResize"                        "0"
        "pinCorner"                         "2"
        "visible"                           "1"
        "enabled"                           "1"
        "tabPosition"                       "0"
        "labelText"                         "&R   Random"
        "textAlignment"                     "west"
        "Command"                           "select 12"
        "Default"                           "1"
        "font"                              ""
        "FgColor"                           "White"
        "defaultFgColor_override"           "White"
        "armedFgColor_override"             "White"
        "depressedFgColor_override"         "White"
        "selectedFgColor_override"          "White"
        "sound_depressed"                   "UI/buttonclick.wav"
        "sound_released"                    "UI/buttonclickrelease.wav"
        "sound_armed"                       "UI/buttonrollover.wav"
        "paintbackground"                   "0"
        "stayselectedonclick"               "1"
        "selectonhover"                     "1"
        "keyboardinputenabled"              "0"
    }
    "EditLoadoutButton"
    {
        "ControlName"                       "CExButton"
        "fieldName"                         "EditLoadoutButton"
        "XPos"                              "15"
        "YPos"                              "rs1-15"
        "ZPos"                              "15"
        "Wide"                              "24"
        "Tall"                              "24"
        "autoResize"                        "0"
        "pinCorner"                         "3"
        "visible"                           "1"
        "enabled"                           "1"
        "tabPosition"                       "0"
        "labelText"                         "&E"
        "font"                              "BodyEm_MD"
        "textAlignment"                     "center"
        "dulltext"                          "0"
        "brighttext"                        "0"
        "default"                           "0"
        "Command"                           "openloadout"
        "sound_depressed"                   "UI/buttonclick.wav"
        "sound_released"                    "UI/buttonclickrelease.wav"
        "DefaultFGColor_Override"           "FinalsGreyDark"
        "ArmedFGColor_Override"             "Menu_Accent"
        "DepressedFGColor_Override"         "Menu_Accent"
        "paintBackground"                   "1"
        "paintbackgroundtype"               "2"
        "DefaultBGColor_Override"           "FinalsKeyBG"
        "ArmedBGColor_Override"             "FinalsKeyBGD_Armed"
        "DepressedBGColor_Override"         "FinalsKeyBGD_Armed"
    }
    "EditLoadoutButton2"
    {
        "ControlName"                       "CExButton"
        "fieldName"                         "EditLoadoutButton2"
        "xpos"                              "-2"
        "ypos"                              "0"
        "zpos"                              "2"
        "wide"                              "80"
        "tall"                              "17"
        "autoResize"                        "0"
        "pinCorner"                         "3"
        "visible"                           "1"
        "enabled"                           "1"
        "tabPosition"                       "0"
        "labelText"                         "EDIT LOADOUT"
        "font"                              "BodyEm_MD"
        "textAlignment"                     "west"
        "dulltext"                          "0"
        "brighttext"                        "0"
        "default"                           "0"
        "Command"                           "openloadout"
        "paintbackgroundtype"               "2"
        "paintbackground"                   "1"
        "sound_depressed"                   "UI/buttonclick.wav"
        "sound_released"                    "UI/buttonclickrelease.wav"
        "defaultBgColor_override"           "0 0 0 0"
        "armedBgColor_override"             "0 0 0 0"
        "depressedBgColor_override"         "0 0 0 0"
        "defaultFgColor_override"           "WHITE"
        "armedFgColor_override"             "WHITE"
        "depressedFgColor_override"         "WHITE"
        "border_default"                    "NoBorder"
        "border_armed"                      "NoBorder"
        "pin_to_sibling"                    "EditLoadoutButton"
        "pin_corner_to_sibling"             "pin_center_left"
        "pin_to_sibling_corner"             "pin_center_right"
    }
    "CancelButton"	// dead
    {
        "ControlName"           "CExButton"
        "fieldName"             "CancelButton"
        "XPos"                  "999"
        "YPos"                  "999"
        "ZPos"                  "0"
        "Wide"                  "0"
        "Tall"                  "0"
        "visible"               "0"
        "enabled"               "0"
    }
    "CancelButtonReal"
    {
        "ControlName"                       "CExButton"
        "fieldName"                         "CancelButtonReal"
        "XPos"                              "0"
        "YPos"                              "0"
        "ZPos"                              "15"
        "Wide"                              "24"
        "Tall"                              "24"
        "autoResize"                        "0"
        "pinCorner"                         "3"
        "visible"                           "1"
        "enabled"                           "1"
        "tabPosition"                       "0"
        "labelText"                         "&Q"
        "font"                              "BodyEm_MD"
        "textAlignment"                     "center"
        "dulltext"                          "0"
        "brighttext"                        "0"
        "default"                           "0"
        "Command"                           "vguicancel"
        "sound_depressed"                   "UI/buttonclick.wav"
        "sound_released"                    "UI/buttonclickrelease.wav"
        "DefaultFGColor_Override"           "FinalsGreyDark"
        "ArmedFGColor_Override"             "Menu_Accent"
        "DepressedFGColor_Override"         "Menu_Accent"
        "paintBackground"                   "1"
        "paintbackgroundtype"               "2"
        "DefaultBGColor_Override"           "FinalsKeyBG"
        "ArmedBGColor_Override"             "FinalsKeyBGD_Armed"
        "DepressedBGColor_Override"         "FinalsKeyBGD_Armed"
        "pin_to_sibling"                    "EditLoadoutButton2"
        "pin_corner_to_sibling"             "pin_center_left"
        "pin_to_sibling_corner"             "pin_center_right"
    }
    "CancelButton2"
    {
        "ControlName"                       "CExButton"
        "fieldName"                         "CancelButton2"
        "xpos"                              "0"
        "ypos"                              "0"
        "zpos"                              "2"
        "wide"                              "40"
        "tall"                              "17"
        "autoResize"                        "0"
        "pinCorner"                         "3"
        "visible"                           "1"
        "enabled"                           "1"
        "tabPosition"                       "0"
        "labelText"                         "BACK"
        "font"                              "BodyEm_MD"
        "textAlignment"                     "center"
        "dulltext"                          "0"
        "brighttext"                        "0"
        "default"                           "0"
        "Command"                           "back"
        "paintbackgroundtype"               "2"
        "paintbackground"                   "1"
        "sound_depressed"                   "UI/buttonclick.wav"
        "sound_released"                    "UI/buttonclickrelease.wav"
        "defaultBgColor_override"           "0 0 0 0"
        "armedBgColor_override"             "0 0 0 0"
        "depressedBgColor_override"         "0 0 0 0"
        "defaultFgColor_override"           "White"
        "armedFgColor_override"             "White"
        "depressedFgColor_override"         "White"
        "border_default"                    "NoBorder"
        "border_armed"                      "NoBorder"
        "pin_to_sibling"                    "CancelButtonReal"
        "pin_corner_to_sibling"             "pin_center_left"
        "pin_to_sibling_corner"             "pin_center_right"
    }
    "ResetButton" [$WIN32]
    {
        "ControlName"           "CExButton"
        "fieldName"             "ResetButton"
        "xpos"                  "9999"
        "ypos"                  "9999"
        "zpos"                  "6"
        "wide"                  "110"
        "tall"                  "25"
        "autoResize"            "0"
        "pinCorner"             "2"
        "visible"               "0"
        "enabled"               "0"
        "tabPosition"           "0"
        "labelText"             "#TF_ClassMenu_Reset"
        "textAlignment"         "center"
        "Command"               "resetclass"
        "font"                  "HudFontSmallBold"
    }
    "ClassMenuSelect"	// dead
    {
        "ControlName"           "CExLabel"
        "fieldName"             "ClassMenuSelect"
        "xpos"                  "9999"
        "ypos"                  "9999"
        "zpos"                  "5"
        "wide"                  "0"
        "tall"                  "0"
        "autoResize"            "0"
        "pinCorner"             "0"
        "visible"               "0"
        "enabled"               "0"
        "labelText"             "#TF_SelectAClass"
        "textAlignment"         "west"
        "font"                  "MenuMainTitle"
        "fgcolor"               "HudOffWhite"
    }
    "MenuBG"
    {
        "ControlName"           "ImagePanel"
        "fieldName"             "MenuBG"
        "xpos"                  "0"
        "ypos"                  "0"
        "zpos"                  "-1000001"
        "wide"                  "f0"
        "tall"                  "480"
        "autoResize"            "0"
        "pinCorner"             "0"
        "visible"               "1"
        "enabled"               "1"
        "fillcolor"             "TransparentBlack"
    }
    "Hint"
    {
        "ControlName"           "CExLabel"
        "fieldName"             "Hint"
        "xpos"                  "9999"
        "ypos"                  "9999"
        "zpos"                  "2"
        "wide"                  "600"
        "tall"                  "50"
        "autoResize"            "1"
        "pinCorner"             "2"
        "visible"               "0"
        "enabled"               "0"
        "tabPosition"           "0"
        "labelText"             "%hint%"
        "textAlignment"         "left"
        "wrap"                  "1"
        "font"                  "HudFontMediumSmallSecondary"
        "fgcolor"               "HudTrainingHint"
    }
    "ShadedBar"
    {
        "ControlName"                   "ImagePanel"
        "fieldName"                     "ShadedBar"
        "xpos"                          "0"
        "ypos"                          "0"
        "zpos"                          "0"
        "wide"                          "0"
        "tall"                          "0"
        "visible"                       "0"
        "enabled"                       "0"
        "PaintBackgroundType"           "0"
        "fillcolor"                     ""
    }
    "localPlayerImage"
    {
        "ControlName"           "CTFImagePanel"
        "fieldName"             "localPlayerImage"
        "xpos"                  "9999"
        "ypos"                  "9999"
        "zpos"                  "9"
        "wide"                  "45"
        "tall"                  "90"
        "visible"               "0"
        "enabled"               "0"
        "image"                 ""
        "scaleImage"            "0"
    }
    "localPlayerBG"
    {
        "ControlName"               "CTFImagePanel"
        "fieldName"                 "localPlayerBG"
        "xpos"                      "9999"
        "ypos"                      "9999"
        "zpos"                      "2"
        "wide"                      "55"
        "tall"                      "80"
        "autoResize"                "0"
        "pinCorner"                 "0"
        "visible"                   "0"
        "enabled"                   "0"
        "image"                     "../hud/color_panel_clear"
        "scaleImage"                "1"
        "teambg_2"                  "../hud/color_panel_clear"
        "teambg_3"                  "../hud/color_panel_clear"
        "src_corner_height"         "23"	// pixels inside the image
        "src_corner_width"          "23"
        "draw_corner_width"         "5"	// screen size of the corners ( and sides ), proportional
        "draw_corner_height"        "5"
    }
    "countImage0" [$WIN32]
    {
        "ControlName"           "CTFImagePanel"
        "fieldName"             "countImage0"
        "xpos"                  "9999"
        "ypos"                  "9999"
        "zpos"                  "9"
        "wide"                  "30"
        "tall"                  "60"
        "visible"               "0"
        "enabled"               "0"
        "image"                 ""
        "scaleImage"            "1"
    }
    "countImage1" [$WIN32]
    {
        "ControlName"           "CTFImagePanel"
        "fieldName"             "countImage1"
        "xpos"                  "9999"
        "ypos"                  "9999"
        "zpos"                  "9"
        "wide"                  "30"
        "tall"                  "60"
        "visible"               "0"
        "enabled"               "0"
        "image"                 ""
        "scaleImage"            "1"
    }
    "countImage2" [$WIN32]
    {
        "ControlName"           "CTFImagePanel"
        "fieldName"             "countImage2"
        "xpos"                  "9999"
        "ypos"                  "9999"
        "zpos"                  "9"
        "wide"                  "30"
        "tall"                  "60"
        "visible"               "0"
        "enabled"               "0"
        "image"                 ""
        "scaleImage"            "1"
    }
    "countImage3" [$WIN32]
    {
        "ControlName"           "CTFImagePanel"
        "fieldName"             "countImage3"
        "xpos"                  "9999"
        "ypos"                  "9999"
        "zpos"                  "9"
        "wide"                  "30"
        "tall"                  "60"
        "visible"               "0"
        "enabled"               "0"
        "image"                 ""
        "scaleImage"            "1"
    }
    "countImage4" [$WIN32]
    {
        "ControlName"           "CTFImagePanel"
        "fieldName"             "countImage4"
        "xpos"                  "9999"
        "ypos"                  "9999"
        "zpos"                  "9"
        "wide"                  "30"
        "tall"                  "60"
        "visible"               "0"
        "enabled"               "0"
        "image"                 ""
        "scaleImage"            "1"
    }
    "countImage5" [$WIN32]
    {
        "ControlName"           "CTFImagePanel"
        "fieldName"             "countImage5"
        "xpos"                  "9999"
        "ypos"                  "9999"
        "zpos"                  "9"
        "wide"                  "30"
        "tall"                  "60"
        "visible"               "0"
        "enabled"               "0"
        "image"                 ""
        "scaleImage"            "1"
    }
    "countImage6" [$WIN32]
    {
        "ControlName"           "CTFImagePanel"
        "fieldName"             "countImage6"
        "xpos"                  "9999"
        "ypos"                  "9999"
        "zpos"                  "9"
        "wide"                  "30"
        "tall"                  "60"
        "visible"               "0"
        "enabled"               "0"
        "image"                 ""
        "scaleImage"            "1"
    }
    "countImage7" [$WIN32]
    {
        "ControlName"           "CTFImagePanel"
        "fieldName"             "countImage7"
        "xpos"                  "9999"
        "ypos"                  "9999"
        "zpos"                  "9"
        "wide"                  "30"
        "tall"                  "60"
        "visible"               "0"
        "enabled"               "0"
        "image"                 ""
        "scaleImage"            "1"
    }
    "countImage8" [$WIN32]
    {
        "ControlName"           "CTFImagePanel"
        "fieldName"             "countImage8"
        "xpos"                  "9999"
        "ypos"                  "9999"
        "zpos"                  "9"
        "wide"                  "30"
        "tall"                  "60"
        "visible"               "0"
        "enabled"               "0"
        "image"                 ""
        "scaleImage"            "1"
    }
    "countImage9" [$WIN32]
    {
        "ControlName"           "CTFImagePanel"
        "fieldName"             "countImage9"
        "xpos"                  "9999"
        "ypos"                  "9999"
        "zpos"                  "9"
        "wide"                  "30"
        "tall"                  "60"
        "visible"               "0"
        "enabled"               "0"
        "image"                 ""
        "scaleImage"            "1"
    }
    "countImage10" [$WIN32]
    {
        "ControlName"           "CTFImagePanel"
        "fieldName"             "countImage10"
        "xpos"                  "9999"
        "ypos"                  "9999"
        "zpos"                  "9"
        "wide"                  "30"
        "tall"                  "60"
        "visible"               "0"
        "enabled"               "0"
        "image"                 ""
        "scaleImage"            "1"
    }
    "CountLabel" [$WIN32]
    {
        "ControlName"           "CExLabel"
        "fieldName"             "CountLabel"
        "xpos"                  "9999"
        "ypos"                  "9999"
        "zpos"                  "10"
        "wide"                  "150"
        "tall"                  "18"
        "autoResize"            "1"
        "pinCorner"             "2"
        "visible"               "0"
        "enabled"               "0"
        "tabPosition"           "0"
        "labelText"             "#TF_TeamCount"
        "textAlignment"         "left"
        "font"                  "HudFontMediumSmallSecondary"
        "fgcolor"               "owFULLWHITE"
    }
    "numScout"
    {
        "ControlName"                   "CExLabel"
        "fieldName"                     "numScout"
        "xpos"                          "-2"
        "ypos"                          "-2"
        "zpos"                          "6"
        "wide"                          "13"
        "tall"                          "13"
        "autoResize"                    "1"
        "pinCorner"                     "2"
        "visible"                       "1"
        "enabled"                       "1"
        "tabPosition"                   "0"
        "labelText"                     "%numScout%"
        "textAlignment"                 "center"
        "font"                          "Header_SM"
        "fgcolor"                       "Black"
        "pin_to_sibling"                "ScoutCard"
        "pin_corner_to_sibling"         "PIN_TOPLEFT"
        "pin_to_sibling_corner"         "PIN_TOPLEFT"
    }
    "numSoldier"
    {
        "ControlName"                   "CExLabel"
        "fieldName"                     "numSoldier"
        "xpos"                          "-2"
        "ypos"                          "-2"
        "zpos"                          "6"
        "wide"                          "13"
        "tall"                          "13"
        "autoResize"                    "1"
        "pinCorner"                     "2"
        "visible"                       "1"
        "enabled"                       "1"
        "tabPosition"                   "0"
        "labelText"                     "%numSoldier%"
        "textAlignment"                 "center"
        "font"                          "Header_SM"
        "fgcolor"                       "Black"
        "pin_to_sibling"                "SoldierCard"
        "pin_corner_to_sibling"         "PIN_TOPLEFT"
        "pin_to_sibling_corner"         "PIN_TOPLEFT"
    }
    "numPyro"
    {
        "ControlName"                   "CExLabel"
        "fieldName"                     "numPyro"
        "xpos"                          "-2"
        "ypos"                          "-2"
        "zpos"                          "6"
        "wide"                          "13"
        "tall"                          "13"
        "autoResize"                    "1"
        "pinCorner"                     "2"
        "visible"                       "1"
        "enabled"                       "1"
        "tabPosition"                   "0"
        "labelText"                     "%numPyro%"
        "textAlignment"                 "center"
        "font"                          "Header_SM"
        "fgcolor"                       "Black"
        "pin_to_sibling"                "PyroCard"
        "pin_corner_to_sibling"         "PIN_TOPLEFT"
        "pin_to_sibling_corner"         "PIN_TOPLEFT"
    }
    "numDemoman"
    {
        "ControlName"                   "CExLabel"
        "fieldName"                     "numDemoman"
        "xpos"                          "-2"
        "ypos"                          "-2"
        "zpos"                          "6"
        "wide"                          "13"
        "tall"                          "13"
        "autoResize"                    "1"
        "pinCorner"                     "2"
        "visible"                       "1"
        "enabled"                       "1"
        "tabPosition"                   "0"
        "labelText"                     "%numDemoman%"
        "textAlignment"                 "center"
        "font"                          "Header_SM"
        "fgcolor"                       "Black"
        "pin_to_sibling"                "DemoCard"
        "pin_corner_to_sibling"         "PIN_TOPLEFT"
        "pin_to_sibling_corner"         "PIN_TOPLEFT"
    }
    "numHeavy"
    {
        "ControlName"                   "CExLabel"
        "fieldName"                     "numHeavy"
        "xpos"                          "-2"
        "ypos"                          "-2"
        "zpos"                          "6"
        "wide"                          "13"
        "tall"                          "13"
        "autoResize"                    "1"
        "pinCorner"                     "2"
        "visible"                       "1"
        "enabled"                       "1"
        "tabPosition"                   "0"
        "labelText"                     "%numHeavy%"
        "textAlignment"                 "center"
        "font"                          "Header_SM"
        "fgcolor"                       "Black"
        "pin_to_sibling"                "HeavyCard"
        "pin_corner_to_sibling"         "PIN_TOPLEFT"
        "pin_to_sibling_corner"         "PIN_TOPLEFT"
    }
    "numEngineer"
    {
        "ControlName"                   "CExLabel"
        "fieldName"                     "numEngineer"
        "xpos"                          "-2"
        "ypos"                          "-2"
        "zpos"                          "6"
        "wide"                          "13"
        "tall"                          "13"
        "autoResize"                    "1"
        "pinCorner"                     "2"
        "visible"                       "1"
        "enabled"                       "1"
        "tabPosition"                   "0"
        "labelText"                     "%numEngineer%"
        "textAlignment"                 "center"
        "font"                          "Header_SM"
        "fgcolor"                       "Black"
        "pin_to_sibling"                "EngineerCard"
        "pin_corner_to_sibling"         "PIN_TOPLEFT"
        "pin_to_sibling_corner"         "PIN_TOPLEFT"
    }
    "numMedic"
    {
        "ControlName"                   "CExLabel"
        "fieldName"                     "numMedic"
        "xpos"                          "-2"
        "ypos"                          "-2"
        "zpos"                          "6"
        "wide"                          "13"
        "tall"                          "13"
        "autoResize"                    "1"
        "pinCorner"                     "2"
        "visible"                       "1"
        "enabled"                       "1"
        "tabPosition"                   "0"
        "labelText"                     "%numMedic%"
        "textAlignment"                 "center"
        "font"                          "Header_SM"
        "fgcolor"                       "Black"
        "pin_to_sibling"                "MedicCard"
        "pin_corner_to_sibling"         "PIN_TOPLEFT"
        "pin_to_sibling_corner"         "PIN_TOPLEFT"
    }
    "numSniper"
    {
        "ControlName"                   "CExLabel"
        "fieldName"                     "numSniper"
        "xpos"                          "-2"
        "ypos"                          "-2"
        "zpos"                          "6"
        "wide"                          "13"
        "tall"                          "13"
        "autoResize"                    "1"
        "pinCorner"                     "2"
        "visible"                       "1"
        "enabled"                       "1"
        "tabPosition"                   "0"
        "labelText"                     "%numSniper%"
        "textAlignment"                 "center"
        "font"                          "Header_SM"
        "fgcolor"                       "Black"
        "pin_to_sibling"                "SniperCard"
        "pin_corner_to_sibling"         "PIN_TOPLEFT"
        "pin_to_sibling_corner"         "PIN_TOPLEFT"
    }
    "numSpy"
    {
        "ControlName"                   "CExLabel"
        "fieldName"                     "numSpy"
        "xpos"                          "-2"
        "ypos"                          "-2"
        "zpos"                          "6"
        "wide"                          "13"
        "tall"                          "13"
        "autoResize"                    "1"
        "pinCorner"                     "2"
        "visible"                       "1"
        "enabled"                       "1"
        "tabPosition"                   "0"
        "labelText"                     "%numSpy%"
        "textAlignment"                 "center"
        "font"                          "Header_SM"
        "fgcolor"                       "Black"
        "pin_to_sibling"                "SpyCard"
        "pin_corner_to_sibling"         "PIN_TOPLEFT"
        "pin_to_sibling_corner"         "PIN_TOPLEFT"
    }
    "MvMUpgradeImageScout"
    {
        "ControlName"           "ImagePanel"
        "fieldName"             "MvMUpgradeImageScout"
        "xpos"                  "c83"
        "ypos"                  "c-63"
        "zpos"                  "10"
        "wide"                  "14"
        "tall"                  "14"
        "visible"               "0"
        "enabled"               "1"
        "image"                 "mvm/class_upgraded"
        "scaleImage"            "1"
    }
    "MvMUpgradeImageSolider"
    {
        "ControlName"           "ImagePanel"
        "fieldName"             "MvMUpgradeImageSolider"
        "xpos"                  "c83"
        "ypos"                  "c-49"
        "zpos"                  "10"
        "wide"                  "14"
        "tall"                  "14"
        "visible"               "0"
        "enabled"               "1"
        "image"                 "mvm/class_upgraded"
        "scaleImage"            "1"
    }
    "MvMUpgradeImagePyro"
    {
        "ControlName"           "ImagePanel"
        "fieldName"             "MvMUpgradeImagePyro"
        "xpos"                  "c83"
        "ypos"                  "c-35"
        "zpos"                  "10"
        "wide"                  "14"
        "tall"                  "14"
        "visible"               "0"
        "enabled"               "1"
        "image"                 "mvm/class_upgraded"
        "scaleImage"            "1"
    }
    "MvMUpgradeImageDemoman"
    {
        "ControlName"           "ImagePanel"
        "fieldName"             "MvMUpgradeImageDemoman"
        "xpos"                  "c83"
        "ypos"                  "c-21"
        "zpos"                  "10"
        "wide"                  "14"
        "tall"                  "14"
        "visible"               "0"
        "enabled"               "1"
        "image"                 "mvm/class_upgraded"
        "scaleImage"            "1"
    }
    "MvMUpgradeImageHeavy"
    {
        "ControlName"           "ImagePanel"
        "fieldName"             "MvMUpgradeImageHeavy"
        "xpos"                  "c83"
        "ypos"                  "c-7"
        "zpos"                  "10"
        "wide"                  "14"
        "tall"                  "14"
        "visible"               "0"
        "enabled"               "1"
        "image"                 "mvm/class_upgraded"
        "scaleImage"            "1"
    }
    "MvMUpgradeImageEngineer"
    {
        "ControlName"           "ImagePanel"
        "fieldName"             "MvMUpgradeImageEngineer"
        "xpos"                  "c83"
        "ypos"                  "c7"
        "zpos"                  "10"
        "wide"                  "14"
        "tall"                  "14"
        "visible"               "0"
        "enabled"               "1"
        "image"                 "mvm/class_upgraded"
        "scaleImage"            "1"
    }
    "MvMUpgradeImageMedic"
    {
        "ControlName"           "ImagePanel"
        "fieldName"             "MvMUpgradeImageMedic"
        "xpos"                  "c83"
        "ypos"                  "c21"
        "zpos"                  "10"
        "wide"                  "14"
        "tall"                  "14"
        "visible"               "0"
        "enabled"               "1"
        "image"                 "mvm/class_upgraded"
        "scaleImage"            "1"
    }
    "MvMUpgradeImageSniper"
    {
        "ControlName"           "ImagePanel"
        "fieldName"             "MvMUpgradeImageSniper"
        "xpos"                  "c83"
        "ypos"                  "c35"
        "zpos"                  "10"
        "wide"                  "14"
        "tall"                  "14"
        "visible"               "0"
        "enabled"               "1"
        "image"                 "mvm/class_upgraded"
        "scaleImage"            "1"
    }
    "MvMUpgradeImageSpy"
    {
        "ControlName"           "ImagePanel"
        "fieldName"             "MvMUpgradeImageSpy"
        "xpos"                  "c83"
        "ypos"                  "c49"
        "zpos"                  "10"
        "wide"                  "14"
        "tall"                  "14"
        "visible"               "0"
        "enabled"               "1"
        "image"                 "mvm/class_upgraded"
        "scaleImage"            "1"
    }
    "StartExplanation"
    {
        "ControlName"                   "CExplanationPopup"
        "fieldName"                     "StartExplanation"
        "xpos"                          "0"
        "ypos"                          "0"
        "zpos"                          "10000"
        "wide"                          "250"
        "tall"                          "165"
        "visible"                       "0"
        "PaintBackgroundType"           "2"
        "paintbackground"               "0"
        "border"                        "MainMenuHighlightBorder"
        "force_close"                   "1"
        "end_x"                         "c-170"
        "end_y"                         "115"
        "end_wide"                      "300"
        "end_tall"                      "240"
        "callout_inparents_x"           "c-270"
        "callout_inparents_y"           "40"
        "next_explanation"              "VoucherExplanation"
        "TitleLabel"
        {
            "ControlName"               "CExLabel"
            "fieldName"                 "TitleLabel"
            "font"                      "HudFontSmallBold"
            "labelText"                 "#TF_MvM_UpgradeExplanation_Title"
            "textAlignment"             "north"
            "xpos"                      "20"
            "ypos"                      "10"
            "wide"                      "260"
            "tall"                      "30"
            "autoResize"                "0"
            "pinCorner"                 "0"
            "visible"                   "1"
            "enabled"                   "1"
            "wrap"                      "1"
            "fgcolor_override"          "46 43 42 255"
        }
        "TextLabel"
        {
            "ControlName"               "CExLabel"
            "fieldName"                 "TextLabel"
            "font"                      "HudFontSmall"
            "labelText"                 "#TF_MvM_UpgradeExplanation_Text"
            "textAlignment"             "north-west"
            "xpos"                      "20"
            "ypos"                      "45"
            "wide"                      "260"
            "tall"                      "170"
            "autoResize"                "0"
            "pinCorner"                 "0"
            "visible"                   "1"
            "enabled"                   "1"
            "wrap"                      "1"
            "fgcolor_override"          "46 43 42 255"
        }
        "CloseButton"
        {
            "ControlName"                       "CExImageButton"
            "fieldName"                         "CloseButton"
            "xpos"                              "280"
            "ypos"                              "5"
            "zpos"                              "10"
            "wide"                              "14"
            "tall"                              "14"
            "autoResize"                        "0"
            "pinCorner"                         "0"
            "visible"                           "0"
            "enabled"                           "0"
            "tabPosition"                       "0"
            "labeltext"                         ""
            "font"                              "HudFontSmallBold"
            "textAlignment"                     "center"
            "dulltext"                          "0"
            "brighttext"                        "0"
            "default"                           "0"
            "sound_depressed"                   "UI/buttonclick.wav"
            "sound_released"                    "UI/buttonclickrelease.wav"
            "Command"                           "close"
            "paintbackground"                   "0"
            "defaultFgColor_override"           "46 43 42 255"
            "armedFgColor_override"             "oworange"
            "depressedFgColor_override"         "46 43 42 255"
            "image_drawcolor"                   "117 107 94 255"
            "image_armedcolor"                  "oworange"
            "SubImage"
            {
                "ControlName"           "ImagePanel"
                "fieldName"             "SubImage"
                "xpos"                  "0"
                "ypos"                  "0"
                "zpos"                  "1"
                "wide"                  "14"
                "tall"                  "14"
                "visible"               "1"
                "enabled"               "1"
                "image"                 "close_button"
                "scaleImage"            "1"
            }
        }
    }
    // MARK: Player Model
    "TFPlayerModel"
    {
        "ControlName"                   "CTFPlayerModelPanel"
        "fieldName"                     "TFPlayerModel"
        "xpos"                          "0"
        "ypos"                          "0"
        "zpos"                          "-10000"
        "wide"                          "f0"
        "tall"                          "f0"
        "autoResize"                    "0"
        "pinCorner"                     "0"
        "visible"                       "1"
        "enabled"                       "1"
        "render_texture"                "0"
        "fov"                           "20"
        "allow_rot"                     "0"
        "paintbackground"               "1"
        "paintbackgroundenabled"        "1"
        "bgcolor_override"              "255 255 255 0"
        "model"
        {
            "force_pos"             "1"
            "angles_x"              "0"
            "angles_y"              "180"
            "angles_z"              "0"
            "origin_x"              "600"	// distance from camera
            "origin_y"              "-5"	// right to left
            "origin_z"              "-50"	// bottom to top
            "frame_origin_x"        "0"
            "frame_origin_y"        "0"
            "frame_origin_z"        "0"
            "spotlight"             "1"
            "modelname"             ""
            "vcd"                   "class_select.vcd"
            "animation"
            {
                "name"              "PRIMARY"
                "activity"          "ACT_MP_STAND_PRIMARY"
                "default"           "1"
            }
            "animation"
            {
                "name"              "SECONDARY"
                "activity"          "ACT_MP_STAND_SECONDARY"
            }
            "animation"
            {
                "name"              "MELEE"
                "activity"          "ACT_MP_STAND_MELEE"
            }
            "animation"
            {
                "name"              "BUILDING"
                "activity"          "ACT_MP_STAND_BUILDING"
            }
            "animation"
            {
                "name"              "PDA"
                "activity"          "ACT_MP_STAND_PDA"
            }
            "animation"
            {
                "name"              "ITEM1"
                "activity"          "ACT_MP_STAND_ITEM1"
            }
            "animation"
            {
                "name"              "ITEM2"
                "activity"          "ACT_MP_STAND_ITEM2"
            }
            "animation"
            {
                "name"              "MELEE_ALLCLASS"
                "activity"          "ACT_MP_STAND_MELEE_ALLCLASS"
            }
        }
    }
    "ClassTipsPanel"
    {
        "ControlName"           "CTFClassTipsPanel"
        "fieldName"             "ClassTipsPanel"
        "xpos"                  "9999"
        "ypos"                  "9999"
        "zpos"                  "7"
        "wide"                  "235"
        "tall"                  "165"
        "autoResize"            "0"
        "pinCorner"             "0"
        "visible"               "0"
        "enabled"               "0"
        "tabPosition"           "0"
    }
    "ClassHighlightPanel"
    {
        "ControlName"                   "CExplanationPopup"
        "fieldName"                     "ClassHighlightPanel"
        "xpos"                          "c-75"
        "ypos"                          "280"
        "zpos"                          "100"
        "wide"                          "250"
        "tall"                          "170"
        "visible"                       "0"
        "PaintBackgroundType"           "2"
        "paintbackground"               "0"
        "border"                        "MainMenuHighlightBorder"
        "start_x"                       "c-238"
        "start_y"                       "100"
        "start_wide"                    "1"
        "start_tall"                    "1"
        "end_x"                         "c-325"
        "end_y"                         "250"
        "end_wide"                      "275"
        "end_tall"                      "150"
        "callout_inparents_x"           "c-210"
        "callout_inparents_y"           "437"
        "TitleLabel"
        {
            "ControlName"               "CExLabel"
            "fieldName"                 "TitleLabel"
            "font"                      "HudFontSmallBold"
            "labelText"                 "#CMenu_ClassHighlightPanel_Title"
            "textAlignment"             "north-west"
            "xpos"                      "10"
            "ypos"                      "10"
            "wide"                      "210"
            "tall"                      "20"
            "autoResize"                "0"
            "pinCorner"                 "0"
            "visible"                   "1"
            "enabled"                   "1"
            "wrap"                      "1"
            "fgcolor_override"          "46 43 42 255"
        }
        "ClassHighlightText"
        {
            "ControlName"               "CExLabel"
            "fieldName"                 "ClassHighlightText"
            "font"                      "HudFontSmall"
            "labelText"                 "%ClassHighlightText%"
            "textAlignment"             "north-west"
            "xpos"                      "20"
            "ypos"                      "30"
            "wide"                      "210"
            "tall"                      "115"
            "autoResize"                "0"
            "pinCorner"                 "0"
            "visible"                   "1"
            "enabled"                   "1"
            "wrap"                      "1"
            "fgcolor_override"          "46 43 42 255"
        }
        "CloseButton"
        {
            "ControlName"                       "CExImageButton"
            "fieldName"                         "CloseButton"
            "xpos"                              "255"
            "ypos"                              "5"
            "zpos"                              "10"
            "wide"                              "14"
            "tall"                              "14"
            "autoResize"                        "0"
            "pinCorner"                         "0"
            "visible"                           "1"
            "enabled"                           "1"
            "tabPosition"                       "0"
            "labeltext"                         ""
            "font"                              "HudFontSmallBold"
            "textAlignment"                     "center"
            "dulltext"                          "0"
            "brighttext"                        "0"
            "default"                           "1"
            "sound_depressed"                   "UI/buttonclick.wav"
            "sound_released"                    "UI/buttonclickrelease.wav"
            "Command"                           "close"
            "paintbackground"                   "0"
            "defaultFgColor_override"           "46 43 42 255"
            "armedFgColor_override"             "OWWHITE"
            "depressedFgColor_override"         "46 43 42 255"
            "image_drawcolor"                   "117 107 94 255"
            "image_armedcolor"                  "oworange"
            "SubImage"
            {
                "ControlName"           "ImagePanel"
                "fieldName"             "SubImage"
                "xpos"                  "0"
                "ypos"                  "0"
                "zpos"                  "1"
                "wide"                  "14"
                "tall"                  "14"
                "visible"               "1"
                "enabled"               "1"
                "image"                 "close_button"
                "scaleImage"            "1"
            }
        }
    }
}