"Resource/UI/ItemModelPanel.res"
{
    "SpectatorGUIHealth"
    {
        "ControlName"                       "EditablePanel"
        "fieldName"                         "SpectatorGUIHealth"
        "xpos"                              "0"
        "ypos"                              "0"
        "wide"                              "128"
        "tall"                              "62"
        "visible"                           "1"
        "enabled"                           "1"
        "HealthBonusPosAdj"                 "288"	// TODO - add baselog options for this 1440p: 384, 1080p: 288
        "HealthDeathWarning"                "1.00"
        // "TFFont"                            "HudFontSmall"
        "HealthDeathWarningColor"           "HUDDeathWarning"
        "TextColor"                         "White"
    }
    "itemmodelpanel"
    {
        "ControlName"                   "CEmbeddedItemModelPanel"
        "fieldName"                     "itemmodelpanel"
        "xpos"                          "0"
        "ypos"                          "0"
        "zpos"                          "1"
        "wide"                          "100"
        "tall"                          "100"
        "autoResize"                    "0"
        "pinCorner"                     "0"
        "visible"                       "1"
        "enabled"                       "1"
        "useparentbg"                   "1"
        "fov"                           "54"
        "start_framed"                  "1"
        "disable_manipulation"          "1"
        "model"
        {
            "angles_x"          "10"
            "angles_y"          "130"
            "angles_z"          "0"
        }
    }
    "DisguiseStatusBG"
    {
        "ControlName"               "ImagePanel"
        "fieldName"                 "DisguiseStatusBG"
        "xpos"                      "0"
        "ypos"                      "12"
        "zpos"                      "-1"
        "wide"                      "120"
        "tall"                      "26"
        "autoResize"                "0"
        "pinCorner"                 "0"
        "visible"                   "1"
        "enabled"                   "1"
        "fillcolor"                 "blank"
        "src_corner_height"         "23"	// pixels inside the image
        "src_corner_width"          "23"
        "draw_corner_width"         "5"	// screen size of the corners ( and sides ), proportional
        "draw_corner_height"        "5"
    }
    "DisguiseNameLabel"
    {
        "ControlName"           "Label"
        "fieldName"             "DisguiseNameLabel"
        "font"                  "Body_MD"
        "xpos"                  "35"
        "ypos"                  "24"
        "zpos"                  "1"
        "wide"                  "110"
        "tall"                  "24"
        "autoResize"            "0"
        "pinCorner"             "0"
        "visible"               "1"
        "enabled"               "1"
        "labelText"             "%disguisename%"
        "textAlignment"         "west"
        "dulltext"              "0"
        "brighttext"            "0"
    }
    "DisguiseNameLabelShadow"
    {
        "ControlName"               "Label"
        "fieldName"                 "DisguiseNameLabelShadow"
        "font"                      "Body_MD_Blur"
        "xpos"                      "0"
        "ypos"                      "0"
        "zpos"                      "1"
        "wide"                      "110"
        "tall"                      "24"
        "autoResize"                "0"
        "pinCorner"                 "0"
        "visible"                   "1"
        "enabled"                   "1"
        "labelText"                 "%disguisename%"
        "textAlignment"             "west"
        "dulltext"                  "0"
        "brighttext"                "0"
        "fgcolor_override"          "Shadow"
        "pin_to_sibling"            "DisguiseNameLabel"
    }
    "WeaponNameLabel"
    {
        "ControlName"                   "Label"
        "fieldName"                     "WeaponNameLabel"
        "font"                          "Body_SM"
        "xpos"                          "cs-0.5"
        "ypos"                          "0"
        "zpos"                          "1"
        "wide"                          "110"
        "tall"                          "12"
        "proportionaltoparent"          "1"
        "autoResize"                    "0"
        "pinCorner"                     "0"
        "visible"                       "1"
        "enabled"                       "1"
        "labelText"                     "%weaponname%"
        "textAlignment"                 "center"
        "dulltext"                      "0"
        "brighttext"                    "0"
    }
    "WeaponNameLabelShadow"
    {
        "ControlName"               "Label"
        "fieldName"                 "WeaponNameLabelShadow"
        "font"                      "Body_SM_Blur"
        "xpos"                      "0"
        "ypos"                      "0"
        "zpos"                      "1"
        "wide"                      "110"
        "tall"                      "24"
        "autoResize"                "0"
        "pinCorner"                 "0"
        "visible"                   "1"
        "enabled"                   "1"
        "labelText"                 "%weaponname%"
        "textAlignment"             "center"
        "dulltext"                  "0"
        "brighttext"                "0"
        "fgcolor_override"          "Shadow"
        "pin_to_sibling"            "WeaponNameLabel"
    }
}