"Resource/UI/FreezePanel_Basic.res"
{
    "FreezePanelBase"
    {
        "ControlName"                   "EditablePanel"
        "fieldName"                     "FreezePanelBase"
        "xpos"                          "rs1-20"
        "ypos"                          "cs-0.5+20"
        "proportionaltoparent"          "1"
        "wide"                          "128"
        "tall"                          "85"
        "visible"                       "1"
        "EliminatedBG"
        {
            "ControlName"               "CTFImagePanel"
            "fieldName"                 "EliminatedBG"
            "xpos"                      "0"
            "ypos"                      "0"
            "zpos"                      "-1"
            "wide"                      "128"
            "tall"                      "20"
            "visible"                   "1"
            "enabled"                   "1"
            //	"image"						"../hud/color_panel_blu"
            "scaleImage"                "1"
            "image"                     "replay\thumbnails\blank"
            "teambg_1"                  "replay\thumbnails\blank"	// teams are swapped as this panel shows your team, not the team that killed you
            "teambg_2"                  "replay/thumbnails/panels/roundedcorners_blue"	// while on red team
            "teambg_3"                  "replay/thumbnails/panels/roundedcorners_red"	// while on blue team
            "src_corner_height"         "10"
            "src_corner_width"          "10"
            "draw_corner_width"         "3"
            "draw_corner_height"        "3"
        }
        "EliminatedLabel"
        {
            "ControlName"                   "CExLabel"
            "FieldName"                     "EliminatedLabel"
            "XPos"                          "0"
            "YPos"                          "2"
            "ZPos"                          "1"
            "Wide"                          "128"
            "Tall"                          "16"
            "Visible"                       "1"
            "Enabled"                       "1"
            "ProportionalToParent"          "1"
            "LabelText"                     "ELIMINATED BY"
            "Font"                          "HeaderEm_MD"
            "TextAlignment"                 "center"
            "FGColor"                       "White"
            "alpha"                         "255"
        }
        "FreezePanelHealthMod"
        {
            "ControlName"               "CTFImagePanel"
            "fieldName"                 "FreezePanelHealthMod"
            "xpos"                      "0"
            "ypos"                      "23"
            "zpos"                      "10"
            "wide"                      "128"
            "tall"                      "12"
            "visible"                   "1"
            "enabled"                   "1"
            //	"image"						"../hud/color_panel_blu"
            "scaleImage"                "1"
            "image"                     "replay\thumbnails\blank"
            "teambg_1"                  "replay\thumbnails\blank"	// teams are swapped as this panel shows your team, not the team that killed you
            "teambg_2"                  "replay/thumbnails/mod_blue"	// while on red team
            "teambg_3"                  "replay/thumbnails/mod_red"	// while on blue team
            "src_corner_height"         "23"
            "src_corner_width"          "23"
            "draw_corner_width"         "3"
            "draw_corner_height"        "3"
        }
        "Refract"
        {
            "ControlName"                   "ImagePanel"
            "fieldName"                     "Refract"
            "xpos"                          "0"
            "ypos"                          "0"
            "zpos"                          "11"
            "wide"                          "128"
            "tall"                          "12"
            "proportionaltoparent"          "1"
            "visible"                       "1"
            "enabled"                       "1"
            "proportionaltoparent"          "1"
            "image"                         "replay/thumbnails/healthbar/healthbar-8-refract"
            "scaleImage"                    "1"
            "pin_to_sibling"                "FreezePanelHealthMod"
        }
        "FreezePanelHealth"
        {
            "ControlName"                       "CTFFreezePanelHealth"
            "fieldName"                         "FreezePanelHealth"
            "xpos"                              "0"
            "ypos"                              "23"
            "zpos"                              "5"
            "wide"                              "128"
            "tall"                              "62"
            "visible"                           "1"
            "enabled"                           "1"
            "HealthBonusPosAdj"                 "288"	// set by customizations
            "HealthDeathWarning"                "1.00"
            // "TFFont"					"HudFontSmall"
            "HealthDeathWarningColor"           "HUDDeathWarning"
            "TextColor"                         "White"
        }
        "FreezeLabelKillerName"
        {
            "ControlName"               "Label"
            "fieldName"                 "FreezeLabelKillerName"
            "font"                      "BodyEM_MD"
            "fgcolor_override"          "White"
            "xpos"                      "34"
            "ypos"                      "23+16"
            "zpos"                      "5"
            "wide"                      "320"
            "tall"                      "14"
            "autoResize"                "0"
            "pinCorner"                 "0"
            "visible"                   "1"
            "enabled"                   "1"
            "labelText"                 "%killername%"
            "textAlignment"             "west"
        }
        "FreezeLabelKillerNameShadow"
        {
            "ControlName"               "Label"
            "fieldName"                 "FreezeLabelKillerNameShadow"
            "font"                      "BodyEM_MD_Blur"
            "fgcolor_override"          "Shadow"
            "xpos"                      "0"
            "ypos"                      "0"
            "zpos"                      "4"
            "wide"                      "320"
            "tall"                      "14"
            "autoResize"                "0"
            "pinCorner"                 "0"
            "visible"                   "1"
            "enabled"                   "1"
            "labelText"                 "%killername%"
            "textAlignment"             "west"
            "pin_to_sibling"            "FreezeLabelKillerName"
        }
        "FreezeLabel"
        {
            "ControlName"           "CExLabel"
            "FieldName"             "FreezeLabel"
            "XPos"                  "9999"
            "YPos"                  "9999"
            "Wide"                  "0"
            "Tall"                  "0"
            "Visible"               "0"
            "Enabled"               "0"
            "Alpha"                 "0"
        }
        "FreezeLabelKiller"
        {
            "ControlName"           "Label"
            "fieldName"             "FreezeLabelKiller"
            "wide"                  "0"
            "tall"                  "0"
            "visible"               "0"
            "enabled"               "0"
        }
        "HPBackgroundPanel"
        {
            "ControlName"           "EditablePanel"
            "fieldName"             "HPBackgroundPanel"
            "xpos"                  "0"
            "ypos"                  "0"
            "zpos"                  "1"
            "wide"                  "0"
            "tall"                  "0"
            "visible"               "1"
            "HPPanelDark"
            {
                "ControlName"               "ScalableImagePanel"
                "fieldName"                 "HPPanelDark"
                "xpos"                      "0"
                "ypos"                      "0"
                "zpos"                      "1"
                "wide"                      "0"
                "tall"                      "0"
                "visible"                   "1"
                "enabled"                   "1"
                "image"                     "../hud/color_panel_brown"
                "scaleImage"                "1"
                "src_corner_height"         "23"
                "src_corner_width"          "23"
                "draw_corner_width"         "3"
                "draw_corner_height"        "3"
            }
        }
        "AvatarImage"
        {
            "ControlName"           "CAvatarImagePanel"
            "fieldName"             "AvatarImage"
            "wide"                  "0"
            "tall"                  "0"
            "visible"               "0"
            "enabled"               "0"
        }
        "NemesisSubPanel"
        {
            "ControlName"           "EditablePanel"
            "fieldName"             "NemesisSubPanel"
            "wide"                  "0"
            "tall"                  "0"
            "visible"               "0"
            "enabled"               "0"
            "NemesisPanelBG"
            {
                "ControlName"           "ScalableImagePanel"
                "fieldName"             "NemesisPanelBG"
                "wide"                  "0"
                "tall"                  "0"
                "visible"               "0"
                "enabled"               "0"
            }
            "NemesisIcon"
            {
                "ControlName"           "ImagePanel"
                "fieldName"             "NemesisIcon"
                "wide"                  "0"
                "tall"                  "0"
                "visible"               "0"
                "enabled"               "0"
            }
            "NemesisLabel"
            {
                "ControlName"           "Label"
                "fieldName"             "NemesisLabel"
                "wide"                  "0"
                "tall"                  "0"
                "visible"               "0"
                "enabled"               "0"
            }
        }
        "FreezePanelBG"
        {
            "ControlName"               "CTFImagePanel"
            "fieldName"                 "FreezePanelBG"
            "xpos"                      "30"
            "ypos"                      "30"
            "zpos"                      "0"
            "wide"                      "0"
            "tall"                      "0"
            "visible"                   "0"
            "enabled"                   "0"
            //	"image"						"../hud/color_panel_blu"
            "scaleImage"                "1"
            "image"                     "replay\thumbnails\blank"
            "teambg_1"                  "replay\thumbnails\blank"
            "teambg_2"                  "replay\thumbnails\blank"
            "teambg_3"                  "replay\thumbnails\blank"
            "src_corner_height"         "23"
            "src_corner_width"          "23"
            "draw_corner_width"         "3"
            "draw_corner_height"        "3"
        }
    }
    "itempanel"
    {
        "ControlName"                   "CItemModelPanel"
        "fieldName"                     "itempanel"
        "xpos"                          "0"	//r230
        "ypos"                          "0"
        "zpos"                          "10"
        "wide"                          "0"
        "tall"                          "0"
        "visible"                       "0"
        "bgcolor_override"              "255 255 255 0"
        "PaintBackgroundType"           "0"
        "model_ypos"                    "10"
        "model_center_x"                "1"
        "model_wide"                    "90"
        "model_tall"                    "60"
        "text_xpos"                     "10"
        "text_ypos"                     "10"
        "text_wide"                     "200"
        "text_center"                   "1"
        "max_text_height"               "100"
        "padding_height"                "10"
        "resize_to_text"                "1"
        "text_forcesize"                "2"
        "itemmodelpanel"
        {
            "fieldName"                     "itemmodelpanel"
            "use_item_rendertarget"         "0"
            "useparentbg"                   "1"
            "inventory_image_type"          "1"
        }
        "ItemLabel"
        {
            "ControlName"           "Label"
            "fieldName"             "ItemLabel"
            "font"                  "Nim11"
            "xpos"                  "5"
            "ypos"                  "3"
            "zpos"                  "1"
            "wide"                  "0"
            "tall"                  "11"
            "autoResize"            "0"
            "pinCorner"             "0"
            "visible"               "1"
            "enabled"               "1"
            "labelText"             "#FreezePanel_Item"
            "textAlignment"         "west"
            "dulltext"              "0"
            "brighttext"            "0"
        }
    }
    "ScreenshotPanel"
    {
        "ControlName"           "EditablePanel"
        "fieldName"             "ScreenshotPanel"
        "wide"                  "0"
        "tall"                  "0"
        "visible"               "0"
        "enabled"               "0"
        "ScreenshotPanelBG"
        {
            "ControlName"           "ImagePanel"
            "fieldName"             "ScreenshotPanelBG"
            "wide"                  "0"
            "tall"                  "0"
            "visible"               "0"
            "enabled"               "0"
        }
        "ScreenshotIcon"
        {
            "ControlName"           "ImagePanel"
            "fieldName"             "ScreenshotIcon"
            "wide"                  "0"
            "tall"                  "0"
            "visible"               "0"
            "enabled"               "0"
        }
        "ScreenshotLabel"
        {
            "ControlName"           "Label"
            "fieldName"             "ScreenshotLabel"
            "wide"                  "0"
            "tall"                  "0"
            "visible"               "0"
            "enabled"               "0"
        }
    }
}