"Resource/UI/GlobalChat.res"
{
    "PartyChat"
    {
        "FieldName"                             "PartyChat"
        "Visible"                               "1"
        "Enabled"                               "1"
        "XPos"                                  "0"
        "YPos"                                  "0"
        "ZPos"                                  "9999"
        "Wide"                                  "228"
        "Tall"                                  "140"
        "ProportionalToParent"                  "1"
        "KeyboardInputEnabled"                  "1"
        "MouseInputEnabled"                     "1"
        "Border"                                "NoBorder"
        "BGColor_Override"                      "Blank"
        "paintBackground"                       "1"
        "paintbackgroundtype"                   "2"
        "roundedCorners"                        "15"
        "log_font_small"                        "Body_MD"
        "log_font_medium"                       "Body_MD"
        "log_font_large"                        "Body_MD"
        "chat_color_default"                    "White"
        "chat_color_player_name"                "Party"
        "chat_color_chat_text"                  "White"
        "chat_color_party_event"                "FinalsYellow"
        "Collapsed_Height"                      "0"
        "Expanded_Height"                       "120"
        "Resize_Time"                           "0.3"
        "invalidate_parent_on_resize"           "0"
    }
    "ChatBG"
    {
        "ControlName"                   "EditablePanel"
        "FieldName"                     "ChatBG"
        "XPos"                          "0"
        "YPos"                          "0"
        "ZPos"                          "-1"
        "Wide"                          "f0"
        "Tall"                          "110"
        "Visible"                       "1"
        "ProportionalToParent"          "1"
        "BGColor_Override"              "TransparentBlack"
        "paintBackground"               "1"
        "paintBackgroundType"           "2"
        "RoundedCorners"                "15"
        "Pin_To_Sibling"                "chatlog"
        "Pin_Corner_To_Sibling"         "PIN_TOPLEFT"
        "Pin_To_Sibling_Corner"         "PIN_TOPLEFT"
    }
    "ChatLog"
    {
        "FieldName"                     "ChatLog"
        "XPos"                          "cs-0.5"
        "YPos"                          "5"
        "ZPos"                          "1"
        "Wide"                          "f0"
        "Tall"                          "f20"
        "Visible"                       "1"
        "ProportionalToParent"          "1"
        "RoundedCorners"                "0"
        "PaintBackground"               "0"
        "ScrollBar"
        {
            "FieldName"                     "ScrollBar"
            "XPos"                          "rs1-1"
            "YPos"                          "0"
            "Tall"                          "f0"
            "Wide"                          "5"
            "ZPos"                          "1000"
            "nobuttons"                     "1"
            "ProportionalToParent"          "1"
            "Slider"
            {
                "FGColor_Override"          "ChatScrollbar"
            }
            "UpButton"
            {
                "ControlName"           "Button"
                "FieldName"             "UpButton"
                "Visible"               "0"
            }
            "DownButton"
            {
                "ControlName"           "Button"
                "FieldName"             "DownButton"
                "Visible"               "0"
            }
        }
    }
    "ChatEntry"
    {
        "FieldName"                     "ChatEntry"
        "XPos"                          "0"
        "YPos"                          "0"
        "ZPos"                          "1"
        "Wide"                          "184"
        "Tall"                          "15"
        "Visible"                       "1"
        "ProportionalToParent"          "1"
        "FGColor_Override"              "White"
        "BGColor_Override"              "PartyChatEntry"
        "RoundedCorners"                "8"
        "Alpha"                         "0"
        "MouseInputEnabled"             "0"
        "Pin_To_Sibling"                "chatlog"
        "Pin_Corner_To_Sibling"         "PIN_TOPRIGHT"
        "Pin_To_Sibling_Corner"         "PIN_BOTTOMRIGHT"
    }
    "ChatEntryTopLine"
    {
        "ControlName"                   "EditablePanel"
        "FieldName"                     "ChatEntryTopLine"
        "XPos"                          "0"
        "YPos"                          "0"
        "ZPos"                          "1"
        "Wide"                          "f0"
        "Tall"                          "1"
        "Visible"                       "1"
        "ProportionalToParent"          "1"
        "BGColor_Override"              "PartyChatTopLine"
        "Pin_To_Sibling"                "chatlog"
        "Pin_Corner_To_Sibling"         "PIN_BOTTOMLEFT"
        "Pin_To_Sibling_Corner"         "PIN_BOTTOMLEFT"
    }
    "ChatPartyLabel"
    {
        "ControlName"                   "CExLabel"
        "FieldName"                     "ChatPartyLabel"
        "XPos"                          "0"
        "YPos"                          "0"
        "ZPos"                          "1"
        "Wide"                          "45"
        "Tall"                          "15"
        "Visible"                       "1"
        "ProportionalToParent"          "1"
        "labelText"                     "PARTY"
        "textAlignment"                 "center"
        "font"                          "BodyEM_XS"
        "FGColor_Override"              "Party"
        "Pin_To_Sibling"                "chatlog"
        "Pin_Corner_To_Sibling"         "PIN_TOPLEFT"
        "Pin_To_Sibling_Corner"         "PIN_BOTTOMLEFT"
    }
    "ChatPartyLabelBG"
    {
        "ControlName"                   "EditablePanel"
        "FieldName"                     "ChatPartyLabelBG"
        "XPos"                          "0"
        "YPos"                          "0"
        "ZPos"                          "1"
        "Wide"                          "45"
        "Tall"                          "15"
        "Visible"                       "1"
        "ProportionalToParent"          "1"
        "BGColor_Override"              "Black"
        "paintBackground"               "1"
        "paintBackgroundType"           "2"
        "RoundedCorners"                "4"
        "Pin_To_Sibling"                "chatlog"
        "Pin_Corner_To_Sibling"         "PIN_TOPLEFT"
        "Pin_To_Sibling_Corner"         "PIN_BOTTOMLEFT"
    }
    "EntryShadow"	// dead
    {
        "ControlName"                   "Panel"
        "FieldName"                     "EntryShadow"
        "XPos"                          "0"
        "YPos"                          "0"
        "ZPos"                          "2"
        "Wide"                          "0"
        "Tall"                          "0"
        "Visible"                       "0"
        "ProportionalToParent"          "1"
        "BGColor_Override"              "Blank"
        "RoundedCorners"                "0"
        "Border"                        "NoBorder"
        "KeyboardInputEnabled"          "0"
        "MouseInputEnabled"             "0"
    }
}