"Resource/UI/hud_obj_sentrygun_disp.res"
{
    "BuildingStatusItem"
    {
        "ControlName"           "Frame"
        "fieldName"             "SentryGunMvm"
        "xpos"                  "0"	// set in hudanimations=>EngineerBuildings
        "ypos"                  "0"	// set in hudanimations=>EngineerBuildings
        "wide"                  "160"
        "tall"                  "22"
        "autoResize"            "0"
        "pinCorner"             "0"
        "visible"               "1"
        "enabled"               "1"
        "tabPosition"           "0"
    }
    "Background"	// dead
    {
        "ControlName"           "ImagePanel"
        "fieldName"             "Background"
        "xpos"                  "0"
        "ypos"                  "0"
        "zpos"                  "-1"
        "wide"                  "0"
        "tall"                  "0"
        "visible"               "1"
        "enabled"               "1"
        "scaleImage"            "1"
        //	"icon"			"obj_status_background_tall_disabled"
        //	"iconColor"		"White"
        "fillcolor"             "blank"
    }
    "BackgroundReal"
    {
        "ControlName"                   "EditablePanel"
        "fieldName"                     "BackgroundReal"
        "xpos"                          "2"
        "ypos"                          "0"
        "zpos"                          "-1"
        "wide"                          "115"
        "tall"                          "33"
        "visible"                       "1"
        "enabled"                       "1"
        "scaleImage"                    "1"
        "paintBackgroundType"           "2"
        "roundedcorners"                "15"
        "bgcolor_override"              "TransparentLightesterBlack"
    }
    "Icon_Sentry_1"
    {
        "ControlName"           "CIconPanel"
        "fieldName"             "Icon_Sentry_1"
        "xpos"                  "30"
        "ypos"                  "1"
        "wide"                  "15"
        "tall"                  "15"
        "visible"               "1"
        "enabled"               "1"
        "scaleImage"            "1"
        "icon"                  "obj_status_sentrygun_1"
        "iconColor"             "White"
    }
    "NotBuiltPanel"
    {
        "ControlName"           "EditablePanel"
        "fieldName"             "NotBuiltPanel"
        "xpos"                  "0"
        "ypos"                  "0"
        "wide"                  "160"
        "tall"                  "20"
        "visible"               "1"
        "NotBuiltLabel"
        {
            "ControlName"           "CExLabel"
            "fieldName"             "NotBuiltLabel"
            "font"                  "BodyEm_MD"
            "xpos"                  "60"
            "ypos"                  "0"
            "wide"                  "200"
            "tall"                  "20"
            "autoResize"            "0"
            "pinCorner"             "0"
            "visible"               "1"
            "enabled"               "1"
            "labelText"             "#Building_hud_disp_sentry_not_built"
            "textAlignment"         "west"
            "dulltext"              "0"
            "brighttext"            "0"
        }
    }
    "BuiltPanel"
    {
        "ControlName"           "EditablePanel"
        "fieldName"             "BuiltPanel"
        "xpos"                  "0"
        "ypos"                  "0"
        "wide"                  "160"
        "tall"                  "20"
        "visible"               "0"
        "Icon_Upgrade_1"
        {
            "ControlName"           "CIconPanel"
            "fieldName"             "Icon_Upgrade_1"
            "xpos"                  "46"
            "ypos"                  "4"
            "zpos"                  "1"
            "wide"                  "8"
            "tall"                  "8"
            "visible"               "0"
            "enabled"               "0"
            "scaleImage"            "1"
            "icon"                  ""
            "iconColor"             "White"
        }
        "AlertTray"
        {
            "ControlName"           "CBuildingStatusAlertTray"
            "fieldName"             "AlertTray"
            "xpos"                  "114"
            "ypos"                  "0"
            "ypos"                  "0"
            "zpos"                  "-2"
            "wide"                  "44"
            "tall"                  "30"
            "visible"               "0"
            "enabled"               "0"
            "icon"                  "obj_status_alert_background_tall"
        }
        "WrenchIcon"
        {
            "ControlName"           "CIconPanel"
            "fieldName"             "WrenchIcon"
            "xpos"                  "121"
            "ypos"                  "18"
            "zpos"                  "1"
            "wide"                  "17"
            "tall"                  "17"
            "visible"               "0"
            "enabled"               "0"
            "scaleImage"            "1"
            "icon"                  "obj_status_icon_wrench"
            "iconColor"             "White"
        }
        "SapperIcon"
        {
            "ControlName"           "CIconPanel"
            "fieldName"             "SapperIcon"
            "xpos"                  "117"
            "ypos"                  "12"
            "zpos"                  "1"
            "wide"                  "15"
            "tall"                  "15"
            "visible"               "0"
            "enabled"               "0"
            "scaleImage"            "1"
            "icon"                  "obj_status_icon_sapper"
            "iconColor"             "White"
        }
        "Health"
        {
            "ControlName"           "CBuildingHealthBar"
            "fieldName"             "Health"
            "font"                  "DinBold9"
            "xpos"                  "13"
            "ypos"                  "4"
            "wide"                  "8"
            "tall"                  "15"
            "autoResize"            "0"
            "pinCorner"             "0"
            "visible"               "1"
            "enabled"               "1"
            "textAlignment"         "west"
            "dulltext"              "0"
            "brighttext"            "0"
        }
        "BuildingPanel"
        {
            "ControlName"           "EditablePanel"
            "fieldName"             "BuildingPanel"
            "xpos"                  "60"
            "ypos"                  "0"
            "wide"                  "100"
            "tall"                  "30"
            "visible"               "0"
            "BuildingLabel"
            {
                "ControlName"           "CExLabel"
                "fieldName"             "BuildingLabel"
                "font"                  "BodyEm_MD"
                "xpos"                  "0"
                "ypos"                  "18"
                "wide"                  "200"
                "tall"                  "12"
                "autoResize"            "0"
                "pinCorner"             "0"
                "visible"               "1"
                "enabled"               "1"
                "labelText"             "#Building_hud_building"
                "textAlignment"         "west"
                "dulltext"              "0"
                "brighttext"            "0"
            }
            "BuildingProgress"
            {
                "ControlName"               "ContinuousProgressBar"
                "fieldName"                 "BuildingProgress"
                "font"                      "DinBold9"
                "xpos"                      "0"
                "ypos"                      "29"
                "wide"                      "50"
                "tall"                      "8"
                "autoResize"                "0"
                "pinCorner"                 "0"
                "visible"                   "1"
                "enabled"                   "1"
                "textAlignment"             "west"
                "dulltext"                  "0"
                "brighttext"                "0"
                "bgcolor_override"          "ItemMeterBGForMod2x"
            }
            "BuildingProgressMod2xWhite"
            {
                "ControlName"           "ImagePanel"
                "fieldName"             "BuildingProgressMod2xWhite"
                "xpos"                  "0"
                "ypos"                  "0"
                "wide"                  "50"
                "tall"                  "8"
                "visible"               "1"
                "enabled"               "1"
                "scaleImage"            "1"
                "image"                 "replay/thumbnails/mod2x"
                "drawcolor"             "White"
                "pin_to_sibling"        "BuildingProgress"
            }
        }
        "RunningPanel"
        {
            "ControlName"           "EditablePanel"
            "fieldName"             "RunningPanel"
            "xpos"                  "60"
            "ypos"                  "0"
            "wide"                  "100"
            "tall"                  "20"
            "visible"               "0"
            "KillIcon"
            {
                "ControlName"           "ImagePanel"
                "fieldName"             "KillIcon"
                "xpos"                  "0"
                "ypos"                  "5"
                "zpos"                  "1"
                "wide"                  "10"
                "tall"                  "10"
                "visible"               "0"
                "enabled"               "0"
                "scaleImage"            "1"
                "image"                 "../hud/hud_obj_status_kill_64"
                "drawcolor"             "White"
            }
            "KillsLabel"
            {
                "ControlName"           "CExLabel"
                "fieldName"             "KillsLabel"
                "font"                  "Body_SM"
                "xpos"                  "12"
                "ypos"                  "6"
                "wide"                  "200"
                "tall"                  "22"
                "autoResize"            "0"
                "pinCorner"             "0"
                "visible"               "0"
                "enabled"               "0"
                "labelText"             "#Building_hud_sentry_kills_assists"
                "textAlignment"         "north-west"
                "dulltext"              "0"
                "brighttext"            "0"
            }
            "ShellIcon"
            {
                "ControlName"           "ImagePanel"
                "fieldName"             "ShellIcon"
                "xpos"                  "0"
                "ypos"                  "6"
                "zpos"                  "1"
                "wide"                  "10"
                "tall"                  "10"
                "visible"               "1"
                "enabled"               "1"
                "scaleImage"            "1"
                "image"                 "../hud/hud_obj_status_ammo_64"
                "drawcolor"             "White"
            }
            "Shells"
            {
                "ControlName"               "ContinuousProgressBar"
                "fieldName"                 "Shells"
                "font"                      "DinBold9"
                "xpos"                      "12"
                "ypos"                      "7"
                "wide"                      "38"
                "tall"                      "8"
                "autoResize"                "0"
                "pinCorner"                 "0"
                "visible"                   "1"
                "enabled"                   "1"
                "textAlignment"             "west"
                "dulltext"                  "0"
                "brighttext"                "0"
                "bgcolor_override"          "ItemMeterBGForMod2x"
            }
            "ShellsMod2xWhite"
            {
                "ControlName"           "ImagePanel"
                "fieldName"             "ShellsMod2xWhite"
                "xpos"                  "0"
                "ypos"                  "0"
                "wide"                  "38"
                "tall"                  "8"
                "visible"               "1"
                "enabled"               "1"
                "scaleImage"            "1"
                "image"                 "replay/thumbnails/mod2x"
                "drawcolor"             "White"
                "pin_to_sibling"        "Shells"
            }
        }
    }
}