"Resource/UI/hud_obj_sentrygun.res"
{
    "BuildingStatusItem"
    {
        "ControlName"           "Frame"
        "fieldName"             "SentryGun"
        "xpos"                  "0"	// set in hudanimations=>EngineerBuildings
        "ypos"                  "0"	// set in hudanimations=>EngineerBuildings
        "wide"                  "160"
        "tall"                  "55"
        "autoResize"            "0"
        "pinCorner"             "0"
        "visible"               "1"
        "enabled"               "1"
        "tabPosition"           "0"
    }
    "Background"	// dead
    {
        "ControlName"           "ImagePanel"
        "fieldName"             "Background"
        "xpos"                  "0"
        "ypos"                  "0"
        "zpos"                  "-1"
        "wide"                  "0"
        "tall"                  "0"
        "visible"               "1"
        "enabled"               "1"
        "scaleImage"            "1"
        //	"icon"			"obj_status_background_tall_disabled"
        //	"iconColor"		"White"
        "fillcolor"             "blank"
    }
    "BackgroundReal"
    {
        "ControlName"                   "EditablePanel"
        "fieldName"                     "BackgroundReal"
        "xpos"                          "2"
        "ypos"                          "3"
        "zpos"                          "-1"
        "wide"                          "115"
        "tall"                          "60"
        "visible"                       "1"
        "enabled"                       "1"
        "scaleImage"                    "1"
        "paintBackgroundType"           "2"
        "roundedcorners"                "15"
        "bgcolor_override"              "TransparentLightesterBlack"
    }
    "Icon_Sentry_1"
    {
        "ControlName"           "CIconPanel"
        "fieldName"             "Icon_Sentry_1"
        "xpos"                  "22"
        "ypos"                  "12"
        "wide"                  "36"
        "tall"                  "36"
        "visible"               "1"
        "enabled"               "1"
        "scaleImage"            "1"
        "icon"                  "obj_status_sentrygun_1"
        "iconColor"             "White"
    }
    "Icon_Sentry_2"
    {
        "ControlName"           "CIconPanel"
        "fieldName"             "Icon_Sentry_2"
        "xpos"                  "22"
        "ypos"                  "12"
        "wide"                  "36"
        "tall"                  "36"
        "visible"               "0"
        "enabled"               "1"
        "scaleImage"            "1"
        "icon"                  "obj_status_sentrygun_2"
        "iconColor"             "White"
    }
    "Icon_Sentry_3"
    {
        "ControlName"           "CIconPanel"
        "fieldName"             "Icon_Sentry_3"
        "xpos"                  "22"
        "ypos"                  "12"
        "wide"                  "36"
        "tall"                  "36"
        "visible"               "0"
        "enabled"               "1"
        "scaleImage"            "1"
        "icon"                  "obj_status_sentrygun_3"
        "iconColor"             "White"
    }
    "NotBuiltPanel"
    {
        "ControlName"           "EditablePanel"
        "fieldName"             "NotBuiltPanel"
        "xpos"                  "0"
        "ypos"                  "0"
        "wide"                  "160"
        "tall"                  "60"
        "visible"               "1"
        "NotBuiltLabel"
        {
            "ControlName"               "CExLabel"
            "fieldName"                 "NotBuiltLabel"
            "font"                      "BodyEM_MD"
            "xpos"                      "60"
            "ypos"                      "0"
            "wide"                      "200"
            "tall"                      "60"
            "autoResize"                "0"
            "pinCorner"                 "0"
            "visible"                   "1"
            "enabled"                   "1"
            "labelText"                 "#Building_hud_sentry_not_built"
            "labelText_lodef"           "#Building_hud_sentry_not_built_360"
            "textAlignment"             "west"
            "dulltext"                  "0"
            "brighttext"                "0"
        }
    }
    "BuiltPanel"
    {
        "ControlName"           "EditablePanel"
        "fieldName"             "BuiltPanel"
        "xpos"                  "0"
        "ypos"                  "0"
        "wide"                  "160"
        "tall"                  "60"
        "visible"               "0"
        "Icon_Upgrade_1"
        {
            "ControlName"           "CIconPanel"
            "fieldName"             "Icon_Upgrade_1"
            "xpos"                  "46"
            "ypos"                  "4"
            "zpos"                  "1"
            "wide"                  "8"
            "tall"                  "8"
            "visible"               "0"
            "enabled"               "1"
            "scaleImage"            "1"
            "icon"                  "obj_status_upgrade_1"
            "iconColor"             "White"
        }
        "Icon_Upgrade_2"
        {
            "ControlName"           "CIconPanel"
            "fieldName"             "Icon_Upgrade_2"
            "xpos"                  "46"
            "ypos"                  "4"
            "zpos"                  "1"
            "wide"                  "8"
            "tall"                  "8"
            "visible"               "0"
            "enabled"               "1"
            "scaleImage"            "1"
            "icon"                  "obj_status_upgrade_2"
            "iconColor"             "White"
        }
        "Icon_Upgrade_3"
        {
            "ControlName"           "CIconPanel"
            "fieldName"             "Icon_Upgrade_3"
            "xpos"                  "46"
            "ypos"                  "4"
            "zpos"                  "1"
            "wide"                  "8"
            "tall"                  "8"
            "visible"               "0"
            "enabled"               "1"
            "scaleImage"            "1"
            "icon"                  "obj_status_upgrade_3"
            "iconColor"             "White"
        }
        "AlertTray"
        {
            "ControlName"           "CBuildingStatusAlertTray"
            "fieldName"             "AlertTray"
            "xpos"                  "114"
            "ypos"                  "0"
            "zpos"                  "-2"
            "wide"                  "44"
            "tall"                  "60"
            "visible"               "1"
            "enabled"               "1"
            "icon"                  "obj_status_alert_background_tall"
        }
        "WrenchIcon"
        {
            "ControlName"           "CIconPanel"
            "fieldName"             "WrenchIcon"
            "xpos"                  "121"
            "ypos"                  "18"
            "zpos"                  "1"
            "wide"                  "27"
            "tall"                  "27"
            "visible"               "0"
            "enabled"               "1"
            "scaleImage"            "1"
            "icon"                  "obj_status_icon_wrench"
            "iconColor"             "White"
        }
        "SapperIcon"
        {
            "ControlName"           "CIconPanel"
            "fieldName"             "SapperIcon"
            "xpos"                  "117"
            "ypos"                  "12"
            "zpos"                  "1"
            "wide"                  "35"
            "tall"                  "35"
            "visible"               "0"
            "enabled"               "1"
            "scaleImage"            "1"
            "icon"                  "obj_status_icon_sapper"
            "iconColor"             "White"
        }
        "Health"
        {
            "ControlName"           "CBuildingHealthBar"
            "fieldName"             "Health"
            "xpos"                  "13"
            "ypos"                  "3"
            "wide"                  "8"
            "tall"                  "53"
            "visible"               "1"
            "enabled"               "1"
            "dulltext"              "0"
            "brighttext"            "0"
        }
        "ModTest"
        {
            "ControlName"                   "ImagePanel"
            "fieldName"                     "ModTest"
            "xpos"                          "13"
            "ypos"                          "0"
            "zpos"                          "1"
            "wide"                          "8"
            "tall"                          "f0"
            "proportionaltoparent"          "1"
            "visible"                       "1"
            "enabled"                       "1"
            "dulltext"                      "0"
            "brighttext"                    "0"
            "scaleImage"                    "1"
            "image"                         "replay/thumbnails/mod"
        }
        "BuildingPanel"
        {
            "ControlName"           "EditablePanel"
            "fieldName"             "BuildingPanel"
            "xpos"                  "60"
            "ypos"                  "0"
            "wide"                  "100"
            "tall"                  "60"
            "visible"               "0"
            "BuildingLabel"
            {
                "ControlName"           "CExLabel"
                "fieldName"             "BuildingLabel"
                "font"                  "BodyEm_MD"
                "xpos"                  "0"
                "ypos"                  "14"
                "wide"                  "200"
                "tall"                  "16"
                "visible"               "1"
                "enabled"               "1"
                "labelText"             "#Building_hud_building"
                "textAlignment"         "west"
                "dulltext"              "0"
                "brighttext"            "0"
            }
            "BuildingProgress"
            {
                "ControlName"               "ContinuousProgressBar"
                "fieldName"                 "BuildingProgress"
                "xpos"                      "0"
                "ypos"                      "29"
                "wide"                      "50"
                "tall"                      "8"
                "autoResize"                "0"
                "pinCorner"                 "0"
                "visible"                   "1"
                "enabled"                   "1"
                "dulltext"                  "0"
                "brighttext"                "0"
                "bgcolor_override"          "ItemMeterBG"
            }
        }
        "RunningPanel"
        {
            "ControlName"           "EditablePanel"
            "fieldName"             "RunningPanel"
            "xpos"                  "60"
            "ypos"                  "0"
            "wide"                  "100"
            "tall"                  "60"
            "visible"               "0"
            "KillIcon"
            {
                "ControlName"           "ImagePanel"
                "fieldName"             "KillIcon"
                "xpos"                  "0"
                "ypos"                  "12"
                "zpos"                  "1"
                "wide"                  "10"
                "tall"                  "10"
                "visible"               "1"
                "enabled"               "1"
                "scaleImage"            "1"
                "image"                 "../hud/hud_obj_status_kill_64"
                "drawcolor"             "White"
            }
            "KillsLabel"
            {
                "ControlName"           "CExLabel"
                "fieldName"             "KillsLabel"
                "font"                  "Body_SM"
                "xpos"                  "12"
                "ypos"                  "9"
                "wide"                  "200"
                "tall"                  "22"
                "autoResize"            "0"
                "pinCorner"             "0"
                "visible"               "1"
                "enabled"               "1"
                "labelText"             "#Building_hud_sentry_kills_assists"
                "textAlignment"         "north-west"
                "dulltext"              "0"
                "brighttext"            "0"
            }
            "ShellIcon"
            {
                "ControlName"           "ImagePanel"
                "fieldName"             "ShellIcon"
                "xpos"                  "0"
                "ypos"                  "25"
                "zpos"                  "1"
                "wide"                  "10"
                "tall"                  "10"
                "visible"               "1"
                "enabled"               "1"
                "scaleImage"            "1"
                "image"                 "../hud/hud_obj_status_ammo_64"
                "drawcolor"             "White"
            }
            "Shells"
            {
                "ControlName"               "ContinuousProgressBar"
                "fieldName"                 "Shells"
                "xpos"                      "12"
                "ypos"                      "26"
                "wide"                      "38"
                "tall"                      "8"
                "autoResize"                "0"
                "pinCorner"                 "0"
                "visible"                   "1"
                "enabled"                   "1"
                "dulltext"                  "0"
                "brighttext"                "0"
                "bgcolor_override"          "ItemMeterBG"
            }
            "RocketIcon"
            {
                "ControlName"           "ImagePanel"
                "fieldName"             "RocketIcon"
                "xpos"                  "0"
                "ypos"                  "38"
                "zpos"                  "1"
                "wide"                  "10"
                "tall"                  "10"
                "visible"               "0"
                "enabled"               "1"
                "scaleImage"            "1"
                "image"                 "../hud/hud_obj_status_rockets_64"
                "drawcolor"             "White"
            }
            "Rockets"
            {
                "ControlName"               "ContinuousProgressBar"
                "fieldName"                 "Rockets"
                "xpos"                      "12"
                "ypos"                      "39"
                "wide"                      "38"
                "tall"                      "8"
                "autoResize"                "0"
                "pinCorner"                 "0"
                "visible"                   "0"
                "enabled"                   "1"
                "dulltext"                  "0"
                "brighttext"                "0"
                "bgcolor_override"          "ItemMeterBG"
            }
            "UpgradeIcon"
            {
                "ControlName"           "CIconPanel"
                "fieldName"             "UpgradeIcon"
                "xpos"                  "0"
                "ypos"                  "38"
                "zpos"                  "1"
                "wide"                  "10"
                "tall"                  "10"
                "visible"               "1"
                "enabled"               "1"
                "scaleImage"            "1"
                "icon"                  "ico_metal"
                "iconColor"             "White"
            }
            "Upgrade"
            {
                "ControlName"               "ContinuousProgressBar"
                "fieldName"                 "Upgrade"
                "xpos"                      "12"
                "ypos"                      "39"
                "wide"                      "38"
                "tall"                      "8"
                "autoResize"                "0"
                "pinCorner"                 "0"
                "visible"                   "1"
                "enabled"                   "1"
                "dulltext"                  "0"
                "brighttext"                "0"
                "bgcolor_override"          "ItemMeterBG"
            }
        }
    }
}