"Resource/UI/HudAccountPanel.res"
{
    "CHudAccountPanel"
    {
        "delta_item_x"              "15"
        "delta_item_start_y"        "130"
        "delta_item_end_y"          "130"
        "PositiveColor"             "owgreen"
        "NegativeColor"             "HealthHurt"
        "delta_lifetime"            "1.2"
        "delta_item_font"           "HealthAmmo_Alt"
    }
    "AccountBG"
    {
        "ControlName"                   "EditablePanel"
        "fieldName"                     "AccountBG"
        "xpos"                          "0"
        "ypos"                          "0"
        "zpos"                          "0"
        "wide"                          "f0"
        "tall"                          "f0"
        "proportionaltoparent"          "1"
        "visible"                       "1"
        "enabled"                       "1"
        "paintBackgroundType"           "2"
        "bgcolor_override"              "TransparentLightestBlack"
    }
    "MetalIcon"
    {
        "ControlName"                   "CIconPanel"
        "fieldName"                     "MetalIcon"
        "xpos"                          "4"
        "ypos"                          "cs-0.5"
        "zpos"                          "1"
        "wide"                          "15"
        "tall"                          "15"
        "proportionaltoparent"          "1"
        "visible"                       "1"
        "enabled"                       "1"
        "scaleImage"                    "1"
        "icon"                          "ico_metal"
        "iconColor"                     "White"
    }
    "MetalIconShadow"
    {
        "ControlName"                   "CExLabel"
        "FieldName"                     "MetalIconShadow"
        "XPos"                          "-2"
        "YPos"                          "3"
        "ZPos"                          "-1"
        "Wide"                          "26"
        "Tall"                          "26"
        "Visible"                       "1"
        "Enabled"                       "1"
        "ProportionalToParent"          "1"
        "LabelText"                     "H"
        "TextAlignment"                 "center"
        "Font"                          "HeaderEm_LG_Blur"
        "textinsety"                    "-6"
        "FGColor"                       "Shadow"
    }
    "AccountValue"
    {
        "ControlName"                   "CExLabel"
        "fieldName"                     "AccountValue"
        "xpos"                          "rs1-4"
        "ypos"                          "0"
        "zpos"                          "2"
        "wide"                          "55"
        "tall"                          "26"
        "proportionaltoparent"          "1"
        "autoResize"                    "1"
        "pinCorner"                     "2"
        "visible"                       "1"
        "enabled"                       "1"
        "tabPosition"                   "0"
        "labelText"                     "%metal%"
        "textAlignment"                 "east"
        "textinsetx"                    "5"
        "dulltext"                      "0"
        "brighttext"                    "0"
        "font"                          "HealthAmmo"
        "fgcolor_override"              "White"
    }
    "AccountValueShadow"
    {
        "ControlName"                   "CExLabel"
        "fieldName"                     "AccountValueShadow"
        "xpos"                          "rs1-4"
        "ypos"                          "0"
        "zpos"                          "-1"
        "wide"                          "55"
        "tall"                          "26"
        "proportionaltoparent"          "1"
        "autoResize"                    "1"
        "pinCorner"                     "2"
        "visible"                       "1"
        "enabled"                       "1"
        "tabPosition"                   "0"
        "labelText"                     "%metal%"
        "textAlignment"                 "east"
        "textinsetx"                    "5"
        "dulltext"                      "0"
        "brighttext"                    "0"
        "font"                          "HealthAmmo_Blur"
        "fgcolor_override"              "Shadow"
    }
}