"Resource/UI/HudDemomanPipes_Base.res"
{
    "ChargeAnchor"
    {
        "ControlName"               "EditablePanel"
        "fieldName"                 "ChargeAnchor"
        "xpos"                      "cs-0.5"
        "ypos"                      "cs-0.5+40+8"
        "zpos"                      "7"
        "wide"                      "30"
        "tall"                      "10"
        "visible"                   "0"
        "enabled"                   "1"
        "bgcolor_override"          "blue"
    }
	"ItemEffectMeterBG"
    {
        "ControlName"           "EditablePanel"
        "fieldName"             "ItemEffectMeterBG"
        "font"                  "Default"
        "xpos"                  "0"
        "ypos"                  "0"
        "zpos"                  "-10"
        "wide"                  "30"
        "tall"                  "6"
        "visible"               "1"
        "proportionaltoparent"          "1"
        "border"                "ItemEffectMeterBG"
        "pin_to_sibling"    "ChargeAnchor"
        
    }
    "ChargeMeter"
    {
        "ControlName"                   "ContinuousProgressBar"
        "FieldName"                     "ChargeMeter"
        "XPos"                          "-1"
        "YPos"                          "-1"
        "ZPos"                          "2"
        "Wide"                          "28"
        "Tall"                          "4"
        "Visible"                       "1"
        "Enabled"                       "1"
        "ProportionalToParent"          "1"
        "bgcolor_override"              "blank"	//actually has influence
        "FGColor_Override"         "PureWhite"
        "pin_to_sibling"    "ChargeAnchor"
    }
    "mod"
    {
        "ControlName"                   "ImagePanel"
        "fieldName"                     "mod"
        "xpos"                          "0"
        "ypos"                          "0"
        "zpos"                          "4"
        "wide"                          "30"
        "tall"                          "6"
        "visible"                       "1"
        "enabled"                       "1"
        "proportionaltoparent"          "1"
        "image"                         "replay/thumbnails/mod"
        "scaleImage"                    "1"
        "drawcolor"                     "ItemMeterFG"
        "pin_to_sibling"    "ChargeAnchor"
    }
    "ItemEffectMeterRoundedCorners"
    {
        "ControlName"                   "EditablePanel"
        "fieldName"                     "ItemEffectMeterRoundedCorners"
        "xpos"                          "-1"
        "ypos"                          "-1"
        "zpos"                          "3"
        "wide"                          "28"
        "tall"                          "4"
        "visible"                       "1"
        "proportionaltoparent"          "1"
        "border"                        "ItemEffectMeterRoundedCorners"
        "pin_to_sibling"    "ChargeAnchor"
    }
    "ChargeLabel"
    {
        "ControlName"                       "CExLabel"
        "FieldName"                         "ChargeLabel"
        "XPos"                              "0"
        "YPos"                              "0"
        "ZPos"                              "3"
        "Wide"                              "0"
        "Tall"                              "0"
        "Visible"                           "1"
        "Enabled"                           "0"
        "ProportionalToParent"              "1"
        "LabelText"                         "#TF_Charge"
        "TextAlignment"                     "south"
        "Font"                              "ScoreboardVerySmall"
        "DisabledFGColor2_Override"         "White"
        "Pin_To_Sibling"                    "ChargeMeter"
        "Pin_Corner_To_Sibling"             "PIN_CENTER_TOP"
        "Pin_To_Sibling_Corner"             "PIN_CENTER_TOP"
    }
    "PipesPresentPanel"
    {
        "ControlName"           "EditablePanel"
        "FieldName"             "PipesPresentPanel"
        "XPos"                  "0"
        "YPos"                  "0"
        "ZPos"                  "1"
        "Wide"                  "f0"
        "Tall"                  "f0"
        "Visible"               "1"
        "NumPipesLabel"
        {
            "ControlName"                   "CExLabel"
            "FieldName"                     "NumPipesLabel"
            "XPos"                          "cs-0.5"
            "YPos"                          "c50"
            "ZPos"                          "2"
            "Wide"                          "30"
            "Tall"                          "20"
            "Visible"                       "1"
            "Enabled"                       "1"
            "ProportionalToParent"          "1"
            "LabelText"                     "%activepipes%"
            "TextAlignment"                 "center"
            "Font"                          "m0refont24"
            "FGColor"                       "White"
        }
        "NumPipesLabelDropshadow"
        {
            "ControlName"                   "CExLabel"
            "FieldName"                     "NumPipesLabelDropshadow"
            "XPos"                          "-1"
            "YPos"                          "-1"
            "ZPos"                          "2"
            "Wide"                          "30"
            "Tall"                          "20"
            "Visible"                       "1"
            "Enabled"                       "1"
            "ProportionalToParent"          "1"
            "LabelText"                     "%activepipes%"
            "TextAlignment"                 "center"
            "Font"                          "m0refont24"
            "FGColor"                       "Black"
            "Pin_To_Sibling"                "NumPipesLabel"
        }
        "PipeIcon"
        {
            "ControlName"           "CTFImagePanel"
            "FieldName"             "PipeIcon"
            "XPos"                  "9999"
            "YPos"                  "9999"
            "Wide"                  "0"
            "Tall"                  "0"
            "Visible"               "0"
            "Enabled"               "0"
        }
    }
    //==================================================================================================================================================
    // REMOVED ELEMENTS
    //==================================================================================================================================================
    "background"
    {
        "ControlName"           "CTFImagePanel"
        "FieldName"             "background"
        "XPos"                  "9999"
        "YPos"                  "9999"
        "Wide"                  "0"
        "Tall"                  "0"
        "Visible"               "0"
        "Enabled"               "0"
    }
    "NoPipesPresentPanel"
    {
        "ControlName"           "EditablePanel"
        "FieldName"             "NoPipesPresentPanel"
        "XPos"                  "9999"
        "YPos"                  "9999"
        "Wide"                  "0"
        "Tall"                  "0"
        "Visible"               "0"
        "Enabled"               "0"
    }
}