"Resource/UI/HudDemomanCharge.res"
{
    "ChargeAnchor"
    {
        "ControlName"               "EditablePanel"
        "fieldName"                 "ChargeAnchor"
        "xpos"                      "cs-0.5"
        "ypos"                      "cs-0.5+40"
        "zpos"                      "7"
        "wide"                      "30"
        "tall"                      "10"
        "visible"                   "0"
        "enabled"                   "1"
        "bgcolor_override"          "blue"
    }
	"ItemEffectMeterBG"
    {
        "ControlName"           "EditablePanel"
        "fieldName"             "ItemEffectMeterBG"
        "font"                  "Default"
        "xpos"                  "0"
        "ypos"                  "0"
        "zpos"                  "-10"
        "wide"                  "30"
        "tall"                  "6"
        "visible"               "1"
        "proportionaltoparent"          "1"
        "border"                "ItemEffectMeterBG"
        "pin_to_sibling"    "ChargeAnchor"
        
    }
    "ChargeMeter"
    {
        "ControlName"                   "ContinuousProgressBar"
        "FieldName"                     "ChargeMeter"
        "XPos"                          "-1"
        "YPos"                          "-1"
        "ZPos"                          "2"
        "Wide"                          "28"
        "Tall"                          "4"
        "Visible"                       "1"
        "Enabled"                       "1"
        "ProportionalToParent"          "1"
        "bgcolor_override"              "blank"	//actually has influence
        "FGColor_Override"         "PureWhite"
        "pin_to_sibling"    "ChargeAnchor"
    }
    "mod"
    {
        "ControlName"                   "ImagePanel"
        "fieldName"                     "mod"
        "xpos"                          "0"
        "ypos"                          "0"
        "zpos"                          "4"
        "wide"                          "30"
        "tall"                          "6"
        "visible"                       "1"
        "enabled"                       "1"
        "proportionaltoparent"          "1"
        "image"                         "replay/thumbnails/mod"
        "scaleImage"                    "1"
        "drawcolor"                     "ItemMeterFG"
        "pin_to_sibling"    "ChargeAnchor"
    }
    "ItemEffectMeterRoundedCorners"
    {
        "ControlName"                   "EditablePanel"
        "fieldName"                     "ItemEffectMeterRoundedCorners"
        "xpos"                          "-1"
        "ypos"                          "-1"
        "zpos"                          "3"
        "wide"                          "28"
        "tall"                          "4"
        "visible"                       "1"
        "proportionaltoparent"          "1"
        "border"                        "ItemEffectMeterRoundedCorners"
        "pin_to_sibling"    "ChargeAnchor"
    }
}