"Resource/UI/HudDemomanCharge.res"
{
    "ChargeAnchor"
    {
        "ControlName"               "EditablePanel"
        "fieldName"                 "ChargeAnchor"
        "xpos"                      "0"
        "ypos"                      "0"
        "zpos"                      "7"
        "wide"                      "30"
        "tall"                      "6"
        "visible"                   "0"
        "enabled"                   "1"
        "bgcolor_override"          "blue"
    }
    "Mod"
    {
        "ControlName"                   "EditablePanel"
        "fieldName"                     "Mod"
        "xpos"                          "0"
        "ypos"                          "0"
        "zpos"                          "4"
        "wide"                          "30"
        "tall"                          "6"
        "visible"                       "1"
        "proportionaltoparent"          "1"
        "border"                        "ItemEffectMeterMod_Stamina"
        "pin_to_sibling"                "ChargeAnchor"
    }
    "ItemEffectMeterRoundedCorners"
    {
        "ControlName"                   "EditablePanel"
        "fieldName"                     "ItemEffectMeterRoundedCorners"
        "xpos"                          "-1"
        "ypos"                          "-1"
        "zpos"                          "3"
        "wide"                          "28"
        "tall"                          "4"
        "visible"                       "1"
        "proportionaltoparent"          "1"
        "border"                        "ItemEffectMeterRoundedCorners_Stamina"
        "pin_to_sibling"                "ChargeAnchor"
    }
    "ChargeMeter"
    {
        "ControlName"                   "ContinuousProgressBar"
        "FieldName"                     "ChargeMeter"
        "XPos"                          "-1"
        "YPos"                          "-1"
        "ZPos"                          "2"
        "Wide"                          "28"
        "Tall"                          "4"
        "Visible"                       "1"
        "Enabled"                       "1"
        "ProportionalToParent"          "1"
        "bgcolor_override"              "blank"	//actually has influence
        "FGColor_Override"              "PureWhite"
        "pin_to_sibling"                "ChargeAnchor"
    }
    "ModMultiplier"
    {
        "ControlName"                   "ImagePanel"
        "fieldName"                     "ModMultiplier"
        "xpos"                          "0"
        "ypos"                          "0"
        "zpos"                          "0"
        "wide"                          "f0"
        "tall"                          "6"
        "visible"                       "1"
        "enabled"                       "1"
        "proportionaltoparent"          "1"
        "scaleImage"                    "1"
        "paintBorder"                   "1"
        "border"                        "ItemEffectMeterBG_Stamina_Inv"
         "pin_to_sibling"                "ChargeAnchor"
    }    
    "ItemEffectMeterBG"
    {
        "ControlName"                   "EditablePanel"
        "fieldName"                     "ItemEffectMeterBG"
        "font"                          "Default"
        "xpos"                          "0"
        "ypos"                          "0"
        "zpos"                          "-10"
        "wide"                          "30"
        "tall"                          "6"
        "visible"                       "1"
        "proportionaltoparent"          "1"
        "border"                        "ItemEffectMeterBG_Stamina"
        "pin_to_sibling"                "ChargeAnchor"
    }
}