"Resource/UI/HudDemomanPipes_Base.res"
{
    "ChargeAnchor"
    {
        "ControlName"               "EditablePanel"
        "fieldName"                 "ChargeAnchor"
        "xpos"                      "cs-0.5"
        "ypos"                      "c0+44"
        "zpos"                      "7"
        "wide"                      "30"
        "tall"                      "6"
        "visible"                   "0"
        "enabled"                   "1"
        "bgcolor_override"          "blue"
    }
    "Mod"
    {
        "ControlName"                   "EditablePanel"
        "fieldName"                     "Mod"
        "xpos"                          "0"
        "ypos"                          "0"
        "zpos"                          "4"
        "wide"                          "30"
        "tall"                          "6"
        "visible"                       "1"
        "proportionaltoparent"          "1"
        "border"                        "ItemEffectMeterMod_Stamina"
        "pin_to_sibling"                "ChargeAnchor"
    }
    "ItemEffectMeterRoundedCorners"
    {
        "ControlName"                   "EditablePanel"
        "fieldName"                     "ItemEffectMeterRoundedCorners"
        "xpos"                          "-1"
        "ypos"                          "-1"
        "zpos"                          "3"
        "wide"                          "28"
        "tall"                          "4"
        "visible"                       "1"
        "proportionaltoparent"          "1"
        "border"                        "ItemEffectMeterRoundedCorners_Stamina"
        "pin_to_sibling"                "ChargeAnchor"
    }
    "ChargeMeter"
    {
        "ControlName"                   "ContinuousProgressBar"
        "FieldName"                     "ChargeMeter"
        "XPos"                          "-1"
        "YPos"                          "-1"
        "ZPos"                          "2"
        "Wide"                          "28"
        "Tall"                          "4"
        "Visible"                       "1"
        "Enabled"                       "1"
        "ProportionalToParent"          "1"
        "bgcolor_override"              "blank"	//actually has influence
        "FGColor_Override"              "PureWhite"
        "pin_to_sibling"                "ChargeAnchor"
    }
    "ModMultiplier"
    {
        "ControlName"                   "ImagePanel"
        "fieldName"                     "ModMultiplier"
        "xpos"                          "0"
        "ypos"                          "0"
        "zpos"                          "0"
        "wide"                          "30"
        "tall"                          "6"
        "visible"                       "1"
        "enabled"                       "1"
        "proportionaltoparent"          "1"
        "scaleImage"                    "1"
        "paintBorder"                   "1"
        "border"                        "ItemEffectMeterBG_Stamina_Inv"
        "pin_to_sibling"                "ChargeAnchor"
    }
    "ItemEffectMeterBG"
    {
        "ControlName"                   "EditablePanel"
        "fieldName"                     "ItemEffectMeterBG"
        "font"                          "Default"
        "xpos"                          "0"
        "ypos"                          "0"
        "zpos"                          "-10"
        "wide"                          "30"
        "tall"                          "6"
        "visible"                       "1"
        "proportionaltoparent"          "1"
        "border"                        "ItemEffectMeterBG_Stamina"
        "pin_to_sibling"                "ChargeAnchor"
    }
    "ChargeLabel"	// dead
    {
        "ControlName"                       "CExLabel"
        "FieldName"                         "ChargeLabel"
        "XPos"                              "0"
        "YPos"                              "0"
        "ZPos"                              "3"
        "Wide"                              "0"
        "Tall"                              "0"
        "Visible"                           "1"
        "Enabled"                           "0"
        "ProportionalToParent"              "1"
        "LabelText"                         "#TF_Charge"
        "TextAlignment"                     "south"
        "Font"                              "ScoreboardVerySmall"
        "DisabledFGColor2_Override"         "White"
        "Pin_To_Sibling"                    "ChargeMeter"
        "Pin_Corner_To_Sibling"             "PIN_CENTER_TOP"
        "Pin_To_Sibling_Corner"             "PIN_CENTER_TOP"
    }
    "PipesPresentPanel"
    {
        "ControlName"                   "EditablePanel"
        "FieldName"                     "PipesPresentPanel"
        "XPos"                          "rs1-73"
        "YPos"                          "rs1-23"
        "ZPos"                          "1"
        "Wide"                          "60"
        "Tall"                          "20"
        "proportionaltoparent"          "1"
        "Visible"                       "1"
        "PipeIcon"
        {
            "ControlName"           "CTFImagePanel"
            "fieldName"             "PipeIcon"
            "xpos"                  "0"
            "ypos"                  "0"
            "wide"                  "20"
            "tall"                  "20"
            "visible"               "1"
            "enabled"               "1"
            "drawcolor"             "White"
            "image"                 "replay/thumbnails/portraits/demoman"
            "scaleImage"            "1"
            "teambg_2"              "replay/thumbnails/portraits/demoman"
            "teambg_3"              "replay/thumbnails/portraits/demoman"
        }
        "TEST"
        {
            "ControlName"                   "CExLabel"
            "FieldName"                     "TEST"
            "XPos"                          "0"
            "YPos"                          "0"
            "ZPos"                          "-1"
            "Wide"                          "20"
            "Tall"                          "20"
            "Visible"                       "1"
            "Enabled"                       "1"
            "ProportionalToParent"          "1"
            "LabelText"                     "o"
            "TextAlignment"                 "center"
            "Font"                          "HeaderEm_XL_Blur"
            "textinsety"                    "-6"
            "FGColor"                       "Shadow"
            "pin_to_sibling"                "PipeIcon"
        }
        "NumPipesLabel"
        {
            "ControlName"                   "CExLabel"
            "FieldName"                     "NumPipesLabel"
            "XPos"                          "22"
            "YPos"                          "0"
            "ZPos"                          "2"
            "Wide"                          "20"
            "Tall"                          "f0"
            "Visible"                       "1"
            "Enabled"                       "1"
            "ProportionalToParent"          "1"
            "LabelText"                     "%activepipes%"
            "TextAlignment"                 "west"
            "Font"                          "HealthAmmo"
            "FGColor"                       "White"
        }
        "NumPipesLabelDropshadow"
        {
            "ControlName"                   "CExLabel"
            "FieldName"                     "NumPipesLabelDropshadow"
            "XPos"                          "-1"
            "YPos"                          "-1"
            "ZPos"                          "2"
            "Wide"                          "20"
            "Tall"                          "f0"
            "Visible"                       "1"
            "Enabled"                       "1"
            "ProportionalToParent"          "1"
            "LabelText"                     "%activepipes%"
            "TextAlignment"                 "west"
            "Font"                          "HealthAmmo_Blur"
            "FGColor"                       "Shadow"
            "Pin_To_Sibling"                "NumPipesLabel"
        }
    }
    //==================================================================================================================================================
    // REMOVED ELEMENTS
    //==================================================================================================================================================
    "background"
    {
        "ControlName"           "CTFImagePanel"
        "FieldName"             "background"
        "XPos"                  "9999"
        "YPos"                  "9999"
        "Wide"                  "0"
        "Tall"                  "0"
        "Visible"               "0"
        "Enabled"               "0"
    }
    "NoPipesPresentPanel"
    {
        "ControlName"           "EditablePanel"
        "FieldName"             "NoPipesPresentPanel"
        "XPos"                  "9999"
        "YPos"                  "9999"
        "Wide"                  "0"
        "Tall"                  "0"
        "Visible"               "0"
        "Enabled"               "0"
    }
}