"Resource/UI/HudMedicCharge.res"
{
    "Background"
    {
        "ControlName"           "CTFImagePanel"
        "fieldName"             "Background"
        "xpos"                  "0"
        "ypos"                  "0"
        "zpos"                  "0"
        "wide"                  "0"
        "tall"                  "0"
        "visible"               "1"
        "enabled"               "1"
        "image"                 "../hud/medic_charge_blue_bg"
        "scaleImage"            "1"
        "teambg_2"              "../hud/medic_charge_red_bg"
        "teambg_3"              "../hud/medic_charge_blue_bg"
    }
    // MARK: Label
    "ChargeLabel"
    {
        "ControlName"                   "CExLabel"
        "fieldName"                     "ChargeLabel"
        "xpos"                          "0"
        "ypos"                          "0"
        "zpos"                          "123"
        "wide"                          "f0"
        "tall"                          "20"
        "proportionaltoparent"          "1"
        "autoResize"                    "1"
        "pinCorner"                     "2"
        "visible"                       "1"
        "enabled"                       "1"
        "tabPosition"                   "0"
        "labelText"                     "#TF_UberchargeMinHUD"
        "textAlignment"                 "center"
        "dulltext"                      "0"
        "brighttext"                    "0"
        "font"                          "HealthAmmo"
        "fgcolor_override"              "White"
    }
    "ChargeLabelShadow"
    {
        "ControlName"               "CExLabel"
        "fieldName"                 "ChargeLabelShadow"
        "xpos"                      "0"
        "ypos"                      "0"
        "zpos"                      "123"
        "wide"                      "150"
        "tall"                      "125"
        "autoResize"                "1"
        "pinCorner"                 "2"
        "visible"                   "1"
        "enabled"                   "1"
        "tabPosition"               "0"
        "labelText"                 "#TF_UberchargeMinHUD"
        "textAlignment"             "center"
        "dulltext"                  "0"
        "brighttext"                "0"
        "font"                      "HealthAmmo_Blur"
        "fgcolor_override"          "Shadow"
        "pin_to_sibling"            "ChargeLabel"
    }
    "IndividualChargesLabel"
    {
        "ControlName"                   "CExLabel"
        "fieldName"                     "IndividualChargesLabel"
        "xpos"                          "cs0+4"
        "ypos"                          "0"
        "zpos"                          "999"
        "wide"                          "30"
        "tall"                          "20"
        "proportionaltoparent"          "1"
        "autoResize"                    "1"
        "pinCorner"                     "2"
        "visible"                       "1"
        "enabled"                       "1"
        "tabPosition"                   "0"
        "labelText"                     "#TF_IndividualUberchargesMinHUD"
        "textAlignment"                 "west"
        "dulltext"                      "0"
        "brighttext"                    "0"
        "font"                          "HealthAmmo"
        "fgcolor_override"              "White"
    }
    // MARK: Bar
    "Mod"
    {
        "ControlName"                   "ImagePanel"
        "fieldName"                     "Mod"
        "xpos"                          "cs-0.5"
        "ypos"                          "rs1"
        "zpos"                          "4"
        "wide"                          "f0"
        "tall"                          "4"
        // "tall"                          "6" // TODO - STAMINA_STYLE
        "visible"                       "1"
        "enabled"                       "1"
        "proportionaltoparent"          "1"
        "image"                         "replay/thumbnails/mod"
        "scaleImage"                    "1"
        "drawcolor"                     "ItemMeterFG"
    }
    "ChargeMeter"
    {
        "ControlName"                   "ContinuousProgressBar"
        "fieldName"                     "ChargeMeter"
        "font"                          "Oblique9"
        "xpos"                          "0"
        "ypos"                          "rs1"
        "zpos"                          "2"
        "wide"                          "f0"
        "tall"                          "4"
        "proportionaltoparent"          "1"
        "autoResize"                    "0"
        "pinCorner"                     "0"
        "visible"                       "1"
        "enabled"                       "1"
        "textAlignment"                 "west"
        "dulltext"                      "0"
        "brighttext"                    "0"
        "bgcolor_override"              "Blank"
        "fgcolor_override"              "PureWhite"
    }
    "ChargeMeter1"
    {
        "ControlName"                   "ContinuousProgressBar"
        "fieldName"                     "ChargeMeter1"
        "font"                          "Default"
        "xpos"                          "0"
        "ypos"                          "rs1"
        "proportionaltoparent"          "1"
        "zpos"                          "2"
        "wide"                          "p0.25"
        "tall"                          "4"
        "autoResize"                    "0"
        "pinCorner"                     "0"
        "visible"                       "1"
        "enabled"                       "1"
        "textAlignment"                 "west"
        "dulltext"                      "0"
        "brighttext"                    "0"
        "bgcolor_override"              "Blank"
        "fgcolor_override"              "PureWhite"
    }
    "ChargeMeter2"
    {
        "ControlName"                   "ContinuousProgressBar"
        "fieldName"                     "ChargeMeter2"
        "font"                          "Default"
        "xpos"                          "p0.25"
        "ypos"                          "rs1"
        "proportionaltoparent"          "1"
        "zpos"                          "2"
        "wide"                          "p0.25"
        "tall"                          "4"
        "autoResize"                    "0"
        "pinCorner"                     "0"
        "visible"                       "1"
        "enabled"                       "1"
        "textAlignment"                 "west"
        "dulltext"                      "0"
        "brighttext"                    "0"
        "bgcolor_override"              "Blank"
        "fgcolor_override"              "PureWhite"
    }
    "ChargeMeter3"
    {
        "ControlName"                   "ContinuousProgressBar"
        "fieldName"                     "ChargeMeter3"
        "font"                          "Default"
        "xpos"                          "p0.5"
        "ypos"                          "rs1"
        "proportionaltoparent"          "1"
        "zpos"                          "2"
        "wide"                          "p0.25"
        "tall"                          "4"
        "autoResize"                    "0"
        "pinCorner"                     "0"
        "visible"                       "1"
        "enabled"                       "1"
        "textAlignment"                 "west"
        "dulltext"                      "0"
        "brighttext"                    "0"
        "bgcolor_override"              "Blank"
        "fgcolor_override"              "PureWhite"
    }
    "ChargeMeter4"
    {
        "ControlName"                   "ContinuousProgressBar"
        "fieldName"                     "ChargeMeter4"
        "font"                          "Default"
        "xpos"                          "p0.75"
        "ypos"                          "rs1"
        "proportionaltoparent"          "1"
        "zpos"                          "2"
        "wide"                          "p0.25"
        "tall"                          "4"
        "autoResize"                    "0"
        "pinCorner"                     "0"
        "visible"                       "1"
        "enabled"                       "1"
        "textAlignment"                 "west"
        "dulltext"                      "0"
        "brighttext"                    "0"
        "bgcolor_override"              "Blank"
        "fgcolor_override"              "PureWhite"
    }
    "ModMultiplier"
    {
        "ControlName"                   "ImagePanel"
        "fieldName"                     "ModMultiplier"
        "xpos"                          "cs-0.5"
        "ypos"                          "rs1"
        "zpos"                          "0"
        "wide"                          "f0"
        "tall"                          "4"
        // "tall"                          "6" // TODO - STAMINA_STYLE
        "visible"                       "1"
        "enabled"                       "1"
        "proportionaltoparent"          "1"
        "image"                         "replay/thumbnails/mod2x"
        "scaleImage"                    "1"
        "drawcolor"                     "ItemMeterFGInv"
    }
    "ItemEffectMeterBG"
    {
        "ControlName"                   "EditablePanel"
        "fieldName"                     "ItemEffectMeterBG"
        "font"                          "Default"
        "xpos"                          "cs-0.5"
        "ypos"                          "rs1"
        "zpos"                          "-10"
        "wide"                          "f0"
        "tall"                          "4"
        // "tall"                  "6"  // TODO - STAMINA_STYLE
        "visible"                       "1"
        "bgcolor_override"              "PureWhite"
        "proportionaltoparent"          "1"
        "border"                        ""
        // "border"                "ItemEffectMeterBG_Stamina"  // TODO - STAMINA_STYLE
    }
    
    //==================================================================================================================================================
	// VACCINATOR RESIST ICON
	//==================================================================================================================================================
	"ResistIconAnchor"
	{
		"ControlName"								"Panel"
		"FieldName"									"ResistIconAnchor"
		"XPos"										"cs-1-4"
		"YPos"										"0"
		"Wide"										"20"
		"Tall"										"20"
		"Visible"									"1"
		"Enabled"									"1"
		"ProportionalToParent"						"1"
	}
	"ResistIcon"
	{
		"ControlName"								"ImagePanel"
		"FieldName"									"ResistIcon"
		"XPos"										"0"
		"YPos"										"0"
		"Wide"										"18"
		"Tall"										"18"
		"Visible"									"1"
		"Enabled"									"1"
		"Image"										"../HUD/defense_buff_bullet_blue"
		"ScaleImage"								"1"

		"Pin_To_Sibling"							"ResistIconAnchor"
		"Pin_Corner_To_Sibling"						"PIN_CENTER_RIGHT"
		"Pin_To_Sibling_Corner"						"PIN_CENTER_RIGHT"
	}

    "HealthClusterIcon" // dead
	{
		"ControlName"								"ImagePanel"
		"FieldName"									"HealthClusterIcon"
		"XPos"										"9999"
		"YPos"										"9999"
		"Wide"										"0"
		"Tall"										"0"
		"Visible"									"0"
		"Enabled"									"0"
	}
}