"Resource/UI/HudObjectiveTimePanel.res"
{
    "WaitingForPlayersLabel"
    {
        "ControlName"                   "CExLabel"
        "fieldName"                     "WaitingForPlayersLabel"
        "xpos"                          "cs-0.5"
        "ypos"                          "18"
        "zpos"                          "5"
        "wide"                          "45"
        "tall"                          "15"
        "proportionaltoparent"          "1"
        "visible"                       "0"
        "enabled"                       "1"
        "labelText"                     "WAITING"
        "textAlignment"                 "center"
        "dulltext"                      "0"
        "brighttext"                    "0"
        "wrap"                          "0"
        "font"                          "BodyEm_MD"
        "fgcolor_override"              "FinalsYellow"
        "bgcolor_override"              "Blank"
        "if_match"
        {
            "xpos"          "c-82"
            "ypos"          "45"
            "font"          "HudFontSmallestBold"
        }
    }
    "OvertimeLabel"
    {
        "ControlName"                   "CExLabel"
        "fieldName"                     "OvertimeLabel"
        "xpos"                          "cs-0.5"
        "ypos"                          "18"
        "zpos"                          "5"
        "wide"                          "45"
        "tall"                          "15"
        "proportionaltoparent"          "1"
        "visible"                       "0"
        "enabled"                       "1"
        "labelText"                     "OVERTIME"
        "textAlignment"                 "center"
        "dulltext"                      "0"
        "brighttext"                    "0"
        "wrap"                          "0"
        "font"                          "BodyEm_MD"
        "fgcolor_override"              "FinalsYellow"
        "bgcolor_override"              "Blank"
        "if_match"
        {
            "xpos"          "c-82"
            "ypos"          "45"
            "font"          "HudFontSmallestBold"
        }
    }
    "SuddenDeathLabel"
    {
        "ControlName"                   "CExLabel"
        "fieldName"                     "SuddenDeathLabel"
        "xpos"                          "cs-0.5"
        "ypos"                          "18"
        "zpos"                          "5"
        "wide"                          "45"
        "tall"                          "15"
        "proportionaltoparent"          "1"
        "visible"                       "0"
        "enabled"                       "1"
        "labelText"                     "SUDDEN DEATH"
        "textAlignment"                 "center"
        "dulltext"                      "0"
        "brighttext"                    "0"
        "wrap"                          "0"
        "font"                          "BodyEm_MD"
        "fgcolor_override"              "FinalsYellow"
        "bgcolor_override"              "Blank"
        "if_match"
        {
            "xpos"          "c-82"
            "ypos"          "45"
            "font"          "HudFontSmallestBold"
        }
    }
    "SetupLabel"
    {
        "ControlName"                   "CExLabel"
        "fieldName"                     "SetupLabel"
        "xpos"                          "cs-0.5"
        "ypos"                          "18"
        "zpos"                          "5"
        "wide"                          "45"
        "tall"                          "15"
        "proportionaltoparent"          "1"
        "visible"                       "0"
        "enabled"                       "1"
        "labelText"                     "SETUP"
        "textAlignment"                 "center"
        "dulltext"                      "0"
        "brighttext"                    "0"
        "wrap"                          "0"
        "font"                          "BodyEm_MD"
        "fgcolor_override"              "FinalsYellow"
        "bgcolor_override"              "Blank"
        "if_match"
        {
            "xpos"          "c-82"
            "ypos"          "45"
            "font"          "HudFontSmallestBold"
        }
    }
    "ServerTimeLimitLabel"
    {
        "ControlName"                   "CExLabel"
        "fieldName"                     "ServerTimeLimitLabel"
        "xpos"                          "55"
        "ypos"                          "14"
        "zpos"                          "5"
        "wide"                          "45"
        "tall"                          "15"
        "proportionaltoparent"          "1"
        "visible"                       "0"
        "enabled"                       "1"
        "labelText"                     "%servertimeleft%"
        "textAlignment"                 "center"
        "dulltext"                      "0"
        "brighttext"                    "0"
        "wrap"                          "0"
        "font"                          "DinBold11"
        "fgcolor_override"              "owFULLWHITE"
        "bgcolor_override"              "0 0 0 75"
        "if_match"
        {
            "xpos"          "cs-0.5"
            "ypos"          "17"
            "font"          "Oblique12"
        }
    }
    // MARK: Dead
    "TimePanelProgressBar"
    {
        "ControlName"           "CTFProgressBar"
        "FieldName"             "TimePanelProgressBar"
        "XPos"                  "9999"
        "YPos"                  "9999"
        "Wide"                  "0"
        "Tall"                  "0"
        "Visible"               "0"
        "Enabled"               "0"
    }
    "WaitingForPlayersBG"
    {
        "ControlName"           "CTFImagePanel"
        "FieldName"             "WaitingForPlayersBG"
        "XPos"                  "9999"
        "YPos"                  "9999"
        "Wide"                  "0"
        "Tall"                  "0"
        "Visible"               "0"
        "Enabled"               "0"
    }
    "OvertimeBG"
    {
        "ControlName"           "CTFImagePanel"
        "FieldName"             "OvertimeBG"
        "XPos"                  "9999"
        "YPos"                  "9999"
        "Wide"                  "0"
        "Tall"                  "0"
        "Visible"               "0"
        "Enabled"               "0"
    }
    "SuddenDeathBG"
    {
        "ControlName"           "CTFImagePanel"
        "FieldName"             "SuddenDeathBG"
        "XPos"                  "9999"
        "YPos"                  "9999"
        "Wide"                  "0"
        "Tall"                  "0"
        "Visible"               "0"
        "Enabled"               "0"
    }
    "SetupBG"
    {
        "ControlName"           "CTFImagePanel"
        "FieldName"             "SetupBG"
        "XPos"                  "9999"
        "YPos"                  "9999"
        "Wide"                  "0"
        "Tall"                  "0"
        "Visible"               "0"
        "Enabled"               "0"
    }
}