"Resource/UI/HudPlayerHealth.res"
{
    // player health data
    "HudPlayerHealth"
    {
        "ControlName"                       "EditablePanel"
        "fieldName"                         "HudPlayerHealth"
        "xpos"                              "20"
        "ypos"                              "rs1-20"
        "xpos_minmode"                      "20"
        "ypos_minmode"                      "rs1-20"
        "zpos"                              "2"
        "wide"                              "128"
        "tall"                              "60"
        "visible"                           "1"
        "enabled"                           "1"
        "HealthBonusPosAdj"                 "288" // TODO - add baselog options for this 1440p: 384, 1080p: 288
        "HealthDeathWarning"                "1.0"
        "HealthDeathWarningColor"           "HUDDeathWarning"
    }
    // MARK: Health Numbers
    // MARK: Anchor
    "HealthBGReal"
    {
        "ControlName"                   "EditablePanel"
        "fieldName"                     "HealthBGReal"
        "xpos"                          "0"
        "ypos"                          "rs1-20"
        "zpos"                          "0"
        "wide"                          "64"
        "tall"                          "26"
        "proportionaltoparent"          "1"
        "visible"                       "1"
        "enabled"                       "1"
        "bgcolor_override"              "TransparentLightestBlack"
        "paintBackground"               "1"
        "paintBackgroundType"           "2"
    }
    // Health Number
    "PlayerStatusHealthValue"
    {
        "ControlName"                   "CExLabel"
        "fieldName"                     "PlayerStatusHealthValue"
        "xpos"                          "-5"
        "ypos"                          "-3"
        "zpos"                          "5"
        "auto_wide_tocontents"          "1"
        "tall"                          "20"
        "visible"                       "1"
        "enabled"                       "1"
        "labelText"                     "%Health%"
        "textAlignment"                 "east"
        "font"                          "HealthAmmo"
        "textinsetx"                    "5"
        "fgcolor"                       "HealthAmmo"
        "pin_to_sibling"                "HealthBGReal"
        "pin_corner_to_sibling"         "PIN_BOTTOMLEFT"
        "pin_to_sibling_corner"         "PIN_BOTTOMLEFT"
    }
    "PlayerStatusHealthValueShadow"
    {
        "ControlName"                   "CExLabel"
        "fieldName"                     "PlayerStatusHealthValueShadow"
        "xpos"                          "0"
        "ypos"                          "0"
        "zpos"                          "-1"
        "auto_wide_tocontents"          "1"
        "tall"                          "20"
        "visible"                       "1"
        "enabled"                       "1"
        "labelText"                     "%Health%"
        "textAlignment"                 "east"
        "font"                          "HealthAmmo_Blur"
        "textinsetx"                    "5"
        "fgcolor"                       "Shadow"
        "pin_to_sibling"                "PlayerStatusHealthValue"
    }
    // Slash
    "Slash"	// normal slash
    {
        "ControlName"                   "CExLabel"
        "fieldName"                     "Slash"
        "xpos"                          "-3"
        "ypos"                          "0"
        "wide"                          "10"
        "tall"                          "20"
        "visible"                       "1"
        "enabled"                       "1"
        "font"                          "HealthAmmo_Alt"
        "textinsety"                    "3"
        "fgcolor"                       "HealthAmmo_Alt"
        "labelText"                     "/"
        "zpos"                          "0"
        "textAlignment"                 "center"
        "pin_to_sibling"                "PlayerStatusHealthValue"
        "pin_corner_to_sibling"         "PIN_BOTTOMLEFT"
        "pin_to_sibling_corner"         "PIN_BOTTOMRIGHT"
    }
    "SlashShadow"	//slash shadow
    {
        "ControlName"           "CExLabel"
        "fieldName"             "SlashShadow"
        "xpos"                  "0"
        "ypos"                  "0"
        "wide"                  "10"
        "tall"                  "20"
        "visible"               "1"
        "enabled"               "1"
        "font"                  "HealthAmmo_Alt_Blur"
        "textinsety"            "3"
        "fgcolor"               "Shadow"
        "labelText"             "/"
        "zpos"                  "-1"
        "textAlignment"         "center"
        "pin_to_sibling"        "Slash"
    }
    // Max Health
    "MaxHealth"
    {
        "ControlName"                   "CExLabel"
        "fieldName"                     "MaxHealth"
        "xpos"                          "-4"
        "ypos"                          "0"
        "zpos"                          "0"
        "auto_wide_tocontents"          "1"
        "tall"                          "20"
        "visible"                       "1"
        "enabled"                       "1"
        "labelText"                     "%MaxHealth%"
        "textAlignment"                 "west"
        "font"                          "HealthAmmo_Alt"
        "textinsetx"                    "5"
        "textinsety"                    "3"
        "fgcolor"                       "HealthAmmo_Alt"
        "pin_to_sibling"                "Slash"
        "pin_corner_to_sibling"         "PIN_BOTTOMLEFT"
        "pin_to_sibling_corner"         "PIN_BOTTOMRIGHT"
    }
    "MaxHealthShadow"
    {
        "ControlName"                   "CExLabel"
        "fieldName"                     "MaxHealthShadow"
        "xpos"                          "0"
        "ypos"                          "0"
        "zpos"                          "-1"
        "auto_wide_tocontents"          "1"
        "tall"                          "20"
        "visible"                       "1"
        "enabled"                       "1"
        "labelText"                     "%MaxHealth%"
        "textAlignment"                 "west"
        "font"                          "HealthAmmo_Alt_Blur"
        "textinsetx"                    "5"
        "textinsety"                    "3"
        "fgcolor"                       "Shadow"
        "pin_to_sibling"                "MaxHealth"
    }
    // MARK: Bar
    "PlayerStatusHealthBonusImage"
    {
        "ControlName"                   "ImagePanel"
        "fieldName"                     "PlayerStatusHealthBonusImage"
        "xpos"                          "r0"
        "ypos"                          "rs1"
        "zpos"                          "3"
        "wide"                          "16"
        "tall"                          "16"
        "proportionaltoparent"          "1"
        "visible"                       "0"
        "enabled"                       "1"
        "image"                         "../hud/health_over_bg"
        "scaleImage"                    "1"
        "proportionaltoparent"          "1"
    }
    "BarFG"	// actually background, static
    {
        "ControlName"                   "EditablePanel"
        "fieldName"                     "BarFG"
        "xpos"                          "0"
        "ypos"                          "rs1"
        "zpos"                          "0"
        "wide"                          "128"
        "tall"                          "16"
        "visible"                       "1"
        "enabled"                       "1"
        "bgcolor_override"              "White"
        "paintBackground"               "1"
        "proportionaltoparent"          "1"
    }
    refract
    {
        "ControlName"                   "ImagePanel"
        "fieldName"                     "refract"
        "xpos"                          "0"
        "ypos"                          "rs1"
        "zpos"                          "4"
        "wide"                          "128"
        "tall"                          "16"
        "proportionaltoparent"          "1"
        "visible"                       "1"
        "enabled"                       "1"
        "proportionaltoparent"          "1"
        "image"                         "replay/thumbnails/healthbar/healthbar-8-refract"
        "scaleImage"                    "1"
        "drawcolor"                     "ItemMeterFG"
    }
    "BarBG"	// actually foreground, moves from right to left as health lowers
    {
        "ControlName"                   "ImagePanel"
        "fieldName"                     "BarBG"
        "xpos"                          "0"
        "ypos"                          "0"
        "zpos"                          "0"
        "wide"                          "128"
        "tall"                          "16"
        "visible"                       "1"
        "enabled"                       "1"
        "fillcolor"                     "Black"
        "scaleImage"                    "1"
        "proportionaltoparent"          "1"
        "pin_to_sibling"                "PlayerStatusHealthBonusImage"
        "pin_to_sibling_corner"         "7"
        "pin_corner_to_sibling"         "7"
    }
    "OverHealBar"
    {
        "ControlName"                   "ImagePanel"
        "fieldName"                     "OverHealBar"
        "xpos"                          "-144"	
        "ypos"                          "0"
        "zpos"                          "3"
        "wide"                          "128"
        "tall"                          "16"
        "visible"                       "1"
        "enabled"                       "1"
        "fillcolor"                     "FinalsOverhealBar"
        "scaleImage"                    "1"
        "proportionaltoparent"          "1"
        "pin_to_sibling"                "PlayerStatusHealthBonusImage"
        "pin_to_sibling_corner"         "5"
        "pin_corner_to_sibling"         "5"
    }
    // "PlayerStatusHealthValue"
    // {
    //     "ControlName"                   "CExLabel"
    //     "fieldName"                     "PlayerStatusHealthValue"
    //     "xpos"                          "rs1"
    //     "ypos"                          "32"
    //     "zpos"                          "5"
    //     "wide"                          "32"
    //     "tall"                          "16"
    //     "visible"                       "1"
    //     "enabled"                       "1"
    //     "labelText"                     "%Health%"
    //     "textAlignment"                 "center"
    //     "font"                          "HudClassHealth"
    //     "fgcolor"                       "TanDark"
    //     "proportionaltoparent"          "1"
    // }
    // "PlayerStatusMaxHealthValue"
    // {
    //     "ControlName"                   "CExLabel"
    //     "fieldName"                     "PlayerStatusMaxHealthValue"
    //     "xpos"                          "rs1"
    //     "ypos"                          "0"
    //     "zpos"                          "6"
    //     "wide"                          "18"
    //     "tall"                          "32"
    //     "visible"                       "1"
    //     "enabled"                       "1"
    //     "labelText"                     "%MaxHealth%"
    //     "textAlignment"                 "south"
    //     "font"                          "DefaultSmall"
    //     "fgcolor"                       "TanDark"
    //     "proportionaltoparent"          "1"
    // }
    "PlayerStatusHealthImage"
    {
        "ControlName"           "ImagePanel"
        "fieldName"             "PlayerStatusHealthImage"
        "xpos"                  "99999"
        "ypos"                  "99999"
        "zpos"                  "4"
        "wide"                  "0"
        "tall"                  "0"
        "visible"               "1"
        "enabled"               "1"
        "scaleImage"            "1"
    }
    "PlayerStatusHealthImageBG"
    {
        "ControlName"           "ImagePanel"
        "fieldName"             "PlayerStatusHealthImageBG"
        "xpos"                  "99999"
        "ypos"                  "99999"
        "zpos"                  "3"
        "wide"                  "0"
        "tall"                  "0"
        "visible"               "0"
        "enabled"               "1"
        "image"                 "../hud/health_bg"
        "scaleImage"            "1"
    }
    // MARK: Status
    "PlayerStatusBleedImage"
    {
        "ControlName"           "ImagePanel"
        "fieldName"             "PlayerStatusBleedImage"
        "xpos"                  "85"
        "ypos"                  "0"
        "zpos"                  "7"
        "wide"                  "32"
        "tall"                  "32"
        "visible"               "1"
        "enabled"               "1"
        "scaleImage"            "1"
        "image"                 "../vgui/bleed_drop"
        "fgcolor"               "TanDark"
    }
    "PlayerStatusHookBleedImage"
    {
        "ControlName"           "ImagePanel"
        "fieldName"             "PlayerStatusHookBleedImage"
        "xpos"                  "85"
        "ypos"                  "0"
        "zpos"                  "8"
        "wide"                  "32"
        "tall"                  "32"
        "visible"               "1"
        "enabled"               "1"
        "scaleImage"            "1"
        "image"                 "../vgui/bleed_drop_grapple"
        "fgcolor"               "TanDark"
    }
    "PlayerStatusMilkImage"
    {
        "ControlName"           "ImagePanel"
        "fieldName"             "PlayerStatusMilkImage"
        "xpos"                  "117"
        "ypos"                  "0"
        "zpos"                  "7"
        "wide"                  "32"
        "tall"                  "32"
        "visible"               "1"
        "enabled"               "1"
        "scaleImage"            "1"
        "image"                 "../vgui/bleed_drop"
        "fgcolor"               "TanDark"
    }
    "PlayerStatusGasImage"
    {
        "ControlName"           "ImagePanel"
        "fieldName"             "PlayerStatusGasImage"
        "xpos"                  "117"
        "ypos"                  "0"
        "zpos"                  "7"
        "wide"                  "32"
        "tall"                  "32"
        "visible"               "1"
        "enabled"               "1"
        "scaleImage"            "1"
        "image"                 "../vgui/covered_in_gas"
        "fgcolor"               "TanDark"
    }
    "PlayerStatusMarkedForDeathImage"
    {
        "ControlName"           "ImagePanel"
        "fieldName"             "PlayerStatusMarkedForDeathImage"
        "xpos"                  "85"
        "ypos"                  "100"
        "zpos"                  "7"
        "wide"                  "32"
        "tall"                  "32"
        "visible"               "1"
        "enabled"               "1"
        "scaleImage"            "1"
        "image"                 "../vgui/marked_for_death"
        "fgcolor"               "TanDark"
    }
    "PlayerStatusMarkedForDeathSilentImage"
    {
        "ControlName"           "ImagePanel"
        "fieldName"             "PlayerStatusMarkedForDeathSilentImage"
        "xpos"                  "0"
        "ypos"                  "0"
        "zpos"                  "7"
        "wide"                  "32"
        "tall"                  "32"
        "visible"               "1"
        "enabled"               "1"
        "scaleImage"            "1"
        "image"                 "../vgui/marked_for_death"
        "fgcolor"               "TanDark"
    }
    "PlayerStatus_MedicUberBulletResistImage"
    {
        "ControlName"           "ImagePanel"
        "fieldName"             "PlayerStatus_MedicUberBulletResistImage"
        "xpos"                  "85"
        "ypos"                  "0"
        "zpos"                  "7"
        "wide"                  "32"
        "tall"                  "32"
        "visible"               "1"
        "enabled"               "1"
        "scaleImage"            "1"
        "image"                 "../HUD/defense_buff_bullet_blue"
        "fgcolor"               "TanDark"
    }
    "PlayerStatus_MedicUberBlastResistImage"
    {
        "ControlName"           "ImagePanel"
        "fieldName"             "PlayerStatus_MedicUberBlastResistImage"
        "xpos"                  "85"
        "ypos"                  "0"
        "zpos"                  "7"
        "wide"                  "32"
        "tall"                  "32"
        "visible"               "1"
        "enabled"               "1"
        "scaleImage"            "1"
        "image"                 "../HUD/defense_buff_explosion_blue"
        "fgcolor"               "TanDark"
    }
    "PlayerStatus_MedicUberFireResistImage"
    {
        "ControlName"           "ImagePanel"
        "fieldName"             "PlayerStatus_MedicUberFireResistImage"
        "xpos"                  "85"
        "ypos"                  "0"
        "zpos"                  "7"
        "wide"                  "32"
        "tall"                  "32"
        "visible"               "1"
        "enabled"               "1"
        "scaleImage"            "1"
        "image"                 "../HUD/defense_buff_fire_blue"
        "fgcolor"               "TanDark"
    }
    "PlayerStatus_MedicSmallBulletResistImage"
    {
        "ControlName"           "ImagePanel"
        "fieldName"             "PlayerStatus_MedicSmallBulletResistImage"
        "xpos"                  "85"
        "ypos"                  "0"
        "zpos"                  "7"
        "wide"                  "32"
        "tall"                  "32"
        "visible"               "1"
        "enabled"               "1"
        "scaleImage"            "1"
        "image"                 "../HUD/defense_buff_bullet_blue"
        "fgcolor"               "TanDark"
    }
    "PlayerStatus_MedicSmallBlastResistImage"
    {
        "ControlName"           "ImagePanel"
        "fieldName"             "PlayerStatus_MedicSmallBlastResistImage"
        "xpos"                  "85"
        "ypos"                  "0"
        "zpos"                  "7"
        "wide"                  "32"
        "tall"                  "32"
        "visible"               "1"
        "enabled"               "1"
        "scaleImage"            "1"
        "image"                 "../HUD/defense_buff_explosion_blue"
        "fgcolor"               "TanDark"
    }
    "PlayerStatus_MedicSmallFireResistImage"
    {
        "ControlName"           "ImagePanel"
        "fieldName"             "PlayerStatus_MedicSmallFireResistImage"
        "xpos"                  "85"
        "ypos"                  "0"
        "zpos"                  "7"
        "wide"                  "32"
        "tall"                  "32"
        "visible"               "1"
        "enabled"               "1"
        "scaleImage"            "1"
        "image"                 "../HUD/defense_buff_fire_blue"
        "fgcolor"               "TanDark"
    }
    "PlayerStatus_WheelOfDoom"
    {
        "ControlName"           "ImagePanel"
        "fieldName"             "PlayerStatus_WheelOfDoom"
        "xpos"                  "130"
        "ypos"                  "38"
        "zpos"                  "7"
        "wide"                  "32"
        "tall"                  "32"
        "visible"               "1"
        "enabled"               "1"
        "scaleImage"            "1"
        "image"                 "../signs/death_wheel_whammy"
        "fgcolor"               "TanDark"
    }
    "PlayerStatus_SoldierOffenseBuff"
    {
        "ControlName"           "ImagePanel"
        "fieldName"             "PlayerStatus_SoldierOffenseBuff"
        "xpos"                  "85"
        "ypos"                  "0"
        "zpos"                  "7"
        "wide"                  "32"
        "tall"                  "32"
        "visible"               "1"
        "enabled"               "1"
        "scaleImage"            "1"
        "image"                 "../HUD/defense_buff_bullet_blue"
        "fgcolor"               "TanDark"
    }
    "PlayerStatus_SoldierDefenseBuff"
    {
        "ControlName"           "ImagePanel"
        "fieldName"             "PlayerStatus_SoldierDefenseBuff"
        "xpos"                  "85"
        "ypos"                  "0"
        "zpos"                  "7"
        "wide"                  "32"
        "tall"                  "32"
        "visible"               "1"
        "enabled"               "1"
        "scaleImage"            "1"
        "image"                 "../HUD/defense_buff_bullet_blue"
        "fgcolor"               "TanDark"
    }
    "PlayerStatus_SoldierHealOnHitBuff"
    {
        "ControlName"           "ImagePanel"
        "fieldName"             "PlayerStatus_SoldierHealOnHitBuff"
        "xpos"                  "85"
        "ypos"                  "0"
        "zpos"                  "7"
        "wide"                  "32"
        "tall"                  "32"
        "visible"               "1"
        "enabled"               "1"
        "scaleImage"            "1"
        "image"                 "../HUD/defense_buff_bullet_blue"
        "fgcolor"               "TanDark"
    }
    "PlayerStatus_SpyMarked"
    {
        "ControlName"           "ImagePanel"
        "fieldName"             "PlayerStatus_SpyMarked"
        "xpos"                  "115"
        "ypos"                  "0"
        "zpos"                  "7"
        "wide"                  "32"
        "tall"                  "32"
        "visible"               "0"
        "enabled"               "1"
        "scaleImage"            "1"
        "image"                 ""
        "fgcolor"               "TanDark"
    }
    "PlayerStatus_Parachute"
    {
        "ControlName"           "ImagePanel"
        "fieldName"             "PlayerStatus_Parachute"
        "xpos"                  "85"
        "ypos"                  "0"
        "zpos"                  "7"
        "wide"                  "32"
        "tall"                  "32"
        "visible"               "0"
        "enabled"               "1"
        "scaleImage"            "1"
        "image"                 ""
        "fgcolor"               "TanDark"
    }
    "PlayerStatus_RuneStrength"
    {
        "ControlName"           "ImagePanel"
        "fieldName"             "PlayerStatus_RuneStrength"
        "xpos"                  "85"
        "ypos"                  "0"
        "zpos"                  "7"
        "wide"                  "32"
        "tall"                  "32"
        "visible"               "1"
        "enabled"               "1"
        "scaleImage"            "1"
        "image"                 "../Effects/powerup_strength_hud"
        "fgcolor"               "TanDark"
    }
    "PlayerStatus_RuneHaste"
    {
        "ControlName"           "ImagePanel"
        "fieldName"             "PlayerStatus_RuneHaste"
        "xpos"                  "85"
        "ypos"                  "0"
        "zpos"                  "7"
        "wide"                  "32"
        "tall"                  "32"
        "visible"               "1"
        "enabled"               "1"
        "scaleImage"            "1"
        "image"                 "../Effects/powerup_haste_hud"
        "fgcolor"               "TanDark"
    }
    "PlayerStatus_RuneRegen"
    {
        "ControlName"           "ImagePanel"
        "fieldName"             "PlayerStatus_RuneRegen"
        "xpos"                  "85"
        "ypos"                  "0"
        "zpos"                  "7"
        "wide"                  "32"
        "tall"                  "32"
        "visible"               "1"
        "enabled"               "1"
        "scaleImage"            "1"
        "image"                 "../Effects/powerup_regen_hud"
        "fgcolor"               "TanDark"
    }
    "PlayerStatus_RuneResist"
    {
        "ControlName"           "ImagePanel"
        "fieldName"             "PlayerStatus_RuneResist"
        "xpos"                  "85"
        "ypos"                  "0"
        "zpos"                  "7"
        "wide"                  "32"
        "tall"                  "32"
        "visible"               "1"
        "enabled"               "1"
        "scaleImage"            "1"
        "image"                 "../Effects/powerup_resist_hud"
        "fgcolor"               "TanDark"
    }
    "PlayerStatus_RuneVampire"
    {
        "ControlName"           "ImagePanel"
        "fieldName"             "PlayerStatus_RuneVampire"
        "xpos"                  "85"
        "ypos"                  "0"
        "zpos"                  "7"
        "wide"                  "32"
        "tall"                  "32"
        "visible"               "1"
        "enabled"               "1"
        "scaleImage"            "1"
        "image"                 "../Effects/powerup_vampire_hud"
        "fgcolor"               "TanDark"
    }
    "PlayerStatus_RuneReflect"
    {
        "ControlName"           "ImagePanel"
        "fieldName"             "PlayerStatus_RuneReflect"
        "xpos"                  "85"
        "ypos"                  "0"
        "zpos"                  "7"
        "wide"                  "32"
        "tall"                  "32"
        "visible"               "1"
        "enabled"               "1"
        "scaleImage"            "1"
        "image"                 "../Effects/powerup_reflect_hud"
        "fgcolor"               "TanDark"
    }
    "PlayerStatus_RunePrecision"
    {
        "ControlName"           "ImagePanel"
        "fieldName"             "PlayerStatus_RunePrecision"
        "xpos"                  "85"
        "ypos"                  "0"
        "zpos"                  "7"
        "wide"                  "32"
        "tall"                  "32"
        "visible"               "1"
        "enabled"               "1"
        "scaleImage"            "1"
        "image"                 "../Effects/powerup_precision_hud"
        "fgcolor"               "TanDark"
    }
    "PlayerStatus_RuneAgility"
    {
        "ControlName"           "ImagePanel"
        "fieldName"             "PlayerStatus_RuneAgility"
        "xpos"                  "85"
        "ypos"                  "0"
        "zpos"                  "7"
        "wide"                  "32"
        "tall"                  "32"
        "visible"               "1"
        "enabled"               "1"
        "scaleImage"            "1"
        "image"                 "../Effects/powerup_agility_hud"
        "fgcolor"               "TanDark"
    }
    "PlayerStatus_RuneKnockout"
    {
        "ControlName"           "ImagePanel"
        "fieldName"             "PlayerStatus_RuneKnockout"
        "xpos"                  "85"
        "ypos"                  "0"
        "zpos"                  "7"
        "wide"                  "32"
        "tall"                  "32"
        "visible"               "1"
        "enabled"               "1"
        "scaleImage"            "1"
        "image"                 "../Effects/powerup_knockout_hud"
        "fgcolor"               "TanDark"
    }
    "PlayerStatus_RuneKing"
    {
        "ControlName"           "ImagePanel"
        "fieldName"             "PlayerStatus_RuneKing"
        "xpos"                  "85"
        "ypos"                  "0"
        "zpos"                  "7"
        "wide"                  "32"
        "tall"                  "32"
        "visible"               "1"
        "enabled"               "1"
        "scaleImage"            "1"
        "image"                 "../Effects/powerup_king_hud"
        "fgcolor"               "TanDark"
    }
    "PlayerStatus_RunePlague"
    {
        "ControlName"           "ImagePanel"
        "fieldName"             "PlayerStatus_RunePlague"
        "xpos"                  "85"
        "ypos"                  "0"
        "zpos"                  "7"
        "wide"                  "32"
        "tall"                  "32"
        "visible"               "1"
        "enabled"               "1"
        "scaleImage"            "1"
        "image"                 "../Effects/powerup_plague_hud"
        "fgcolor"               "TanDark"
    }
    "PlayerStatus_RuneSupernova"
    {
        "ControlName"           "ImagePanel"
        "fieldName"             "PlayerStatus_RuneSupernova"
        "xpos"                  "85"
        "ypos"                  "0"
        "zpos"                  "7"
        "wide"                  "32"
        "tall"                  "32"
        "visible"               "1"
        "enabled"               "1"
        "scaleImage"            "1"
        "image"                 "../Effects/powerup_supernova_hud"
        "fgcolor"               "TanDark"
    }
    "PlayerStatusSlowed"
    {
        "ControlName"           "ImagePanel"
        "fieldName"             "PlayerStatusSlowed"
        "xpos"                  "85"
        "ypos"                  "0"
        "zpos"                  "7"
        "wide"                  "32"
        "tall"                  "32"
        "visible"               "1"
        "enabled"               "1"
        "scaleImage"            "1"
        "image"                 "../vgui/slowed"
        "fgcolor"               "TanDark"
    }
}