"Resource/UI/HudPlayerHealth.res"
{
    // player health data
    "HudPlayerHealth"
    {
        "ControlName"                       "EditablePanel"
        "fieldName"                         "HudPlayerHealth"
        "xpos"                              "0"
        "ypos"                              "0"
        "zpos"                              "2"
        "wide"                              "f0"
        "tall"                              "480"
        "visible"                           "1"
        "enabled"                           "1"
        "HealthBonusPosAdj"                 "35"
        "HealthDeathWarning"                "0.49"
        "HealthDeathWarningColor"           "HUDDeathWarning"
    }
    // MARK: Anchor
    "HealthAnchor"
    {
        "ControlName"               "EditablePanel"
        "fieldName"                 "HealthAnchor"
        "xpos"                      "20"
        "ypos"                      "rs1-20"
        "zpos"                      "7"
        "wide"                      "1"
        "tall"                      "1"
        "visible"                   "0"
        "enabled"                   "1"
        "bgcolor_override"          "blue"
    }
    "HealthBGBuff"	// - Credit to Yoshee for helping out with the overheal/low health animations :)
    {
        "ControlName"           "ScalableImagePanel"
        "fieldName"             "HealthBGBuff"
        "xpos"                  "0"
        "ypos"                  "0"
        "zpos"                  "2"
        "wide"                  "f0"
        "tall"                  "480"
        "visible"               "1"
        "enabled"               "1"
        "image"                 "replay/thumbnails/ow_overheal"
        "alpha"                 "0"
    }
    "HealthBGLow"	// - Credit to Yoshee for helping out with the overheal/low health animations :)
    {
        "ControlName"           "ScalableImagePanel"
        "fieldName"             "HealthBGLow"
        "xpos"                  "0"
        "ypos"                  "0"
        "zpos"                  "2"
        "wide"                  "f0"
        "tall"                  "480"
        "visible"               "1"
        "enabled"               "1"
        "image"                 "replay/thumbnails/ow_lowhealth"
        "alpha"                 "0"
    }
    "PlayerStatusHealthImageBG"
    {
        "ControlName"           "ImagePanel"
        "fieldName"             "PlayerStatusHealthImageBG"
        "xpos"                  "9999"
        "ypos"                  "9999"
        "zpos"                  "3"
        "wide"                  "0"
        "tall"                  "0"
        "visible"               "1"
        "enabled"               "1"
        "image"                 "../hud/health_bg"
        "scaleImage"            "1"
    }
    "PlayerStatusHealthBonusImage"
    {
        "xpos"          "0"
        "ypos"          "0"
        "wide"          "0"
        "tall"          "0"
        "image"         "replay/thumbnails/ow_overheal"
        "alpha"         "0"
    }
    // MARK: Health Number
    "PlayerStatusHealthValue"
    {
        "ControlName"                   "CExLabel"
        "fieldName"                     "PlayerStatusHealthValue"
        "xpos"                          "0"
        "ypos"                          "0"
        "zpos"                          "5"
        "wide"                          "40"
        "tall"                          "20"
        "visible"                       "1"
        "enabled"                       "1"
        "labelText"                     "%Health%"
        "textAlignment"                 "east"
        "font"                          "HealthAmmo"
        "textinsetx"                    "5"
        "fgcolor"                       "HealthAmmo"
        "pin_to_sibling"                "HealthAnchor"
        "pin_corner_to_sibling"         "PIN_BOTTOMLEFT"
        "pin_to_sibling_corner"         "PIN_BOTTOMRIGHT"
    }
    "PlayerStatusHealthValueShadow"
    {
        "ControlName"           "CExLabel"
        "fieldName"             "PlayerStatusHealthValueShadow"
        "xpos"                  "0"
        "ypos"                  "0"
        "zpos"                  "-1"
        "wide"                  "40"
        "tall"                  "20"
        "visible"               "1"
        "enabled"               "1"
        "labelText"             "%Health%"
        "textAlignment"         "east"
        "font"                  "HealthAmmo_Blur"
        "textinsetx"            "5"
        "fgcolor"               "Shadow"
        "pin_to_sibling"        "PlayerStatusHealthValue"
    }
    // MARK: Slash
    "Slash1"	// normal slash
    {
        "ControlName"                   "CExLabel"
        "fieldName"                     "Slash1"
        "font"                          "HealthAmmo_Alt"
        "textinsety"                    "3"
        "fgcolor"                       "HealthAmmo_Alt"
        "xpos"                          "-3"
        "ypos"                          "0"
        "labelText"                     "/"
        "zpos"                          "0"
        "wide"                          "10"
        "tall"                          "20"
        "visible"                       "1"
        "enabled"                       "1"
        "textAlignment"                 "center"
        "pin_to_sibling"                "PlayerStatusHealthValue"
        "pin_corner_to_sibling"         "PIN_BOTTOMLEFT"
        "pin_to_sibling_corner"         "PIN_BOTTOMRIGHT"
    }
    "SlashShadow1"	//slash shadow
    {
        "ControlName"           "CExLabel"
        "fieldName"             "SlashShadow1"
        "font"                  "HealthAmmo_Alt_Blur"
        "textinsety"            "3"
        "fgcolor"               "Shadow"
        "xpos"                  "0"
        "ypos"                  "0"
        "labelText"             "/"
        "zpos"                  "-1"
        "wide"                  "10"
        "tall"                  "20"
        "visible"               "1"
        "enabled"               "1"
        "textAlignment"         "center"
        "pin_to_sibling"        "Slash1"
    }
    // MARK: Max Health
    "MaxHealth"
    {
        "ControlName"                   "CExLabel"
        "fieldName"                     "MaxHealth"
        "xpos"                          "-3"
        "ypos"                          "0"
        "zpos"                          "0"
        "wide"                          "40"
        "tall"                          "20"
        "visible"                       "1"
        "enabled"                       "1"
        "labelText"                     "%MaxHealth%"
        "textAlignment"                 "west"
        "font"                          "HealthAmmo_Alt"
        "textinsetx"                    "5"
        "textinsety"                    "3"
        "fgcolor"                       "HealthAmmo_Alt"
        "pin_to_sibling"                "Slash1"
        "pin_corner_to_sibling"         "PIN_BOTTOMLEFT"
        "pin_to_sibling_corner"         "PIN_BOTTOMRIGHT"
    }
    "MaxHealthShadow"
    {
        "ControlName"           "CExLabel"
        "fieldName"             "MaxHealthShadow"
        "xpos"                  "0"
        "ypos"                  "0"
        "zpos"                  "-1"
        "wide"                  "40"
        "tall"                  "20"
        "visible"               "1"
        "enabled"               "1"
        "labelText"             "%MaxHealth%"
        "textAlignment"         "west"
        "font"                  "HealthAmmo_Alt_Blur"
        "textinsetx"            "5"
        "textinsety"            "3"
        "fgcolor"               "Shadow"
        "pin_to_sibling"        "MaxHealth"
    }
    // MARK: Status
    "StatusFix"	// Credit to Rawrsor for providing this
    {
        "ControlName"                   "EditablePanel"
        "fieldName"                     "StatusFix"
        "xpos"                          "0"
        "ypos"                          "0"
        "wide"                          "1"
        "tall"                          "1"
        "visible"                       "1"
        "enabled"                       "1"
        "pin_to_sibling"                "MaxHealth"
        "pin_corner_to_sibling"         "PIN_BOTTOMLEFT"
        "pin_to_sibling_corner"         "PIN_BOTTOMRIGHT"
    }
    "PlayerStatusBleedImage"
    {
        "ControlName"                   "ImagePanel"
        "fieldName"                     "PlayerStatusBleedImage"
        "xpos"                          "85"
        "ypos"                          "0"
        "zpos"                          "7"
        "wide"                          "18"
        "tall"                          "18"
        "visible"                       "1"
        "enabled"                       "1"
        "scaleImage"                    "1"
        "image"                         "../vgui/bleed_drop"
        "fgcolor"                       "TanDark"
        "pin_to_sibling"                "StatusFix"
        "pin_corner_to_sibling"         "1"
        "pin_to_sibling_corner"         "1"
    }
    "PlayerStatusMilkImage"
    {
        "ControlName"                   "ImagePanel"
        "fieldName"                     "PlayerStatusMilkImage"
        "xpos"                          "65"
        "ypos"                          "0"
        "zpos"                          "7"
        "wide"                          "18"
        "tall"                          "18"
        "visible"                       "1"
        "enabled"                       "1"
        "scaleImage"                    "1"
        "image"                         "../vgui/bleed_drop"
        "fgcolor"                       "TanDark"
        "pin_to_sibling"                "StatusFix"
        "pin_corner_to_sibling"         "1"
        "pin_to_sibling_corner"         "1"
    }
    "PlayerStatusHookBleedImage"
    {
        "ControlName"                   "ImagePanel"
        "fieldName"                     "PlayerStatusHookBleedImage"
        "xpos"                          "85"
        "ypos"                          "0"
        "zpos"                          "8"
        "wide"                          "18"
        "tall"                          "18"
        "visible"                       "1"
        "enabled"                       "1"
        "scaleImage"                    "1"
        "image"                         "../vgui/bleed_drop_grapple"
        "fgcolor"                       "TanDark"
        "pin_to_sibling"                "StatusFix"
        "pin_corner_to_sibling"         "1"
        "pin_to_sibling_corner"         "1"
    }
    "PlayerStatusMarkedForDeathImage"
    {
        "ControlName"                   "ImagePanel"
        "fieldName"                     "PlayerStatusMarkedForDeathImage"
        "xpos"                          "85"
        "ypos"                          "0"
        "zpos"                          "7"
        "wide"                          "18"
        "tall"                          "18"
        "visible"                       "1"
        "enabled"                       "1"
        "scaleImage"                    "1"
        "image"                         "../vgui/marked_for_death"
        "fgcolor"                       "TanDark"
        "pin_to_sibling"                "StatusFix"
        "pin_corner_to_sibling"         "1"
        "pin_to_sibling_corner"         "1"
    }
    "PlayerStatusMarkedForDeathSilentImage"
    {
        "ControlName"                   "ImagePanel"
        "fieldName"                     "PlayerStatusMarkedForDeathSilentImage"
        "xpos"                          "85"
        "ypos"                          "0"
        "zpos"                          "7"
        "wide"                          "18"
        "tall"                          "18"
        "visible"                       "1"
        "enabled"                       "1"
        "scaleImage"                    "1"
        "image"                         "../vgui/marked_for_death"
        "fgcolor"                       "TanDark"
        "pin_to_sibling"                "StatusFix"
        "pin_corner_to_sibling"         "1"
        "pin_to_sibling_corner"         "1"
    }
    "PlayerStatus_MedicUberBulletResistImage"
    {
        "ControlName"                   "ImagePanel"
        "fieldName"                     "PlayerStatus_MedicUberBulletResistImage"
        "xpos"                          "85"
        "ypos"                          "0"
        "zpos"                          "7"
        "wide"                          "18"
        "tall"                          "18"
        "visible"                       "1"
        "enabled"                       "1"
        "scaleImage"                    "1"
        "image"                         "../HUD/defense_buff_bullet_blue"
        "fgcolor"                       "TanDark"
        "pin_to_sibling"                "StatusFix"
        "pin_corner_to_sibling"         "1"
        "pin_to_sibling_corner"         "1"
    }
    "PlayerStatus_MedicUberBlastResistImage"
    {
        "ControlName"                   "ImagePanel"
        "fieldName"                     "PlayerStatus_MedicUberBlastResistImage"
        "xpos"                          "85"
        "ypos"                          "0"
        "zpos"                          "7"
        "wide"                          "18"
        "tall"                          "18"
        "visible"                       "1"
        "enabled"                       "1"
        "scaleImage"                    "1"
        "image"                         "../HUD/defense_buff_explosion_blue"
        "fgcolor"                       "TanDark"
        "pin_to_sibling"                "StatusFix"
        "pin_corner_to_sibling"         "1"
        "pin_to_sibling_corner"         "1"
    }
    "PlayerStatus_MedicUberFireResistImage"
    {
        "ControlName"                   "ImagePanel"
        "fieldName"                     "PlayerStatus_MedicUberFireResistImage"
        "xpos"                          "85"
        "ypos"                          "0"
        "zpos"                          "7"
        "wide"                          "18"
        "tall"                          "18"
        "visible"                       "1"
        "enabled"                       "1"
        "scaleImage"                    "1"
        "image"                         "../HUD/defense_buff_fire_blue"
        "fgcolor"                       "TanDark"
        "pin_to_sibling"                "StatusFix"
        "pin_corner_to_sibling"         "1"
        "pin_to_sibling_corner"         "1"
    }
    "PlayerStatus_MedicSmallBulletResistImage"
    {
        "ControlName"                   "ImagePanel"
        "fieldName"                     "PlayerStatus_MedicSmallBulletResistImage"
        "xpos"                          "85"
        "ypos"                          "0"
        "zpos"                          "7"
        "wide"                          "18"
        "tall"                          "18"
        "visible"                       "1"
        "enabled"                       "1"
        "scaleImage"                    "1"
        "image"                         "../HUD/defense_buff_bullet_blue"
        "fgcolor"                       "TanDark"
        "pin_to_sibling"                "StatusFix"
        "pin_corner_to_sibling"         "1"
        "pin_to_sibling_corner"         "1"
    }
    "PlayerStatus_MedicSmallBlastResistImage"
    {
        "ControlName"                   "ImagePanel"
        "fieldName"                     "PlayerStatus_MedicSmallBlastResistImage"
        "xpos"                          "85"
        "ypos"                          "0"
        "zpos"                          "7"
        "wide"                          "18"
        "tall"                          "18"
        "visible"                       "1"
        "enabled"                       "1"
        "scaleImage"                    "1"
        "image"                         "../HUD/defense_buff_explosion_blue"
        "fgcolor"                       "TanDark"
        "pin_to_sibling"                "StatusFix"
        "pin_corner_to_sibling"         "1"
        "pin_to_sibling_corner"         "1"
    }
    "PlayerStatus_MedicSmallFireResistImage"
    {
        "ControlName"                   "ImagePanel"
        "fieldName"                     "PlayerStatus_MedicSmallFireResistImage"
        "xpos"                          "85"
        "ypos"                          "0"
        "zpos"                          "7"
        "wide"                          "18"
        "tall"                          "18"
        "visible"                       "1"
        "enabled"                       "1"
        "scaleImage"                    "1"
        "image"                         "../HUD/defense_buff_fire_blue"
        "fgcolor"                       "TanDark"
        "pin_to_sibling"                "StatusFix"
        "pin_corner_to_sibling"         "1"
        "pin_to_sibling_corner"         "1"
    }
    "PlayerStatus_WheelOfDoom"
    {
        "ControlName"                   "ImagePanel"
        "fieldName"                     "PlayerStatus_WheelOfDoom"
        "xpos"                          "130"
        "ypos"                          "38"
        "zpos"                          "7"
        "wide"                          "18"
        "tall"                          "18"
        "visible"                       "1"
        "enabled"                       "1"
        "scaleImage"                    "1"
        "image"                         "../signs/death_wheel_whammy"
        "fgcolor"                       "TanDark"
        "pin_to_sibling"                "StatusFix"
        "pin_corner_to_sibling"         "1"
        "pin_to_sibling_corner"         "1"
    }
    "PlayerStatus_SoldierOffenseBuff"
    {
        "ControlName"                   "ImagePanel"
        "fieldName"                     "PlayerStatus_SoldierOffenseBuff"
        "xpos"                          "85"
        "ypos"                          "0"
        "zpos"                          "7"
        "wide"                          "18"
        "tall"                          "18"
        "visible"                       "1"
        "enabled"                       "1"
        "scaleImage"                    "1"
        "image"                         "../HUD/defense_buff_bullet_blue"
        "fgcolor"                       "TanDark"
        "pin_to_sibling"                "StatusFix"
        "pin_corner_to_sibling"         "1"
        "pin_to_sibling_corner"         "1"
    }
    "PlayerStatus_SoldierDefenseBuff"
    {
        "ControlName"                   "ImagePanel"
        "fieldName"                     "PlayerStatus_SoldierDefenseBuff"
        "xpos"                          "85"
        "ypos"                          "0"
        "zpos"                          "7"
        "wide"                          "18"
        "tall"                          "18"
        "visible"                       "1"
        "enabled"                       "1"
        "scaleImage"                    "1"
        "image"                         "../HUD/defense_buff_bullet_blue"
        "fgcolor"                       "TanDark"
        "pin_to_sibling"                "StatusFix"
        "pin_corner_to_sibling"         "1"
        "pin_to_sibling_corner"         "1"
    }
    "PlayerStatus_SoldierHealOnHitBuff"
    {
        "ControlName"                   "ImagePanel"
        "fieldName"                     "PlayerStatus_SoldierHealOnHitBuff"
        "xpos"                          "85"
        "ypos"                          "0"
        "zpos"                          "7"
        "wide"                          "18"
        "tall"                          "18"
        "visible"                       "1"
        "enabled"                       "1"
        "scaleImage"                    "1"
        "image"                         "../HUD/defense_buff_bullet_blue"
        "fgcolor"                       "TanDark"
        "pin_to_sibling"                "StatusFix"
        "pin_corner_to_sibling"         "1"
        "pin_to_sibling_corner"         "1"
    }
    "PlayerStatus_Parachute"
    {
        "ControlName"                   "ImagePanel"
        "fieldName"                     "PlayerStatus_Parachute"
        "xpos"                          "85"
        "ypos"                          "0"
        "zpos"                          "7"
        "wide"                          "18"
        "tall"                          "18"
        "visible"                       "0"
        "enabled"                       "1"
        "scaleImage"                    "1"
        "image"                         ""
        "fgcolor"                       "TanDark"
        "pin_to_sibling"                "StatusFix"
        "pin_corner_to_sibling"         "1"
        "pin_to_sibling_corner"         "1"
    }
    "PlayerStatus_RuneStrength"
    {
        "ControlName"                   "ImagePanel"
        "fieldName"                     "PlayerStatus_RuneStrength"
        "xpos"                          "85"
        "ypos"                          "0"
        "zpos"                          "7"
        "wide"                          "18"
        "tall"                          "18"
        "visible"                       "1"
        "enabled"                       "1"
        "scaleImage"                    "1"
        "image"                         "../Effects/powerup_strength_hud"
        "fgcolor"                       "TanDark"
        "pin_to_sibling"                "StatusFix"
        "pin_corner_to_sibling"         "1"
        "pin_to_sibling_corner"         "1"
    }
    "PlayerStatus_RuneHaste"
    {
        "ControlName"                   "ImagePanel"
        "fieldName"                     "PlayerStatus_RuneHaste"
        "xpos"                          "85"
        "ypos"                          "0"
        "zpos"                          "7"
        "wide"                          "18"
        "tall"                          "18"
        "visible"                       "1"
        "enabled"                       "1"
        "scaleImage"                    "1"
        "image"                         "../Effects/powerup_haste_hud"
        "fgcolor"                       "TanDark"
        "pin_to_sibling"                "StatusFix"
        "pin_corner_to_sibling"         "1"
        "pin_to_sibling_corner"         "1"
    }
    "PlayerStatus_RuneRegen"
    {
        "ControlName"                   "ImagePanel"
        "fieldName"                     "PlayerStatus_RuneRegen"
        "xpos"                          "85"
        "ypos"                          "0"
        "zpos"                          "7"
        "wide"                          "18"
        "tall"                          "18"
        "visible"                       "1"
        "enabled"                       "1"
        "scaleImage"                    "1"
        "image"                         "../Effects/powerup_regen_hud"
        "fgcolor"                       "TanDark"
        "pin_to_sibling"                "StatusFix"
        "pin_corner_to_sibling"         "1"
        "pin_to_sibling_corner"         "1"
    }
    "PlayerStatus_RuneResist"
    {
        "ControlName"                   "ImagePanel"
        "fieldName"                     "PlayerStatus_RuneResist"
        "xpos"                          "85"
        "ypos"                          "0"
        "zpos"                          "7"
        "wide"                          "18"
        "tall"                          "18"
        "visible"                       "1"
        "enabled"                       "1"
        "scaleImage"                    "1"
        "image"                         "../Effects/powerup_resist_hud"
        "fgcolor"                       "TanDark"
        "pin_to_sibling"                "StatusFix"
        "pin_corner_to_sibling"         "1"
        "pin_to_sibling_corner"         "1"
    }
    "PlayerStatus_RuneVampire"
    {
        "ControlName"                   "ImagePanel"
        "fieldName"                     "PlayerStatus_RuneVampire"
        "xpos"                          "85"
        "ypos"                          "0"
        "zpos"                          "7"
        "wide"                          "18"
        "tall"                          "18"
        "visible"                       "1"
        "enabled"                       "1"
        "scaleImage"                    "1"
        "image"                         "../Effects/powerup_vampire_hud"
        "fgcolor"                       "TanDark"
        "pin_to_sibling"                "StatusFix"
        "pin_corner_to_sibling"         "1"
        "pin_to_sibling_corner"         "1"
    }
    "PlayerStatus_RuneReflect"
    {
        "ControlName"                   "ImagePanel"
        "fieldName"                     "PlayerStatus_RuneReflect"
        "xpos"                          "85"
        "ypos"                          "0"
        "zpos"                          "7"
        "wide"                          "18"
        "tall"                          "18"
        "visible"                       "1"
        "enabled"                       "1"
        "scaleImage"                    "1"
        "image"                         "../Effects/powerup_reflect_hud"
        "fgcolor"                       "TanDark"
        "pin_to_sibling"                "StatusFix"
        "pin_corner_to_sibling"         "1"
        "pin_to_sibling_corner"         "1"
    }
    "PlayerStatus_RunePrecision"
    {
        "ControlName"                   "ImagePanel"
        "fieldName"                     "PlayerStatus_RunePrecision"
        "xpos"                          "85"
        "ypos"                          "0"
        "zpos"                          "7"
        "wide"                          "18"
        "tall"                          "18"
        "visible"                       "1"
        "enabled"                       "1"
        "scaleImage"                    "1"
        "image"                         "../Effects/powerup_precision_hud"
        "fgcolor"                       "TanDark"
        "pin_to_sibling"                "StatusFix"
        "pin_corner_to_sibling"         "1"
        "pin_to_sibling_corner"         "1"
    }
    "PlayerStatus_RuneAgility"
    {
        "ControlName"                   "ImagePanel"
        "fieldName"                     "PlayerStatus_RuneAgility"
        "xpos"                          "85"
        "ypos"                          "0"
        "zpos"                          "7"
        "wide"                          "18"
        "tall"                          "18"
        "visible"                       "1"
        "enabled"                       "1"
        "scaleImage"                    "1"
        "image"                         "../Effects/powerup_agility_hud"
        "fgcolor"                       "TanDark"
        "pin_to_sibling"                "StatusFix"
        "pin_corner_to_sibling"         "1"
        "pin_to_sibling_corner"         "1"
    }
    "PlayerStatus_RuneKnockout"
    {
        "ControlName"                   "ImagePanel"
        "fieldName"                     "PlayerStatus_RuneKnockout"
        "xpos"                          "85"
        "ypos"                          "0"
        "zpos"                          "7"
        "wide"                          "18"
        "tall"                          "18"
        "visible"                       "1"
        "enabled"                       "1"
        "scaleImage"                    "1"
        "image"                         "../Effects/powerup_knockout_hud"
        "fgcolor"                       "TanDark"
        "pin_to_sibling"                "StatusFix"
        "pin_corner_to_sibling"         "1"
        "pin_to_sibling_corner"         "1"
    }
    "PlayerStatus_RuneKing"
    {
        "ControlName"           "ImagePanel"
        "fieldName"             "PlayerStatus_RuneKing"
        "xpos"                  "85"
        "ypos"                  "0"
        "zpos"                  "7"
        "wide"                  "18"
        "tall"                  "18"
        "visible"               "1"
        "enabled"               "1"
        "scaleImage"            "1"
        "image"                 "../Effects/powerup_king_hud"
        "fgcolor"               "TanDark"
    }
    "PlayerStatus_RunePlague"
    {
        "ControlName"           "ImagePanel"
        "fieldName"             "PlayerStatus_RunePlague"
        "xpos"                  "85"
        "ypos"                  "0"
        "zpos"                  "7"
        "wide"                  "18"
        "tall"                  "18"
        "visible"               "1"
        "enabled"               "1"
        "scaleImage"            "1"
        "image"                 "../Effects/powerup_plague_hud"
        "fgcolor"               "TanDark"
    }
    "PlayerStatus_RuneSupernova"
    {
        "ControlName"           "ImagePanel"
        "fieldName"             "PlayerStatus_RuneSupernova"
        "xpos"                  "85"
        "ypos"                  "0"
        "zpos"                  "7"
        "wide"                  "18"
        "tall"                  "18"
        "visible"               "1"
        "enabled"               "1"
        "scaleImage"            "1"
        "image"                 "../Effects/powerup_supernova_hud"
        "fgcolor"               "TanDark"
    }
    // MARK: Dead
    "PlayerStatusHealthImage"
    {
        "ControlName"           "ImagePanel"
        "fieldName"             "PlayerStatusHealthImage"
        "xpos"                  "9999"
        "ypos"                  "9999"
        "zpos"                  "3"
        "wide"                  "0"
        "tall"                  "0"
        "visible"               "1"
        "enabled"               "1"
        "scaleImage"            "1"
    }
}