"Resource/UI/MainMenuOverride.res"
{
    "CustomShaderOverlay"
    {
        "ControlName"                   "EditablePanel"
        "FieldName"                     "CustomShaderOverlay"
        "xpos"                          "0"
        "ypos"                          "0"
        "zpos"                          "-10000"
        "wide"                          "f0"
        "tall"                          "480"
        "proportionaltoparent"          "1"
        "Visible"                       "1"
        "MouseInputEnabled"             "0"
        "SubButton"
        {
            "FieldName"             "SubButton"
            "ControlName"           "ImagePanel"
            "xpos"                  "0"
            "ypos"                  "0"
            "zpos"                  "-10000"
            "wide"                  "f0"
            "tall"                  "480"
            "scaleimage"            "1"
            "image"                 "replay/thumbnails/shaders/flipy"
            "visible"               "0"
            "enabled"               "1"
        }
    }
    "DashboardDimmer"
    {
        "wide"          "9999"
        "tall"          "9999"
    }
    "ChatPin"
    {
        "ControlName"           "Panel"
        "ypos"                  "s-1+3"
        "xpos"                  "s-1"
    }
    "partychat"
    {
        "pin_to_sibling"                "ChatPin"
        "pin_to_sibling_corner"         "3"
    }
    "MainMenuOverride"
    {
        "FieldName"                 "MainMenuOverride"
        "Visible"                   "1"
        "Enabled"                   "1"
        "XPos"                      "0"
        "YPos"                      "0"
        "ZPos"                      "0"
        "Wide"                      "f0"
        "Tall"                      "480"
        "update_url"                "http://store.steampowered.com/news/?filter=updates&appids=440"
        "blog_url"                  "http://www.teamfortress.com/"
        "button_x_offset"           "-241"
        "button_y"                  "190"
        "button_y_delta"            "3"
        "Button_KV"
        {
            "XPos"              "0"
            "YPos"              "190"
            "Wide"              "150"
            "Tall"              "17"
            "Visible"           "1"
            "SubButton"
            {
                "ControlName"                       "CExImageButton"
                "FieldName"                         "SubButton"
                "XPos"                              "0"
                "YPos"                              "0"
                "Wide"                              "150"
                "Tall"                              "17"
                "Visible"                           "1"
                "Enabled"                           "1"
                "Font"                              "MainMenuLarge"
                "AllCaps"                           "1"
                "TextAlignment"                     "west"
                "Sound_Depressed"                   "UI/buttonclick.wav"
                "PaintBackground"                   "0"
                "PaintBorder"                       "0"
                "DefaultFGColor_Override"           "White"
                "ArmedFGColor_Override"             "Menu_Accent"
                "DepressedFGColor_Override"         "Menu_Accent"
            }
        }
        "SaxxySettings"
        {
            "XPos"                              "0"
            "YPos"                              "0"
            "ZPos"                              "-101"
            "Wide"                              "f0"
            "Tall"                              "480"
            "Visible"                           "1"
            "Enabled"                           "1"
            "flashbounds_x"                     "50"
            "flashbounds_y"                     "65"
            "flashbounds_w"                     "250"
            "flashbounds_h"                     "120"
            "flashstartsize_min"                "8"
            "flashstartsize_max"                "12"
            "flash_maxscale"                    "4"
            "flash_lifelength_min"              ".1"
            "flash_lifelength_max"              ".2"
            "curtain_anim_duration"             "4.0"
            "curtain_open_time"                 "2.8"
            "flash_start_time"                  "4.0"
            "initial_freakout_duration"         "15.0"
            "clap_sound_duration"               "10.0"
            "CameraFlashSettings"
            {
                "Visible"           "1"
                "Enabled"           "1"
                "TileImage"         "0"
                "ScaleImage"        "1"
                "ZPos"              "9"
            }
        }
    }
    // ==================================================================================================================================================
    // STATUS ICONS ANCHOR
    // Moves all the menu buttons at the same time
    // ==================================================================================================================================================
    "MainMenuAnchor"
    {
        "ControlName"           "Panel"
        "FieldName"             "MainMenuAnchor"
        "XPos"                  "rs1"
        "YPos"                  "180"
        "Wide"                  "0"
        "Tall"                  "0"
        "Visible"               "0"
        "Enabled"               "0"
    }
    // ==================================================================================================================================================
    // RANK & BADGE
    // ==================================================================================================================================================
    "RankPanel"
    {
        "ControlName"                   "CPvPRankPanel"
        "FieldName"                     "RankPanel"
        "XPos"                          "0"
        "YPos"                          "99999"
        "ZPos"                          "1"
        "Wide"                          "200"
        "Tall"                          "43"
        "Visible"                       "0"
        "ProportionalToParent"          "1"
        "MouseInputEnabled"             "0"
        "matchgroup"                    "MatchGroup_Casual_12v12"
        "show_model"                    "0"
        "show_type"                     "1"
        "Pin_To_Sibling"                "MainMenuAnchor"
        "Pin_Corner_To_Sibling"         "PIN_BOTTOMLEFT"
        "Pin_To_Sibling_Corner"         "PIN_TOPLEFT"
    }
    "RankModelPanel"
    {
        "ControlName"                   "CPvPRankPanel"
        "FieldName"                     "RankModelPanel"
        "XPos"                          "424"
        "YPos"                          "99999"
        "ZPos"                          "2"
        "Wide"                          "900"
        "Tall"                          "900"
        "Visible"                       "1"
        "ProportionalToParent"          "1"
        "MouseInputEnabled"             "1"
        "matchgroup"                    "MatchGroup_Casual_12v12"
        "show_progress"                 "0"
        "Pin_To_Sibling"                "RankPanel"
        "Pin_Corner_To_Sibling"         "PIN_BOTTOMLEFT"
        "Pin_To_Sibling_Corner"         "PIN_TOPLEFT"
    }
    "CycleRankTypeButton"
    {
        "ControlName"                   "CExImageButton"
        "FieldName"                     "CycleRankTypeButton"
        "XPos"                          "0"
        "YPos"                          "99999"
        "ZPos"                          "16"
        "Wide"                          "130"
        "Tall"                          "43"
        "Visible"                       "1"
        "Enabled"                       "1"
        "Command"                       "open_rank_type_menu"
        "ActionSignalLevel"             "1"
        "ProportionalToParent"          "1"
        "Sound_Depressed"               "UI/buttonclick.wav"
        "PaintBackground"               "0"
        "PaintBorder"                   "0"
        "Alpha"                         "0"
        "Pin_To_Sibling"                "RankPanel"
    }
    "NoGCMessage"
    {
        "ControlName"                   "CExLabel"
        "FieldName"                     "NoGCMessage"
        "XPos"                          "-3"	// No clue why this is offset tbh
        "YPos"                          "0"
        "ZPos"                          "0"
        "Wide"                          "0"
        "Tall"                          "0"
        "Visible"                       "1"
        "ProportionalToParent"          "1"
        "MouseInputEnabled"             "0"
        "AllCaps"                       "1"
        "Font"                          "MainMenuLarge"
        "FGColor"                       "Red"
        "LabelText"                     "No Connection To Steam"
        "TextAlignment"                 "west"
        "Pin_To_Sibling"                "MainMenuAnchor"
        "Pin_Corner_To_Sibling"         "PIN_BOTTOMLEFT"
        "Pin_To_Sibling_Corner"         "PIN_TOPLEFT"
    }
    "NoGCImage"
    {
        "ControlName"                   "ImagePanel"
        "FieldName"                     "NoGCImage"
        "XPos"                          "0"
        "YPos"                          "5"
        "ZPos"                          "-99"
        "Wide"                          "40"
        "Tall"                          "40"
        "Visible"                       "1"
        "Enabled"                       "1"
        "Image"                         "gc_dc"
        "ScaleImage"                    "1"
        "ProportionalToParent"          "1"
        "DrawColor"                     "Red"
        "Pin_To_Sibling"                "NoGCMessage"
        "Pin_Corner_To_Sibling"         "PIN_BOTTOMLEFT"
        "Pin_To_Sibling_Corner"         "PIN_TOPLEFT"
    }
    // MARK: MAIN MENU TOP BAR
    "QuitTopBar"
    {
        "ControlName"                       "CExImageButton"
        "FieldName"                         "QuitTopBar"
        "XPos"                              "rs1-15"
        "YPos"                              "10"
        "ZPos"                              "15"
        "Wide"                              "32"
        "Tall"                              "32"
        "Visible"                           "1"
        "Enabled"                           "1"
        "ProportionalToParent"              "1"
        "Use_Proportional_Insets"           "1"
        "TextInsetX"                        "5"
        "Font"                              "Symbols16"
        "LabelText"                         "O"
        "Command"                           "quit"
        "TextAlignment"                     "center"
        "Sound_Depressed"                   "UI/buttonclick.wav"
        "DefaultFGColor_Override"           "White"
        "ArmedFGColor_Override"             "Menu_Accent"
        "DepressedFGColor_Override"         "Menu_Accent"
        "paintBackground"                   "0"
        "paintborder"                       "1"
        "border_default"                    "BG_TransparentBlack"
        "border_depressed"                  "OL_White_BG_TransparentBlack_Glow_Blue"
        "border_armed"                      "OL_White_BG_TransparentBlack_Glow_Blue"
    }
    "Settings"
    {
        "ControlName"                       "CExImageButton"
        "FieldName"                         "Settings"
        "XPos"                              "-8"
        "YPos"                              "0"
        "ZPos"                              "15"
        "Wide"                              "32"
        "Tall"                              "32"
        "Visible"                           "1"
        "Enabled"                           "1"
        "ProportionalToParent"              "1"
        "Use_Proportional_Insets"           "1"
        "TextInsetX"                        "5"
        "Font"                              "Symbols16"
        "LabelText"                         "T"
        "Command"                           "OpenOptionsDialog"
        "TextAlignment"                     "center"
        "Sound_Depressed"                   "UI/buttonclick.wav"
        "DefaultFGColor_Override"           "White"
        "ArmedFGColor_Override"             "Menu_Accent"
        "DepressedFGColor_Override"         "Menu_Accent"
        "paintBackground"                   "0"
        "paintborder"                       "1"
        "border_default"                    "BG_TransparentBlack"
        "border_depressed"                  "OL_White_BG_TransparentBlack_Glow_Blue"
        "border_armed"                      "OL_White_BG_TransparentBlack_Glow_Blue"
        "Pin_To_Sibling"                    "QuitTopBar"
        "Pin_Corner_To_Sibling"             "PIN_TOPRIGHT"
        "Pin_To_Sibling_Corner"             "PIN_TOPLEFT"
    }
    "Advanced"
    {
        "ControlName"                       "CExImageButton"
        "FieldName"                         "Advanced"
        "XPos"                              "-8"
        "YPos"                              "0"
        "ZPos"                              "15"
        "Wide"                              "32"
        "Tall"                              "32"
        "Visible"                           "1"
        "Enabled"                           "1"
        "ProportionalToParent"              "1"
        "Use_Proportional_Insets"           "1"
        "TextInsetX"                        "5"
        "Font"                              "Symbols16"
        "LabelText"                         "U"
        "Command"                           "opentf2options"
        "TextAlignment"                     "center"
        "Sound_Depressed"                   "UI/buttonclick.wav"
        "DefaultFGColor_Override"           "White"
        "ArmedFGColor_Override"             "Menu_Accent"
        "DepressedFGColor_Override"         "Menu_Accent"
        "paintBackground"                   "0"
        "paintborder"                       "1"
        "border_default"                    "BG_TransparentBlack"
        "border_depressed"                  "OL_White_BG_TransparentBlack_Glow_Blue"
        "border_armed"                      "OL_White_BG_TransparentBlack_Glow_Blue"
        "Pin_To_Sibling"                    "Settings"
        "Pin_Corner_To_Sibling"             "PIN_TOPRIGHT"
        "Pin_To_Sibling_Corner"             "PIN_TOPLEFT"
    }
    "NotificationBell"
    {
        "ControlName"                       "CExImageButton"
        "FieldName"                         "NotificationBell"
        "XPos"                              "-8"
        "YPos"                              "0"
        "ZPos"                              "15"
        "Wide"                              "32"
        "Tall"                              "32"
        "Visible"                           "1"
        "Enabled"                           "1"
        "ProportionalToParent"              "1"
        "Use_Proportional_Insets"           "1"
        "TextInsetX"                        "5"
        "Font"                              "HypnotizeIcons16"
        "LabelText"                         "X"
        "Command"                           "noti_show"
        "TextAlignment"                     "center"
        "Sound_Depressed"                   "UI/buttonclick.wav"
        "DefaultFGColor_Override"           "White"
        "ArmedFGColor_Override"             "Menu_Accent"
        "DepressedFGColor_Override"         "Menu_Accent"
        "paintBackground"                   "0"
        "paintborder"                       "1"
        "border_default"                    "BG_TransparentBlack"
        "border_depressed"                  "OL_White_BG_TransparentBlack_Glow_Blue"
        "border_armed"                      "OL_White_BG_TransparentBlack_Glow_Blue"
        "Pin_To_Sibling"                    "Advanced"
        "Pin_Corner_To_Sibling"             "PIN_TOPRIGHT"
        "Pin_To_Sibling_Corner"             "PIN_TOPLEFT"
    }
    // ==================================================================================================================================================
    // NOTIFICATIONS BUTTON
    // ==================================================================================================================================================
    "Notifications_ShowButtonPanel"
    {
        "ControlName"                   "EditablePanel"
        "FieldName"                     "Notifications_ShowButtonPanel"
        "XPos"                          "0"
        "YPos"                          "0"
        "ZPos"                          "16"
        "mouseinputenabled"             "0"
        "Wide"                          "16"
        "Tall"                          "16"
        "Visible"                       "1"
        "Pin_To_Sibling"                "NotificationBell"
        "Pin_Corner_To_Sibling"         "PIN_TOPRIGHT"
        "Pin_To_Sibling_Corner"         "PIN_TOPRIGHT"
        "Notifications_CountLabel"
        {
            "ControlName"                   "CExLabel"
            "FieldName"                     "Notifications_CountLabel"
            "XPos"                          "cs-0.5"
            "YPos"                          "cs-0.5"
            "ZPos"                          "4"
            "Wide"                          "f0"
            "Tall"                          "f0"
            "Visible"                       "1"
            "Enabled"                       "1"
            "ProportionalToParent"          "1"
            "MouseInputEnabled"             "0"
            "Font"                          "NotificationDot"
            "textinsetx"                    "4"
            "LabelText"                     "."
            "TextAlignment"                 "east"
            "FGColor"                       "FinalsYellow"
        }
        "Notifications_ShowButtonPanel_SB"	// dead
        {
            "ControlName"                       "CExImageButton"
            "FieldName"                         "Notifications_ShowButtonPanel_SB"
            "XPos"                              "cs-0.5"
            "YPos"                              "cs-0.5"
            "ZPos"                              "15"
            "Wide"                              "0"
            "Tall"                              "0"
            "Visible"                           "0"
            "Enabled"                           "1"
            "ProportionalToParent"              "1"
            "Use_Proportional_Insets"           "1"
            "TextInsetX"                        "5"
            "Font"                              "HypnotizeIcons16"
            "LabelText"                         "X"
            "AllCaps"                           "1"
            "TextAlignment"                     "center"
            "Command"                           "noti_show"
            "ActionSignalLevel"                 "2"
            "Sound_Depressed"                   "UI/buttonclick.wav"
            "PaintBackground"                   "0"
            "PaintBorder"                       "0"
            "PaintBackground"                   "0"
            "DefaultFGColor_Override"           "White"
            "ArmedFGColor_Override"             "Menu_Accent"
            "DepressedFGColor_Override"         "Menu_Accent"
            "paintbackground"                   "1"
            "paintborder"                       "1"
            "border_default"                    "BG_TransparentBlack"
            "border_depressed"                  "OL_White_BG_TransparentBlack_Glow_Blue"
            "border_armed"                      "OL_White_BG_TransparentBlack_Glow_Blue"
        }
    }
    // ==================================================================================================================================================
    // NOTIFICATIONS PANEL
    // ==================================================================================================================================================
    "Notifications_Panel"
    {
        "ControlName"                   "EditablePanel"
        "FieldName"                     "Notifications_Panel"
        "XPos"                          "2"
        "YPos"                          "-6"
        "ZPos"                          "17"
        "Wide"                          "210"
        "Tall"                          "80"
        "Visible"                       "0"
        "PaintBackgroundType"           "0"
        "PaintBackground"               "1"
        "BGColor_Override"              "TransparentLightBlack"
        "Pin_To_Sibling"                "NotificationBell"
        "Pin_Corner_To_Sibling"         "PIN_TOPRIGHT"
        "Pin_To_Sibling_Corner"         "PIN_TOPRIGHT"
        "Notifications_CloseButton"
        {
            "ControlName"                       "CExImageButton"
            "fieldName"                         "Notifications_CloseButton"
            "xpos"                              "rs1-2"
            "ypos"                              "-6"
            "zpos"                              "10"
            "Wide"                              "32"
            "Tall"                              "32"
            "Visible"                           "1"
            "Enabled"                           "1"
            "ProportionalToParent"              "1"
            "Use_Proportional_Insets"           "1"
            "TextInsetX"                        "5"
            "Font"                              "HypnotizeIcons16"
            "LabelText"                         "X"
            "Command"                           "noti_hide"
            "TextAlignment"                     "center"
            "Sound_Depressed"                   "UI/buttonclick.wav"
            "DefaultFGColor_Override"           "White"
            "ArmedFGColor_Override"             "Menu_Accent"
            "DepressedFGColor_Override"         "Menu_Accent"
            "paintBackground"                   "0"
            "paintborder"                       "1"
            "border_default"                    "BG_TransparentBlack"
            "border_depressed"                  "OL_White_BG_TransparentBlack_Glow_Blue"
            "border_armed"                      "OL_White_BG_TransparentBlack_Glow_Blue"
        }
        "Notifications_TitleLabel"
        {
            "ControlName"                       "CExLabel"
            "FieldName"                         "Notifications_TitleLabel"
            "XPos"                              "0"
            "YPos"                              "0"
            "Wide"                              "250"
            "Tall"                              "20"
            "Visible"                           "1"
            "Enabled"                           "1"
            "Wrap"                              "0"
            "ProportionalToParent"              "1"
            "Use_Proportional_Insets"           "1"
            "Font"                              "Header_MD"
            "LabelText"                         "%notititle%"
            "TextAlignment"                     "west"
            "Textinsetx"                        "3"
            "FGColor"                           "White"
            "PaintBackground"                   "1"
            "PaintBackgroundType"               "0"
            "BGcolor_Override"                  "blank"
        }
        "Notifications_Scroller"
        {
            "ControlName"                   "ScrollableEditablePanel"
            "FieldName"                     "Notifications_Scroller"
            "XPos"                          "0"
            "YPos"                          "21"
            "Wide"                          "217"
            "Tall"                          "43"
            "PaintBackgroundType"           "0"
            "FGColor_Override"              "White"
            "paintBackground"               "0"
            "BGcolor_Override"              "Black"
            "Notifications_Control"
            {
                "ControlName"           "CMainMenuNotificationsControl"
                "FieldName"             "Notifications_Control"
                "XPos"                  "0"
                "YPos"                  "0"
                "Wide"                  "217"
                "Tall"                  "43"
                "Visible"               "1"
            }
        }
    }
    // ==================================================================================================================================================
    // MARK: MAIN MENU BUTTONS
    // ==================================================================================================================================================
    "Version"
    {
        "ControlName"                   "EditablePanel"
        "FieldName"                     "Version"
        "XPos"                          "10"
        "YPos"                          "0"
        "ZPos"                          "15"
        "Wide"                          "0"
        "Tall"                          "0"
        "Visible"                       "0"
        "Pin_To_Sibling"                "MainMenuAnchor"
        "pin_corner_to_sibling"         "PIN_TOPRIGHT"
        "pin_to_sibling_corner"         "PIN_TOPLEFT"
        "SubButton"
        {
            "ControlName"                       "CExImageButton"
            "FieldName"                         "SubButton"
            "XPos"                              "0"
            "YPos"                              "0"
            "Wide"                              "f0"
            "Tall"                              "f0"
            "Visible"                           "1"
            "Enabled"                           "1"
            "ProportionalToParent"              "1"
            "Use_Proportional_Insets"           "1"
            "TextInsetX"                        "5"
            "Font"                              "TitleFont"
            "AllCaps"                           "0"
            "TextAlignment"                     "east"
            "Sound_Depressed"                   "UI/buttonclick.wav"
            "PaintBackground"                   "0"
            "PaintBorder"                       "0"
            "DefaultFGColor_Override"           "White"
            "ArmedFGColor_Override"             "Menu_Accent"
            "DepressedFGColor_Override"         "Menu_Accent"
        }
    }
    "ServersFG"
    {
        "ControlName"               "EditablePanel"
        "FieldName"                 "ServersFG"
        "XPos"                      "0"
        "YPos"                      "0"
        "ZPos"                      "15"
        "Wide"                      "200"
        "Tall"                      "32"
        "mouseinputenabled"         "0"
        "Pin_To_Sibling"            "Servers"
        "SubButton"
        {
            "ControlName"                       "CExImageButton"
            "FieldName"                         "SubButton"
            "XPos"                              "0"
            "YPos"                              "0"
            "ZPos"                              "1"
            "Wide"                              "f0"
            "Tall"                              "f0"
            "Visible"                           "1"
            "Enabled"                           "1"
            "ProportionalToParent"              "1"
            "Use_Proportional_Insets"           "1"
            "TextInsetX"                        "5"
            "LabelText"                         "Servers"
            "Font"                              "MainMenuLarge"
            "AllCaps"                           "1"
            "TextAlignment"                     "east"
            "Sound_Depressed"                   "UI/buttonclick.wav"
            "PaintBackground"                   "0"
            "PaintBorder"                       "0"
            "DefaultFGColor_Override"           "White"
            "ArmedFGColor_Override"             "White"
            "DepressedFGColor_Override"         "White"
        }
    }
    "Servers"
    {
        "ControlName"                   "EditablePanel"
        "FieldName"                     "Servers"
        "XPos"                          "-10"
        "YPos"                          "0"
        "ZPos"                          "15"
        "Wide"                          "200"
        "Tall"                          "32"
        "Pin_To_Sibling"                "Version"
        "Pin_Corner_To_Sibling"         "PIN_TOPRIGHT"
        "Pin_To_Sibling_Corner"         "PIN_BOTTOMRIGHT"
        "SubImage"
        {
            "ControlName"                       "CExImageButton"
            "FieldName"                         "SubImage"
            "XPos"                              "-3"
            "YPos"                              "0"
            "Wide"                              "f0"
            "Tall"                              "f0"
            "Visible"                           "1"
            "Enabled"                           "1"
            "ProportionalToParent"              "1"
            "Use_Proportional_Insets"           "1"
            "TextInsetX"                        "5"
            "TextInsetY"                        "-0.5"
            "LabelText"                         "Servers"
            "Font"                              "MainMenuLarge_Blur"
            "AllCaps"                           "1"
            "TextAlignment"                     "east"
            "Sound_Depressed"                   "UI/buttonclick.wav"
            "PaintBackground"                   "0"
            "PaintBorder"                       "0"
            "DefaultFGColor_Override"           "Blank"
            "ArmedFGColor_Override"             "MenuBlur_Accent"
            "DepressedFGColor_Override"         "MenuBlur_Accent"
        }
    }
    "Create"	// dead
    {
        "ControlName"                   "EditablePanel"
        "FieldName"                     "Create"
        "XPos"                          "2"
        "YPos"                          "-1"
        "ZPos"                          "16"
        "Wide"                          "0"
        "Tall"                          "0"
        "Pin_To_Sibling"                "Servers"
        "Pin_Corner_To_Sibling"         "PIN_CENTER_LEFT"
        "Pin_To_Sibling_Corner"         "PIN_CENTER_RIGHT"
        "SubButton"
        {
            "ControlName"                       "CExImageButton"
            "FieldName"                         "SubButton"
            "XPos"                              "0"
            "YPos"                              "0"
            "Wide"                              "f0"
            "Tall"                              "f0"
            "Visible"                           "1"
            "Enabled"                           "1"
            "ProportionalToParent"              "1"
            "Use_Proportional_Insets"           "1"
            "TextInsetX"                        "5"
            "Font"                              "VerdanaMenu"
            "AllCaps"                           "1"
            "TextAlignment"                     "west"
            "Sound_Depressed"                   "UI/buttonclick.wav"
            "PaintBackground"                   "0"
            "PaintBorder"                       "0"
            "DefaultFGColor_Override"           "White"
            "ArmedFGColor_Override"             "Menu_Accent"
            "DepressedFGColor_Override"         "Menu_Accent"
        }
    }
    "ItemsFG"
    {
        "ControlName"               "EditablePanel"
        "FieldName"                 "ItemsFG"
        "XPos"                      "0"
        "YPos"                      "0"
        "ZPos"                      "15"
        "Wide"                      "200"
        "Tall"                      "32"
        "mouseinputenabled"         "0"
        "Pin_To_Sibling"            "Items"
        "SubButton"
        {
            "ControlName"                       "CExImageButton"
            "FieldName"                         "SubButton"
            "XPos"                              "0"
            "YPos"                              "0"
            "ZPos"                              "1"
            "Wide"                              "f0"
            "Tall"                              "f0"
            "Visible"                           "1"
            "Enabled"                           "1"
            "ProportionalToParent"              "1"
            "Use_Proportional_Insets"           "1"
            "TextInsetX"                        "5"
            "LabelText"                         "Equipment"
            "Font"                              "MainMenuLarge"
            "AllCaps"                           "1"
            "TextAlignment"                     "east"
            "Sound_Depressed"                   "UI/buttonclick.wav"
            "PaintBackground"                   "0"
            "PaintBorder"                       "0"
            "DefaultFGColor_Override"           "White"
            "ArmedFGColor_Override"             "White"
            "DepressedFGColor_Override"         "White"
        }
    }
    "Items"
    {
        "ControlName"                   "EditablePanel"
        "FieldName"                     "Items"
        "XPos"                          "0"
        "YPos"                          "0"
        "ZPos"                          "15"
        "Wide"                          "200"
        "Tall"                          "32"
        "Pin_To_Sibling"                "Servers"
        "Pin_Corner_To_Sibling"         "PIN_TOPRIGHT"
        "Pin_To_Sibling_Corner"         "PIN_BOTTOMRIGHT"
        "SubImage"
        {
            "ControlName"                       "CExImageButton"
            "FieldName"                         "SubImage"
            "XPos"                              "-3"
            "YPos"                              "0"
            "ZPos"                              "1"
            "Wide"                              "f0"
            "Tall"                              "f0"
            "Visible"                           "1"
            "Enabled"                           "1"
            "ProportionalToParent"              "1"
            "Use_Proportional_Insets"           "1"
            "TextInsetX"                        "5"
            "TextInsetY"                        "-0.5"
            "LabelText"                         "Equipment"
            "Font"                              "MainMenuLarge_Blur"
            "AllCaps"                           "1"
            "TextAlignment"                     "east"
            "Sound_Depressed"                   "UI/buttonclick.wav"
            "PaintBackground"                   "0"
            "PaintBorder"                       "0"
            "DefaultFGColor_Override"           "Blank"
            "ArmedFGColor_Override"             "MenuBlur_Accent"
            "DepressedFGColor_Override"         "MenuBlur_Accent"
        }
    }
    "Contracker"	// dead
    {
        "ControlName"                   "EditablePanel"
        "FieldName"                     "Contracker"
        "XPos"                          "0"
        "YPos"                          "0"
        "ZPos"                          "15"
        "Wide"                          "0"
        "Tall"                          "0"
        "Pin_To_Sibling"                "Items"
        "Pin_Corner_To_Sibling"         "PIN_TOPRIGHT"
        "Pin_To_Sibling_Corner"         "PIN_BOTTOMRIGHT"
        "SubButton"
        {
            "ControlName"                       "CExImageButton"
            "FieldName"                         "SubButton"
            "XPos"                              "0"
            "YPos"                              "0"
            "Wide"                              "f0"
            "Tall"                              "f0"
            "Visible"                           "1"
            "Enabled"                           "1"
            "ProportionalToParent"              "1"
            "Use_Proportional_Insets"           "1"
            "TextInsetX"                        "5"
            "Font"                              "MainMenuLarge"
            "AllCaps"                           "1"
            "TextAlignment"                     "west"
            "Sound_Depressed"                   "UI/buttonclick.wav"
            "PaintBackground"                   "0"
            "PaintBorder"                       "0"
            "DefaultFGColor_Override"           "White"
            "ArmedFGColor_Override"             "Menu_Accent"
            "DepressedFGColor_Override"         "Menu_Accent"
        }
    }
    "StoreFG"
    {
        "ControlName"               "EditablePanel"
        "FieldName"                 "StoreFG"
        "XPos"                      "0"
        "YPos"                      "0"
        "ZPos"                      "15"
        "Wide"                      "200"
        "Tall"                      "32"
        "mouseinputenabled"         "0"
        "Pin_To_Sibling"            "Store"
        "SubButton"
        {
            "ControlName"                       "CExImageButton"
            "FieldName"                         "SubButton"
            "XPos"                              "0"
            "YPos"                              "0"
            "ZPos"                              "1"
            "Wide"                              "f0"
            "Tall"                              "f0"
            "Visible"                           "1"
            "Enabled"                           "1"
            "ProportionalToParent"              "1"
            "Use_Proportional_Insets"           "1"
            "TextInsetX"                        "5"
            "LabelText"                         "STORE"
            "Font"                              "MainMenuLarge"
            "AllCaps"                           "1"
            "TextAlignment"                     "east"
            "Sound_Depressed"                   "UI/buttonclick.wav"
            "PaintBackground"                   "0"
            "PaintBorder"                       "0"
            "DefaultFGColor_Override"           "White"
            "ArmedFGColor_Override"             "White"
            "DepressedFGColor_Override"         "White"
        }
    }
    "Store"
    {
        "ControlName"                   "EditablePanel"
        "FieldName"                     "Store"
        "XPos"                          "0"
        "YPos"                          "0"
        "ZPos"                          "15"
        "Wide"                          "200"
        "Tall"                          "32"
        "Pin_To_Sibling"                "Items"
        "Pin_Corner_To_Sibling"         "PIN_TOPRIGHT"
        "Pin_To_Sibling_Corner"         "PIN_BOTTOMRIGHT"
        "SubImage"
        {
            "ControlName"                       "CExImageButton"
            "FieldName"                         "SubImage"
            "XPos"                              "-3"
            "YPos"                              "0"
            "ZPos"                              "1"
            "Wide"                              "f0"
            "Tall"                              "f0"
            "Visible"                           "1"
            "Enabled"                           "1"
            "ProportionalToParent"              "1"
            "Use_Proportional_Insets"           "1"
            "TextInsetX"                        "5"
            "TextInsetY"                        "-0.5"
            "LabelText"                         "STORE"
            "Font"                              "MainMenuLarge_Blur"
            "AllCaps"                           "1"
            "TextAlignment"                     "east"
            "Sound_Depressed"                   "UI/buttonclick.wav"
            "PaintBackground"                   "0"
            "PaintBorder"                       "0"
            "DefaultFGColor_Override"           "Blank"
            "ArmedFGColor_Override"             "MenuBlur_Accent"
            "DepressedFGColor_Override"         "MenuBlur_Accent"
        }
    }
    "Workshop"	// disabled
    {
        "ControlName"                   "EditablePanel"
        "FieldName"                     "Workshop"
        "XPos"                          "99999"
        "YPos"                          "0"
        "ZPos"                          "15"
        "Wide"                          "150"
        "Tall"                          "17"
        "Pin_To_Sibling"                "Store"
        "Pin_Corner_To_Sibling"         "PIN_TOPRIGHT"
        "Pin_To_Sibling_Corner"         "PIN_BOTTOMRIGHT"
        "SubButton"
        {
            "ControlName"                       "CExImageButton"
            "FieldName"                         "SubButton"
            "XPos"                              "0"
            "YPos"                              "0"
            "Wide"                              "f0"
            "Tall"                              "f0"
            "Visible"                           "1"
            "Enabled"                           "1"
            "ProportionalToParent"              "1"
            "Use_Proportional_Insets"           "1"
            "TextInsetX"                        "5"
            "Font"                              "MainMenuLarge"
            "AllCaps"                           "1"
            "TextAlignment"                     "east"
            "Sound_Depressed"                   "UI/buttonclick.wav"
            "PaintBackground"                   "0"
            "PaintBorder"                       "0"
            "DefaultFGColor_Override"           "White"
            "ArmedFGColor_Override"             "Menu_Accent"
            "DepressedFGColor_Override"         "Menu_Accent"
        }
    }
    "DemoUI"	// disabled
    {
        "ControlName"                   "EditablePanel"
        "FieldName"                     "DemoUI"
        "XPos"                          "99999"
        "YPos"                          "0"
        "ZPos"                          "15"
        "Wide"                          "150"
        "Tall"                          "17"
        "Pin_To_Sibling"                "Workshop"
        "Pin_Corner_To_Sibling"         "PIN_TOPRIGHT"
        "Pin_To_Sibling_Corner"         "PIN_BOTTOMRIGHT"
        "SubButton"
        {
            "ControlName"                       "CExImageButton"
            "FieldName"                         "SubButton"
            "XPos"                              "0"
            "YPos"                              "0"
            "Wide"                              "f0"
            "Tall"                              "f0"
            "Visible"                           "1"
            "Enabled"                           "1"
            "ProportionalToParent"              "1"
            "Use_Proportional_Insets"           "1"
            "TextInsetX"                        "5"
            "Font"                              "MainMenuLarge"
            "AllCaps"                           "1"
            "TextAlignment"                     "east"
            "Sound_Depressed"                   "UI/buttonclick.wav"
            "PaintBackground"                   "0"
            "PaintBorder"                       "0"
            "DefaultFGColor_Override"           "White"
            "ArmedFGColor_Override"             "Menu_Accent"
            "DepressedFGColor_Override"         "Menu_Accent"
        }
    }
    // ==================================================================================================================================================
    // INGAME BUTTONS
    // ==================================================================================================================================================
    "TransparentBackground"
    {
        "ControlName"                           "EditablePanel"
        "FieldName"                             "TransparentBackground"
        "XPos"                                  "0"
        "YPos"                                  "0"
        "ZPos"                                  "-1"
        "Wide"                                  "f0"
        "Tall"                                  "f0"
        "ProportionalToParent"                  "1"
        "Visible"                               "0"
        "Enabled"                               "1"
        "PaintBackground"                       "1"
        "PaintBackgroundType"                   "0"
        "BGColor_Override"                      "TransparentMediumBlack"
        "InFocus_BGColor_Override"              "TransparentMediumBlack"
        "OutOfFocus_BGColor_Override"           "TransparentMediumBlack"
    }
    "DisconnectFG"
    {
        "ControlName"               "EditablePanel"
        "FieldName"                 "DisconnectFG"
        "XPos"                      "0"
        "YPos"                      "0"
        "ZPos"                      "15"
        "Wide"                      "100"
        "Tall"                      "32"
        "mouseinputenabled"         "0"
        "Pin_To_Sibling"            "Disconnect"
        "SubButton"
        {
            "ControlName"                       "CExImageButton"
            "FieldName"                         "SubButton"
            "XPos"                              "0"
            "YPos"                              "0"
            "ZPos"                              "1"
            "Wide"                              "f0"
            "Tall"                              "f0"
            "Visible"                           "1"
            "Enabled"                           "1"
            "ProportionalToParent"              "1"
            "Use_Proportional_Insets"           "1"
            "TextInsetX"                        "5"
            "LabelText"                         "Disconnect"
            "Font"                              "MainMenuLarge"
            "AllCaps"                           "1"
            "TextAlignment"                     "east"
            "Sound_Depressed"                   "UI/buttonclick.wav"
            "PaintBackground"                   "0"
            "PaintBorder"                       "0"
            "DefaultFGColor_Override"           "White"
            "ArmedFGColor_Override"             "White"
            "DepressedFGColor_Override"         "White"
        }
    }
    "Disconnect"
    {
        "ControlName"                   "EditablePanel"
        "FieldName"                     "Disconnect"
        "XPos"                          "0"
        "YPos"                          "5"
        "ZPos"                          "15"
        "Wide"                          "100"
        "Tall"                          "32"
        "Visible"                       "0"
        "Pin_To_Sibling"                "Store"
        "Pin_Corner_To_Sibling"         "PIN_TOPRIGHT"
        "Pin_To_Sibling_Corner"         "PIN_BOTTOMRIGHT"
        "SubImage"
        {
            "ControlName"                       "CExImageButton"
            "FieldName"                         "SubImage"
            "XPos"                              "-3"
            "YPos"                              "0"
            "ZPos"                              "1"
            "Wide"                              "f0"
            "Tall"                              "f0"
            "Visible"                           "1"
            "Enabled"                           "1"
            "ProportionalToParent"              "1"
            "Use_Proportional_Insets"           "1"
            "TextInsetX"                        "5"
            "TextInsetY"                        "-0.5"
            "LabelText"                         "Disconnect"
            "Font"                              "MainMenuLarge_Blur"
            "AllCaps"                           "1"
            "TextAlignment"                     "east"
            "Sound_Depressed"                   "UI/buttonclick.wav"
            "PaintBackground"                   "0"
            "PaintBorder"                       "0"
            "DefaultFGColor_Override"           "Blank"
            "ArmedFGColor_Override"             "MenuBlur_Accent"
            "DepressedFGColor_Override"         "MenuBlur_Accent"
        }
    }
    "Vote"
    {
        "ControlName"           "EditablePanel"
        "FieldName"             "Vote"
        "XPos"                  "10"
        "YPos"                  "1"
        "ZPos"                  "15"
        "Wide"                  "0"
        "Tall"                  "0"
        "Visible"               "0"
        "Pin_To_Sibling"        "MainMenuAnchor"
        "SubButton"
        {
            "ControlName"                       "CExImageButton"
            "FieldName"                         "SubButton"
            "XPos"                              "0"
            "YPos"                              "0"
            "Wide"                              "f0"
            "Tall"                              "f0"
            "Visible"                           "1"
            "Enabled"                           "1"
            "ProportionalToParent"              "1"
            "Use_Proportional_Insets"           "1"
            "TextInsetX"                        "5"
            "Font"                              "Symbols18"
            "TextAlignment"                     "center"
            "Sound_Depressed"                   "UI/buttonclick.wav"
            "PaintBackground"                   "0"
            "PaintBorder"                       "0"
            "DefaultFGColor_Override"           "White"
            "ArmedFGColor_Override"             "Menu_Accent"
            "DepressedFGColor_Override"         "Menu_Accent"
        }
    }
    "Mute"
    {
        "ControlName"           "EditablePanel"
        "FieldName"             "Mute"
        "XPos"                  "2"
        "YPos"                  "0"
        "ZPos"                  "15"
        "Wide"                  "20"
        "Tall"                  "17"
        "Visible"               "1"
        "Pin_To_Sibling"        "MainMenuAnchor"
        "SubButton"
        {
            "ControlName"                       "CExImageButton"
            "FieldName"                         "SubButton"
            "XPos"                              "0"
            "YPos"                              "0"
            "Wide"                              "f0"
            "Tall"                              "f0"
            "Visible"                           "1"
            "Enabled"                           "1"
            "ProportionalToParent"              "1"
            "Use_Proportional_Insets"           "1"
            "TextInsetX"                        "5"
            "Font"                              "Symbols18"
            "TextAlignment"                     "center"
            "Sound_Depressed"                   "UI/buttonclick.wav"
            "PaintBackground"                   "0"
            "PaintBorder"                       "0"
            "DefaultFGColor_Override"           "White"
            "ArmedFGColor_Override"             "Menu_Accent"
            "DepressedFGColor_Override"         "Menu_Accent"
        }
    }
    "Achievements"
    {
        "ControlName"                   "EditablePanel"
        "FieldName"                     "Achievements"
        "XPos"                          "2"
        "YPos"                          "0"
        "ZPos"                          "15"
        "Wide"                          "20"
        "Tall"                          "17"
        "Visible"                       "1"
        "Command"                       "OpenAchievementsDialog"
        "Pin_To_Sibling"                "Mute"
        "Pin_Corner_To_Sibling"         "PIN_TOPLEFT"
        "Pin_To_Sibling_Corner"         "PIN_TOPRIGHT"
        "SubButton"
        {
            "ControlName"                       "CExImageButton"
            "FieldName"                         "SubButton"
            "XPos"                              "0"
            "YPos"                              "0"
            "Wide"                              "f0"
            "Tall"                              "f0"
            "Visible"                           "1"
            "Enabled"                           "1"
            "ProportionalToParent"              "1"
            "Use_Proportional_Insets"           "1"
            "TextInsetX"                        "5"
            "Font"                              "Symbols18"
            "TextAlignment"                     "center"
            "Sound_Depressed"                   "UI/buttonclick.wav"
            "PaintBackground"                   "0"
            "PaintBorder"                       "0"
            "DefaultFGColor_Override"           "White"
            "ArmedFGColor_Override"             "Menu_Accent"
            "DepressedFGColor_Override"         "Menu_Accent"
        }
    }
    "Fix_Visual_Glitches"
    {
        "ControlName"                   "EditablePanel"
        "FieldName"                     "Fix_Visual_Glitches"
        "XPos"                          "2"
        "YPos"                          "0"
        "ZPos"                          "15"
        "Wide"                          "20"
        "Tall"                          "17"
        "Visible"                       "1"
        "Pin_To_Sibling"                "Achievements"
        "Pin_Corner_To_Sibling"         "PIN_TOPLEFT"
        "Pin_To_Sibling_Corner"         "PIN_TOPRIGHT"
        "SubButton"
        {
            "ControlName"                       "CExImageButton"
            "FieldName"                         "SubButton"
            "XPos"                              "0"
            "YPos"                              "0"
            "Wide"                              "f0"
            "Tall"                              "f0"
            "Visible"                           "1"
            "Enabled"                           "1"
            "ProportionalToParent"              "1"
            "Use_Proportional_Insets"           "1"
            "TextInsetX"                        "5"
            "Font"                              "Symbols18"
            "TextAlignment"                     "center"
            "Sound_Depressed"                   "UI/buttonclick.wav"
            "PaintBackground"                   "0"
            "PaintBorder"                       "0"
            "DefaultFGColor_Override"           "White"
            "ArmedFGColor_Override"             "Menu_Accent"
            "DepressedFGColor_Override"         "Menu_Accent"
        }
    }
    "HUD_Sound_Reload"
    {
        "ControlName"                   "EditablePanel"
        "FieldName"                     "HUD_Sound_Reload"
        "XPos"                          "2"
        "YPos"                          "0"
        "ZPos"                          "15"
        "Wide"                          "20"
        "Tall"                          "17"
        "Visible"                       "1"
        "Pin_To_Sibling"                "Fix_Visual_Glitches"
        "Pin_Corner_To_Sibling"         "PIN_TOPLEFT"
        "Pin_To_Sibling_Corner"         "PIN_TOPRIGHT"
        "SubButton"
        {
            "ControlName"                       "CExImageButton"
            "FieldName"                         "SubButton"
            "XPos"                              "0"
            "YPos"                              "0"
            "Wide"                              "f0"
            "Tall"                              "f0"
            "Visible"                           "1"
            "Enabled"                           "1"
            "ProportionalToParent"              "1"
            "Use_Proportional_Insets"           "1"
            "TextInsetX"                        "5"
            "Font"                              "Symbols18"
            "TextAlignment"                     "center"
            "Sound_Depressed"                   "UI/buttonclick.wav"
            "PaintBackground"                   "0"
            "PaintBorder"                       "0"
            "DefaultFGColor_Override"           "White"
            "ArmedFGColor_Override"             "Menu_Accent"
            "DepressedFGColor_Override"         "Menu_Accent"
        }
    }
    // MARK: BOTTOM CORNER BUTTONS
    "GitHub_Link"
    {
        "ControlName"                       "CExButton"
        "FieldName"                         "GitHub_Link"
        "XPos"                              "rs1-4"
        "YPos"                              "rs1-4"
        "ZPos"                              "20"
        "Wide"                              "20"
        "Tall"                              "20"
        "Visible"                           "1"
        "Enabled"                           "1"
        "ProportionalToParent"              "1"
        "LabelText"                         "^"
        "Font"                              "Symbols20"
        "TextAlignment"                     "center"
        "Command"                           "url https://github.com/itsmmarc/the-finals-hud"
        "PaintBackground"                   "0"
        "DefaultFGColor_Override"           "White"
        "ArmedFGColor_Override"             "Menu_Accent"
        "DepressedFGColor_Override"         "White"
    }
    "Kofi_Link"
    {
        "ControlName"                       "CExButton"
        "FieldName"                         "Kofi_Link"
        "XPos"                              "-1"
        "YPos"                              "-1"
        "ZPos"                              "20"
        "Wide"                              "22"
        "Tall"                              "22"
        "Visible"                           "1"
        "Enabled"                           "1"
        "ProportionalToParent"              "1"
        "LabelText"                         "K"
        "Font"                              "JumpHudIcons20"
        "TextAlignment"                     "center"
        "Command"                           "url https://ko-fi.com/itsmmarc"
        "PaintBackground"                   "0"
        "DefaultFGColor_Override"           "White"
        "ArmedFGColor_Override"             "Menu_Accent"
        "DepressedFGColor_Override"         "White"
        "Pin_To_Sibling"                    "GitHub_Link"
        "pin_corner_to_sibling"             "PIN_TOPRIGHT"
        "pin_to_sibling_corner"             "PIN_TOPLEFT"
    }
    // ==================================================================================================================================================
    // QUICKPLAY
    // ==================================================================================================================================================
    "Quickplay"	// disabled
    {
        "ControlName"           "EditablePanel"
        "FieldName"             "Quickplay"
        "XPos"                  "99999"	// rs1-48
        "YPos"                  "0"
        "ZPos"                  "10005"
        "Wide"                  "24"
        "Tall"                  "19"
        "SubButton"
        {
            "ControlName"                       "CExImageButton"
            "FieldName"                         "SubButton"
            "XPos"                              "0"
            "YPos"                              "0"
            "Wide"                              "f0"
            "Tall"                              "f0"
            "Visible"                           "1"
            "Enabled"                           "1"
            "ProportionalToParent"              "1"
            "Font"                              "Symbols20"
            "AllCaps"                           "0"
            "TextAlignment"                     "center"
            "Sound_Depressed"                   "UI/buttonclick.wav"
            "PaintBackground"                   "1"
            "PaintBorder"                       "0"
            "RoundedCorners"                    "0"
            "DefaultFGColor_Override"           "White"
            "ArmedFGColor_Override"             "White"
            "DepressedFGColor_Override"         "White"
            "DefaultBGColor_Override"           "0 150 135 255"
            "ArmedBGColor_Override"             "0 100 90 255"
            "DepressedBGColor_Override"         "0 150 135 255"
        }
    }
    // ==================================================================================================================================================
    // FRIENDS LIST
    // ==================================================================================================================================================
    "Friends"	// disabled
    {
        "ControlName"           "EditablePanel"
        "FieldName"             "Friends"
        "XPos"                  "139"
        "YPos"                  "0"
        "ZPos"                  "10005"
        "Wide"                  "0"
        "Tall"                  "0"
        "SubButton"
        {
            "ControlName"                       "CExImageButton"
            "FieldName"                         "SubButton"
            "XPos"                              "0"
            "YPos"                              "0"
            "Wide"                              "f0"
            "Tall"                              "f0"
            "Visible"                           "1"
            "Enabled"                           "1"
            "ProportionalToParent"              "1"
            "Font"                              "Symbols18"
            "AllCaps"                           "0"
            "TextAlignment"                     "center"
            "Sound_Depressed"                   "UI/buttonclick.wav"
            "PaintBackground"                   "1"
            "PaintBorder"                       "0"
            "RoundedCorners"                    "0"
            "DefaultFGColor_Override"           "White"
            "ArmedFGColor_Override"             "White"
            "DepressedFGColor_Override"         "White"
            "DefaultBGColor_Override"           "TransparentBlack"
            "ArmedBGColor_Override"             "Menu_Accent"
            "DepressedBGColor_Override"         "Menu_Accent"
        }
    }
    "MOTD_Panel"	// disabled
    {
        "ControlName"           "EditablePanel"
        "FieldName"             "MOTD_Panel"
        "XPos"                  "c150"
        "YPos"                  "99999"
        "ZPos"                  "11"
        "Wide"                  "110"
        "Tall"                  "214"
        "Visible"               "0"
    }
    "NotMOTD_Panel"
    {
        "ControlName"           "EditablePanel"
        "FieldName"             "NotMOTD_Panel"
        "XPos"                  "c150"
        "YPos"                  "cs-0.5"
        "ZPos"                  "11"
        "Wide"                  "110"
        "Tall"                  "214"
        "Visible"               "0"
        "CloseButton"	// disabled
        {
            "ControlName"                       "CExImageButton"
            "FieldName"                         "CloseButton"
            "XPos"                              "rs1"
            "YPos"                              "0"
            "ZPos"                              "1"
            "Wide"                              "16"
            "Tall"                              "16"
            "Visible"                           "0"
            "Enabled"                           "0"
            "ProportionalToParent"              "1"
            "Font"                              "Symbols18"
            "TextAlignment"                     "center"
            "LabelText"                         "X"
            "AllCaps"                           "1"
            "Command"                           "motd_hide"
            "ActionSignalLevel"                 "2"
            "Sound_Depressed"                   "UI/buttonclick.wav"
            "PaintBackground"                   "1"
            "RoundedCorners"                    "0"
            "DefaultBGColor_Override"           "TransparentLightBlack"
            "ArmedBGColor_Override"             "TransparentLightBlack"
            "DepressedBGColor_Override"         "TransparentLightBlack"
            "DefaultFGColor_Override"           "White"
            "ArmedFGColor_Override"             "Menu_Accent"
            "DepressedFGColor_Override"         "Menu_Accent"
        }
        "FriendsContainer"
        {
            "ControlName"                   "EditablePanel"
            "FieldName"                     "FriendsContainer"
            "XPos"                          "cs-0.5"
            "YPos"                          "cs-0.5"
            "ZPos"                          "0"
            "Wide"                          "f0"
            "Tall"                          "f0"
            "Visible"                       "1"
            "ProportionalToParent"          "1"
            "PaintBackground"               "1"
            "PaintBackgroundType"           "0"
            "BGColor_Override"              "TransparentLightBlack"
            "TitleLabel"
            {
                "ControlName"                       "CExLabel"
                "FieldName"                         "TitleLabel"
                "XPos"                              "0"
                "YPos"                              "0"
                "Wide"                              "f0"
                "Tall"                              "16"
                "Visible"                           "1"
                "Enabled"                           "1"
                "ProportionalToParent"              "1"
                "Use_Proportional_Insets"           "1"
                "Font"                              "MainMenuLarge"
                "LabelText"                         "#TF_Competitive_Friends"
                "TextAlignment"                     "west"
                "TextInsetX"                        "3"
                "FGColor"                           "White"
                "PaintBackground"                   "1"
                "PaintBackgroundType"               "0"
                "BGColor_Override"                  "TransparentLightBlack"
            }
            "SteamFriendsList"
            {
                "ControlName"                   "CSteamFriendsListPanel"
                "FieldName"                     "SteamFriendsList"
                "XPos"                          "rs1"
                "YPos"                          "rs1-2"
                "ZPos"                          "500"
                "Wide"                          "f2"
                "Tall"                          "f20"
                "Visible"                       "1"
                "ProportionalToParent"          "1"
                "PaintBackground"               "0"
                "PaintBackgroundType"           "0"
                "BGColor_Override"              "0 0 0 255"
                "columns_count"                 "1"
                "inset_x"                       "0"
                "inset_y"                       "0"
                "row_gap"                       "2"
                "column_gap"                    "0"
                "restrict_width"                "0"
                "FriendPanel_KV"
                {
                    "Wide"          "104"
                    "Tall"          "20"
                }
                "ScrollBar"
                {
                    "ControlName"                   "ScrollBar"
                    "FieldName"                     "ScrollBar"
                    "XPos"                          "rs1"
                    "YPos"                          "0"
                    "Tall"                          "f0"
                    "Wide"                          "4"
                    "ZPos"                          "1000"
                    "nobuttons"                     "1"
                    "ProportionalToParent"          "1"
                    "Slider"
                    {
                        "FGColor_Override"          "ScrollBar"
                    }
                }
            }
        }
    }
    // ==================================================================================================================================================
    // TOOLTIP PANEL
    // ==================================================================================================================================================
    "TooltipPanel"
    {
        "ControlName"                   "EditablePanel"
        "FieldName"                     "TooltipPanel"
        "XPos"                          "0"
        "YPos"                          "0"
        "ZPos"                          "10000"
        "Wide"                          "140"
        "Tall"                          "20"
        "Visible"                       "0"
        "PaintBackground"               "1"
        "PaintBackgroundType"           "0"
        "BGColor_Override"              "TransparentBlack"
        "TipSubLabel"
        {
            "ControlName"                   "CExLabel"
            "FieldName"                     "TipSubLabel"
            "XPos"                          "0"
            "YPos"                          "0"
            "ZPos"                          "2"
            "Wide"                          "f0"
            "Tall"                          "f0"
            "Visible"                       "1"
            "Enabled"                       "1"
            "ProportionalToParent"          "1"
            "AllCaps"                       "1"
            "Font"                          "HudFontSmallestBold"
            "LabelText"                     "%tipsubtext%"
            "TextAlignment"                 "center"
            "FGColor"                       "White"
        }
        "TipLabel"
        {
            "ControlName"                   "CExLabel"
            "FieldName"                     "TipLabel"
            "XPos"                          "0"
            "YPos"                          "0"
            "ZPos"                          "2"
            "Wide"                          "f0"
            "Tall"                          "f0"
            "Visible"                       "1"
            "Enabled"                       "1"
            "ProportionalToParent"          "1"
            "AllCaps"                       "1"
            "Font"                          "HudFontSmallestBold"
            "LabelText"                     "%tiptext%"
            "TextAlignment"                 "center"
            "FGColor"                       "White"
        }
    }
    "MouseOverItemPanel"
    {
        "ControlName"                   "CItemModelPanel"
        "FieldName"                     "MouseOverItemPanel"
        "XPos"                          "c-70"
        "YPos"                          "270"
        "ZPos"                          "100"
        "Wide"                          "300"
        "Tall"                          "300"
        "Visible"                       "0"
        "PaintBackground"               "1"
        "BGColor_Override"              "TransparentLightestBlack"
        "NoItem_TextColor"              "White"
        "PaintBackgroundType"           "0"
        "Text_YPos"                     "20"
        "Text_Center"                   "1"
        "Model_Hide"                    "1"
        "Resize_To_Text"                "1"
        "Padding_Height"                "15"
        "AttribLabel"
        {
            "Font"                  "ItemFontAttribLarge"
            "XPos"                  "0"
            "YPos"                  "30"
            "ZPos"                  "2"
            "Wide"                  "140"
            "Tall"                  "60"
            "Visible"               "1"
            "Enabled"               "1"
            "LabelText"             "%attriblist%"
            "TextAlignment"         "center"
            "FGColor"               "White"
            "CenterWrap"            "1"
        }
    }
}