"Resource/UI/MapInfoMenu.res"
{
	"mapinfo"
	{
		"ControlName"	"Frame"
		"fieldName"		"mapinfo"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"0"
		"wide"			"f0"
		"tall"			"480"
		"autoResize"	"1"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
	}

	"MapInfoTitle"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"MapInfoTitle"
		"xpos"			"5"
		"ypos"			"5"
		"zpos"			"1"
		"wide"			"225"
		"tall"			"50"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"%mapname%"
		"textAlignment"	"west"
		"font"			"oblique48"
		"fgcolor"		"owORANGE"
	}
	"Blurfact"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"Blurfact"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"-999"
		"wide"			"f0"
		"tall"			"f0"
		"autoResize"	"1"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"image"			"replay/thumbnails/blurfact"
	}
	"specBG"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"specBG"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"-21"
		"wide"			"f0"
		"tall"			"70"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"fillcolor"		"0 0 0 180"
	}	
	"specBG2"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"specBG2"
		"xpos"			"0"
		"ypos"			"70"
		"zpos"			"-21"
		"wide"			"f0"
		"tall"			"1"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"fillcolor"		"150 150 150 220"
	}
	"MapInfoType"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"MapInfoType"
		"xpos"			"-51"
		"ypos"			"45"
		"zpos"			"1"
		"wide"			"225"
		"tall"			"24"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"%gamemode%"
		"textAlignment"	"center"
		"font"			"DinBold12"
		"fgcolor"		"owORANGE"
	}	
	
	"MapInfoText"
	{
		"ControlName"	"CExRichText"
		"fieldName"		"MapInfoText"
		"font"			"Nim12"
		"xpos"			"5"
		"ypos"			"75"
		"zpos"			"3"
		"wide"			"f0"
		"tall"			"200"
		"autoResize"	"3"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"paintborder"	"0"
		"textAlignment"	"northwest"
		"fgcolor"		"owFULLWHITE"
	}
	
	"MapImage"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"MapImage"
		"xpos"			"0"
		"ypos"			"5"
		"zpos"			"2"
		"wide"			"0"
		"tall"			"0"
		"visible"		"0"
		"enabled"		"0"
		"image"			""
		"scaleImage"	"1"		
	}
	"MapInfoContinue" [$WIN32]
	{
		"ControlName"	"CExButton"
		"fieldName"		"MapInfoContinue"
		"xpos"			"r135290"
		"xpos_lodef"			"r222"
		"xpos_hidef"			"r232"
		"ypos"			"r41230"
		"ypos_lodef"			"r64"
		"ypos_hidef"			"r54"
		"zpos"			"6"
		"wide"			"0"
		"tall"			"0"
		"autoResize"	"0"
		"pinCorner"		"2"
		"visible"		"0"
		"enabled"		"0"
		"labelText"		"#TF_Continue"
		"textAlignment"	"center"
		"dulltext"		"0"
		"brighttext"	"0"
		"command"		"continue"
		"default"		"1"
		"font"			"MenuSmallFont"
		"fgcolor"		"Black"
	}
	"OkButton"
    {
        "ControlName"                       "CExButton"
        "fieldName"                         "OkButton"
        "XPos"                              "15"
        "YPos"                              "rs1-15"
        "ZPos"                              "15"
        "Wide"                              "24"
        "Tall"                              "24"
        "autoResize"                        "0"
        "pinCorner"                         "3"
        "visible"                           "1"
        "enabled"                           "1"
        "tabPosition"                       "0"
        "labelText"                         "&E"
        "font"                              "BodyEm_MD"
        "textAlignment"                     "center"
        "dulltext"                          "0"
        "brighttext"                        "0"
        "default"                           "0"
        "Command"                           "continue"
        "sound_depressed"                   "UI/buttonclick.wav"
        "sound_released"                    "UI/buttonclickrelease.wav"
        "DefaultFGColor_Override"           "FinalsGreyDark"
        "ArmedFGColor_Override"             "Menu_Accent"
        "DepressedFGColor_Override"         "Menu_Accent"
        "paintBackground"                   "1"
        "paintbackgroundtype"               "2"
        "DefaultBGColor_Override"           "FinalsKeyBG"
        "ArmedBGColor_Override"             "FinalsKeyBGD_Armed"
        "DepressedBGColor_Override"         "FinalsKeyBGD_Armed"
    }
    "OkButton2"
    {
        "ControlName"                       "CExButton"
        "fieldName"                         "OkButton2"
        "xpos"                              "0"
        "ypos"                              "0"
        "zpos"                              "2"
        "wide"                              "40"
        "tall"                              "17"
        "autoResize"                        "0"
        "pinCorner"                         "3"
        "visible"                           "1"
        "enabled"                           "1"
        "tabPosition"                       "0"
        "labelText"                         "NEXT"
        "font"                              "BodyEm_MD"
        "textAlignment"                     "center"
        "dulltext"                          "0"
        "brighttext"                        "0"
        "default"                           "0"
        "Command"                           "continue"
        "paintbackgroundtype"               "2"
        "paintbackground"                   "1"
        "sound_depressed"                   "UI/buttonclick.wav"
        "sound_released"                    "UI/buttonclickrelease.wav"
        "defaultBgColor_override"           "0 0 0 0"
        "armedBgColor_override"             "0 0 0 0"
        "depressedBgColor_override"         "0 0 0 0"
        "defaultFgColor_override"           "White"
        "armedFgColor_override"             "White"
        "depressedFgColor_override"         "White"
        "border_default"                    "NoBorder"
        "border_armed"                      "NoBorder"
        "pin_to_sibling"                    "OkButton"
        "pin_corner_to_sibling"             "pin_center_left"
        "pin_to_sibling_corner"             "pin_center_right"
    }
	"MapInfoWatchIntro"     // dead
	{
		"ControlName"	"CExButton"
		"fieldName"		"MapInfoWatchIntro"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"0"
		"wide"			"0"
		"tall"			"0"
		"autoResize"	"0"
		"pinCorner"		"2"
		"visible"		"0"
		"enabled"		"0"
		"labelText"		""
		"textAlignment"	""
		"dulltext"		"0"
		"brighttext"	"0"
		"command"		""
		"font"			""
	}
	"MapInfoBack"   // dead
	{
		"ControlName"	"CExButton"
		"fieldName"		"MapInfoBack"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"0"
		"wide"			"0"
		"tall"			"0"
		"autoResize"	"0"
		"pinCorner"		"2"
		"visible"		"0"
		"enabled"		"0"
		"labelText"		""
		"textAlignment"	"center"
		"dulltext"		"0"
		"brighttext"	"0"
		"command"		"back"
		"font"			"MenuSmallFont"
		"fgcolor"		"Black"
	}
	"MapInfoBackReal"
    {
        "ControlName"                       "CExButton"
        "fieldName"                         "MapInfoBackReal"
        "XPos"                              "0"
        "YPos"                              "0"
        "ZPos"                              "15"
        "Wide"                              "24"
        "Tall"                              "24"
        "autoResize"                        "0"
        "pinCorner"                         "3"
        "visible"                           "1"
        "enabled"                           "1"
        "tabPosition"                       "0"
        "labelText"                         "&Q"
        "font"                              "BodyEm_MD"
        "textAlignment"                     "center"
        "dulltext"                          "0"
        "brighttext"                        "0"
        "default"                           "0"
        "Command"                           "back"
        "sound_depressed"                   "UI/buttonclick.wav"
        "sound_released"                    "UI/buttonclickrelease.wav"
        "DefaultFGColor_Override"           "FinalsGreyDark"
        "ArmedFGColor_Override"             "Menu_Accent"
        "DepressedFGColor_Override"         "Menu_Accent"
        "paintBackground"                   "1"
        "paintbackgroundtype"               "2"
        "DefaultBGColor_Override"           "FinalsKeyBG"
        "ArmedBGColor_Override"             "FinalsKeyBGD_Armed"
        "DepressedBGColor_Override"         "FinalsKeyBGD_Armed"
        "pin_to_sibling"                    "OkButton2"
        "pin_corner_to_sibling"             "pin_center_left"
        "pin_to_sibling_corner"             "pin_center_right"
    }
    "MapInfoBack2"
    {
        "ControlName"                       "CExButton"
        "fieldName"                         "MapInfoBack2"
        "xpos"                              "0"
        "ypos"                              "0"
        "zpos"                              "2"
        "wide"                              "40"
        "tall"                              "17"
        "autoResize"                        "0"
        "pinCorner"                         "3"
        "visible"                           "1"
        "enabled"                           "1"
        "tabPosition"                       "0"
        "labelText"                         "BACK"
        "font"                              "BodyEm_MD"
        "textAlignment"                     "center"
        "dulltext"                          "0"
        "brighttext"                        "0"
        "default"                           "0"
        "Command"                           "back"
        "paintbackgroundtype"               "2"
        "paintbackground"                   "1"
        "sound_depressed"                   "UI/buttonclick.wav"
        "sound_released"                    "UI/buttonclickrelease.wav"
        "defaultBgColor_override"           "0 0 0 0"
        "armedBgColor_override"             "0 0 0 0"
        "depressedBgColor_override"         "0 0 0 0"
        "defaultFgColor_override"           "White"
        "armedFgColor_override"             "White"
        "depressedFgColor_override"         "White"
        "border_default"                    "NoBorder"
        "border_armed"                      "NoBorder"
        "pin_to_sibling"                    "MapInfoBackReal"
        "pin_corner_to_sibling"             "pin_center_left"
        "pin_to_sibling_corner"             "pin_center_right"
    }
	
	"MenuBG"
	{
		"ControlName"	"CModelPanel"
		"fieldName"		"MenuBG"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"0"		
		"wide"			"f0"
		"tall"			"480"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"0"
		"fov"			"20"
	}					

	"ShadedBar"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"ShadedBar"
		"xpos"			"0"
		"ypos"			"r50"
		"ypos_lodef"			"r74"
		"ypos_hidef"			"r65"
		"zpos"			"5"
		"wide"			"f0"
		"tall"			"50"
		"tall_lodef"			"74"
		"tall_hidef"			"65"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"0"
		"tabPosition"	"0"	
		"image"			"loadout_bottom_gradient"
		"tileImage"		"1"
		"PaintBackgroundType"	"2"
	}	
}
