"#base"         "MatchMakingDashboardSidePanel.res"
"Resource/UI/MatchMakingDashboardPlayList.res"
{
    "ExpandableList"
    {
        "fieldName"                     "ExpandableList"
        "xpos"                          "r0"
        "ypos"                          "0"
        "zpos"                          "15"
        "wide"                          "f0"
        "tall"                          "f0"
        "visible"                       "1"
        "proportionaltoparent"          "1"
    }
    "TitleAnchor"
    {
        "ControlName"                   "ImagePanel"
        "fieldName"                     "TitleAnchor"
        "xpos"                          "c0"
        "ypos"                          "30"
        "zpos"                          "6"
        "wide"                          "0"
        "tall"                          "0"
        "autoResize"                    "0"
        "pinCorner"                     "0"
        "visible"                       "1"
        "enabled"                       "1"
        "tabPosition"                   "0"
        "fillcolor"                     "SolarTeamBLU"
        "PaintBackgroundType"           "0"
    }
    "Title"
    {
        "ControlName"                   "Label"
        "fieldName"                     "Title"
        "xpos"                          "0"
        "ypos"                          "0"
        "zpos"                          "99"
        "wide"                          "f0"
        "tall"                          "35"
        "proportionaltoparent"          "1"
        "labeltext"                     "#TF_Matchmaking_HeaderModeSelect"
        "textAlignment"                 "center"
        "font"                          "SLItalicMedium"
        "fgcolor_override"              "TanLight"
        "auto_wide_tocontents"          "1"
        "textinsetx"                    "20"
        "allcaps"                       "1"
        "mouseinputenabled"             "0"
        "pin_to_sibling"                "TitleAnchor"
        "pin_corner_to_sibling"         "4"
        "pin_to_sibling_corner"         "4"
    }
    "TitleStroke"
    {
        "ControlName"                   "Label"
        "fieldName"                     "TitleStroke"
        "xpos"                          "0"
        "ypos"                          "0"
        "zpos"                          "98"
        "wide"                          "f0"
        "tall"                          "35"
        "proportionaltoparent"          "1"
        "labeltext"                     "#TF_Matchmaking_HeaderModeSelect"
        "textAlignment"                 "center"
        "font"                          "SLItalicMediumStroke"
        "fgcolor_override"              "TanDarker"
        "border"                        "BorderTargetIDTanDarker"
        "auto_wide_tocontents"          "1"
        "textinsetx"                    "20"
        "allcaps"                       "1"
        "visible"                       "1"
        "enabled"                       "1"
        "mouseinputenabled"             "0"
        "pin_to_sibling"                "TitleAnchor"
        "pin_corner_to_sibling"         "4"
        "pin_to_sibling_corner"         "4"
    }
    "TopBar"
    {
        "ControlName"           "ImagePanel"
        "fieldName"             "TopBar"
        "xpos"                  "0"
        "ypos"                  "0"
        "zpos"                  "-10"
        "wide"                  "f0"
        "tall"                  "50"
        "fillcolor"             "Black"
        "autoResize"            "0"
        "pinCorner"             "0"
        "visible"               "1"
        "enabled"               "1"
    }
    "BottomBar"
    {
        "ControlName"           "ImagePanel"
        "fieldName"             "BottomBar"
        "xpos"                  "0"
        "ypos"                  "r50"
        "zpos"                  "-10"
        "wide"                  "f0"
        "tall"                  "50"
        "fillcolor"             "Black"
        "autoResize"            "0"
        "pinCorner"             "0"
        "visible"               "1"
        "enabled"               "1"
    }
    "bggradient"
    {
        "ControlName"                   "CTFImagePanel"
        "fieldName"                     "bggradient"
        "xpos"                          "0"
        "ypos"                          "0"
        "zpos"                          "-11"
        "wide"                          "f-20"
        "tall"                          "f-20"
        "drawcolor"                     "128 100 75 255"
        "autoResize"                    "0"
        "pinCorner"                     "0"
        "visible"                       "1"
        "enabled"                       "1"
        "image"                         "training/gradient_black"
        "alpha"                         "250"
        "proportionaltoparent"          "1"
    }
    "CenterBar"
    {
        "ControlName"                   "ImagePanel"
        "fieldName"                     "CenterBar"
        "xpos"                          "cs-0.5"
        "ypos"                          "0"
        "zpos"                          "-12"
        "wide"                          "20"
        "tall"                          "f0"
        "fillcolor"                     "TanLight"
        "autoResize"                    "0"
        "pinCorner"                     "0"
        "visible"                       "1"
        "enabled"                       "1"
        "proportionaltoparent"          "1"
    }
    "bgpanel"
    {
        "ControlName"           "CTFImagePanel"
        "fieldName"             "bgpanel"
        "visible"               "0"
        "enabled"               "0"
    }
    "bgline"
    {
        "ControlName"               "ImagePanel"
        "fieldName"                 "bgline"
        "xpos"                      "0"
        "ypos"                      "0"
        "zpos"                      "-13"
        "wide"                      "f0"
        "tall"                      "f0"
        "visible"                   "1"
        "enabled"                   "1"
        "image"                     "replay/thumbnails/linebg_tandarker_bigger_overlay"
        "scaleImage"                "1"
        "mouseinputenabled"         "0"
    }
    "BLUTint"
    {
        "ControlName"                   "ImagePanel"
        "fieldName"                     "BLUTint"
        "xpos"                          "0"
        "ypos"                          "0"
        "zpos"                          "-15"
        "wide"                          "p0.5"
        "tall"                          "f0"
        "fillcolor"                     "SolarTeamBLU"
        "autoResize"                    "0"
        "pinCorner"                     "0"
        "visible"                       "1"
        "enabled"                       "1"
        "proportionaltoparent"          "1"
    }
    "REDTint"
    {
        "ControlName"                   "ImagePanel"
        "fieldName"                     "REDTint"
        "xpos"                          "c0"
        "ypos"                          "0"
        "zpos"                          "-15"
        "wide"                          "p0.5"
        "tall"                          "f0"
        "fillcolor"                     "SolarTeamRED"
        "autoResize"                    "0"
        "pinCorner"                     "0"
        "visible"                       "1"
        "enabled"                       "1"
        "proportionaltoparent"          "1"
    }
    "titlegradient"
    {
        "visible"           "0"
    }
    "shade"
    {
        "visible"           "0"
    }
    "InnerGradient"
    {
        "visible"           "0"
    }
    "OuterGradient"
    {
        "visible"           "0"
    }
    "CloseButton"
    {
        "visible"           "0"
    }
    "ReturnButton"
    {
        "visible"           "0"
        "ypos"              "9999"
    }
    "playlist"
    {
        //	"ControlName"	"CTFPlaylistPanel"
        "fieldName"                     "playlist"
        "xpos"                          "cs-0.5"
        "ypos"                          "50"
        "zpos"                          "100"
        "wide"                          "550"
        "tall"                          "400"
        "visible"                       "1"
        "proportionaltoparent"          "1"
    }
    "ExitButtonKey"
    {
        "ControlName"                       "CExButton"
        "FieldName"                         "ExitButtonKey"
        "XPos"                              "15"
        "YPos"                              "rs1-15"
        "ZPos"                              "15"
        "Wide"                              "24"
        "Tall"                              "24"
        "Visible"                           "1"
        "Enabled"                           "1"
        "ProportionalToParent"              "1"
        "Use_Proportional_Insets"           "1"
        "TextInsetX"                        "5"
        "Font"                              "BodyEm_MD"
        "LabelText"                         "[]"
        "Command"                           "nav_close"
        "TextAlignment"                     "center"
        "Sound_Depressed"                   "UI/buttonclick.wav"
        "DefaultFGColor_Override"           "FinalsGreyDark"
        "ArmedFGColor_Override"             "Menu_Accent"
        "DepressedFGColor_Override"         "Menu_Accent"
        "paintBackground"                   "1"
        "paintbackgroundtype"               "2"
        "DefaultBGColor_Override"           "FinalsKeyBG"
        "ArmedBGColor_Override"             "FinalsKeyBGD_Armed"
        "DepressedBGColor_Override"         "FinalsKeyBGD_Armed"
    }
    "ExitButton"	//same as safemode
    {
        "ControlName"                       "CExImageButton"
        "fieldName"                         "ExitButton"
        "xpos"                              "0"
        "ypos"                              "0"
        "zpos"                              "11"
        "wide"                              "60"
        "tall"                              "24"
        "visible"                           "1"
        "enabled"                           "1"
        "use_proportional_insets"           "1"
        "font"                              "BodyEm_MD"
        "textAlignment"                     "west"
        "default"                           "1"
        "sound_armed"                       "UI/buttonrollover.wav"
        "sound_depressed"                   "UI/buttonclick.wav"
        "labeltext"                         "#TF_Close"
        "proportionaltoparent"              "1"
        "command"                           "nav_close"
        "paintbackground"                   "0"
        "paintBorder"                       "0"
        "defaultFgColor_override"           "White"
        "armedFgColor_override"             "Menu_Accent"
        "depressedFgColor_override"         "Menu_Accent"
        "defaultBgColor_override"           "Blank"
        "armedBgColor_override"             "Blank"
        "depressedBgColor_override"         "Blank"
        "pin_to_sibling"                    "ExitButtonKey"
        "pin_corner_to_sibling"             "pin_center_left"
        "pin_to_sibling_corner"             "pin_center_right"
        "SubImage"	// dead
        {
            "ControlName"                   "CExImageButton"
            "fieldName"                     "SubImage"
            "xpos"                          "99999"
            "ypos"                          "99999"
            "zpos"                          "1"
            "wide"                          "0"
            "tall"                          "0"
            "visible"                       "0"
            "enabled"                       "0"
            "image"                         ""
            "scaleImage"                    "1"
            "proportionaltoparent"          "1"
        }
    }
}