"Resource/UI/MatchmakingCategoryPanel.res"
{
    "MatchmakingCategoryPanel"
    {
        "fieldName"                     "MatchmakingCategoryPanel"
        "xpos"                          "0"
        "ypos"                          "0"
        "wide"                          "f0"
        "tall"                          "50"
        "proportionaltoparent"          "1"
        "collapsed_height"              "24"
        "resize_time"                   "0.2"
    }
    "TopContainer"
    {
        "Controlname"                   "EditablePanel"
        "fieldName"                     "TopContainer"
        "xpos"                          "0"
        "ypos"                          "0"
        "zpos"                          "2"
        "wide"                          "f0"
        "tall"                          "24"
        "visible"                       "1"
        "enabled"                       "1"
        "proportionaltoparent"          "1"
        "Shade"
        {
            "fieldName"                     "Shade"
            "ControlName"                   "EditablePanel"
            "xpos"                          "0"
            "ypos"                          "0"
            "zpos"                          "10"
            "wide"                          "f0"
            "tall"                          "f0"
            "mouseinputenabled"             "0"
            "proportionaltoparent"          "1"
            "paintBackground"               "1"
            "paintBackgroundType"           "2"
        }
        "BGRoundedCorners"
        {
            "ControlName"                   "EditablePanel"
            "fieldName"                     "BGRoundedCorners"
            "xpos"                          "0"
            "ypos"                          "0"
            "zpos"                          "10"
            "wide"                          "80"
            "tall"                          "f0"
            "visible"                       "1"
            "enabled"                       "1"
            "scaleImage"                    "1"
            "proportionaltoparent"          "1"
            "paintBorder"                   "1"
            "border"                        "RoundedCorners_FinalsBlack_LeftOnly"
        }
        "BGImageGradient"
        {
            "ControlName"                   "ImagePanel"
            "fieldName"                     "BGImageGradient"
            "xpos"                          "0"
            "ypos"                          "0"
            "zpos"                          "1"
            "wide"                          "160"
            "tall"                          "40"
            "visible"                       "1"
            "enabled"                       "1"
            "scaleImage"                    "1"
            "image"                         "replay/thumbnails/gamemodeselect/gradient-white-rtl"
            "proportionaltoparent"          "1"
        }
        "BGImage"
        {
            "ControlName"                   "ImagePanel"
            "fieldName"                     "BGImage"
            "xpos"                          "0"
            "ypos"                          "0"
            "zpos"                          "0"
            "wide"                          "160"
            "tall"                          "40"
            "visible"                       "1"
            "enabled"                       "1"
            "scaleImage"                    "1"
            "proportionaltoparent"          "1"
        }
        "BGColor"
        {
            "ControlName"                   "EditablePanel"
            "fieldName"                     "BGColor"
            "xpos"                          "0"
            "ypos"                          "0"
            "zpos"                          "-1"
            "wide"                          "f0"
            "tall"                          "f0"
            "visible"                       "1"
            "enabled"                       "1"
            "mouseinputenabled"             "0"
            "proportionaltoparent"          "1"
            "paintBackground"               "1"
            "paintBackgroundType"           "2"
            "bgcolor_override"              "White"
        }
        "EntryToggleButton"	// open/close arrow
        {
            "ControlName"                       "CExImageButton"
            "fieldName"                         "EntryToggleButton"
            "xpos"                              "rs1-3"
            "ypos"                              "0"
            "zpos"                              "100"
            "wide"                              "20"
            "tall"                              "f0"
            "proportionaltoparent"              "1"
            "actionsignallevel"                 "2"
            "command"                           "toggle_collapse"
            "labeltext"                         ""
            "font"                              ""
            "textinsetx"                        ""
            "textAlignment"                     "west"
            "stay_armed_on_click"               "1"
            "border_default"                    "NoBorder"
            "border_armed"                      "NoBorder"
            "defaultBgColor_override"           "blank"
            "armedBgColor_override"             "FinalsYellow"	// TODO - make this look good
            "selectedBGColor_override"          "FinalsYellow"
            "sound_armed"                       "ui/item_info_mouseover.wav"
            "sound_depressed"                   "UI/buttonclick.wav"
            "sound_released"                    "UI/buttonclickrelease.wav"
            "button_activation_type"            "1"
            "SubImage"
            {
                "ControlName"                   "ImagePanel"
                "fieldName"                     "SubImage"
                "xpos"                          "cs-0.5"
                "ypos"                          "cs-0.5"
                "zpos"                          "1"
                "wide"                          "p0.85"
                "tall"                          "p0.85"
                "visible"                       "1"
                "enabled"                       "1"
                "scaleImage"                    "1"
                "proportionaltoparent"          "1"
            }
        }
        "CheckButton"
        {
            "ControlName"                   "CExCheckButton"
            "fieldName"                     "CheckButton"
            "xpos"                          "-4"
            "ypos"                          "0"
            "zpos"                          "3"
            "wide"                          "25"
            "tall"                          "f0"
            "proportionaltoparent"          "1"
            "labeltext"                     ""
            "smallcheckimage"               "1"
            "sound_depressed"               "UI/buttonclickrelease.wav"
            "button_activation_type"        "1"
            "pin_to_sibling"                "EntryToggleButton"
            "pin_corner_to_sibling"         "PIN_TOPRIGHT"
            "pin_to_sibling_corner"         "PIN_TOPLEFT"
        }
        "TitleReal"
        {
            "ControlName"                       "CExLabel"
            "fieldName"                         "TitleReal"
            "xpos"                              "100"
            "ypos"                              "-3"
            "zpos"                              "3"
            "wide"                              "200"
            "tall"                              "f0"
            "visible"                           "1"
            "enabled"                           "1"
            "labelText"                         "%title_token%"
            "textinsetx"                        "5"
            "textinsety"                        "2"
            "use_proportional_insets"           "1"
            "font"                              "ButtonEm_MD"
            "AllCaps"                           "1"
            "textAlignment"                     "west"
            "dulltext"                          "0"
            "brighttext"                        "0"
            "default"                           "1"
            "proportionaltoparent"              "1"
            "mouseinputenabled"                 "0"
            "fgcolor"                           "Black"
        }
        "TitleShadow"
        {
            "ControlName"                       "CExLabel"
            "fieldName"                         "TitleShadow"
            "xpos"                              "0"
            "ypos"                              "0"
            "zpos"                              "2"
            "wide"                              "200"
            "tall"                              "f0"
            "visible"                           "1"
            "enabled"                           "1"
            "labelText"                         "%title_token%"
            "textinsetx"                        "5"
            "textinsety"                        "2"
            "use_proportional_insets"           "1"
            "font"                              "ButtonEm_MD_Blur"
            "AllCaps"                           "1"
            "textAlignment"                     "west"
            "dulltext"                          "0"
            "brighttext"                        "0"
            "default"                           "1"
            "proportionaltoparent"              "1"
            "mouseinputenabled"                 "0"
            "fgcolor_override"                  "Shadow"
            "pin_to_sibling"                    "TitleReal"
        }
        "Title"	// dead
        {
            "ControlName"                       "CExLabel"
            "fieldName"                         "Title"
            "xpos"                              "99999"
            "ypos"                              "99999"
            "zpos"                              "3"
            "wide"                              "0"
            "tall"                              "0"
            "visible"                           "1"
            "enabled"                           "1"
            "labelText"                         "%title_token%"
            "textinsetx"                        "5"
            "use_proportional_insets"           "1"
            "font"                              ""
            "textAlignment"                     "west"
            "dulltext"                          "0"
            "brighttext"                        "0"
            "default"                           "1"
            "proportionaltoparent"              "1"
            "mouseinputenabled"                 "0"
        }
    }
    "MapsContainer"
    {
        "Controlname"                   "EditablePanel"
        "fieldName"                     "MapsContainer"
        "xpos"                          "0"
        "ypos"                          "0"
        "zpos"                          "0"
        "wide"                          "f0"
        "tall"                          "0"
        "visible"                       "1"
        "enabled"                       "1"
        "proportionaltoparent"          "1"
        "border"                        "BorderBlackCornersVerySmall"
        "pinCorner"                     "2"
        "autoResize"                    "1"
        "skip_autoresize"               "1"
        "bgcolor_override"              "0 0 0 0"
    }
}