"#base"         "MatchMakingDashboardSidePanel.res"
// MATCHMAKING CASUAL GAMEMODES LIST SCREEN
"Resource/UI/MatchMakingDashboardCasualCriteria.res"
{
    "CasualCriteria"
    {
        "fieldName"                     "CasualCriteria"
        "xpos"                          "r0"
        "ypos"                          "0"
        "zpos"                          "13"
        "wide"                          "f0"
        "tall"                          "f0"
        "visible"                       "1"
        "proportionaltoparent"          "1"
    }
    "GamemodesLabel" // @SCREENTITLE
    {
        "ControlName"               "Label"
        "fieldName"                 "GamemodesLabel"
        "xpos"                      "20"
        "ypos"                      "20"
        "zpos"                      "1"
        "wide"                      "300"
        "tall"                      "25"
        "labelText"                 "GAMEMODES"
        "textAlignment"             "west"
        "font"                      "HeaderEm_XL"
        "visible"                   "1"
        "enabled"                   "1"
        "fgcolor_override"          "White"
    }
    "shade"
    {
        "visible"           "0"
    }
    "InnerGradient"
    {
        "visible"           "0"
    }
    "OuterGradient"
    {
        "visible"           "0"
    }
    "CloseButton"
    {
        "visible"           "0"
    }
    "criteria"
    {
        "ControlName"                   "CCasualCriteriaPanel"
        "fieldName"                     "criteria"
        "xpos"                          "-3"
        "ypos"                          "40"
        "zpos"                          "100"
        "wide"                          "f0"
        "tall"                          "f40"
        "visible"                       "1"
        "proportionaltoparent"          "1"
    }
    "TopBar"	// dead
    {
        "ControlName"           "ImagePanel"
        "fieldName"             "TopBar"
        "xpos"                  "99999"
        "ypos"                  "99999"
        "zpos"                  "-10"
        "wide"                  "0"
        "tall"                  "0"
        "fillcolor"             "Blank"
        "autoResize"            "0"
        "pinCorner"             "0"
        "visible"               "1"
        "enabled"               "1"
    }
    "BottomBar"	// dead
    {
        "ControlName"           "ImagePanel"
        "fieldName"             "BottomBar"
        "xpos"                  "99999"
        "ypos"                  "99999"
        "zpos"                  "-10"
        "wide"                  "0"
        "tall"                  "0"
        "fillcolor"             "Blank"
        "autoResize"            "0"
        "pinCorner"             "0"
        "visible"               "1"
        "enabled"               "1"
    }
    "BGImage"
    {
        "ControlName"                   "ImagePanel"
        "fieldName"                     "BGImage"
        "xpos"                          "0"
        "ypos"                          "0"
        "zpos"                          "-11"
        "wide"                          "f0"
        "tall"                          "f0"
        "visible"                       "1"
        "enabled"                       "1"
        "image"                         "replay/thumbnails/WT2_BKG"
        "proportionaltoparent"          "1"
    }
    "bgpanel"
    {
        "ControlName"           "CTFImagePanel"
        "fieldName"             "bgpanel"
        "visible"               "0"
        "enabled"               "0"
    }
    "titlegradient"
    {
        "visible"           "0"
    }
    "QueueButtonFG"
    {
        "ControlName"               "EditablePanel"
        "FieldName"                 "QueueButtonFG"
        "XPos"                      "-4"
        "YPos"                      "0"
        "ZPos"                      "102"
        "Wide"                      "120"
        "Tall"                      "32"
        "mouseinputenabled"         "0"
        "Pin_To_Sibling"            "QueueButton"
        "SubButton"
        {
            "ControlName"                       "CExImageButton"
            "FieldName"                         "SubButton"
            "XPos"                              "0"
            "YPos"                              "0"
            "ZPos"                              "1"
            "Wide"                              "f0"
            "Tall"                              "f0"
            "Visible"                           "1"
            "Enabled"                           "1"
            "ProportionalToParent"              "1"
            "LabelText"                         "SEARCH"
            "Font"                              "MainMenuLarge"
            "AllCaps"                           "1"
            "TextAlignment"                     "west"
            "TextInsetX"                        "10"
            "Sound_Depressed"                   "UI/buttonclick.wav"
            "PaintBackground"                   "0"
            "PaintBorder"                       "0"
            "DefaultFGColor_Override"           "White"
            "ArmedFGColor_Override"             "White"
            "DepressedFGColor_Override"         "White"
        }
    }
    "QueueButton"
    {
        "ControlName"                       "CExImageButton"
        "fieldName"                         "QueueButton"
        "xpos"                              "rs1-10-3"
        "ypos"                              "rs1-40-82"
        "zpos"                              "101"
        "wide"                              "120"
        "tall"                              "32"
        "autoResize"                        "0"
        "pinCorner"                         "3"
        "visible"                           "1"
        "enabled"                           "1"
        "tabPosition"                       "0"
        "dulltext"                          "0"
        "brighttext"                        "0"
        "Command"                           "find_game"
        "font"                              "MainMenuLarge_Blur"
        "labeltext"                         "SEARCH"
        "TextAlignment"                     "west"
        "textinsetx"                        "10"
        "AllCaps"                           "1"
        "Sound_Depressed"                   "UI/buttonclick.wav"
        "PaintBackground"                   "0"
        "PaintBorder"                       "0"
        "DefaultFGColor_Override"           "Blank"
        "ArmedFGColor_Override"             "MenuBlur_Accent"
        "DepressedFGColor_Override"         "MenuBlur_Accent"
        "SubImage"
        {
            "ControlName"                   "ImagePanel"
            "fieldName"                     "SubImage"
            "xpos"                          "99999"
            "ypos"                          "99999"
            "zpos"                          "1"
            "wide"                          "0"
            "tall"                          "0"
            "visible"                       "0"
            "enabled"                       "0"
            "scaleImage"                    "1"
            "proportionaltoparent"          "1"
            "image"                         ""
            "drawcolor_override"            "TanLight"
        }
    }
    "ToolTipButtonHack"
    {
        "ControlName"                           "EditablePanel"
        "fieldName"                             "ToolTipButtonHack"
        "xpos"                                  "0"
        "ypos"                                  "0"
        "zpos"                                  "103"
        "wide"                                  "120"
        "tall"                                  "32"
        "visible"                               "0"
        "enabled"                               "1"
        "mouseinputenabled"                     "1"
        "eatmouseinput"                         "0"
        "showtooltipswhenmousedisabled"         "1"
        "proportionaltoparent"                  "1"
        "pin_to_sibling"                        "QueueButton"
    }
    "ExitButtonKey"
    {
        "ControlName"                       "CExButton"
        "FieldName"                         "ExitButtonKey"
        "XPos"                              "15"
        "YPos"                              "rs1-15"
        "ZPos"                              "101"
        "Wide"                              "24"
        "Tall"                              "24"
        "Visible"                           "1"
        "Enabled"                           "1"
        "ProportionalToParent"              "1"
        "Use_Proportional_Insets"           "1"
        "TextInsetX"                        "5"
        "Font"                              "BodyEm_MD"
        "LabelText"                         "[a]"
        "Command"                           "nav_close"
        "TextAlignment"                     "center"
        "Sound_Depressed"                   "UI/buttonclick.wav"
        "DefaultFGColor_Override"           "FinalsGreyDark"
        "ArmedFGColor_Override"             "Menu_Accent"
        "DepressedFGColor_Override"         "Menu_Accent"
        "paintBackground"                   "1"
        "paintbackgroundtype"               "2"
        "DefaultBGColor_Override"           "FinalsKeyBG"
        "ArmedBGColor_Override"             "FinalsKeyBGD_Armed"
        "DepressedBGColor_Override"         "FinalsKeyBGD_Armed"
    }
    "ExitButton"	//same as safemode
    {
        "ControlName"                       "CExImageButton"
        "fieldName"                         "ExitButton"
        "xpos"                              "0"
        "ypos"                              "0"
        "zpos"                              "101"
        "wide"                              "60"
        "tall"                              "24"
        "visible"                           "1"
        "enabled"                           "1"
        "use_proportional_insets"           "1"
        "font"                              "BodyEm_MD"
        "textAlignment"                     "west"
        "default"                           "1"
        "sound_armed"                       "UI/buttonrollover.wav"
        "sound_depressed"                   "UI/buttonclick.wav"
        "labeltext"                         "#TF_Close"
        "proportionaltoparent"              "1"
        "command"                           "nav_close"
        "paintbackground"                   "0"
        "paintBorder"                       "0"
        "defaultFgColor_override"           "White"
        "armedFgColor_override"             "Menu_Accent"
        "depressedFgColor_override"         "Menu_Accent"
        "defaultBgColor_override"           "Blank"
        "armedBgColor_override"             "Blank"
        "depressedBgColor_override"         "Blank"
        "pin_to_sibling"                    "ExitButtonKey"
        "pin_corner_to_sibling"             "pin_center_left"
        "pin_to_sibling_corner"             "pin_center_right"
        "SubImage"	// dead
        {
            "ControlName"                   "CExImageButton"
            "fieldName"                     "SubImage"
            "xpos"                          "99999"
            "ypos"                          "99999"
            "zpos"                          "1"
            "wide"                          "0"
            "tall"                          "0"
            "visible"                       "0"
            "enabled"                       "0"
            "image"                         ""
            "scaleImage"                    "1"
            "proportionaltoparent"          "1"
        }
    }
}