"Resource/UI/Scoreboard.res"
{
    "scores"
    {
        "ControlName"                   "CTFClientScoreBoardDialog"
        "fieldName"                     "scoreinfo"
        "xpos"                          "c-300"
        "ypos"                          "0"
        "wide"                          "f0"
        "tall"                          "480"
        "visible"                       "1"
        "enabled"                       "1"
        "medal_width"                   "0"
        "medal_column_width"            "0"
        "avatar_width"                  "25"
        "spacer"                        "2"
        "name_width"                    "85"
        "nemesis_width"                 "15"
        "class_width"                   "15"
        "score_width"                   "30"
        "ping_width"                    "30"
        "killstreak_width"              "15"
        "killstreak_image_width"        "15"
    }
    // MARK: Background
    "MainBG"
    {
        "ControlName"           "ImagePanel"
        "fieldName"             "MainBG"
        "xpos"                  "0"
        "ypos"                  "0"
        "zpos"                  "-100"
        "wide"                  "f0"
        "tall"                  "480"
        "pinCorner"             "0"
        "visible"               "1"
        "enabled"               "1"
        "fillcolor"             "TransparentBlack"
        "if_mvm"
        {
            "visible"           "0"
        }
    }
    // MARK: Top Right Labels
    "MapName"
    {
        "ControlName"           "CExLabel"
        "fieldName"             "MapName"
        "font"                  "HeaderSEM_MD"
        "labelText"             "%mapname%"
        "textAlignment"         "east"
        "textinsetx"            "5"
        "xpos"                  "rs1-20"
        "ypos"                  "20"
        "zpos"                  "4"
        "wide"                  "116"
        "tall"                  "16"
        "autoResize"            "0"
        "pinCorner"             "0"
        "visible"               "1"
        "enabled"               "1"
        "fgcolor"               "White"
        "if_mvm"
        {
            "visible"           "0"
        }
    }
    "MapNameShadow"
    {
        "ControlName"           "CExLabel"
        "fieldName"             "MapNameShadow"
        "font"                  "HeaderSEm_MD_Blur"
        "labelText"             "%mapname%"
        "textAlignment"         "east"
        "textinsetx"            "5"
        "xpos"                  "0"
        "ypos"                  "0"
        "zpos"                  "4"
        "wide"                  "116"
        "tall"                  "16"
        "autoResize"            "0"
        "pinCorner"             "0"
        "visible"               "1"
        "enabled"               "1"
        "fgcolor"               "Shadow"
        "pin_to_sibling"        "MapName"
        "if_mvm"
        {
            "visible"           "0"
        }
    }
    "ServerLabel"
    {
        "ControlName"                   "CExLabel"
        "fieldName"                     "ServerLabel"
        "font"                          "Header_XS"
        "AllCaps"                       "1"
        "labelText"                     "%server%"
        "textAlignment"                 "east"
        "textinsetx"                    "5"
        "xpos"                          "0"
        "ypos"                          "0"
        "zpos"                          "999"
        "wide"                          "235"
        "tall"                          "12"
        "autoResize"                    "0"
        "pinCorner"                     "0"
        "visible"                       "1"
        "enabled"                       "1"
        "fgcolor"                       "HealthAmmo_Alt"
        "pin_to_sibling"                "MapName"
        "pin_corner_to_sibling"         "PIN_TOPRIGHT"
        "pin_to_sibling_corner"         "PIN_BOTTOMRIGHT"
        "if_mvm"
        {
            "ypos"              "28"
            "visible"           "1"
        }
    }
    "ServerTimeLeftValueReal"
    {
        "ControlName"                   "CExLabel"
        "fieldName"                     "ServerTimeLeftValueReal"
        "font"                          "Header_XS"
        "AllCaps"                       "1"
        "labelText"                     "%servertime%"
        "textAlignment"                 "east"
        "textinsetx"                    "5"
        "xpos"                          "0"
        "ypos"                          "0"
        "zpos"                          "999"
        "wide"                          "100"
        "tall"                          "12"
        "autoResize"                    "0"
        "pinCorner"                     "0"
        "visible"                       "1"
        "enabled"                       "1"
        "fgcolor"                       "HealthAmmo_Alt"
        "centerwrap"                    "0"
        "pin_to_sibling"                "ServerLabel"
        "pin_corner_to_sibling"         "PIN_TOPRIGHT"
        "pin_to_sibling_corner"         "PIN_BOTTOMRIGHT"
        "if_mvm"
        {
            "visible"           "0"
        }
    }
    // MARK: Main Scoreboard
    "ScoreboardLabel"
    {
        "ControlName"                   "CExLabel"
        "fieldName"                     "ScoreboardLabel"
        "font"                          "HeaderSEM_SM"
        "labelText"                     "SCOREBOARD"
        "textAlignment"                 "west"
        "textinsetx"                    "5"
        "xpos"                          "0"
        "ypos"                          "3"
        "zpos"                          "4"
        "wide"                          "368"
        "tall"                          "16"
        "autoResize"                    "0"
        "pinCorner"                     "0"
        "visible"                       "1"
        "enabled"                       "1"
        "fgcolor"                       "White"
        "pin_to_sibling"                "BlueTeamBG"
        "pin_corner_to_sibling"         "PIN_BOTTOMLEFT"
        "pin_to_sibling_corner"         "PIN_TOPLEFT"
        "if_mvm"
        {
            "visible"           "0"
        }
    }
    "ScoreboardLabelShadow"
    {
        "ControlName"           "CExLabel"
        "fieldName"             "ScoreboardLabelShadow"
        "font"                  "HeaderSEM_SM_Blur"
        "labelText"             "SCOREBOARD"
        "textAlignment"         "west"
        "textinsetx"            "5"
        "xpos"                  "0"
        "ypos"                  "0"
        "zpos"                  "4"
        "wide"                  "368"
        "tall"                  "16"
        "autoResize"            "0"
        "pinCorner"             "0"
        "visible"               "1"
        "enabled"               "1"
        "fgcolor"               "Shadow"
        "pin_to_sibling"        "ScoreboardLabel"
        "if_mvm"
        {
            "visible"           "0"
        }
    }
    "BlueTeamBG"
    {
        "ControlName"                   "EditablePanel"
        "fieldName"                     "BlueTeamBG"
        "xpos"                          "20"
        "ypos"                          "54"
        "zpos"                          "-99"
        "wide"                          "368"
        "tall"                          "167"
        "autoResize"                    "0"
        "pinCorner"                     "0"
        "visible"                       "1"
        "enabled"                       "1"
        "paintBackgroundType"           "2"
        "bgcolor_override"              "Blue"
        "if_mvm"
        {
            "visible"           "0"
        }
    }
    "BlueTeamLabelReal"
    {
        "ControlName"                   "CExLabel"
        "fieldName"                     "BlueTeamLabelReal"
        "font"                          "HeaderSEM_XS"
        "labelText"                     "%blueteamname%"
        "textAlignment"                 "center"
        "textinsetx"                    "5"
        "xpos"                          "0"
        "ypos"                          "-10"
        "zpos"                          "4"
        "wide"                          "70"
        "tall"                          "12"
        "autoResize"                    "0"
        "pinCorner"                     "0"
        "visible"                       "1"
        "enabled"                       "1"
        "fgcolor"                       "White"
        "pin_to_sibling"                "BlueTeamBG"
        "pin_corner_to_sibling"         "PIN_BOTTOMLEFT"
        "pin_to_sibling_corner"         "PIN_CENTER_LEFT"
        "if_mvm"
        {
            "visible"           "0"
        }
    }
    "BlueTeamLogo"
    {
        "ControlName"                   "ImagePanel"
        "FieldName"                     "BlueTeamLogo"
        "XPos"                          "0"
        "YPos"                          "0"
        "ZPos"                          "1"
        "Wide"                          "40"
        "Tall"                          "40"
        "proportionaltoparent"          "1"
        "Visible"                       "1"
        "Enabled"                       "1"
        "image"                         "replay/thumbnails/team_logo_blu_white"
        "drawcolor"                     "White"
        "scaleImage"                    "1"
        "pin_to_sibling"                "BlueTeamLabelReal"
        "pin_corner_to_sibling"         "PIN_CENTER_BOTTOM"
        "pin_to_sibling_corner"         "PIN_CENTER_TOP"
    }
    "BlueTeamScore"
    {
        "ControlName"                   "CExLabel"
        "fieldName"                     "BlueTeamScore"
        "font"                          "HeaderEM_XL"
        "labelText"                     "%blueteamscore%"
        "textAlignment"                 "center"
        "xpos"                          "0"
        "ypos"                          "20"
        "zpos"                          "10000"
        "wide"                          "70"
        "tall"                          "26"
        "autoResize"                    "0"
        "pinCorner"                     "0"
        "visible"                       "1"
        "enabled"                       "1"
        "fgcolor"                       "White"
        "pin_to_sibling"                "BlueTeamBG"
        "pin_corner_to_sibling"         "PIN_TOPLEFT"
        "pin_to_sibling_corner"         "PIN_CENTER_LEFT"
        "if_mvm"
        {
            "visible"           "0"
        }
    }
    "Divider1"
    {
        "ControlName"                   "ImagePanel"
        "fieldName"                     "Divider1"
        "xpos"                          "0"
        "ypos"                          "18"
        "zpos"                          "0"
        "wide"                          "176"
        "tall"                          "1"
        "visible"                       "1"
        "enabled"                       "1"
        "fillcolor"                     "TransparentLightestWhite"
        "scaleImage"                    "1"
        "pin_to_sibling"                "BlueTeamBG"
        "pin_corner_to_sibling"         "PIN_TOPLEFT"
        "pin_to_sibling_corner"         "PIN_BOTTOMLEFT"
    }
    "VerseLabel"
    {
        "ControlName"                   "CExLabel"
        "fieldName"                     "VerseLabel"
        "font"                          "HeaderSEm_SM"
        "labelText"                     "VS"
        "textAlignment"                 "center"
        "xpos"                          "0"
        "ypos"                          "12"
        "zpos"                          "3"
        "wide"                          "50"
        "tall"                          "13"
        "autoResize"                    "0"
        "pinCorner"                     "0"
        "visible"                       "1"
        "enabled"                       "1"
        "fgcolor"                       "255 255 255 180"
        "pin_to_sibling"                "BlueTeamBG"
        "pin_corner_to_sibling"         "PIN_CENTER_TOP"
        "pin_to_sibling_corner"         "PIN_CENTER_BOTTOM"
        "if_mvm"
        {
            "visible"           "0"
        }
    }
    "VerseLabelBlur"
    {
        "ControlName"           "CExLabel"
        "fieldName"             "VerseLabelBlur"
        "font"                  "HeaderSEm_SM_Blur"
        "labelText"             "VS"
        "textAlignment"         "center"
        "xpos"                  "0"
        "ypos"                  "0"
        "zpos"                  "3"
        "wide"                  "50"
        "tall"                  "13"
        "autoResize"            "0"
        "pinCorner"             "0"
        "visible"               "1"
        "enabled"               "1"
        "fgcolor"               "Shadow"
        "pin_to_sibling"        "VerseLabel"
        "if_mvm"
        {
            "visible"           "0"
        }
    }
    "Divider2"
    {
        "ControlName"                   "ImagePanel"
        "fieldName"                     "Divider2"
        "xpos"                          "0"
        "ypos"                          "18"
        "zpos"                          "0"
        "wide"                          "175"
        "tall"                          "1"
        "visible"                       "1"
        "enabled"                       "1"
        "fillcolor"                     "TransparentLightestWhite"
        "scaleImage"                    "1"
        "pin_to_sibling"                "BlueTeamBG"
        "pin_corner_to_sibling"         "PIN_TOPRIGHT"
        "pin_to_sibling_corner"         "PIN_BOTTOMRIGHT"
    }
    "RedTeamBG"
    {
        "ControlName"                   "EditablePanel"
        "fieldName"                     "RedTeamBG"
        "xpos"                          "0"
        "ypos"                          "18"
        "zpos"                          "-99"
        "wide"                          "368"
        "tall"                          "167"
        "autoResize"                    "0"
        "pinCorner"                     "0"
        "visible"                       "1"
        "enabled"                       "1"
        "paintBackgroundType"           "2"
        "bgcolor_override"              "Red"
        "pin_to_sibling"                "Divider1"
        "pin_corner_to_sibling"         "PIN_TOPLEFT"
        "pin_to_sibling_corner"         "PIN_BOTTOMLEFT"
        "if_mvm"
        {
            "visible"           "0"
        }
    }
    "RedTeamLabelReal"
    {
        "ControlName"                   "CExLabel"
        "fieldName"                     "RedTeamLabelReal"
        "font"                          "HeaderSEM_XS"
        "labelText"                     "%redteamname%"
        "textAlignment"                 "center"
        "textinsetx"                    "5"
        "xpos"                          "0"
        "ypos"                          "-10"
        "zpos"                          "4"
        "wide"                          "70"
        "tall"                          "12"
        "autoResize"                    "0"
        "pinCorner"                     "0"
        "visible"                       "1"
        "enabled"                       "1"
        "fgcolor"                       "White"
        "pin_to_sibling"                "RedTeamBG"
        "pin_corner_to_sibling"         "PIN_BOTTOMLEFT"
        "pin_to_sibling_corner"         "PIN_CENTER_LEFT"
        "if_mvm"
        {
            "visible"           "0"
        }
    }
    "RedTeamLogo"
    {
        "ControlName"                   "ImagePanel"
        "FieldName"                     "RedTeamLogo"
        "XPos"                          "-3"
        "YPos"                          "4"
        "ZPos"                          "1"
        "Wide"                          "38"
        "Tall"                          "38"
        "proportionaltoparent"          "1"
        "Visible"                       "1"
        "Enabled"                       "1"
        "image"                         "replay/thumbnails/team_logo_red_white"
        "drawcolor"                     "White"
        "scaleImage"                    "1"
        "pin_to_sibling"                "RedTeamLabelReal"
        "pin_corner_to_sibling"         "PIN_CENTER_BOTTOM"
        "pin_to_sibling_corner"         "PIN_CENTER_TOP"
    }
    "RedTeamScore"
    {
        "ControlName"                   "CExLabel"
        "fieldName"                     "RedTeamScore"
        "font"                          "HeaderEM_XL"
        "labelText"                     "%redteamscore%"
        "textAlignment"                 "center"
        "xpos"                          "0"
        "ypos"                          "20"
        "zpos"                          "10000"
        "wide"                          "70"
        "tall"                          "26"
        "autoResize"                    "0"
        "pinCorner"                     "0"
        "visible"                       "1"
        "enabled"                       "1"
        "fgcolor"                       "White"
        "pin_to_sibling"                "RedTeamBG"
        "pin_corner_to_sibling"         "PIN_TOPLEFT"
        "pin_to_sibling_corner"         "PIN_CENTER_LEFT"
        "if_mvm"
        {
            "visible"           "0"
        }
    }
    "BluePlayerList"
    {
        "ControlName"                   "SectionedListPanel"
        "fieldName"                     "BluePlayerList"
        "xpos"                          "0"
        "ypos"                          "17"
        "zpos"                          "20"
        "wide"                          "300"
        "tall"                          "183"
        "pinCorner"                     "0"
        "visible"                       "1"
        "enabled"                       "1"
        "tabPosition"                   "0"
        "autoresize"                    "3"
        "linespacing"                   "13"
        "linegap"                       "1"
        "fgcolor"                       "blue"
        "pin_to_sibling"                "BlueTeamBG"
        "pin_corner_to_sibling"         "PIN_TOPRIGHT"
        "pin_to_sibling_corner"         "PIN_TOPRIGHT"
        //"show_columns"	"1"
        "if_mvm"
        {
            "visible"           "0"
        }
    }
    "RedPlayerList"
    {
        "ControlName"                   "SectionedListPanel"
        "fieldName"                     "RedPlayerList"
        "xpos"                          "0"
        "ypos"                          "17"
        "zpos"                          "20"
        "wide"                          "300"
        "tall"                          "183"
        "pinCorner"                     "0"
        "visible"                       "1"
        "enabled"                       "1"
        "tabPosition"                   "0"
        "autoresize"                    "3"
        "linespacing"                   "13"
        "linegap"                       "1"
        "fgcolor"                       "red"
        "pin_to_sibling"                "RedTeamBG"
        "pin_corner_to_sibling"         "PIN_TOPRIGHT"
        "pin_to_sibling_corner"         "PIN_TOPRIGHT"
        //"show_columns"	"1"
        "if_mvm"
        {
            "visible"           "0"
        }
    }
    "Spectators"
    {
        "ControlName"                   "CExLabel"
        "fieldName"                     "Spectators"
        "font"                          "BodyEM_XS"
        "labelText"                     "%spectators%"
        "textAlignment"                 "west"
        "textinsetx"                    "5"
        "xpos"                          "0"
        "ypos"                          "0"
        "zpos"                          "4"
        "wide"                          "560"
        "tall"                          "12"
        "autoResize"                    "0"
        "pinCorner"                     "0"
        "visible"                       "1"
        "enabled"                       "1"
        "fgcolor"                       "HealthAmmo_Alt"
        "pin_to_sibling"                "RedTeamBG"
        "pin_corner_to_sibling"         "PIN_TOPLEFT"
        "pin_to_sibling_corner"         "PIN_BOTTOMLEFT"
        "if_mvm"
        {
            "xpos"          "c-280"
            "ypos"          "356"
        }
    }
    "SpectatorsShadow"
    {
        "ControlName"           "CExLabel"
        "fieldName"             "SpectatorsShadow"
        "font"                  "BodyEM_XS_Blur"
        "labelText"             "%spectators%"
        "textAlignment"         "west"
        "textinsetx"            "5"
        "xpos"                  "0"
        "ypos"                  "0"
        "zpos"                  "4"
        "wide"                  "560"
        "tall"                  "12"
        "autoResize"            "0"
        "pinCorner"             "0"
        "visible"               "1"
        "enabled"               "1"
        "fgcolor"               "Shadow"
        "pin_to_sibling"        "Spectators"
    }
    "SpectatorsInQueue"
    {
        "ControlName"                   "CExLabel"
        "fieldName"                     "SpectatorsInQueue"
        "font"                          "BodyEM_XS"
        "labelText"                     "%waitingtoplay%"
        "textAlignment"                 "west"
        "textinsetx"                    "5"
        "xpos"                          "0"
        "ypos"                          "0"
        "zpos"                          "4"
        "wide"                          "560"
        "tall"                          "12"
        "autoResize"                    "0"
        "pinCorner"                     "0"
        "visible"                       "1"
        "enabled"                       "1"
        "fgcolor"                       "White"
        "pin_to_sibling"                "Spectators"
        "pin_corner_to_sibling"         "PIN_TOPLEFT"
        "pin_to_sibling_corner"         "PIN_BOTTOMLEFT"
        "if_mvm"
        {
            "visible"           "0"
        }
    }
    // MARK: Player Stats
    "StatsLabel"
    {
        "ControlName"                   "CExLabel"
        "fieldName"                     "StatsLabel"
        "font"                          "HeaderSEM_SM"
        "labelText"                     "PERFORMANCE"
        "textAlignment"                 "west"
        "textinsetx"                    "5"
        "xpos"                          "12"
        "ypos"                          "0"
        "zpos"                          "4"
        "wide"                          "368"
        "tall"                          "16"
        "autoResize"                    "0"
        "pinCorner"                     "0"
        "visible"                       "1"
        "enabled"                       "1"
        "fgcolor"                       "White"
        "pin_to_sibling"                "ScoreboardLabel"
        "pin_corner_to_sibling"         "PIN_BOTTOMLEFT"
        "pin_to_sibling_corner"         "PIN_BOTTOMRIGHT"
        "if_mvm"
        {
            "visible"           "0"
        }
    }
    "StatsLabelShadow"
    {
        "ControlName"           "CExLabel"
        "fieldName"             "StatsLabelShadow"
        "font"                  "HeaderSEM_SM_Blur"
        "labelText"             "PERFORMANCE"
        "textAlignment"         "west"
        "textinsetx"            "5"
        "xpos"                  "0"
        "ypos"                  "0"
        "zpos"                  "4"
        "wide"                  "368"
        "tall"                  "16"
        "autoResize"            "0"
        "pinCorner"             "0"
        "visible"               "1"
        "enabled"               "1"
        "fgcolor"               "Shadow"
        "pin_to_sibling"        "StatsLabel"
        "if_mvm"
        {
            "visible"           "0"
        }
    }
    "LocalPlayerStatsPanel"
    {
        "ControlName"                   "EditablePanel"
        "fieldName"                     "LocalPlayerStatsPanel"
        "xpos"                          "0"
        "ypos"                          "3"
        "zpos"                          "3"
        "wide"                          "150"
        "tall"                          "167"
        "autoResize"                    "0"
        "pinCorner"                     "0"
        "visible"                       "1"
        "enabled"                       "1"
        "pin_to_sibling"                "StatsLabel"
        "pin_corner_to_sibling"         "PIN_TOPLEFT"
        "pin_to_sibling_corner"         "PIN_BOTTOMLEFT"
        "StatsPanelBG"	// dead
        {
            "ControlName"                   "EditablePanel"
            "fieldName"                     "StatsPanelBG"
            "xpos"                          "99999"
            "ypos"                          "99999"
            "zpos"                          "0"
            "wide"                          "0"
            "tall"                          "0"
            "proportionaltoparent"          "1"
            "visible"                       "0"
            "enabled"                       "0"
            "paintBackground"               "1"
            "paintBackgroundType"           "2"
            "roundedCorners"                "15"
            "bgcolor_override"              "Blank"
            "if_mvm"
            {
                "visible"           "0"
            }
        }
        "StatsPanelBGReal"
        {
            "ControlName"                   "EditablePanel"
            "fieldName"                     "StatsPanelBGReal"
            "xpos"                          "0"
            "ypos"                          "0"
            "zpos"                          "0"
            "wide"                          "f0"
            "tall"                          "f0"
            "proportionaltoparent"          "1"
            "visible"                       "1"
            "enabled"                       "1"
            "paintBackground"               "1"
            "paintBackgroundType"           "2"
            "roundedCorners"                "15"
            "bgcolor_override"              "TransparentLightBlack"
            "if_mvm"
            {
                "visible"           "0"
            }
        }
        "KillsLabel"
        {
            "ControlName"           "CExLabel"
            "fieldName"             "KillsLabel"
            "font"                  "Body_SM"
            "labelText"             "Eliminations"
            "textAlignment"         "west"
            "xpos"                  "10"
            "ypos"                  "5"
            "zpos"                  "3"
            "wide"                  "116"
            "tall"                  "14"
            "autoResize"            "0"
            "pinCorner"             "0"
            "visible"               "1"
            "enabled"               "1"
            "fgcolor"               "White"
        }
        "KillsReal"
        {
            "ControlName"                   "CExLabel"
            "fieldName"                     "KillsReal"
            "font"                          "BodyEm_LG"
            "labelText"                     "%kills%"
            "textAlignment"                 "west"
            "xpos"                          "0"
            "ypos"                          "0"
            "zpos"                          "3"
            "wide"                          "50"
            "tall"                          "14"
            "autoResize"                    "0"
            "pinCorner"                     "0"
            "visible"                       "1"
            "enabled"                       "1"
            "fgcolor"                       "White"
            "pin_to_sibling"                "KillsLabel"
            "pin_corner_to_sibling"         "PIN_TOPLEFT"
            "pin_to_sibling_corner"         "PIN_BOTTOMLEFT"
        }
        "AssistsLabel"
        {
            "ControlName"                   "CExLabel"
            "fieldName"                     "AssistsLabel"
            "font"                          "Body_SM"
            "labelText"                     "Assists"
            "textAlignment"                 "west"
            "xpos"                          "0"
            "ypos"                          "5"
            "zpos"                          "3"
            "wide"                          "116"
            "tall"                          "14"
            "autoResize"                    "0"
            "pinCorner"                     "0"
            "visible"                       "1"
            "enabled"                       "1"
            "fgcolor"                       "White"
            "pin_to_sibling"                "KillsReal"
            "pin_corner_to_sibling"         "PIN_TOPLEFT"
            "pin_to_sibling_corner"         "PIN_BOTTOMLEFT"
        }
        "AssistsReal"
        {
            "ControlName"                   "CExLabel"
            "fieldName"                     "AssistsReal"
            "font"                          "BodyEm_LG"
            "labelText"                     "%assists%"
            "textAlignment"                 "west"
            "xpos"                          "0"
            "ypos"                          "0"
            "zpos"                          "3"
            "wide"                          "50"
            "tall"                          "14"
            "autoResize"                    "0"
            "pinCorner"                     "0"
            "visible"                       "1"
            "enabled"                       "1"
            "fgcolor"                       "White"
            "pin_to_sibling"                "AssistsLabel"
            "pin_corner_to_sibling"         "PIN_TOPLEFT"
            "pin_to_sibling_corner"         "PIN_BOTTOMLEFT"
        }
        "DeathsLabel"
        {
            "ControlName"                   "CExLabel"
            "fieldName"                     "DeathsLabel"
            "font"                          "Body_SM"
            "labelText"                     "Deaths"
            "textAlignment"                 "west"
            "xpos"                          "0"
            "ypos"                          "5"
            "zpos"                          "3"
            "wide"                          "116"
            "tall"                          "14"
            "autoResize"                    "0"
            "pinCorner"                     "0"
            "visible"                       "1"
            "enabled"                       "1"
            "fgcolor"                       "White"
            "pin_to_sibling"                "AssistsReal"
            "pin_corner_to_sibling"         "PIN_TOPLEFT"
            "pin_to_sibling_corner"         "PIN_BOTTOMLEFT"
        }
        "DeathsReal"
        {
            "ControlName"                   "CExLabel"
            "fieldName"                     "DeathsReal"
            "font"                          "BodyEm_LG"
            "labelText"                     "%deaths%"
            "textAlignment"                 "west"
            "xpos"                          "0"
            "ypos"                          "0"
            "zpos"                          "3"
            "wide"                          "50"
            "tall"                          "14"
            "autoResize"                    "0"
            "pinCorner"                     "0"
            "visible"                       "1"
            "enabled"                       "1"
            "fgcolor"                       "White"
            "pin_to_sibling"                "DeathsLabel"
            "pin_corner_to_sibling"         "PIN_TOPLEFT"
            "pin_to_sibling_corner"         "PIN_BOTTOMLEFT"
        }
        "DamageLabel"
        {
            "ControlName"                   "CExLabel"
            "fieldName"                     "DamageLabel"
            "font"                          "Body_SM"
            "labelText"                     "Combat"
            "textAlignment"                 "west"
            "xpos"                          "0"
            "ypos"                          "5"
            "zpos"                          "3"
            "wide"                          "116"
            "tall"                          "14"
            "autoResize"                    "0"
            "pinCorner"                     "0"
            "visible"                       "1"
            "enabled"                       "1"
            "fgcolor"                       "White"
            "pin_to_sibling"                "DeathsReal"
            "pin_corner_to_sibling"         "PIN_TOPLEFT"
            "pin_to_sibling_corner"         "PIN_BOTTOMLEFT"
        }
        "DamageReal"
        {
            "ControlName"                   "CExLabel"
            "fieldName"                     "DamageReal"
            "font"                          "BodyEm_LG"
            "labelText"                     "%damage%"
            "textAlignment"                 "west"
            "xpos"                          "0"
            "ypos"                          "0"
            "zpos"                          "3"
            "wide"                          "50"
            "tall"                          "14"
            "autoResize"                    "0"
            "pinCorner"                     "0"
            "visible"                       "1"
            "enabled"                       "1"
            "fgcolor"                       "White"
            "pin_to_sibling"                "DamageLabel"
            "pin_corner_to_sibling"         "PIN_TOPLEFT"
            "pin_to_sibling_corner"         "PIN_BOTTOMLEFT"
        }
        "HealingLabel"
        {
            "ControlName"                   "CExLabel"
            "fieldName"                     "HealingLabel"
            "font"                          "Body_SM"
            "labelText"                     "Support"
            "textAlignment"                 "west"
            "xpos"                          "0"
            "ypos"                          "5"
            "zpos"                          "3"
            "wide"                          "116"
            "tall"                          "14"
            "autoResize"                    "0"
            "pinCorner"                     "0"
            "visible"                       "1"
            "enabled"                       "1"
            "fgcolor"                       "White"
            "pin_to_sibling"                "DamageReal"
            "pin_corner_to_sibling"         "PIN_TOPLEFT"
            "pin_to_sibling_corner"         "PIN_BOTTOMLEFT"
        }
        "HealingReal"
        {
            "ControlName"                   "CExLabel"
            "fieldName"                     "HealingReal"
            "font"                          "BodyEm_LG"
            "labelText"                     "%healing%"
            "textAlignment"                 "west"
            "xpos"                          "0"
            "ypos"                          "0"
            "zpos"                          "3"
            "wide"                          "50"
            "tall"                          "14"
            "autoResize"                    "0"
            "pinCorner"                     "0"
            "visible"                       "1"
            "enabled"                       "1"
            "fgcolor"                       "White"
            "pin_to_sibling"                "HealingLabel"
            "pin_corner_to_sibling"         "PIN_TOPLEFT"
            "pin_to_sibling_corner"         "PIN_BOTTOMLEFT"
        }
        "Kills"	// unused
        {
            "ControlName"           "CExLabel"
            "fieldName"             "Kills"
            "font"                  "Nim28"
            "labelText"             "%kills%"
            "textAlignment"         "east"
            "xpos"                  "10"
            "ypos"                  "1"
            "zpos"                  "3"
            "wide"                  "50"
            "tall"                  "55"
            "autoResize"            "0"
            "pinCorner"             "0"
            "visible"               "0"
            "enabled"               "0"
            "fgcolor"               "White"
            "if_mvm"
            {
                "visible"           "0"
                "fgcolor"           "owBLACK"
            }
        }
        "Deaths"	// unused
        {
            "ControlName"           "CExLabel"
            "fieldName"             "Deaths"
            "font"                  "Nim28"
            "labelText"             "%deaths%"
            "textAlignment"         "west"
            "xpos"                  "10"
            "ypos"                  "1"
            "zpos"                  "3"
            "wide"                  "50"
            "tall"                  "55"
            "autoResize"            "0"
            "pinCorner"             "0"
            "visible"               "0"
            "enabled"               "0"
            "fgcolor"               "White"
            "if_mvm"
            {
                "visible"           "0"
                "fgcolor"           "owBLACK"
            }
        }
        "GameType"	// dead
        {
            "ControlName"           "CExLabel"
            "fieldName"             "GameType"
            "font"                  "ScoreboardVerySmall"
            "labelText"             "%gametype%"	// %gametype%
            "textAlignment"         "west"
            "xpos"                  "99999"
            "ypos"                  "99999"
            "zpos"                  "3"
            "wide"                  "0"
            "tall"                  "0"
            "autoResize"            "0"
            "pinCorner"             "0"
            "visible"               "1"
            "enabled"               "1"
            "fgcolor"               "Blank"
        }
        "Assists"	// dead
        {
            "ControlName"           "CExLabel"
            "fieldName"             "Assists"
            "font"                  "DinBold11"
            "labelText"             "%assists%"
            "textAlignment"         "west"
            "xpos"                  "36"
            "ypos"                  "42"
            "zpos"                  "3"
            "wide"                  "35"
            "tall"                  "20"
            "autoResize"            "0"
            "pinCorner"             "0"
            "visible"               "0"
            "enabled"               "0"
            "fgcolor"               "White"
        }
        "Destruction"	// dead
        {
            "ControlName"           "CExLabel"
            "fieldName"             "Destruction"
            "font"                  "Nim10"
            "labelText"             "%destruction%"
            "textAlignment"         "east"
            "xpos"                  "181"
            "ypos"                  "13"
            "zpos"                  "3"
            "wide"                  "35"
            "tall"                  "20"
            "autoResize"            "0"
            "pinCorner"             "0"
            "visible"               "0"
            "enabled"               "0"
            "fgcolor"               "White"
        }
        "CapturesLabel"	// dead
        {
            "ControlName"           "CExLabel"
            "fieldName"             "CapturesLabel"
            "font"                  "Nim10"
            "labelText"             "#TF_ScoreBoard_CapturesLabel"
            "textAlignment"         "west"
            "xpos"                  "99999"
            "ypos"                  "99999"
            "zpos"                  "3"
            "wide"                  "0"
            "tall"                  "0"
            "autoResize"            "0"
            "pinCorner"             "0"
            "visible"               "0"
            "enabled"               "0"
        }
        "DefensesLabel"
        {
            "ControlName"           "CExLabel"
            "fieldName"             "DefensesLabel"
            "font"                  "Nim10"
            "labelText"             "#TF_ScoreBoard_DefensesLabel"
            "textAlignment"         "west"
            "xpos"                  "99999"
            "ypos"                  "99999"
            "zpos"                  "3"
            "wide"                  "0"
            "tall"                  "0"
            "autoResize"            "0"
            "pinCorner"             "0"
            "visible"               "0"
            "enabled"               "0"
        }
        "DominationLabel"
        {
            "ControlName"           "CExLabel"
            "fieldName"             "DominationLabel"
            "font"                  "Nim10"
            "labelText"             "#TF_ScoreBoard_DominationLabel"
            "textAlignment"         "west"
            "xpos"                  "99999"
            "ypos"                  "99999"
            "zpos"                  "3"
            "wide"                  "0"
            "tall"                  "0"
            "autoResize"            "0"
            "pinCorner"             "0"
            "visible"               "0"
            "enabled"               "0"
        }
        "RevengeLabel"
        {
            "ControlName"           "CExLabel"
            "fieldName"             "RevengeLabel"
            "font"                  "Nim10"
            "labelText"             "#TF_ScoreBoard_RevengeLabel"
            "textAlignment"         "west"
            "xpos"                  "99999"
            "ypos"                  "99999"
            "zpos"                  "3"
            "wide"                  "0"
            "tall"                  "0"
            "autoResize"            "0"
            "pinCorner"             "0"
            "visible"               "0"
            "enabled"               "0"
        }
        "Captures"
        {
            "ControlName"           "CExLabel"
            "fieldName"             "Captures"
            "font"                  "Nim10"
            "labelText"             "%captures%"
            "textAlignment"         "east"
            "xpos"                  "99999"
            "ypos"                  "99999"
            "zpos"                  "3"
            "wide"                  "0"
            "tall"                  "0"
            "autoResize"            "0"
            "pinCorner"             "0"
            "visible"               "0"
            "enabled"               "0"
        }
        "Captures2"
        {
            "ControlName"           "CExLabel"
            "fieldName"             "Captures2"
            "font"                  "Nim10"
            "labelText"             "%captures%"
            "textAlignment"         "east"
            "xpos"                  "99999"
            "ypos"                  "99999"
            "zpos"                  "3"
            "wide"                  "0"
            "tall"                  "0"
            "autoResize"            "0"
            "pinCorner"             "0"
            "visible"               "0"
            "enabled"               "0"
        }
        "Defenses"
        {
            "ControlName"           "CExLabel"
            "fieldName"             "Defenses"
            "font"                  "Nim10"
            "labelText"             "%defenses%"
            "textAlignment"         "east"
            "xpos"                  "181"
            "ypos"                  "33"
            "zpos"                  "3"
            "wide"                  "35"
            "tall"                  "20"
            "autoResize"            "0"
            "pinCorner"             "0"
            "visible"               "0"
            "enabled"               "0"
            "fgcolor"               "White"
            "if_mvm"
            {
                "visible"           "0"
                "fgcolor"           "owBLACK"
            }
        }
        "Defenses2"
        {
            "ControlName"           "CExLabel"
            "fieldName"             "Defenses2"
            "font"                  "Nim10"
            "labelText"             "%defenses%"
            "textAlignment"         "east"
            "xpos"                  "99999"
            "ypos"                  "99999"
            "zpos"                  "3"
            "wide"                  "0"
            "tall"                  "0"
            "autoResize"            "0"
            "pinCorner"             "0"
            "visible"               "0"
            "enabled"               "0"
        }
        "Domination"
        {
            "ControlName"           "CExLabel"
            "fieldName"             "Domination"
            "font"                  "Nim10"
            "labelText"             "%dominations%"
            "textAlignment"         "east"
            "xpos"                  "99999"
            "ypos"                  "99999"
            "zpos"                  "3"
            "wide"                  "0"
            "tall"                  "0"
            "autoResize"            "0"
            "pinCorner"             "0"
            "visible"               "0"
            "enabled"               "0"
        }
        "Domination2"
        {
            "ControlName"           "CExLabel"
            "fieldName"             "Domination2"
            "font"                  "Nim10"
            "labelText"             "%dominations%"
            "textAlignment"         "east"
            "xpos"                  "99999"
            "ypos"                  "99999"
            "zpos"                  "3"
            "wide"                  "0"
            "tall"                  "0"
            "autoResize"            "0"
            "pinCorner"             "0"
            "visible"               "0"
            "enabled"               "0"
        }
        "Revenge"
        {
            "ControlName"           "CExLabel"
            "fieldName"             "Revenge"
            "font"                  "Nim10"
            "labelText"             "%Revenge%"
            "textAlignment"         "east"
            "xpos"                  "99999"
            "ypos"                  "99999"
            "zpos"                  "3"
            "wide"                  "0"
            "tall"                  "0"
            "autoResize"            "0"
            "pinCorner"             "0"
            "visible"               "0"
            "enabled"               "0"
        }
        "Revenge2"
        {
            "ControlName"           "CExLabel"
            "fieldName"             "Revenge2"
            "font"                  "Nim10"
            "labelText"             "%Revenge%"
            "textAlignment"         "east"
            "xpos"                  "99999"
            "ypos"                  "99999"
            "zpos"                  "3"
            "wide"                  "0"
            "tall"                  "0"
            "autoResize"            "0"
            "pinCorner"             "0"
            "visible"               "0"
            "enabled"               "0"
        }
        "HealingLabel2"
        {
            "ControlName"           "CExLabel"
            "fieldName"             "HealingLabel2"
            "font"                  "DinMedium9"
            "labelText"             "HEALS"
            "textAlignment"         "west"
            "xpos"                  "99999"
            "ypos"                  "99999"
            "zpos"                  "3"
            "wide"                  "0"
            "tall"                  "0"
            "autoResize"            "0"
            "pinCorner"             "0"
            "visible"               "0"
            "enabled"               "0"
        }
        "InvulnLabel2"
        {
            "ControlName"           "CExLabel"
            "fieldName"             "InvulnLabel2"
            "font"                  "DinMedium9"
            "labelText"             "UBERS"
            "textAlignment"         "west"
            "xpos"                  "99999"
            "ypos"                  "99999"
            "zpos"                  "3"
            "wide"                  "0"
            "tall"                  "0"
            "autoResize"            "0"
            "pinCorner"             "0"
            "visible"               "0"
            "enabled"               "0"
        }
        "TeleportsLabel"
        {
            "ControlName"           "CExLabel"
            "fieldName"             "TeleportsLabel"
            "font"                  "Nim10"
            "labelText"             "#TF_ScoreBoard_TeleportsLabel"
            "textAlignment"         "west"
            "xpos"                  "99999"
            "ypos"                  "99999"
            "zpos"                  "3"
            "wide"                  "0"
            "tall"                  "0"
            "autoResize"            "0"
            "pinCorner"             "0"
            "visible"               "0"
            "enabled"               "0"
        }
        "HeadshotsLabel"
        {
            "ControlName"           "CExLabel"
            "fieldName"             "HeadshotsLabel"
            "font"                  "DinMedium9"
            "labelText"             "HEADSHOTS"
            "textAlignment"         "west"
            "xpos"                  "99999"
            "ypos"                  "99999"
            "zpos"                  "3"
            "wide"                  "0"
            "tall"                  "0"
            "autoResize"            "0"
            "pinCorner"             "0"
            "visible"               "0"
            "enabled"               "0"
        }
        "Healing"	// dead
        {
            "ControlName"           "CExLabel"
            "fieldName"             "Healing"
            "font"                  "DinMedium10"
            "labelText"             "%healing%"
            "textAlignment"         "west"
            "xpos"                  "99999"
            "ypos"                  "99999"
            "zpos"                  "3"
            "wide"                  "0"
            "tall"                  "0"
            "autoResize"            "0"
            "pinCorner"             "0"
            "visible"               "0"
            "enabled"               "0"
        }
        "Invuln"
        {
            "ControlName"           "CExLabel"
            "fieldName"             "Invuln"
            "font"                  "DinBold11"
            "labelText"             "%invulns%"
            "textAlignment"         "east"
            "xpos"                  "99999"
            "ypos"                  "99999"
            "zpos"                  "3"
            "wide"                  "0"
            "tall"                  "0"
            "autoResize"            "0"
            "pinCorner"             "0"
            "visible"               "0"
            "enabled"               "0"
        }
        "Invuln2"
        {
            "ControlName"           "CExLabel"
            "fieldName"             "Invuln2"
            "font"                  "DinBold11"
            "labelText"             "%invulns%"
            "textAlignment"         "east"
            "xpos"                  "99999"
            "ypos"                  "99999"
            "zpos"                  "3"
            "wide"                  "0"
            "tall"                  "0"
            "autoResize"            "0"
            "pinCorner"             "0"
            "visible"               "0"
            "enabled"               "0"
        }
        "Teleports"
        {
            "ControlName"           "CExLabel"
            "fieldName"             "Teleports"
            "font"                  "DinMedium10"
            "labelText"             "%teleports%"
            "textAlignment"         "east"
            "xpos"                  "99999"
            "ypos"                  "99999"
            "zpos"                  "3"
            "wide"                  "0"
            "tall"                  "0"
            "autoResize"            "0"
            "pinCorner"             "0"
            "visible"               "0"
            "enabled"               "0"
        }
        "Teleports2"
        {
            "ControlName"           "CExLabel"
            "fieldName"             "Teleports2"
            "font"                  "DinMedium10"
            "labelText"             "%teleports%"
            "textAlignment"         "east"
            "xpos"                  "99999"
            "ypos"                  "99999"
            "zpos"                  "3"
            "wide"                  "0"
            "tall"                  "0"
            "autoResize"            "0"
            "pinCorner"             "0"
            "visible"               "0"
            "enabled"               "0"
        }
        "Headshots"
        {
            "ControlName"           "CExLabel"
            "fieldName"             "Headshots"
            "font"                  "DinBold11"
            "labelText"             "%headshots%"
            "textAlignment"         "east"
            "xpos"                  "99999"
            "ypos"                  "99999"
            "zpos"                  "3"
            "wide"                  "0"
            "tall"                  "0"
            "autoResize"            "0"
            "pinCorner"             "0"
            "visible"               "0"
            "enabled"               "0"
        }
        "Headshots2"
        {
            "ControlName"           "CExLabel"
            "fieldName"             "Headshots2"
            "font"                  "DinBold11"
            "labelText"             "%headshots%"
            "textAlignment"         "west"
            "xpos"                  "99999"
            "ypos"                  "99999"
            "zpos"                  "3"
            "wide"                  "0"
            "tall"                  "0"
            "autoResize"            "0"
            "pinCorner"             "0"
            "visible"               "0"
            "enabled"               "0"
        }
        "BackstabsLabel"
        {
            "ControlName"           "CExLabel"
            "fieldName"             "BackstabsLabel"
            "font"                  "DinMedium9"
            "labelText"             "STABS"
            "textAlignment"         "west"
            "xpos"                  "99999"
            "ypos"                  "99999"
            "zpos"                  "3"
            "wide"                  "0"
            "tall"                  "0"
            "autoResize"            "0"
            "pinCorner"             "0"
            "visible"               "0"
            "enabled"               "0"
        }
        "Backstabs"
        {
            "ControlName"           "CExLabel"
            "fieldName"             "Backstabs"
            "font"                  "DinBold11"
            "labelText"             "%backstabs%"
            "textAlignment"         "east"
            "xpos"                  "99999"
            "ypos"                  "99999"
            "zpos"                  "3"
            "wide"                  "0"
            "tall"                  "0"
            "autoResize"            "0"
            "pinCorner"             "0"
            "visible"               "0"
            "enabled"               "0"
        }
        "Backstabs2"
        {
            "ControlName"           "CExLabel"
            "fieldName"             "Backstabs2"
            "font"                  "DinBold11"
            "labelText"             "%backstabs%"
            "textAlignment"         "east"
            "xpos"                  "99999"
            "ypos"                  "99999"
            "zpos"                  "3"
            "wide"                  "0"
            "tall"                  "0"
            "autoResize"            "0"
            "pinCorner"             "0"
            "visible"               "0"
            "enabled"               "0"
        }
        "BonusLabel"
        {
            "ControlName"           "CExLabel"
            "fieldName"             "BonusLabel"
            "font"                  "DinMedium10"
            "labelText"             "#TF_ScoreBoard_BonusLabel"
            "textAlignment"         "west"
            "xpos"                  "326"
            "ypos"                  "33"
            "zpos"                  "3"
            "wide"                  "0"
            "tall"                  "0"
            "autoResize"            "0"
            "pinCorner"             "0"
            "visible"               "1"
            "enabled"               "1"
            "fgcolor"               "White"
            "if_mvm"
            {
                "visible"           "1"
                "fgcolor"           "owBLACK"
            }
        }
        "Bonus"
        {
            "ControlName"           "CExLabel"
            "fieldName"             "Bonus"
            "font"                  "DinMedium10"
            "labelText"             "%bonus%"
            "textAlignment"         "east"
            "xpos"                  "381"
            "ypos"                  "33"
            "zpos"                  "3"
            "wide"                  "0"
            "tall"                  "0"
            "autoResize"            "0"
            "pinCorner"             "0"
            "visible"               "0"
            "enabled"               "0"
            "fgcolor"               "White"
            "if_mvm"
            {
                "visible"           "0"
                "fgcolor"           "owBLACK"
            }
        }
        "Bonus2"
        {
            "ControlName"           "CExLabel"
            "fieldName"             "Bonus2"
            "font"                  "DinMedium10"
            "labelText"             "%bonus%"
            "textAlignment"         "east"
            "xpos"                  "381"
            "ypos"                  "33"
            "zpos"                  "3"
            "wide"                  "0"
            "tall"                  "0"
            "autoResize"            "0"
            "pinCorner"             "0"
            "visible"               "1"
            "enabled"               "1"
            "fgcolor"               "White"
            "if_mvm"
            {
                "visible"           "1"
                "fgcolor"           "owBLACK"
            }
        }
        "SupportLabel"
        {
            "ControlName"           "CExLabel"
            "fieldName"             "SupportLabel"
            "font"                  "DinMedium10"
            "labelText"             "#TF_Scoreboard_Support"
            "textAlignment"         "west"
            "xpos"                  "426"
            "ypos"                  "3"
            "zpos"                  "3"
            "wide"                  "0"
            "tall"                  "0"
            "autoResize"            "0"
            "pinCorner"             "0"
            "visible"               "1"
            "enabled"               "1"
            "if_mvm"
            {
                "visible"           "1"
                "fgcolor"           "owBLACK"
            }
        }
        "Support"
        {
            "ControlName"           "CExLabel"
            "fieldName"             "Support"
            "font"                  "DinMedium10"
            "labelText"             "%support%"
            "textAlignment"         "east"
            "xpos"                  "481"
            "ypos"                  "3"
            "zpos"                  "3"
            "wide"                  "0"
            "tall"                  "0"
            "autoResize"            "0"
            "pinCorner"             "0"
            "visible"               "0"
            "enabled"               "0"
            "if_mvm"
            {
                "visible"           "0"
                "fgcolor"           "owBLACK"
            }
        }
        "Support2"
        {
            "ControlName"           "CExLabel"
            "fieldName"             "Support2"
            "font"                  "DinMedium10"
            "labelText"             "%support%"
            "textAlignment"         "east"
            "xpos"                  "481"
            "ypos"                  "3"
            "zpos"                  "3"
            "wide"                  "0"
            "tall"                  "0"
            "autoResize"            "0"
            "pinCorner"             "0"
            "visible"               "1"
            "enabled"               "1"
            "if_mvm"
            {
                "visible"           "1"
                "fgcolor"           "owBLACK"
            }
        }
        "Damage"	// dead
        {
            "ControlName"           "CExLabel"
            "fieldName"             "Damage"
            "font"                  "DinBold11"
            "labelText"             "%damage%"
            "textAlignment"         "east"
            "xpos"                  "99999"
            "ypos"                  "99999"
            "zpos"                  "3"
            "wide"                  "0"
            "tall"                  "0"
            "autoResize"            "0"
            "pinCorner"             "0"
            "visible"               "0"
            "enabled"               "0"
        }
    }
    "MvMScoreboard"
    {
        "ControlName"           "CTFHudMannVsMachineScoreboard"
        "fieldName"             "MvMScoreboard"
        "xpos"                  "0"
        "ypos"                  "5"
        "zpos"                  "10"
        "wide"                  "f0"
        "tall"                  "480"
        "visible"               "0"
        "enabled"               "1"
        "verbose"               "1"
        "if_mvm"
        {
            "visible"           "1"
        }
    }
    // MARK: Dead
    "ServerTimeLeft"	// dead
    {
        "ControlName"           "CExLabel"
        "fieldName"             "ServerTimeLeft"
        "font"                  "Oblique12"
        "labelText"             "%servertimeleft%"
        "textAlignment"         "west"
        "xpos"                  "99999"
        "ypos"                  "99999"
        "zpos"                  "999"
        "wide"                  "0"
        "tall"                  "0"
        "autoResize"            "0"
        "pinCorner"             "0"
        "visible"               "0"
        "enabled"               "0"
        "fgcolor"               "White"
        "if_mvm"
        {
            "visible"           "0"
        }
    }
    "ServerTimeLeftLabel"	// dead
    {
        "ControlName"           "CExLabel"
        "fieldName"             "ServerTimeLeftLabel"
        "font"                  "ScoreboardVerySmall"
        "labelText"             "#Scoreboard_TimeLeftLabel"
        "textAlignment"         "center"
        "xpos"                  "9999"
        "ypos"                  "9999"
        "zpos"                  "2"
        "wide"                  "0"
        "tall"                  "0"
        "autoResize"            "0"
        "pinCorner"             "0"
        "visible"               "0"
        "enabled"               "0"
        "if_mvm"
        {
            "visible"           "0"
        }
    }
    "ScoreboardBackground"	// dead
    {
        "ControlName"           "ImagePanel"
        "fieldName"             "ScoreboardBackground"
        "xpos"                  "99999"
        "ypos"                  "99999"
        "zpos"                  "-1"
        "wide"                  "0"
        "tall"                  "0"
        "pinCorner"             "0"
        "visible"               "1"
        "enabled"               "1"
        "fillcolor"             "Blank"
        "if_mvm"
        {
            "visible"           "0"
        }
    }
    "BlueLeaderAvatar"	// dead
    {
        "ControlName"           "CAvatarImagePanel"
        "fieldName"             "BlueLeaderAvatar"
        "xpos"                  "9999"
        "ypos"                  "9999"
        "zpos"                  "0"
        "wide"                  "0"
        "tall"                  "0"
        "visible"               "0"
        "enabled"               "0"
        "image"                 ""
        "scaleImage"            "1"
        "color_outline"         "Blank"
    }
    "BlueTeamPlayerCount"	// dead
    {
        "ControlName"           "CExLabel"
        "fieldName"             "BlueTeamPlayerCount"
        "font"                  "Futura9"
        "labelText"             "%blueteamplayercount%"
        "textAlignment"         "west"
        "xpos"                  "99999"
        "ypos"                  "99999"
        "zpos"                  "4"
        "wide"                  "0"
        "tall"                  "0"
        "autoResize"            "0"
        "pinCorner"             "0"
        "visible"               "0"
        "enabled"               "0"
        "fgcolor"               "White"
        "if_mvm"
        {
            "visible"           "0"
        }
    }
    "RedTeamPlayerCount"	// dead
    {
        "ControlName"           "CExLabel"
        "fieldName"             "RedTeamPlayerCount"
        "font"                  "Futura9"
        "labelText"             "%redteamplayercount%"
        "textAlignment"         "west"
        "xpos"                  "99999"
        "ypos"                  "99999"
        "zpos"                  "4"
        "wide"                  "0"
        "tall"                  "0"
        "autoResize"            "0"
        "pinCorner"             "0"
        "visible"               "0"
        "enabled"               "0"
        "fgcolor"               "White"
        "if_mvm"
        {
            "visible"           "0"
        }
    }
    "RedLeaderAvatar"	// dead
    {
        "ControlName"           "CAvatarImagePanel"
        "fieldName"             "RedLeaderAvatar"
        "xpos"                  "9999"
        "ypos"                  "9999"
        "zpos"                  "0"
        "wide"                  "0"
        "tall"                  "0"
        "visible"               "0"
        "enabled"               "0"
        "image"                 ""
        "scaleImage"            "1"
        "color_outline"         "Blank"
    }
    "VerticalLine"	// dead
    {
        "ControlName"                   "ImagePanel"
        "fieldName"                     "VerticalLine"
        "xpos"                          "9999"
        "ypos"                          "9999"
        "zpos"                          "9999"
        "wide"                          "0"
        "tall"                          "0"
        "autoResize"                    "0"
        "pinCorner"                     "0"
        "visible"                       "1"
        "enabled"                       "1"
        "tabPosition"                   "0"
        "fillcolor"                     "Blank"
        "PaintBackgroundType"           "0"
        "if_mvm"
        {
            "visible"           "0"
        }
    }
    "ServerTimeLeftValue"
    {
        "ControlName"                   "CExLabel"
        "fieldName"                     "ServerTimeLeftValue"
        "font"                          "Header_XS"
        "AllCaps"                       "1"
        "labelText"                     "%servertime%"
        "textAlignment"                 "east"
        "xpos"                          "99999"
        "ypos"                          "99999"
        "zpos"                          "999"
        "wide"                          "0"
        "tall"                          "0"
        "autoResize"                    "0"
        "pinCorner"                     "0"
        "visible"                       "1"
        "enabled"                       "1"
        "fgcolor"                       "HealthAmmo_Alt"
        "centerwrap"                    "0"
        "pin_to_sibling"                "ServerLabel"
        "pin_corner_to_sibling"         "PIN_TOPRIGHT"
        "pin_to_sibling_corner"         "PIN_BOTTOMRIGHT"
        "if_mvm"
        {
            "visible"           "0"
        }
    }
    "ClassImage"	// dead
    {
        "ControlName"           "ImagePanel"
        "fieldName"             "ClassImage"
        "xpos"                  "99999"
        "ypos"                  "99999"
        "zpos"                  "9"
        "wide"                  "0"
        "tall"                  "0"
        "visible"               "0"
        "enabled"               "0"
        "image"                 "../hud/class_scoutred"
        "scaleImage"            "1"
        "if_mvm"
        {
            "visible"           "1"
        }
    }
    "PlayerNameLabel"	// dead
    {
        "ControlName"               "CExLabel"
        "fieldName"                 "PlayerNameLabel"
        "font"                      "Oblique24"
        "labelText"                 "%playername%"
        "textAlignment"             "west"
        "xpos"                      "99999"
        "ypos"                      "99999"
        "zpos"                      "11"
        "wide"                      "0"
        "tall"                      "0"
        "autoResize"                "0"
        "pinCorner"                 "0"
        "visible"                   "0"
        "enabled"                   "0"
        "fgcolor_override"          "White"
        "if_mvm"
        {
            "visible"           "0"
        }
    }
    "classmodelpanel"	// dead
    {
        "ControlName"                   "CTFPlayerModelPanel"
        "fieldName"                     "classmodelpanel"
        "xpos"                          "99999"
        "ypos"                          "99999"
        "zpos"                          "10"
        "wide"                          "0"
        "tall"                          "0"
        "autoResize"                    "0"
        "pinCorner"                     "0"
        "visible"                       "0"
        "enabled"                       "0"
        "render_texture"                "0"
        "fov"                           "0"
        "allow_rot"                     "1"
        "disable_speak_event"           "1"
        "if_mvm"
        {
            "visible"           "0"
        }
        "model"
        {
            "force_pos"             "0"
            "angles_x"              "0"
            "angles_y"              "0"
            "angles_z"              "0"
            "origin_x"              "175"
            "origin_y"              "0"
            "origin_z"              "0"
            "frame_origin_x"        "0"
            "frame_origin_y"        "0"
            "frame_origin_z"        "0"
            "spotlight"             "1"
            "modelname"             ""
            "animation"
            {
                "name"              "PRIMARY"
                "activity"          "ACT_MP_STAND_PRIMARY"
                "default"           "1"
            }
            "animation"
            {
                "name"              "SECONDARY"
                "activity"          "ACT_MP_STAND_SECONDARY"
            }
            "animation"
            {
                "name"              "MELEE"
                "activity"          "ACT_MP_STAND_MELEE"
            }
            "animation"
            {
                "name"              "BUILDING"
                "activity"          "ACT_MP_STAND_BUILDING"
            }
            "animation"
            {
                "name"              "PDA"
                "activity"          "ACT_MP_STAND_PDA"
            }
            "animation"
            {
                "name"              "ITEM1"
                "activity"          "ACT_MP_STAND_ITEM1"
            }
            "animation"
            {
                "name"              "ITEM2"
                "activity"          "ACT_MP_STAND_ITEM2"
            }
            "animation"
            {
                "name"              "MELEE_ALLCLASS"
                "activity"          "ACT_MP_STAND_MELEE_ALLCLASS"
            }
            "animation"
            {
                "name"              "PRIMARY2"
                "activity"          "ACT_MP_STAND_PRIMARY"
            }
            "animation"
            {
                "name"              "SECONDARY2"
                "activity"          "ACT_MP_STAND_SECONDARY2"
            }
        }
        "customclassdata"
        {
            "undefined"
            {
            }
            "Scout"
            {
                "fov"               "25"
                "angles_x"          "-10"
                "angles_y"          "170"
                "angles_z"          "0"
                "origin_x"          "125"
                "origin_y"          "4"
                "origin_z"          "-82"
            }
            "Sniper"
            {
                "fov"               "25"
                "angles_x"          "-10"
                "angles_y"          "172"
                "angles_z"          "0"
                "origin_x"          "130"
                "origin_y"          "-3"
                "origin_z"          "-97"
            }
            "Soldier"
            {
                "fov"               "25"
                "angles_x"          "-10"
                "angles_y"          "170"
                "angles_z"          "0"
                "origin_x"          "145"
                "origin_y"          "-5"
                "origin_z"          "-90"
            }
            "Demoman"
            {
                "fov"               "25"
                "angles_x"          "-13"
                "angles_y"          "200"
                "angles_z"          "0"
                "origin_x"          "138"
                "origin_y"          "-4"
                "origin_z"          "-93"
            }
            "Medic"
            {
                "fov"               "20"
                "angles_x"          "-5"
                "angles_y"          "178"
                "angles_z"          "0"
                "origin_x"          "150"
                "origin_y"          "-5"
                "origin_z"          "-96"
            }
            "Heavy"
            {
                "fov"               "20"
                "angles_x"          "-5"
                "angles_y"          "200"
                "angles_z"          "0"
                "origin_x"          "200"
                "origin_y"          "0"
                "origin_z"          "-102"
            }
            "Pyro"
            {
                "fov"               "20"
                "angles_x"          "-5"
                "angles_y"          "172"
                "angles_z"          "0"
                "origin_x"          "175"
                "origin_y"          "-5"
                "origin_z"          "-90"
            }
            "Spy"
            {
                "fov"               "20"
                "angles_x"          "-5"
                "angles_y"          "160"
                "angles_z"          "0"
                "origin_x"          "160"
                "origin_y"          "0"
                "origin_z"          "-95"
            }
            "Engineer"
            {
                "fov"               "20"
                "angles_x"          "-10"
                "angles_y"          "168"
                "angles_z"          "0"
                "origin_x"          "140"
                "origin_y"          "-2"
                "origin_z"          "-82"
            }
        }
    }
    "HorizontalLine"	// dead
    {
        "ControlName"                   "ImagePanel"
        "fieldName"                     "HorizontalLine"
        "xpos"                          "9999"
        "ypos"                          "9999"
        "zpos"                          "3"
        "wide"                          "0"
        "tall"                          "0"
        "autoResize"                    "0"
        "pinCorner"                     "0"
        "visible"                       "0"
        "enabled"                       "0"
        "tabPosition"                   "0"
        "fillcolor"                     "Blank"
        "PaintBackgroundType"           "0"
        "if_mvm"
        {
            "visible"           "0"
        }
    }
    "PlayerScoreLabel"	// dead
    {
        "ControlName"           "CExLabel"
        "fieldName"             "PlayerScoreLabel"
        "font"                  "DinBold11"
        "labelText"             "%playerscore%"
        "textAlignment"         "center"
        "xpos"                  "0"
        "ypos"                  "0"
        "zpos"                  "3"
        "wide"                  "0"
        "tall"                  "0"
        "autoResize"            "0"
        "pinCorner"             "0"
        "visible"               "0"
        "enabled"               "0"
        "if_mvm"
        {
            "visible"           "0"
        }
    }
    "LocalPlayerDuelStatsPanel"	// dead
    {
        "ControlName"           "EditablePanel"
        "fieldName"             "LocalPlayerDuelStatsPanel"
        "xpos"                  "9999"
        "ypos"                  "9999"
        "zpos"                  "3"
        "wide"                  "600"
        "tall"                  "53"
        "autoResize"            "0"
        "pinCorner"             "0"
        "visible"               "0"
        "enabled"               "0"
        "if_mvm"
        {
            "visible"           "0"
        }
        "DuelingLabel"
        {
            "ControlName"           "CExLabel"
            "fieldName"             "DuelingLabel"
            "font"                  "ScoreboardSmall"
            "labelText"             "#TF_ScoreBoard_Dueling"
            "textAlignment"         "center"
            "xpos"                  "250"
            "ypos"                  "2	"
            "zpos"                  "3"
            "wide"                  "100"
            "tall"                  "20"
            "autoResize"            "0"
            "pinCorner"             "0"
            "visible"               "1"
            "enabled"               "1"
        }
        "DuelingIcon"
        {
            "ControlName"           "ImagePanel"
            "fieldName"             "DuelingIcon"
            "xpos"                  "284"
            "ypos"                  "15"
            "zpos"                  "2"
            "wide"                  "32"
            "tall"                  "32"
            "visible"               "1"
            "enabled"               "1"
            "image"                 "../backpack/player/items/crafting/icon_dueling"
            "scaleImage"            "1"
        }
        "LocalPlayerData"
        {
            "ControlName"           "EditablePanel"
            "fieldName"             "LocalPlayerData"
            "xpos"                  "75"
            "ypos"                  "0"
            "wide"                  "200"
            "tall"                  "53"
            "autoResize"            "0"
            "pinCorner"             "0"
            "visible"               "1"
            "enabled"               "1"
            "AvatarBGPanel"
            {
                "ControlName"                   "EditablePanel"
                "fieldName"                     "AvatarBGPanel"
                "xpos"                          "157"
                "ypos"                          "7"
                "zpos"                          "-1"
                "wide"                          "36"
                "tall"                          "36"
                "visible"                       "1"
                "PaintBackgroundType"           "2"
                "bgcolor_override"              "117 107 94 255"
            }
            "AvatarImage"
            {
                "ControlName"           "CAvatarImagePanel"
                "fieldName"             "AvatarImage"
                "xpos"                  "159"
                "ypos"                  "9"
                "zpos"                  "0"
                "wide"                  "32"
                "tall"                  "32"
                "visible"               "1"
                "enabled"               "1"
                "image"                 ""
                "scaleImage"            "1"
                "color_outline"         "52 48 45 255"
            }
            "AvatarTextLabel"
            {
                "ControlName"           "CExLabel"
                "fieldName"             "AvatarTextLabel"
                "fgcolor"               "White"
                "xpos"                  "50"
                "ypos"                  "7"
                "zpos"                  "2"
                "wide"                  "100"
                "tall"                  "18"
                "autoResize"            "0"
                "pinCorner"             "0"
                "visible"               "1"
                "enabled"               "1"
                "wrap"                  "0"
                "labelText"             "%playername%"
                "textAlignment"         "east"
                "font"                  "HudFontSmallest"
            }
            "Score"
            {
                "ControlName"           "CExLabel"
                "fieldName"             "Score"
                "labelText"             "%score%"
                "textAlignment"         "east"
                "xpos"                  "50"
                "ypos"                  "23"
                "zpos"                  "3"
                "wide"                  "100"
                "tall"                  "20"
                "autoResize"            "0"
                "pinCorner"             "0"
                "visible"               "1"
                "enabled"               "1"
                "font"                  "ScoreboardMedium"
            }
        }
        "OpponentData"
        {
            "ControlName"           "EditablePanel"
            "fieldName"             "OpponentData"
            "xpos"                  "325"
            "ypos"                  "0"
            "wide"                  "200"
            "tall"                  "53"
            "autoResize"            "0"
            "pinCorner"             "0"
            "visible"               "1"
            "enabled"               "1"
            "AvatarBGPanel"
            {
                "ControlName"                   "EditablePanel"
                "fieldName"                     "AvatarBGPanel"
                "xpos"                          "7"
                "ypos"                          "7"
                "zpos"                          "-1"
                "wide"                          "36"
                "tall"                          "36"
                "visible"                       "1"
                "PaintBackgroundType"           "2"
                "bgcolor_override"              "117 107 94 255"
            }
            "AvatarImage"
            {
                "ControlName"           "CAvatarImagePanel"
                "fieldName"             "AvatarImage"
                "xpos"                  "9"
                "ypos"                  "9"
                "zpos"                  "0"
                "wide"                  "32"
                "tall"                  "32"
                "visible"               "1"
                "enabled"               "1"
                "image"                 ""
                "scaleImage"            "1"
                "color_outline"         "52 48 45 255"
            }
            "AvatarTextLabel"
            {
                "ControlName"           "CExLabel"
                "fieldName"             "AvatarTextLabel"
                "fgcolor"               "White"
                "xpos"                  "50"
                "ypos"                  "7"
                "zpos"                  "2"
                "wide"                  "100"
                "tall"                  "18"
                "autoResize"            "0"
                "pinCorner"             "0"
                "visible"               "1"
                "enabled"               "1"
                "wrap"                  "0"
                "labelText"             "%playername%"
                "textAlignment"         "west"
                "font"                  "HudFontSmallest"
            }
            "Score"
            {
                "ControlName"           "CExLabel"
                "fieldName"             "Score"
                "labelText"             "%score%"
                "textAlignment"         "west"
                "xpos"                  "50"
                "ypos"                  "23"
                "zpos"                  "3"
                "wide"                  "200"
                "tall"                  "20"
                "autoResize"            "0"
                "pinCorner"             "0"
                "visible"               "1"
                "enabled"               "1"
                "font"                  "ScoreboardMedium"
            }
        }
    }
}