"Resource/UI/SpectatorGUIHealth.res"
{
    "PlayerStatusHealthImage"	// dead
    {
        "ControlName"           "ImagePanel"
        "fieldName"             "PlayerStatusHealthImage"
        "xpos"                  "99999"
        "ypos"                  "99999"
        "zpos"                  "4"
        "wide"                  "20"
        "tall"                  "20"
        "visible"               "1"
        "enabled"               "1"
        "scaleImage"            "1"
    }
    "PlayerStatusHealthImageBG"	// dead
    {
        "ControlName"           "ImagePanel"
        "fieldName"             "PlayerStatusHealthImageBG"
        "xpos"                  "99999"
        "ypos"                  "99999"
        "zpos"                  "3"
        "wide"                  "24"
        "tall"                  "24"
        "visible"               "0"
        "enabled"               "0"
        "image"                 "../hud/health_bg"
        "scaleImage"            "1"
    }
    "BuildingStatusHealthImageBG"	// dead
    {
        "ControlName"           "ImagePanel"
        "fieldName"             "BuildingStatusHealthImageBG"
        "xpos"                  "99999"
        "ypos"                  "99999"
        "zpos"                  "2"
        "wide"                  "28"
        "tall"                  "28"
        "visible"               "0"
        "enabled"               "0"
        "image"                 "../hud/health_equip_bg"
        "scaleImage"            "1"
    }
    "PlayerStatusHealthBonusImage"	// dead
    {
        "ControlName"           "ImagePanel"
        "fieldName"             "PlayerStatusHealthBonusImage"
        "xpos"                  "99999"
        "ypos"                  "99999"
        "zpos"                  "3"
        "wide"                  "24"
        "tall"                  "24"
        "visible"               "0"
        "enabled"               "1"
        "image"                 "../hud/health_over_bg"
        "scaleImage"            "1"
    }
    "PlayerStatusHealthValue"
    {
        "ControlName"           "CExLabel"
        "fieldName"             "PlayerStatusHealthValue"
        "xpos"                  "0"
        "ypos"                  "0"
        "zpos"                  "5"
        "wide"                  "20"
        "tall"                  "20"
        "visible"               "1"
        "enabled"               "1"
        "labelText"             "%Health%"
        "textAlignment"         "center"
        "font"                  "BodyEm_MD"
        "fgcolor"               "White"
        "pin_to_sibling"        "HealthBG"
    }
    "PlayerStatusHealthValueShadow"
    {
        "ControlName"           "CExLabel"
        "fieldName"             "PlayerStatusHealthValueShadow"
        "xpos"                  "0"
        "ypos"                  "0"
        "zpos"                  "5"
        "wide"                  "20"
        "tall"                  "20"
        "visible"               "1"
        "enabled"               "1"
        "labelText"             "%Health%"
        "textAlignment"         "center"
        "font"                  "BodyEm_MD_Blur"
        "fgcolor"               "Shadow"
        "pin_to_sibling"        "HealthBG"
    }
    "HealthBG"
    {
        "ControlName"                   "EditablePanel"
        "fieldName"                     "HealthBG"
        "xpos"                          "9"
        "ypos"                          "9"
        "zpos"                          "-1"
        "wide"                          "20"
        "tall"                          "20"
        "visible"                       "1"
        "enabled"                       "1"
        "paintBackground"               "1"
        "paintBackgroundType"           "2"
        "bgcolor_override"              "TransparentBlack"
    }
    "PlayerStatusPlayerLevel"	// idk what this is
    {
        "ControlName"           "CExLabel"
        "fieldName"             "PlayerStatusPlayerLevel"
        "xpos"                  "8"
        "ypos"                  "9"
        "zpos"                  "5"
        "wide"                  "16"
        "tall"                  "12"
        "visible"               "0"
        "enabled"               "1"
        "textAlignment"         "center"
        "font"                  "ScoreboardVerySmall"
        "fgcolor"               "TFOrange"
    }
}