"Resource/UI/Spectator.res"
{
    "Spectator"
    {
        "ControlName"           "Frame"
        "fieldName"             "Spectator"
        "tall"                  "480"
        "autoResize"            "0"
        "pinCorner"             "0"
        "visible"               "1"
        "enabled"               "1"
        "tabPosition"           "0"
    }
    "specgui"
    {
    }
    "BottomBarBG"
    {
        "ControlName"               "EditablePanel"
        "fieldName"                 "BottomBarBG"
        "xpos"                      "0"
        "ypos"                      "rs1"
        "wide"                      "f0"
        "tall"                      "30"
        "visible"                   "1"
        "enabled"                   "1"
        "bgcolor_override"          "red"
    }
    "BottomBarTopLine"
    {
        "ControlName"               "EditablePanel"
        "fieldName"                 "BottomBarTopLine"
        "xpos"                      "0"
        "ypos"                      "0"
        "wide"                      "f0"
        "tall"                      "1"
        "visible"                   "1"
        "enabled"                   "1"
        "bgcolor_override"          "TransparentLightWhite"
        pin_to_sibling BottomBarBG
        pin_corner_to_sibling PIN_BOTTOMLEFT
        pin_to_sibling_corner PIN_TOPLEFT
    }
    "ReinforcementsLabel"	// respawn time
    {
        "ControlName"                   "CExLabel"
        "fieldName"                     "ReinforcementsLabel"
        "xpos"                          "cs-0.5"
        "ypos"                          "rs1"
        "zpos"                          "1111"
        "wide"                          "600"
        "tall"                          "30"
        "proportionaltoparent"          "1"
        "AllCaps"                       "1"
        "autoResize"                    "0"
        "pinCorner"                     "0"
        "visible"                       "1"
        "enabled"                       "1"
        "labelText"                     "#game_respawntime_in_secs"
        "textAlignment"                 "center"
        "font"                          "HeaderEM_LG"
        "fgcolor_override"              "White"
    }
    "BuyBackLabel"
    {
        "ControlName"           "CExLabel"
        "fieldName"             "BuyBackLabel"
        "xpos"                  "-3"
        "ypos"                  "0"
        "wide"                  "320"
        "tall"                  "30"
        "autoResize"            "0"
        "pinCorner"             "0"
        "visible"               "0"
        "enabled"               "1"
        "labelText"             ""
        "textAlignment"         "center"
        "font"                  "HudFontSmall"
        "wrap"                  "1"
        "centerwrap"            "1"
    }
    "CamModeKey"
    {
        "ControlName"                       "CExButton"
        "FieldName"                         "CamModeKey"
        "XPos"                              "14"
        "YPos"                              "rs1-9"
        "ZPos"                              "101"
        "Wide"                              "30"
        "Tall"                              "14"
        "Visible"                           "1"
        "Enabled"                           "1"
        "ProportionalToParent"              "1"
        "Use_Proportional_Insets"           "1"
        "TextInsetX"                        "5"
        "Font"                              "BodyEm_SM"
        "LabelText"                         "SPACE"
        "Command"                           "nav_close"
        "TextAlignment"                     "center"
        "Sound_Depressed"                   "UI/buttonclick.wav"
        "DefaultFGColor_Override"           "Black"
        "ArmedFGColor_Override"             "Menu_Accent"
        "DepressedFGColor_Override"         "Menu_Accent"
        "paintBackground"                   "1"
        "paintbackgroundtype"               "2"
        "DefaultBGColor_Override"           "White"
        "ArmedBGColor_Override"             "FinalsKeyBGD_Armed"
        "DepressedBGColor_Override"         "FinalsKeyBGD_Armed"
    }
    "SwitchCamModeLabel"
    {
        "ControlName"           "CExLabel"
        "fieldName"             "SwitchCamModeLabel"
        "xpos"                  "4"
        "ypos"                  "0"
        "wide"                  "50"
        "tall"                  "12"
        "visible"               "1"
        "enabled"               "1"
        "labelText"             "#TF_Spectator_SwitchCamMode"
        "textAlignment"         "west"
        "font"                  "BodyEM_SM"
        "pin_to_sibling"                "CamModeKey"
        "pin_corner_to_sibling"         "PIN_BOTTOMLEFT"
        "pin_to_sibling_corner"         "PIN_BOTTOMRIGHT"
    }
    "CycleTargetRevLabel"
    {
        "ControlName"           "CExLabel"
        "fieldName"             "CycleTargetRevLabel"
        "xpos"                  "rs1-30"
        "ypos"                  "rs1-9"
        "wide"                  "30"
        "tall"                  "12"
        "autoResize"            "0"
        "pinCorner"             "0"
        "visible"               "1"
        "enabled"               "1"
        "labelText"             "#TF_Spectator_CycleTargetRev"
        "textAlignment"         "west"
        "font"                  "BodyEM_SM"
    }
    "CycleTargetRevKeyLabelReal"
    {
        "ControlName"                   "ImagePanel"
        "fieldName"                     "CycleTargetRevKeyLabelReal"
        "xpos"                          "0"
        "ypos"                          "0"
        "wide"                          "16"
        "tall"                          "16"
        "visible"                       "1"
        "enabled"                       "1"
        "image"                         "replay/thumbnails/rightclick"
        "scaleImage"                    "1"
        "pin_to_sibling"                "CycleTargetRevLabel"
        "pin_corner_to_sibling"         "PIN_CENTER_RIGHT"
        "pin_to_sibling_corner"         "PIN_CENTER_LEFT"
    }
    "CycleTargetFwdKeyLabelReal"
    {
        "ControlName"                   "ImagePanel"
        "fieldName"                     "CycleTargetFwdKeyLabelReal"
        "xpos"                          "2"
        "ypos"                          "0"
        "wide"                          "16"
        "tall"                          "16"
        "visible"                       "1"
        "enabled"                       "1"
        "image"                         "replay/thumbnails/leftclick"
        "scaleImage"                    "1"
        "pin_to_sibling"                "CycleTargetRevKeyLabelReal"
        "pin_corner_to_sibling"         "PIN_CENTER_RIGHT"
        "pin_to_sibling_corner"         "PIN_CENTER_LEFT"
    }
    "CycleTargetFwdLabel"
    {
        "ControlName"                   "CExLabel"
        "fieldName"                     "CycleTargetFwdLabel"
        "xpos"                          "0"
        "ypos"                          "0"
        "wide"                          "30"
        "tall"                          "12"
        "autoResize"                    "0"
        "pinCorner"                     "0"
        "visible"                       "1"
        "enabled"                       "1"
        "labelText"                     "#TF_Spectator_CycleTargetFwd"
        "textAlignment"                 "east"
        "font"                          "BodyEM_SM"
        "pin_to_sibling"                "CycleTargetFwdKeyLabelReal"
        "pin_corner_to_sibling"         "PIN_CENTER_RIGHT"
        "pin_to_sibling_corner"         "PIN_CENTER_LEFT"
    }
    "TipLabel"
    {
        "ControlName"           "CExLabel"
        "fieldName"             "TipLabel"
        "xpos"                  "999999"
        "ypos"                  "999999"
        "wide"                  "0"
        "tall"                  "0"
        "visible"               "0"
        "enabled"               "0"
    }
    "itempanel"
    {
        "ControlName"                   "CItemModelPanel"
        "fieldName"                     "itempanel"
        "xpos"                          "0"
        "ypos"                          "0"
        "zpos"                          "10"
        "wide"                          "190"
        "tall"                          "100"
        "visible"                       "0"
        "bgcolor_override"              "255 255 255 0"
        "PaintBackgroundType"           "0"
        "border"                        "OutlinedGreyBox"
        "model_ypos"                    "10"
        "model_center_x"                "1"
        "model_wide"                    "90"
        "model_tall"                    "60"
        "text_xpos"                     "10"
        "text_ypos"                     "10"
        "text_wide"                     "170"
        "text_center"                   "1"
        "max_text_height"               "100"
        "padding_height"                "10"
        "resize_to_text"                "1"
        "text_forcesize"                "2"
        "itemmodelpanel"
        {
            "fieldName"                     "itemmodelpanel"
            "use_item_rendertarget"         "0"
            "useparentbg"                   "1"
            "inventory_image_type"          "1"	// High quality item image
        }
        "ItemBG"
        {
            "ControlName"           "ImagePanel"
            "fieldName"             "ItemBG"
            "xpos"                  "0"
            "ypos"                  "0"
            "zpos"                  "-1"
            "wide"                  "200"
            "tall"                  "1000"
            "autoResize"            "0"
            "pinCorner"             "0"
            "visible"               "1"
            "enabled"               "1"
            "fillcolor"             "itempanelbg"
        }
        "ItemLabel"
        {
            "ControlName"           "Label"
            "fieldName"             "ItemLabel"
            "font"                  "DefaultSmall"
            "xpos"                  "10"
            "ypos"                  "3"
            "zpos"                  "1"
            "wide"                  "270"
            "tall"                  "9"
            "autoResize"            "0"
            "pinCorner"             "0"
            "visible"               "1"
            "enabled"               "1"
            "labelText"             "#FreezePanel_Item"
            "textAlignment"         "Left"
            "dulltext"              "0"
            "brighttext"            "0"
        }
    }
    "spectator_extras"
    {
        "ControlName"           "EditablePanel"
        "fieldName"             "spectator_extras"
        "xpos"                  "0"
        "ypos"                  "0"
        "wide"                  "f0"
        "tall"                  "480"
        "autoResize"            "0"
        "pinCorner"             "0"
        "visible"               "1"
        "enabled"               "1"
    }
    /////////////////////
    // MARK: Dead
    "TopBar"
    {
        "ControlName"           "Panel"
        "fieldName"             "TopBar"
        "xpos"                  "999999"
        "ypos"                  "999999"
        "wide"                  "0"
        "tall"                  "0"
        "visible"               "0"
        "enabled"               "0"
    }
    "BottomBar"
    {
        "ControlName"           "Frame"
        "fieldName"             "BottomBar"
        "xpos"                  "999999"
        "ypos"                  "999999"
        "wide"                  "0"
        "tall"                  "0"
        "visible"               "0"
        "enabled"               "0"
    }
    "bottombarblank"
    {
        "ControlName"           "Panel"
        "fieldName"             "bottombarblank"
        "xpos"                  "999999"
        "ypos"                  "999999"
        "wide"                  "0"
        "tall"                  "0"
        "visible"               "0"
        "enabled"               "0"
    }
    "CycleTargetFwdKeyLabel"
    {
        "ControlName"           "CExLabel"
        "fieldName"             "CycleTargetFwdKeyLabel"
        "xpos"                  "99999"
        "ypos"                  "99999"
        "wide"                  "0"
        "tall"                  "0"
        "visible"               "0"
        "enabled"               "0"
    }
    "CycleTargetRevKeyLabel"
    {
        "ControlName"           "CExLabel"
        "fieldName"             "CycleTargetRevKeyLabel"
        "xpos"                  "99999"
        "ypos"                  "99999"
        "wide"                  "0"
        "tall"                  "0"
        "visible"               "0"
        "enabled"               "0"
    }
    "MapLabel"
    {
        "ControlName"           "CExLabel"
        "fieldName"             "MapLabel"
        "xpos"                  "999999"
        "ypos"                  "999999"
        "wide"                  "0"
        "tall"                  "0"
        "visible"               "0"
        "enabled"               "0"
    }
    "ClassOrTeamLabel"
    {
        "ControlName"           "CExLabel"
        "fieldName"             "ClassOrTeamLabel"
        "xpos"                  "999999"
        "ypos"                  "999999"
        "wide"                  "0"
        "tall"                  "0"
        "visible"               "0"
        "enabled"               "0"
    }
    "SwitchCamModeKeyLabel"
    {
        "ControlName"           "CExLabel"
        "fieldName"             "SwitchCamModeKeyLabel"
        "xpos"                  "99999"
        "ypos"                  "99999"
        "wide"                  "0"
        "tall"                  "0"
        "visible"               "0"
        "enabled"               "0"
    }
}