"Resource/UI/TargetID.res"
{
    "TargetIDBG"	// team colour modulate
    {
        "ControlName"           "CTFImagePanel"
        "fieldName"             "TargetIDBG"
        "xpos"                  "0"
        "ypos"                  "0"
        "zpos"                  "10"
        "wide"                  "252"	// hardcoded
        "tall"                  "15"	// hardcoded
        "autoResize"            "0"
        "pinCorner"             "0"
        "visible"               "1"
        "enabled"               "1"
        "image"                 "../hud/color_panel_clear"
        "scaleImage"            "1"
        "alpha"                 "255"
        "teambg_1"              "../hud/color_panel_clear"
        "teambg_2"              "replay/thumbnails/panels/target_red"
        "teambg_3"              "replay/thumbnails/panels/target_blue"
    }
    "SpectatorGUIHealth"
    {
        "ControlName"                       "EditablePanel"
        "fieldName"                         "SpectatorGUIHealth"
        "xpos"                              "0"
        "ypos"                              "-13"
        "wide"                              "128"
        "tall"                              "62"
        "visible"                           "1"
        "enabled"                           "1"
        "HealthBonusPosAdj"                 "288"	// TODO - add baselog options for this 1440p: 384, 1080p: 288
        "HealthDeathWarning"                "1.00"
        // "TFFont"                            "DinBold12"
        "HealthDeathWarningColor"           "HUDDeathWarning"
        "TextColor"                         "White"
    }
    "Refract"
    {
        "ControlName"                   "ImagePanel"
        "fieldName"                     "Refract"
        "xpos"                          "0"
        "ypos"                          "-13"
        "zpos"                          "11"
        "wide"                          "128"
        "tall"                          "12"
        "proportionaltoparent"          "1"
        "visible"                       "1"
        "enabled"                       "1"
        "proportionaltoparent"          "1"
        "image"                         "replay/thumbnails/healthbar/healthbar-8-refract"
        "scaleImage"                    "1"
        "pin_to_sibling"                "SpectatorGUIHealth"
    }
    "TargetNameLabelReal"
    {
        "ControlName"                   "CExLabel"
        "fieldName"                     "TargetNameLabelReal"
        "xpos"                          "34"
        "ypos"                          "16"
        "zpos"                          "1"
        "wide"                          "100"
        "tall"                          "14"
        "visible"                       "1"
        "enabled"                       "1"
        "proportionaltoparent"          "1"
        "labelText"                     "%targetname%"
        "textAlignment"                 "west"
        "font"                          "Body_MD"
        "textinsety"                    "-1"
        "fgcolor"                       "White"
    }
    "TargetNameLabelRealShadow"	// shadow
    {
        "ControlName"                   "CExLabel"
        "fieldName"                     "TargetNameLabelRealShadow"
        "xpos"                          "-1"
        "ypos"                          "-1"
        "zpos"                          "1"
        "wide"                          "100"
        "tall"                          "14"
        "visible"                       "1"
        "enabled"                       "1"
        "proportionaltoparent"          "1"
        "labelText"                     "%targetname%"
        "textAlignment"                 "west"
        "font"                          "Body_SM_Blur"
        "fgcolor"                       "Shadow"
        "pin_to_sibling"                "TargetNameLabelReal"
    }
    "TargetDataLabel"	// dead because this resizes the container which resizes the modulate texture and breaks. also cant be moved horizontally
    {
        "ControlName"               "CExLabel"
        "fieldName"                 "TargetDataLabel"
        "font"                      "Body_SM"
        "fgcolor_override"          "White"
        "fgcolor"                   "White"
        "xpos"                      "0"	// hardcoded
        "ypos"                      "0"
        "zpos"                      "1"
        "wide"                      "100"
        "tall"                      "13"
        "autoResize"                "3"
        "pinCorner"                 "0"
        "visible"                   "1"
        "enabled"                   "1"
        "labelText"                 ""	// %targetdata%
        "textAlignment"             "west"
        "dulltext"                  "0"
        "brighttext"                "0"
    }
    "TargetIDBG_Spec_Blue"	// dead
    {
        "ControlName"           "ScalableImagePanel"
        "fieldName"             "TargetIDBG_Spec_Blue"
        "xpos"                  "9999"
        "ypos"                  "9999"
        "zpos"                  "-90"
        "wide"                  "0"
        "tall"                  "0"
        "autoResize"            "0"
        "pinCorner"             "0"
        "visible"               "0"
        "enabled"               "0"
    }
    "TargetIDBG_Spec_Red"	// dead
    {
        "ControlName"           "ScalableImagePanel"
        "fieldName"             "TargetIDBG_Spec_Red"
        "xpos"                  "9999"
        "ypos"                  "9999"
        "zpos"                  "-112"
        "wide"                  "0"
        "tall"                  "0"
        "autoResize"            "0"
        "pinCorner"             "0"
        "visible"               "0"
        "enabled"               "0"
    }
    "TargetNameLabel"	// dead
    {
        "ControlName"                       "CExLabel"
        "fieldName"                         "TargetNameLabel"
        "xpos"                              "0"
        "ypos"                              "0"
        "zpos"                              "1"
        "wide"                              "0"
        "tall"                              "0"
        "visible"                           "1"
        "enabled"                           "0"
        "proportionaltoparent"              "1"
        "labelText"                         ""
        "textAlignment"                     "west"
        "font"                              "TargetID"
        "disabledfgcolor2_override"         "White"
    }
    "AmmoIcon"
    {
        "ControlName"           "ImagePanel"
        "fieldName"             "AmmoIcon"
        "xpos"                  "99999"
        "ypos"                  "24"
        "zpos"                  "12"
        "wide"                  "8"
        "tall"                  "8"
        "visible"               "0"
        "enabled"               "1"
        "image"                 "../hud/leaderboard_class_heavy"
        "scaleImage"            "1"
    }
    "MoveableSubPanel"
    {
        "ControlName"           "EditablePanel"
        "FieldName"             "MoveableSubPanel"
        "XPos"                  "9999"
        "YPos"                  "9999"
        "Wide"                  "0"
        "Tall"                  "0"
        "Visible"               "0"
        "Enabled"               "0"
    }
}