"Resource/UI/TargetID.res"
{
    "TargetIDBG"	// team colour modulate
    {
        "ControlName"           "CTFImagePanel"
        "fieldName"             "TargetIDBG"
        "xpos"                  "0"
        "ypos"                  "0"
        "zpos"                  "10"
        "wide"                  "252"	// hardcoded
        "tall"                  "15"	// hardcoded
        "autoResize"            "0"
        "pinCorner"             "0"
        "visible"               "1"
        "enabled"               "1"
        "image"                 "../hud/color_panel_clear"
        "scaleImage"            "1"
        "alpha"                 "255"
        "teambg_1"              "../hud/color_panel_clear"
        "teambg_2"              "replay/thumbnails/panels/target_red"
        "teambg_3"              "replay/thumbnails/panels/target_blue"
    }
    "SpectatorGUIHealth"
    {
        "ControlName"                       "EditablePanel"
        "fieldName"                         "SpectatorGUIHealth"
        "xpos"                              "0"
        "ypos"                              "-13"
        "wide"                              "128"
        "tall"                              "62"
        "visible"                           "1"
        "enabled"                           "1"
        "HealthBonusPosAdj"                 "384"
        "HealthDeathWarning"                "1.00"
        // "TFFont"                            "DinBold12"
        "HealthDeathWarningColor"           "HUDDeathWarning"
        "TextColor"                         "White"
    }
    "TargetNameLabelReal"
    {
        "ControlName"                   "CExLabel"
        "fieldName"                     "TargetNameLabelReal"
        "xpos"                          "34"
        "ypos"                          "16"
        "zpos"                          "1"
        "wide"                          "100"
        "tall"                          "14"
        "visible"                       "1"
        "enabled"                       "1"
        "proportionaltoparent"          "1"
        "labelText"                     "%targetname%"
        "textAlignment"                 "west"
        "font"                          "Body_MD"
        "textinsety"                    "-1"
        "fgcolor"                       "White"
    }
    "TargetNameLabelRealShadow"	// shadow
    {
        "ControlName"                   "CExLabel"
        "fieldName"                     "TargetNameLabelRealShadow"
        "xpos"                          "-1"
        "ypos"                          "-1"
        "zpos"                          "1"
        "wide"                          "100"
        "tall"                          "14"
        "visible"                       "1"
        "enabled"                       "1"
        "proportionaltoparent"          "1"
        "labelText"                     "%targetname%"
        "textAlignment"                 "west"
        "font"                          "Body_SM_Blur"
        "fgcolor"                       "Shadow"
        "pin_to_sibling"                "TargetNameLabelReal"
    }
    "TargetDataLabel"
    {
        "ControlName"               "CExLabel"
        "fieldName"                 "TargetDataLabel"
        "font"                      "Body_SM"
        "fgcolor_override"          "White"
        "fgcolor"                   "White"
        "xpos"                      "0"	// hardcoded
        "ypos"                      "0"
        "zpos"                      "1"
        "wide"                      "100"
        "tall"                      "13"
        "autoResize"                "3"
        "pinCorner"                 "0"
        "visible"                   "1"
        "enabled"                   "1"
        "labelText"                 "" // %targetdata%
        "textAlignment"             "west"
        "dulltext"                  "0"
        "brighttext"                "0"
    }
    "TargetIDBG_Spec_Blue"	// dead
    {
        "ControlName"           "ScalableImagePanel"
        "fieldName"             "TargetIDBG_Spec_Blue"
        "xpos"                  "9999"
        "ypos"                  "9999"
        "zpos"                  "-90"
        "wide"                  "0"
        "tall"                  "0"
        "autoResize"            "0"
        "pinCorner"             "0"
        "visible"               "0"
        "enabled"               "0"
    }
    "TargetIDBG_Spec_Red"	// dead
    {
        "ControlName"           "ScalableImagePanel"
        "fieldName"             "TargetIDBG_Spec_Red"
        "xpos"                  "9999"
        "ypos"                  "9999"
        "zpos"                  "-112"
        "wide"                  "0"
        "tall"                  "0"
        "autoResize"            "0"
        "pinCorner"             "0"
        "visible"               "0"
        "enabled"               "0"
    }
    "TargetNameLabel"	// dead
    {
        "ControlName"                       "CExLabel"
        "fieldName"                         "TargetNameLabel"
        "xpos"                              "0"
        "ypos"                              "0"
        "zpos"                              "1"
        "wide"                              "0"
        "tall"                              "0"
        "visible"                           "1"
        "enabled"                           "0"
        "proportionaltoparent"              "1"
        "labelText"                         ""
        "textAlignment"                     "west"
        "font"                              "TargetID"
        "disabledfgcolor2_override"         "White"
    }
    "AmmoIcon"
    {
        "ControlName"           "ImagePanel"
        "fieldName"             "AmmoIcon"
        "xpos"                  "99999"
        "ypos"                  "24"
        "zpos"                  "12"
        "wide"                  "8"
        "tall"                  "8"
        "visible"               "0"
        "enabled"               "1"
        "image"                 "../hud/leaderboard_class_heavy"
        "scaleImage"            "1"
    }
    "MoveableSubPanel"
    {
        "ControlName"           "EditablePanel"
        "fieldName"             "MoveableSubPanel"
        "xpos"                  "9999"	// omp -- fix glitch where this is visible in spectator view.
        "ypos"                  "9999"
        "zpos"                  "0"
        "wide"                  "0"
        "tall"                  "0"
        "visible"               "0"
        "enabled"               "0"
        "MoveableIconBG"
        {
            "ControlName"           "CIconPanel"
            "fieldName"             "MoveableIconBG"
            "xpos"                  "9999"
            "ypos"                  "9999"
            "zpos"                  "0"
            "wide"                  "10"
            "tall"                  "36"
            "visible"               "1"
            "enabled"               "1"
            "icon"                  "obj_status_alert_background_tall_nocolor"
            "iconColor"             "HudBlack"
            "scaleImage"            "1"
        }
        "MoveableIcon"
        {
            "ControlName"           "CIconPanel"
            "fieldName"             "MoveableIcon"
            "xpos"                  "5"
            "ypos"                  "7"
            "zpos"                  "11"
            "wide"                  "14"
            "tall"                  "14"
            "visible"               "1"
            "enabled"               "1"
            "icon"                  "obj_status_sentrygun_1"
            "drawcolor"             "ProgressOffWhite"
            "scaleImage"            "1"
        }
        "MoveableSymbolIcon"
        {
            "ControlName"           "ImagePanel"
            "fieldName"             "MoveableSymbolIcon"
            "xpos"                  "16"
            "ypos"                  "-2"
            "zpos"                  "12"
            "wide"                  "16"
            "tall"                  "8"
            "visible"               "1"
            "enabled"               "1"
            "image"                 "../hud/eng_sel_item_movable"
            "drawcolor"             "ProgressOffWhite"
            "scaleImage"            "1"
        }
        "MoveableKeyLabel"
        {
            "ControlName"           "Label"
            "fieldName"             "MoveableKeyLabel"
            "font"                  "mk8"
            "xpos"                  "0"
            "ypos"                  "34"
            "zpos"                  "1"
            "wide"                  "640"
            "tall"                  "10"
            "autoResize"            "0"
            "pinCorner"             "0"
            "visible"               "1"
            "enabled"               "1"
            "labelText"             "%movekey%"
            "textAlignment"         "North"
            "dulltext"              "0"
            "brighttext"            "0"
        }
    }
}