"Resource/UI/TeamMenu.res"
{
    "team"
    {
        "ControlName"           "CTeamMenu"
        "fieldName"             "team"
        "xpos"                  "0"
        "ypos"                  "0"
        "wide"                  "f0"
        "tall"                  "480"
        "autoResize"            "0"
        "pinCorner"             "0"
        "visible"               "1"
        "enabled"               "1"
        "fgcolor"               "0 0 0 0"
        "tabPosition"           "0"
    }
    "SysMenu"	// dead
    {
        "ControlName"           "Menu"
        "fieldName"             "SysMenu"
        "xpos"                  "99999"
        "ypos"                  "99999"
        "wide"                  "0"
        "tall"                  "0"
        "autoResize"            "0"
        "pinCorner"             "0"
        "visible"               "0"
        "enabled"               "0"
        "tabPosition"           "0"
    }
    "MapInfo"	// dead
    {
        "ControlName"           "HTML"
        "fieldName"             "MapInfo"
        "xpos"                  "99999"
        "ypos"                  "99999"
        "wide"                  "0"
        "tall"                  "0"
        "autoResize"            "3"
        "pinCorner"             "0"
        "visible"               "0"
        "enabled"               "0"
        "tabPosition"           "0"
    }
    "SelectATeamLabel"
    {
        "ControlName"               "Label"
        "fieldName"                 "SelectATeamLabel"
        "xpos"                      "20"
        "ypos"                      "20"
        "zpos"                      "1"
        "wide"                      "300"
        "tall"                      "25"
        "labelText"                 "TEAMS"
        "textAlignment"             "west"
        "font"                      "HeaderEm_XL"
        "visible"                   "1"
        "enabled"                   "1"
        "fgcolor_override"          "White"
    }
    "mapname"
    {
        "ControlName"               "Label"
        "fieldName"                 "mapname"
        "xpos"                      "rs1-20"
        "ypos"                      "28" // aligned with bottom of SelectATeamLabel
        "wide"                      "240"
        "tall"                      "24"
        "autoResize"                "0"
        "pinCorner"                 "0"
        "visible"                   "1"
        "enabled"                   "1"
        "labelText"                 ""	// hardcoded to full map file name
        "AllCaps"                   "1"
        "textAlignment"             "east"
        "font"                      "HeaderEm_MD"
        "fgcolor_override"          "White"
    }
    "teambutton0"
    {
        "ControlName"                       "CTFTeamButton"
        "fieldName"                         "teambutton0"
        "xpos"                              "c-50"
        "ypos"                              "230"
        "zpos"                              "3"
        "wide"                              "100"
        "tall"                              "40"
        "autoResize"                        "0"
        "pinCorner"                         "2"
        "visible"                           "1"
        "enabled"                           "1"
        "tabPosition"                       "3"
        "labelText"                         "BLU" [$WIN32]
        "textAlignment"                     "center"
        "dulltext"                          "0"
        "brighttext"                        "0"
        "command"                           "jointeam blue"
        "team"                              "3"	// team red
        "font"                              "DinBold18"
        "border_default"                    "TeamBlueButton"
        "border_armed"                      "TeamBlueButtonSel"
        "defaultFgColor_override"           "255 255 255 255"
        "armedFgColor_override"             "255 255 255 220"
        "depressedFgColor_override"         "255 255 255 128"
        "selectedFgColor_override"          "owFULLWHITE"
    }
    "teambutton1"
    {
        "ControlName"                       "CTFTeamButton"
        "fieldName"                         "teambutton1"
        "xpos"                              "c-50"
        "ypos"                              "275"
        "zpos"                              "3"
        "wide"                              "100"
        "tall"                              "40"
        "autoResize"                        "0"
        "pinCorner"                         "2"
        "visible"                           "1"
        "enabled"                           "1"
        "tabPosition"                       "3"
        "labelText"                         "RED" [$WIN32]
        "labelText"                         "RED" [$WIN32]
        "textAlignment"                     "center"
        "dulltext"                          "0"
        "brighttext"                        "0"
        "command"                           "jointeam red"
        "team"                              "4"	// team red
        "font"                              "DinBold18"
        "border_default"                    "TeamRedButton"
        "border_armed"                      "TeamRedButtonSel"
        "defaultFgColor_override"           "255 255 255 255"
        "armedFgColor_override"             "255 255 255 220"
        "depressedFgColor_override"         "255 255 255 128"
        "selectedFgColor_override"          "owFULLWHITE"
    }
    "teambutton2"
    {
        "ControlName"                       "CTFTeamButton"
        "fieldName"                         "teambutton2"
        "xpos"                              "c-50"
        "ypos"                              "200"
        "zpos"                              "3"
        "wide"                              "0"
        "tall"                              "0"
        "autoResize"                        "0"
        "pinCorner"                         "2"
        "visible"                           "0"
        "enabled"                           "0"
        "tabPosition"                       "1"
        "labelText"                         "Auto-join" [$WIN32]
        "textAlignment"                     "center"
        "command"                           "jointeam auto"
        "font"                              "DinBold18"
        "border_default"                    "owbutton"
        "border_armed"                      "owbuttonsel"
        "defaultFgColor_override"           "255 255 255 255"
        "armedFgColor_override"             "255 255 255 220"
        "depressedFgColor_override"         "255 255 255 128"
        "selectedFgColor_override"          "owFULLWHITE"
    }
    "teambutton3"
    {
        "ControlName"                       "CTFTeamButton"
        "fieldName"                         "teambutton3"
        "xpos"                              "c-50"
        "ypos"                              "325"
        "zpos"                              "3"
        "wide"                              "100"
        "tall"                              "20"
        "autoResize"                        "0"
        "pinCorner"                         "2"
        "visible"                           "1"
        "enabled"                           "1"
        "labelText"                         "SPECTATE" [$WIN32]
        "textAlignment"                     "center"
        "command"                           "jointeam spectate"
        "font"                              "DinBold12"
        "border_default"                    "owbutton"
        "border_armed"                      "owbuttonsel"
        "defaultFgColor_override"           "255 255 255 255"
        "armedFgColor_override"             "255 255 255 220"
        "depressedFgColor_override"         "255 255 255 128"
        "selectedFgColor_override"          "owFULLWHITE"
    }
    "CancelButtonReal"
    {
        "ControlName"                       "CExButton"
        "fieldName"                         "CancelButtonReal"
        "XPos"                              "15"
        "YPos"                              "rs1-15"
        "ZPos"                              "15"
        "Wide"                              "24"
        "Tall"                              "24"
        "autoResize"                        "0"
        "pinCorner"                         "3"
        "visible"                           "1"
        "enabled"                           "1"
        "tabPosition"                       "0"
        "labelText"                         "&Q"
        "font"                              "BodyEm_MD"
        "textAlignment"                     "center"
        "dulltext"                          "0"
        "brighttext"                        "0"
        "default"                           "0"
        "Command"                           "cancel menu"
        "sound_depressed"                   "UI/buttonclick.wav"
        "sound_released"                    "UI/buttonclickrelease.wav"
        "DefaultFGColor_Override"           "FinalsGreyDark"
        "ArmedFGColor_Override"             "Menu_Accent"
        "DepressedFGColor_Override"         "Menu_Accent"
        "paintBackground"                   "1"
        "paintbackgroundtype"               "2"
        "DefaultBGColor_Override"           "FinalsKeyBG"
        "ArmedBGColor_Override"             "FinalsKeyBGD_Armed"
        "DepressedBGColor_Override"         "FinalsKeyBGD_Armed"
    }
    "CancelButton2"
    {
        "ControlName"                       "CExButton"
        "fieldName"                         "CancelButton2"
        "xpos"                              "0"
        "ypos"                              "0"
        "zpos"                              "2"
        "wide"                              "40"
        "tall"                              "17"
        "autoResize"                        "0"
        "pinCorner"                         "3"
        "visible"                           "1"
        "enabled"                           "1"
        "tabPosition"                       "0"
        "labelText"                         "BACK"
        "font"                              "BodyEm_MD"
        "textAlignment"                     "west"
        "dulltext"                          "0"
        "brighttext"                        "0"
        "default"                           "0"
        "Command"                           "cancel menu"
        "paintbackgroundtype"               "2"
        "paintbackground"                   "1"
        "sound_depressed"                   "UI/buttonclick.wav"
        "sound_released"                    "UI/buttonclickrelease.wav"
        "defaultBgColor_override"           "0 0 0 0"
        "armedBgColor_override"             "0 0 0 0"
        "depressedBgColor_override"         "0 0 0 0"
        "defaultFgColor_override"           "White"
        "armedFgColor_override"             "White"
        "depressedFgColor_override"         "White"
        "border_default"                    "NoBorder"
        "border_armed"                      "NoBorder"
        "pin_to_sibling"                    "CancelButtonReal"
        "pin_corner_to_sibling"             "pin_center_left"
        "pin_to_sibling_corner"             "pin_center_right"
    }
    "CancelButton"	// dead
    {
        "ControlName"           "CExButton"
        "fieldName"             "CancelButton"
        "XPos"                  "999"
        "YPos"                  "999"
        "ZPos"                  "0"
        "Wide"                  "0"
        "Tall"                  "0"
        "visible"               "0"
        "enabled"               "0"
    }
    "TeamMenuSelect"
    {
        "ControlName"           "CExLabel"
        "fieldName"             "TeamMenuSelect"
        "xpos"                  "9999"
        "ypos"                  "9999"
        "zpos"                  "6"
        "wide"                  "0"
        "tall"                  "0"
        "autoResize"            "0"
        "pinCorner"             "0"
        "visible"               "0"
        "enabled"               "0"
        "labelText"             "#TF_SelectATeam"
        "textAlignment"         "center"
        "dulltext"              "0"
        "brighttext"            "0"
        "font"                  "Code24"
        "fgcolor"               "HudOffWhite"
    }
    "TeamMenuAuto"
    {
        "ControlName"           "CExLabel"
        "fieldName"             "TeamMenuAuto"
        "xpos"                  "9999" [$WIN32]
        "ypos"                  "9999"
        "zpos"                  "1"
        "wide"                  "0" [$WIN32]
        "tall"                  "0"
        "autoResize"            "0"
        "pinCorner"             "0"
        "visible"               "0"
        "enabled"               "0"
        "labelText"             "#TF_Random"
        "textAlignment"         "center"
        "dulltext"              "0"
        "brighttext"            "0"
        "wrap"                  "0"
        "font"                  "MenuSmallFont"
        "fgcolor"               "black"
    }
    "TeamMenuSpectate"
    {
        "ControlName"           "CExLabel"
        "fieldName"             "TeamMenuSpectate"
        "xpos"                  "9999"
        "ypos"                  "9999"
        "zpos"                  "1"
        "wide"                  "0"
        "tall"                  "0"
        "autoResize"            "0"
        "pinCorner"             "0"
        "visible"               "0"
        "enabled"               "0"
        "labelText"             ""
        "textAlignment"         "center"
        "dulltext"              "0"
        "brighttext"            "0"
        "wrap"                  "0"
        "font"                  "Code17"
        "fgcolor"               "white"
    }
    "MenuBG"
    {
        "ControlName"           "ImagePanel"
        "fieldName"             "MenuBG"
        "xpos"                  "0"
        "ypos"                  "0"
        "zpos"                  "0"
        "wide"                  "f0"
        "tall"                  "480"
        "autoResize"            "0"
        "pinCorner"             "0"
        "visible"               "1"
        "enabled"               "1"
        "fillcolor"             "0 0 0 0"
    }
    "ShadedBar"
    {
        "ControlName"                   "ImagePanel"
        "fieldName"                     "ShadedBar"
        "xpos"                          "9999"
        "ypos"                          "9999"
        "zpos"                          "5"
        "wide"                          "0"
        "tall"                          "0"
        "tall_lodef"                    "74"
        "tall_hidef"                    "65"
        "autoResize"                    "0"
        "pinCorner"                     "0"
        "visible"                       "0"
        "enabled"                       "0"
        "tabPosition"                   "0"
        "image"                         "loadout_bottom_gradient"
        "tileImage"                     "1"
        "PaintBackgroundType"           "0"
    }
    "BlueCount"
    {
        "ControlName"           "CExLabel"
        "fieldName"             "BlueCount"
        "xpos"                  "c-110"
        "ypos"                  "222"
        "zpos"                  "3"
        "wide"                  "50"
        "tall"                  "50"
        "autoResize"            "0"
        "pinCorner"             "0"
        "visible"               "1"
        "enabled"               "1"
        "labelText"             "%bluecount%"
        "textAlignment"         "east"
        "dulltext"              "0"
        "brighttext"            "1"
        "font"                  "DinBlack48"
        "fgcolor"               "owFULLWHITE"
    }
    "BlueCountPlayers"
    {
        "ControlName"           "CExLabel"
        "fieldName"             "BlueCountPlayers"
        "xpos"                  "9999"
        "ypos"                  "9999"
        "zpos"                  "1"
        "wide"                  "90"
        "tall"                  "30"
        "autoResize"            "0"
        "pinCorner"             "0"
        "visible"               "1"
        "enabled"               "1"
        "labelText"             "players"
        "textAlignment"         "east"
        "dulltext"              "0"
        "brighttext"            "1"
        "font"                  "Oblique14"
        "fgcolor"               "255 255 255 175"
    }
    "RedCount"
    {
        "ControlName"           "CExLabel"
        "fieldName"             "RedCount"
        "xpos"                  "c-110"
        "ypos"                  "270"
        "zpos"                  "3"
        "wide"                  "50"
        "tall"                  "50"
        "autoResize"            "0"
        "pinCorner"             "0"
        "visible"               "1"
        "enabled"               "1"
        "labelText"             "%redcount%"
        "textAlignment"         "east"
        "dulltext"              "0"
        "brighttext"            "1"
        "font"                  "DinBlack48"
        "fgcolor"               "owFULLWHITE"
    }
    "RedCountPlayers"
    {
        "ControlName"           "CExLabel"
        "fieldName"             "RedCountPlayers"
        "xpos"                  "9999"
        "ypos"                  "9999"
        "zpos"                  "1"
        "wide"                  "90"
        "tall"                  "30"
        "autoResize"            "0"
        "pinCorner"             "0"
        "visible"               "1"
        "enabled"               "1"
        "labelText"             "players"
        "textAlignment"         "east"
        "dulltext"              "0"
        "brighttext"            "1"
        "font"                  "Oblique14"
        "fgcolor"               "255 255 255 175"
    }
    "bluedoor"
    {
        "ControlName"           "CModelPanel"
        "fieldName"             "bluedoor"
        "xpos"                  "9999"
        "ypos"                  "9999"
        "zpos"                  "2"
        "wide"                  "f0"
        "tall"                  "480"
        "autoResize"            "0"
        "pinCorner"             "0"
        "visible"               "1"
        "enabled"               "1"
        "fov"                   "20"
    }
    "reddoor"
    {
        "ControlName"           "CModelPanel"
        "fieldName"             "reddoor"
        "xpos"                  "9999"
        "ypos"                  "9999"
        "zpos"                  "2"
        "wide"                  "f0"
        "tall"                  "480"
        "autoResize"            "0"
        "pinCorner"             "0"
        "visible"               "1"
        "enabled"               "1"
        "fov"                   "20"
    }
    "autodoor"
    {
        "ControlName"           "CModelPanel"
        "fieldName"             "autodoor"
        "xpos"                  "9999"
        "ypos"                  "9999"
        "zpos"                  "2"
        "wide"                  "f0"
        "tall"                  "480"
        "autoResize"            "0"
        "pinCorner"             "0"
        "visible"               "1"
        "enabled"               "1"
        "fov"                   "20"
    }
    "spectate"
    {
        "ControlName"           "CModelPanel"
        "fieldName"             "spectate"
        "xpos"                  "9999"
        "ypos"                  "9999"
        "zpos"                  "0"
        "wide"                  "f0"
        "tall"                  "480"
        "autoResize"            "0"
        "pinCorner"             "0"
        "visible"               "1"
        "enabled"               "1"
        "fov"                   "20"
    }
    "HighlanderLabel" [$WIN32]
    {
        "ControlName"           "CExLabel"
        "fieldName"             "HighlanderLabel"
        "xpos"                  "9999"
        "ypos"                  "9999"
        "zpos"                  "6"
        "wide"                  "255"
        "tall"                  "50"
        "autoResize"            "0"
        "pinCorner"             "0"
        "visible"               "0"
        "enabled"               "0"
        "labelText"             "#TF_Highlander_Mode"
        "textAlignment"         "Center"
        "dulltext"              "0"
        "brighttext"            "0"
        "font"                  "Oblique12"
        "fgcolor"               "owFULLWHITE"
        "centerwrap"            "1"
    }
    "HighlanderLabelShadow" [$WIN32]
    {
        "ControlName"           "CExLabel"
        "fieldName"             "HighlanderLabelShadow"
        "xpos"                  "9999"
        "ypos"                  "9999"
        "zpos"                  "6"
        "wide"                  "255"
        "tall"                  "50"
        "autoResize"            "0"
        "pinCorner"             "0"
        "visible"               "0"
        "enabled"               "0"
        "labelText"             "#TF_Highlander_Mode"
        "textAlignment"         "Center"
        "dulltext"              "0"
        "brighttext"            "0"
        "font"                  "Oblique12"
        "fgcolor"               "TransparentBlack"
        "centerwrap"            "1"
    }
    "TeamsFullLabel" [$WIN32]
    {
        "ControlName"           "CExLabel"
        "fieldName"             "TeamsFullLabel"
        "xpos"                  "c-50"
        "ypos"                  "c150"
        "zpos"                  "6"
        "wide"                  "105"
        "tall"                  "35"
        "autoResize"            "0"
        "pinCorner"             "0"
        "visible"               "0"
        "enabled"               "1"
        "labelText"             "#TF_Teams_Full"
        "textAlignment"         "center"
        "dulltext"              "0"
        "brighttext"            "0"
        "font"                  "Oblique12"
        "fgcolor"               "owFULLWHITE"
        "centerwrap"            "1"
    }
    "TeamsFullLabelShadow" [$WIN32]
    {
        "ControlName"           "CExLabel"
        "fieldName"             "TeamsFullLabelShadow"
        "xpos"                  "c-49"
        "ypos"                  "c151"
        "zpos"                  "6"
        "wide"                  "105"
        "tall"                  "35"
        "autoResize"            "0"
        "pinCorner"             "0"
        "visible"               "0"
        "enabled"               "1"
        "labelText"             "#TF_Teams_Full"
        "textAlignment"         "center"
        "dulltext"              "0"
        "brighttext"            "0"
        "font"                  "Oblique12"
        "fgcolor"               "TransparentBlack"
        "centerwrap"            "1"
    }
    "TeamsFullArrow" [$WIN32]
    {
        "ControlName"           "CTFImagePanel"
        "fieldName"             "TeamsFullArrow"
        "xpos"                  "9999"
        "ypos"                  "9999"
        "zpos"                  "6"
        "wide"                  "0"
        "tall"                  "0"
        "visible"               "0"
        "enabled"               "0"
        "image"                 "../HUD/arrow_big_down"
        "scaleImage"            "1"
    }
}