"Resource/UI/TextWindow.res"
{
	"info"
	{
		"ControlName"			"CTFTextWindow"
		"fieldName"				"info"
		"xpos"					"0"
		"ypos"					"0"
		"wide"					"f0"
		"tall"					"480"
		"autoResize"			"0"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"settitlebarvisible"	"0"
	}
	
	"TFMessageTitle"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"TFMessageTitle"
		"xpos"			"5"
		"ypos"			"-20"
		"zpos"			"1"
		"wide"			"f0"
		"tall"			"100"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#TF_WELCOME"
		"textAlignment"	"west"
		"dulltext"		"0"
		"brighttext"	"0"
		"font"			"oblique48"
		"fgcolor"		"owORANGE"
	}	
	"Blurfact"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"Blurfact"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"-999"
		"wide"			"f0"
		"tall"			"f0"
		"autoResize"	"1"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"image"			"replay/thumbnails/blurfact"
	}
	"specBG"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"specBG"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"-21"
		"wide"			"f0"
		"tall"			"70"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"fillcolor"		"0 0 0 180"
	}	
	"specBG2"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"specBG2"
		"xpos"			"0"
		"ypos"			"70"
		"zpos"			"-21"
		"wide"			"f0"
		"tall"			"1"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"fillcolor"		"150 150 150 220"
	}
	"TextMessage"
	{
		"ControlName"	"TextEntry"
		"fieldName"		"TextMessage"
		"visible"		"0"
		"enabled"		"0"
	}
	"MainMenuBG"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"MainMenuBG"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"1"
		"wide"			"f0"
		"tall"			"75"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"fillcolor"		"0 0 0 0"
	}
	"TFTextMessage"
	{
		"ControlName"	"CExRichText"
		"fieldName"		"TFTextMessage"
		"xpos"			"5"
		"font"			"Nim12"
		"ypos"			"75"
		"zpos"			"1"
		"wide"			"f0"
		"tall"			"240"
		"autoResize"	"3"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"paintborder"	"0"
		"textAlignment"	"northwest"
		"fgcolor"		"owFULLWHITE"
	}

	"HTMLMessage"
	{
		"ControlName"		"HTML"
		"fieldName"		"HTMLMessage"
		"xpos"			"0"
		"ypos"			"20"
		"zpos"			"1"
		"wide"			"f0"
		"tall"			"295"
		"autoResize"	"1"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintborder"	"0"
	}	
	"ok"
    {
        "ControlName"                       "CExButton"
        "fieldName"                         "ok"
        "XPos"                              "15"
        "YPos"                              "rs1-15"
        "ZPos"                              "15"
        "Wide"                              "24"
        "Tall"                              "24"
        "autoResize"                        "0"
        "pinCorner"                         "3"
        "visible"                           "1"
        "enabled"                           "1"
        "tabPosition"                       "0"
        "labelText"                         "&E"
        "font"                              "BodyEm_MD"
        "textAlignment"                     "center"
        "dulltext"                          "0"
        "brighttext"                        "0"
        "default"                           "0"
        "Command"                           "okay"
        "sound_depressed"                   "UI/buttonclick.wav"
        "sound_released"                    "UI/buttonclickrelease.wav"
        "DefaultFGColor_Override"           "FinalsGreyDark"
        "ArmedFGColor_Override"             "Menu_Accent"
        "DepressedFGColor_Override"         "Menu_Accent"
        "paintBackground"                   "1"
        "paintbackgroundtype"               "2"
        "DefaultBGColor_Override"           "FinalsKeyBG"
        "ArmedBGColor_Override"             "FinalsKeyBGD_Armed"
        "DepressedBGColor_Override"         "FinalsKeyBGD_Armed"
    }
    "ok2"
    {
        "ControlName"                       "CExButton"
        "fieldName"                         "ok2"
        "xpos"                              "0"
        "ypos"                              "0"
        "zpos"                              "2"
        "wide"                              "40"
        "tall"                              "17"
        "autoResize"                        "0"
        "pinCorner"                         "3"
        "visible"                           "1"
        "enabled"                           "1"
        "tabPosition"                       "0"
        "labelText"                         "NEXT"
        "font"                              "BodyEm_MD"
        "textAlignment"                     "center"
        "dulltext"                          "0"
        "brighttext"                        "0"
        "default"                           "0"
        "Command"                           "okay"
        "paintbackgroundtype"               "2"
        "paintbackground"                   "1"
        "sound_depressed"                   "UI/buttonclick.wav"
        "sound_released"                    "UI/buttonclickrelease.wav"
        "defaultBgColor_override"           "0 0 0 0"
        "armedBgColor_override"             "0 0 0 0"
        "depressedBgColor_override"         "0 0 0 0"
        "defaultFgColor_override"           "White"
        "armedFgColor_override"             "White"
        "depressedFgColor_override"         "White"
        "border_default"                    "NoBorder"
        "border_armed"                      "NoBorder"
        "pin_to_sibling"                    "ok"
        "pin_corner_to_sibling"             "pin_center_left"
        "pin_to_sibling_corner"             "pin_center_right"
    }
	"MenuBG"
	{
		"ControlName"	"CModelPanel"
		"fieldName"		"MenuBG"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"0"		
		"wide"			"0"
		"tall"			"0"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"0"
		"fov"			"20"
	}
	
	"ShadedBar"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"ShadedBar"
		"xpos"			"0"
		"ypos"			"r50"
		"zpos"			"5"
		"wide"			"f0"
		"tall"			"50"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"0"
		"tabPosition"	"0"	
		"image"			"loadout_bottom_gradient"
		"tileImage"		"1"
		"PaintBackgroundType"	"2"
	}						
	
	"MessageTitle"
	{
		"ControlName"	"Label"
		"fieldName"		"MessageTitle"
		"visible"		"0"
		"enabled"		"0"
	}		
}
